force-app/main/default/objects/Case/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignment</label>
    <referenceTo>BTN_Assignment__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/AssignmentEndDate__c.field-meta.xml
<CustomField>
    <fullName>AssignmentEndDate__c</fullName>
    <formula>Assignment__r.EndDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assignment End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/AssignmentStartDate__c.field-meta.xml
<CustomField>
    <fullName>AssignmentStartDate__c</fullName>
    <formula>Assignment__r.StartDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assignment Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/ContactLastDayAtWork__c.field-meta.xml
<CustomField>
    <fullName>ContactLastDayAtWork__c</fullName>
    <description>Contact Last Day at Office</description>
    <label>Contact Last Day at Office</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/ContractLength__c.field-meta.xml
<CustomField>
    <fullName>ContractLength__c</fullName>
    <inlineHelpText>Np. określony na rok</inlineHelpText>
    <label>Contract Length</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Freelancer__c.field-meta.xml
<CustomField>
    <fullName>Freelancer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the contact a freelancer?</description>
    <label>Freelancer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Guardian__c.field-meta.xml
<CustomField>
    <fullName>Guardian__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guardian</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Guardian)</relationshipLabel>
    <relationshipName>GuardianCases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Leader__c.field-meta.xml
<CustomField>
    <fullName>Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <inlineHelpText>Np. oddział na ul. Morwowej 1 w Lublinie</inlineHelpText>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lublin Hamleta</fullName>
            </value>
            <value>
                <fullName>Lublin Morwowa</fullName>
            </value>
            <value>
                <fullName>Kielce IX Wieków</fullName>
            </value>
            <value>
                <fullName>Zdalnie</fullName>
            </value>
            <value>
                <fullName>U klienta [Other location is mandatory]</fullName>
            </value>
            <value>
                <fullName>Inne [Other location is mandatory]</fullName>
            </value>
            <value>
                <fullName>Warszawa Karolkowa</fullName>
            </value>
            <value>
                <fullName>Poznań Szyperska</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserB2B__c.field-meta.xml
<CustomField>
    <fullName>NewUserB2B__c</fullName>
    <defaultValue>false</defaultValue>
    <description>New BS User is on B2B</description>
    <inlineHelpText>Is new User on Business-to-business?</inlineHelpText>
    <label>On B2B?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserEmail__c.field-meta.xml
<CustomField>
    <fullName>NewUserEmail__c</fullName>
    <description>New BS User Email</description>
    <label>Britenet Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserFirstName__c.field-meta.xml
<CustomField>
    <fullName>NewUserFirstName__c</fullName>
    <description>New BS User First Name</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserLastName__c.field-meta.xml
<CustomField>
    <fullName>NewUserLastName__c</fullName>
    <description>New BS User Last Name</description>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserProjectRole__c.field-meta.xml
<CustomField>
    <fullName>NewUserProjectRole__c</fullName>
    <description>BS Project Role is converted to Id during process</description>
    <label>Project Role</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserTitle__c.field-meta.xml
<CustomField>
    <fullName>NewUserTitle__c</fullName>
    <description>Title of New BS User</description>
    <label>Position</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Notice_Period_Comment__c.field-meta.xml
<CustomField>
    <fullName>Notice_Period_Comment__c</fullName>
    <label>Notice Period Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NoticePeriod__c.field-meta.xml
<CustomField>
    <fullName>NoticePeriod__c</fullName>
    <inlineHelpText>Standardowo przy B2B powinien być 2 mies.</inlineHelpText>
    <label>Notice Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Od zaraz</fullName>
            </value>
            <value>
                <fullName>3 dni robocze</fullName>
            </value>
            <value>
                <fullName>2 tygodnie</fullName>
            </value>
            <value>
                <fullName>1 miesiąc</fullName>
            </value>
            <value>
                <fullName>2 miesiące</fullName>
            </value>
            <value>
                <fullName>3 miesiące</fullName>
            </value>
            <value>
                <fullName>Zgodnie z kodeksem pracy</fullName>
            </value>
            <value>
                <fullName>Inne</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/OtherLocation__c.field-meta.xml
<CustomField>
    <fullName>OtherLocation__c</fullName>
    <label>Other Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PersonalEmail__c.field-meta.xml
<CustomField>
    <fullName>PersonalEmail__c</fullName>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/PersonalPhone__c.field-meta.xml
<CustomField>
    <fullName>PersonalPhone__c</fullName>
    <label>Personal Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Recommender__c.field-meta.xml
<CustomField>
    <fullName>Recommender__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recommender</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Recommender)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Responsibilities__c</fullName>
    <label>Responsibilities</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/SalaryB2B__c.field-meta.xml
<CustomField>
    <fullName>SalaryB2B__c</fullName>
    <inlineHelpText>Stawka za godzinę, netto</inlineHelpText>
    <label>Salary (za godzinę netto)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/SalaryUoP__c.field-meta.xml
<CustomField>
    <fullName>SalaryUoP__c</fullName>
    <inlineHelpText>Kwota za miesięczne wynagrodzenie, brutto</inlineHelpText>
    <label>Salary (miesięcznie brutto)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/UserEndDate__c.field-meta.xml
<CustomField>
    <fullName>UserEndDate__c</fullName>
    <description>Work End of Employee</description>
    <label>User Work End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/WorkEndDate__c.field-meta.xml
<CustomField>
    <fullName>WorkEndDate__c</fullName>
    <label>Work End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/WorkStartDate__c.field-meta.xml
<CustomField>
    <fullName>WorkStartDate__c</fullName>
    <label>Work Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/WorkStartDateComment__c.field-meta.xml
<CustomField>
    <fullName>WorkStartDateComment__c</fullName>
    <label>Work Start Date Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Freelancer__c.field-meta.xml
<CustomField>
    <fullName>Freelancer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the contact a freelancer?</description>
    <label>Freelancer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Guardian__c.field-meta.xml
<CustomField>
    <fullName>Guardian__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guardian</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Guarded Employees</relationshipLabel>
    <relationshipName>GuardedEmployees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Leader__c.field-meta.xml
<CustomField>
    <fullName>Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Managed Employees</relationshipLabel>
    <relationshipName>ManagedEmployees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Other Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PersonalEmail__c.field-meta.xml
<CustomField>
    <fullName>PersonalEmail__c</fullName>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PersonalPhone__c.field-meta.xml
<CustomField>
    <fullName>PersonalPhone__c</fullName>
    <label>Personal Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Recommender__c.field-meta.xml
<CustomField>
    <fullName>Recommender__c</fullName>
    <label>Recommender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/UserEndDate__c.field-meta.xml
<CustomField>
    <fullName>UserEndDate__c</fullName>
    <description>BS user_end_date</description>
    <label>User Work End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BTN_DAO_Case.cls
/**
 * @author Mateusz Przywara
 * @date   2016-08-18
 * @description DAO class - Data Access Object for Case
 */
public class BTN_DAO_Case extends BTN_DAO {
    /**
     * @author Mateusz Przywara
     * @date   2016-08-18
     * @description Constructor
    */
    public BTN_DAO_Case() {
        addRecordTypeFields();
    }

    public override Schema.SObjectType getSObjectType() {
        return Case.sObjectType;
    }

    public override List<Schema.SObjectField> getSObjectFields() {
        return new List<Schema.SObjectField>{
                Case.Id,
                Case.Assignment__c,
                Case.ContactId,
                Case.AccountId,
                Case.ContactLastDayAtWork__c,
                Case.UserEndDate__c,
                Case.NewUserFirstName__c,
                Case.NewUserLastName__c,
                Case.AssignmentEndDate__c,
                Case.AssignmentStartDate__c,
                Case.City__c,
                Case.ContractLength__c,
                Case.NewUserEmail__c,
                Case.Location__c,
                Case.NewUserB2B__c,
                Case.OtherLocation__c,
                Case.PersonalEmail__c,
                Case.PersonalPhone__c,
                Case.NewUserTitle__c,
                Case.Responsibilities__c,
                Case.SalaryUoP__c,
                Case.SalaryB2B__c,
                Case.NewUserProjectRole__c,
                Case.Sex__c,
                Case.WorkStartDateComment__c,
                Case.ZipCode__c,
                Case.Recommender__c,
                Case.WorkStartDate__c,
                Case.WorkEndDate__c,
                Case.Notice_Period_Comment__c,
                Case.NoticePeriod__c,
                Case.Freelancer__c,
                Case.Leader__c,
                Case.Guardian__c,
                Case.Street__c
        };
    }

        /**
         * @author Mateusz Przywara
         * @date   2016-08-18
         * @description add Record Type fields to Query
         * @return void
         */
    public void addRecordTypeFields() {
        currentFields.add('RecordType.DeveloperName');
    }

        /**
         * @author Mateusz Przywara
         * @date   2016-08-18
         * @description find all Cases
         * @return List<Contact>
         */
    public List<Case> findCases() {
        return findSObjects();
    }

        /**
         * @author Mateusz Przywara
         * @date   2016-08-18
         * @description find Cases added to SFDC from BSS
         * @return List<Case>
         */
    public List<Case> findExternalOnboardingCases() {
        return findSObjectsBy(
                new List<SearchCondition>{
                        new SearchCondition(
                                'RecordType.DeveloperName',
                                '=',
                                BTN_ConstantRepo.CASE_EXTERNAL_ONBOARDING_RECORDTYPE
                        )
                }
        );
    }

        /**
         * @author Mateusz Przywara
         * @date   2016-08-24
         * @description findCaseById find Case
         * @return Case
         */
    public Case findCaseById(Id caseId) {
        return (Case) findSObjectById(caseId);
    }

        /**
         * @author Mateusz Przywara
         * @date   2016-08-18
         * @description find Cases added to SFDC from BSS
         * @return List<Case>
         */
    public List<Case> findExternalOffboardingCases() {
        return findSObjectsBy(
                new List<SearchCondition>{
                        new SearchCondition(
                                'RecordType.DeveloperName',
                                '=',
                                BTN_ConstantRepo.CASE_EXTERNAL_OFFBOARDING_RECORDTYPE
                        )
                }
        );
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-08-30
     * @description find Cases for specified Ids
     * @return List<Case> - found Cases in arranged List
    */
    public List<Case> findCasesInIdSet(Set<Id> caseIdSet) {
        return (List<Case>) findSObjectsBy(
                new List<SearchCondition>{
                        new SearchCondition('Id', 'IN', caseIdSet)
                }
        );
    }
}