force-app/main/default/objects/Case/fields/Freelancer__c.field-meta.xml
<CustomField>
    <fullName>Freelancer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the contact a freelancer?</description>
    <label>Freelancer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Guardian__c.field-meta.xml
<CustomField>
    <fullName>Guardian__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guardian</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Guardian)</relationshipLabel>
    <relationshipName>GuardianCases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Leader__c.field-meta.xml
<CustomField>
    <fullName>Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <inlineHelpText>Np. oddział na ul. Morwowej 1 w Lublinie</inlineHelpText>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lublin Hamleta</fullName>
            </value>
            <value>
                <fullName>Lublin Morwowa</fullName>
            </value>
            <value>
                <fullName>Kielce IX Wieków</fullName>
            </value>
            <value>
                <fullName>Zdalnie</fullName>
            </value>
            <value>
                <fullName>U klienta [Other location is mandatory]</fullName>
            </value>
            <value>
                <fullName>Inne [Other location is mandatory]</fullName>
            </value>
            <value>
                <fullName>Warszawa Karolkowa</fullName>
            </value>
            <value>
                <fullName>Poznań Szyperska</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserB2B__c.field-meta.xml
<CustomField>
    <fullName>NewUserB2B__c</fullName>
    <defaultValue>false</defaultValue>
    <description>New BS User is on B2B</description>
    <inlineHelpText>Is new User on Business-to-business?</inlineHelpText>
    <label>On B2B?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserEmail__c.field-meta.xml
<CustomField>
    <fullName>NewUserEmail__c</fullName>
    <description>New BS User Email</description>
    <label>Britenet Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserFirstName__c.field-meta.xml
<CustomField>
    <fullName>NewUserFirstName__c</fullName>
    <description>New BS User First Name</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserLastName__c.field-meta.xml
<CustomField>
    <fullName>NewUserLastName__c</fullName>
    <description>New BS User Last Name</description>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserProjectRole__c.field-meta.xml
<CustomField>
    <fullName>NewUserProjectRole__c</fullName>
    <description>BS Project Role is converted to Id during process</description>
    <label>Project Role</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserProjectRoleId__c.field-meta.xml
<CustomField>
    <fullName>NewUserProjectRoleId__c</fullName>
    <description>BS Project Role Id</description>
    <label>Project Role Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserTitle__c.field-meta.xml
<CustomField>
    <fullName>NewUserTitle__c</fullName>
    <description>Title of New BS User</description>
    <label>Position</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PersonalEmail__c.field-meta.xml
<CustomField>
    <fullName>PersonalEmail__c</fullName>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/PersonalPhone__c.field-meta.xml
<CustomField>
    <fullName>PersonalPhone__c</fullName>
    <label>Personal Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/WorkStartDate__c.field-meta.xml
<CustomField>
    <fullName>WorkStartDate__c</fullName>
    <label>Work Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/BSexternalId__c.field-meta.xml
<CustomField>
    <fullName>BSexternalId__c</fullName>
    <externalId>true</externalId>
    <label>Britesheet ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Freelancer__c.field-meta.xml
<CustomField>
    <fullName>Freelancer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the contact a freelancer?</description>
    <label>Freelancer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Guardian__c.field-meta.xml
<CustomField>
    <fullName>Guardian__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guardian</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Guarded Employees</relationshipLabel>
    <relationshipName>GuardedEmployees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/joinDateBS__c.field-meta.xml
<CustomField>
    <fullName>joinDateBS__c</fullName>
    <label>BriteSheet join date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Leader__c.field-meta.xml
<CustomField>
    <fullName>Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Managed Employees</relationshipLabel>
    <relationshipName>ManagedEmployees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Other Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PersonalEmail__c.field-meta.xml
<CustomField>
    <fullName>PersonalEmail__c</fullName>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PersonalPhone__c.field-meta.xml
<CustomField>
    <fullName>PersonalPhone__c</fullName>
    <label>Personal Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>ZOHO</description>
    <label>Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SkillAssessment__c.field-meta.xml
<CustomField>
    <fullName>SkillAssessment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skill Assessment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Internal employees</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/classes/BTN_CaseUtils.cls
/**
 * @author Mateusz Przywara
 * @date   2016-08-22
 * @description Utils class for Record Type
 */
public class BTN_CaseUtils {
    private static final String TRIGGER_ERROR_SOURCE = 'Case Trigger';
    private static final String CONTACT_FIRSTNAME_PARAM = 'user_fname';
    private static final String CONTACT_LASTNAME_PARAM = 'user_lname';
    private static final String CONTACT_SEX_PARAM = 'user_sex';
    private static final String CONTACT_MAIL_PARAM = 'user_mail';
    private static final String CONTACT_JOINDATE_PARAM = 'user_join_date';
    private static final String CONTACT_B2B_PARAM = 'user_b2b';
    private static final String CONTACT_TITLE_PARAM = 'user_title';
    private static final String CONTACT_PROJECT_ROLE_ID_PARAM = 'user_projectrole';
    private static final String CONTACT_PERSONAL_PHONE_PARAM = 'user_phone';
    private static final String CONTACT_LEADER_ID_PARAM = 'user_leader_id';
    private static final String CONTACT_GUARDIAN_ID_PARAM = 'user_guardian_id';
    private static final String CONTACT_IS_FREELANCER = 'user_is_freelancer';

    public static final String STATUS_OPEN = 'Open';

    /**
     * @author Mateusz Przywara
     * @date   2016-08-19
     * @description buildParamMapForNewBSUserFromContact Method build Map on the Contact Data
     *      for Britesheet.
     * @param contactUser SFDC Contact - source of Data for new BS User
     * @return Map<String, String> Params Map with values for request body
    */
    public static Map<String, String> buildParamMapForNewBSUserFromCase(Case caseUser) {
        Map<String, String> result = new Map<String, String>();
        result.put(CONTACT_FIRSTNAME_PARAM, caseUser.NewUserFirstName__c);
        result.put(CONTACT_LASTNAME_PARAM, caseUser.NewUserLastName__c);
        result.put(CONTACT_SEX_PARAM, String.valueOf(caseUser.Sex__c).left(1));
        result.put(CONTACT_MAIL_PARAM, caseUser.NewUserEmail__c);
        result.put(CONTACT_JOINDATE_PARAM, ((DateTime)caseUser.WorkStartDate__c).format(System.Label.BSDateFormat));
        result.put(CONTACT_B2B_PARAM, String.valueOf(caseUser.NewUserB2B__c));
        result.put(CONTACT_TITLE_PARAM, caseUser.NewUserTitle__c);
        result.put(CONTACT_PROJECT_ROLE_ID_PARAM, String.valueOf(caseUser.NewUserProjectRoleId__c));
        result.put(CONTACT_PERSONAL_PHONE_PARAM, caseUser.PersonalPhone__c);
        result.put(CONTACT_IS_FREELANCER, String.valueOf(caseUser.Freelancer__c));
        if (caseUser.Leader__r.BSexternalId__c != null) {
            result.put(CONTACT_LEADER_ID_PARAM, String.valueOf(caseUser.Leader__r.BSexternalId__c));
        }
        if (caseUser.Guardian__r.BSexternalId__c != null) {
            result.put(CONTACT_GUARDIAN_ID_PARAM, String.valueOf(caseUser.Guardian__r.BSexternalId__c));
        }
        return result;
    }

	public static Map<String, String> buildParamMapForNewBSUserFromCase(Case newInternalOnboardingCase, Map<Id, Decimal> leaderAndGuardianBSIdsBySalesforceIds) {
		Map<String, String> result = new Map<String, String>();

		result.put(CONTACT_FIRSTNAME_PARAM, newInternalOnboardingCase.NewUserFirstName__c);
		result.put(CONTACT_LASTNAME_PARAM, newInternalOnboardingCase.NewUserLastName__c);
		result.put(CONTACT_SEX_PARAM, String.valueOf(newInternalOnboardingCase.Sex__c).left(1));
		result.put(CONTACT_MAIL_PARAM, newInternalOnboardingCase.NewUserEmail__c);
		result.put(CONTACT_JOINDATE_PARAM, ((DateTime)newInternalOnboardingCase.WorkStartDate__c).format(System.Label.BSDateFormat));
		result.put(CONTACT_B2B_PARAM, String.valueOf(newInternalOnboardingCase.NewUserB2B__c));
		result.put(CONTACT_TITLE_PARAM, newInternalOnboardingCase.NewUserTitle__c);
		result.put(CONTACT_PROJECT_ROLE_ID_PARAM, String.valueOf(newInternalOnboardingCase.NewUserProjectRoleId__c));
		result.put(CONTACT_PERSONAL_PHONE_PARAM, newInternalOnboardingCase.PersonalPhone__c);
		result.put(CONTACT_IS_FREELANCER, String.valueOf(newInternalOnboardingCase.Freelancer__c));

		if (newInternalOnboardingCase.Leader__c != null) {
			result.put(CONTACT_LEADER_ID_PARAM, String.valueOf(leaderAndGuardianBSIdsBySalesforceIds.get(newInternalOnboardingCase.Leader__c)));
		}

		if (newInternalOnboardingCase.Guardian__c != null) {
			result.put(CONTACT_GUARDIAN_ID_PARAM, String.valueOf(leaderAndGuardianBSIdsBySalesforceIds.get(newInternalOnboardingCase.Guardian__c)));
		}

		return result;
	}

    /**
     * @author Mateusz Przywara
     * @date   2016-08-24
     * @description updateInternalContactBSExternalId update Contact by BS response.
     * @param contactId Contact to be updated
     * @param bsId BS External Id from response
     * @param projectRole Project Role Name to fill Contact title
     * @param leaderId Leader(SFDC Contact) selected on New Internal Onboarding form
     * @return Contact Updated Contact with only necessary fields
    */
    public static Contact updateInternalContactBSExternalId(Id contactId, Integer bsId, Case onboardingCase) {
        Contact result = new Contact(
                Id = contactId,
                RecordTypeId = BTN_RecordTypeUtils.getRecordTypeContactInternal().Id,
                BSexternalId__c = bsId,
                Title = onboardingCase.NewUserProjectRole__c,
                ReportsToId = onboardingCase.Leader__c,
                Leader__c = onboardingCase.Leader__c,
                Guardian__c = onboardingCase.Guardian__c,
                Email = onboardingCase.NewUserEmail__c,
                joinDateBS__c = onboardingCase.WorkStartDate__c,
                MailingPostalCode = onboardingCase.ZipCode__c,
                MailingStreet = onboardingCase.Street__c,
                MailingCity = onboardingCase.City__c,
                PersonalEmail__c = onboardingCase.PersonalEmail__c,
                PersonalPhone__c = onboardingCase.PersonalPhone__c,
                Position__c = onboardingCase.NewUserTitle__c,
                Location__c = onboardingCase.Location__c,
                SkillAssessment__c = true,
                Freelancer__c = onboardingCase.Freelancer__c
        );
        update result;
        return result;
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-08-31
     * @description updateCaseContactInfo
     * @param caseItemToUpdate Case being updated
     * @param contactId Source of Contact Id for Case
     * @return Case
    */
    public static Case updateCaseContactInfo(Case caseItemToUpdate, Id contactId) {
        caseItemToUpdate.ContactId = contactId;
        update caseItemToUpdate;
        return caseItemToUpdate;
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-09-01
     * @description executeCaseStandardAssignmentRule Execute Assignment Rule from Apex Code to Assign Ownership to
     *  Resource Managment Queue
     * @param caseIds Case Ids
     * @return
    */
    public static void executeCaseStandardAssignmentRule(Set<Id> caseIds) {
        List<Case> cases = new BTN_DAO_Case().findCasesInIdSet(caseIds);
        Database.DMLOptions dmlOpts = new Database.DMLOptions();
        Id caseAssignmentRuleId =
                new BTN_DAO_AssignmentRule().findCaseAssignmentRule().Id;
        dmlOpts.assignmentRuleHeader.useDefaultRule = true;
        for (Case caseItem : cases) {
            caseItem.setOptions(dmlOpts);
        }
        update cases;
    }

    public static void addCaseSharingForLeader(List<Case> caseList){
        List<CaseShare> caseShareToInsert = new List<CaseShare>();
        Map<Id,Id> contactToUserMap = BTN_Utils.getContactToUserMap(BTN_Utils.getSetOfIds(caseList,'Leader__c'));

        for(Case newCase : caseList){
            if(contactToUserMap.get(newCase.Leader__c) != null && !newCase.Freelancer__c) {
                CaseShare share = new CaseShare();
                share.CaseAccessLevel = 'Edit';
                share.CaseId = newCase.Id;
                share.RowCause = 'Manual';
                share.UserOrGroupId = contactToUserMap.get(newCase.Leader__c);
                caseShareToInsert.add(share);
            }
        }
        insert caseShareToInsert;
    }

    public static void replaceCaseSharingForLeader(Map<Id,Case> newCaseMap, Map<Id,Case> oldCaseMap){
        List<Case> caseToInsert = new List<Case>();
        Map<Id,Id> caseToDelete = new Map<Id,Id>();

        for(Id caseId : newCaseMap.keySet()){
            if(newCaseMap.get(caseId).Leader__c != oldCaseMap.get(caseId).Leader__c){
                caseToInsert.add(newCaseMap.get(caseId));
                caseToDelete.put(oldCaseMap.get(caseId).Leader__c, caseId);
            }
        }
        addCaseSharingForLeader(caseToInsert);
        removeCaseSharingForLeader(caseToDelete);
    }

    public static void removeCaseSharingForLeader(Map<Id,Id> caseMap){
        Map<Id,Id> contactToUserMap = BTN_Utils.getContactToUserMap(caseMap.keySet());

        List<CaseShare> caseShareToDelete = [select id from CaseShare where CaseId in : caseMap.values()
                                                and UserOrGroupId in: contactToUserMap.values()];
        delete caseShareToDelete;
    }
}