force-app/main/default/objects/BTN_Project__c/BTN_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Project__c/fields/BritesheetProjectId__c.field-meta.xml
<CustomField>
    <fullName>BritesheetProjectId__c</fullName>
    <externalId>true</externalId>
    <label>Britesheet Project Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BTN_Project__c/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <label>Project Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Project__c/fields/ProjectType__c.field-meta.xml
<CustomField>
    <fullName>ProjectType__c</fullName>
    <label>Project Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BTN_DAO_Project.cls
/**
 * @author Mateusz Przywara
 * @date   2016-08-09
 * @description BTN_DAO_Project DAO Class
*/
public class BTN_DAO_Project extends BTN_DAO {
   /**
     * @author Mateusz Przywara
     * @date   2016-08-09
     * @description Constructor
    */
    public BTN_DAO_Project() {
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-08-09
     * @description Constructor setting custom List of fields
    */
    public BTN_DAO_Project(List<Schema.SObjectField> customFields) {
        setCustomFields(customFields);
    }

    public override Schema.SObjectType getSObjectType() {
        return BTN_Project__c.sObjectType;
    }

    public override List<Schema.SObjectField> getSObjectFields() {
        return new List<Schema.SObjectField>{
                BTN_Project__c.Id,
                BTN_Project__c.Account__c,
                BTN_Project__c.BritesheetProjectId__c,
                BTN_Project__c.ProjectCode__c,
                BTN_Project__c.ProjectType__c
        };
    }

        /**
         * @author Mateusz Przywara
         * @date   2016-08-09
         * @description findProjects Method returns all Projects
         * @return List<BTN_Project__c>
        */
    public List<BTN_Project__c> findProjects() {
        return (List<BTN_Project__c>) findSObjects();
    }

    /**
        * @author Mateusz Przywara
        * @date   2016-08-18
        * @description findProjectsIn with Ids
        * @param projectIds - Id List
        * @return     List<BTN_Project__c>
    */
    public List<BTN_Project__c> findProjectsIn(Set<Id> projectIds) {
        return (List<BTN_Project__c>) findSObjectsBy(
                new List<SearchCondition>{
                        new SearchCondition(
                                'Account__c != null'
                        ),
                        new SearchCondition(
                                'AND Id',
                                'IN',
                                projectIds
                        )
                }
        );
    }
}