src/objects/BL_CommunitySettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Brite League Community Settings</label>
</CustomObject>

src/objects/BL_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>League__c</fullName>
        <label>League</label>
        <referenceTo>BL_League__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BL_Team__c.object
<CustomObject>
    <fields>
        <fullName>Player1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Player2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams (Player2)</relationshipLabel>
        <relationshipName>Teams2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BL_Utils.cls
public with sharing class BL_Utils {
    private static User CURRENT_USER = getCurrentUser();

    public static User getCurrentUser() {
        if(CURRENT_USER == null || CURRENT_USER.Id != UserInfo.getUserId()){
            CURRENT_USER = [SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()];
        }
        return CURRENT_USER;
    }

    public static String getBLCommunitySettings(String field){
        BL_CommunitySettings__c communitySettings = BL_CommunitySettings__c.getInstance('BriteLeagueSettings');
        return (String)communitySettings.get(field);
    }

    public static List<BL_Competitor__c> getLeagueCompetitors(String leagueId){
        List<BL_Competitor__c> competitors = [
            SELECT Id, Team__c, Team__r.Player1__c, Team__r.Player2__c
            FROM BL_Competitor__c
            WHERE League__c =: leagueId
        ];
        return competitors;
    }
}