src/objects/BL_Competitor__c.object
<CustomObject>
    <label>Competitor</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Competitor__c/fields/GamesDrawn__c.field-meta.xml
<CustomField>
    <fullName>GamesDrawn__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesDrawn</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GamesLost__c.field-meta.xml
<CustomField>
    <fullName>GamesLost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesLost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GamesWon__c.field-meta.xml
<CustomField>
    <fullName>GamesWon__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesWon</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsAgainst__c.field-meta.xml
<CustomField>
    <fullName>GoalsAgainst__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GoalsAgainst</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsDraw__c.field-meta.xml
<CustomField>
    <fullName>GoalsDraw__c</fullName>
    <formula>GoalsFor__c -  GoalsAgainst__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GoalsDraw</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsFor__c.field-meta.xml
<CustomField>
    <fullName>GoalsFor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GoalsFor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/MatchesPlayed__c.field-meta.xml
<CustomField>
    <fullName>MatchesPlayed__c</fullName>
    <formula>GamesDrawn__c + GamesLost__c + GamesWon__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Matches Played</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <formula>(3 *  GamesWon__c) + (1  *  GamesDrawn__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/BL_Team__c.object
<CustomObject>
    <fields>
        <fullName>Player1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Player2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams (Player2)</relationshipLabel>
        <relationshipName>Teams2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/ImageUrl__c.field-meta.xml
<CustomField>
    <fullName>ImageUrl__c</fullName>
    <label>ImageUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/classes/BL_DTO_Team.cls
public virtual class BL_DTO_Team implements Comparable {

    @AuraEnabled
    public Id teamId;
    @AuraEnabled
    public Id competitorId;
    @AuraEnabled
    public String name;
    @AuraEnabled
    public Id player1Id;
    @AuraEnabled
    public Id player2Id;
    @AuraEnabled
    public String player1ImageUrl;
    @AuraEnabled
    public String player2ImageUrl;
    @AuraEnabled
    public String player1Name;
    @AuraEnabled
    public String player2Name;
    @AuraEnabled
    public String player1FirstName;
    @AuraEnabled
    public String player2FirstName;
    @AuraEnabled
    public String player1LastName;
    @AuraEnabled
    public String player2LastName;
    @AuraEnabled
    public String players;
    @AuraEnabled
    public Integer matchesPlayed;
    @AuraEnabled
    public Integer gamesWon;
    @AuraEnabled
    public Integer gamesDrawn;
    @AuraEnabled
    public Integer gamesLost;
    @AuraEnabled
    public Integer goalsFor;
    @AuraEnabled
    public Integer goalsAgainst;
    @AuraEnabled
    public Integer goalsDraw;
    @AuraEnabled
    public Integer points;
    @AuraEnabled
    public String teamIcon;

    private BL_Team__c team;
    private BL_Competitor__c competitor;

    public void setTeam(BL_Team__c team) {
        this.team = team;

        this.teamId = team.Id;
        this.name = team.Name;
        this.player1Id = team.Player1__c;
        this.player1Name = team.Player1__r.Name;
        this.player1FirstName = team.Player1__r.FirstName;
        this.player1LastName = team.Player1__r.LastName;
        this.players = team.Player1__r.LastName;
        this.player1ImageUrl = team.Player1__r.ImageUrl__c;

        if(team.Player2__c != null) {
            this.player2Id = team.Player2__c;
            this.player2Name = team.Player2__r.Name;
            this.player2FirstName = team.Player2__r.FirstName;
            this.player2LastName = team.Player2__r.LastName;
            this.players += ' & ' + team.Player2__r.LastName;
            this.player2ImageUrl = team.Player2__r.ImageUrl__c;
        }

        if(team.RecordType.DeveloperName == BL_Constants.TEAM_RT_BATTLE_ROYALE) {
            this.teamIcon = BL_Constants.ICON_STANDARD_HOUSEHOLD;
        } else if(team.RecordType.DeveloperName == BL_Constants.TEAM_RT_CLASSIC) {
            if(team.Player2__c != null) {
                this.teamIcon = BL_Constants.ICON_STANDARD_CUSTOMERS;
            } else {
                this.teamIcon = BL_Constants.ICON_STANDARD_AVATAR;
            }
        }
    }

    public void setCompetitor(BL_Competitor__c competitor) {
        this.competitor = competitor;

        this.matchesPlayed = Integer.valueOf(competitor.MatchesPlayed__c);
        this.gamesWon = Integer.valueOf(competitor.GamesWon__c);
        this.gamesDrawn = Integer.valueOf(competitor.GamesDrawn__c);
        this.gamesLost = Integer.valueOf(competitor.GamesLost__c);
        this.goalsFor = Integer.valueOf(competitor.GoalsFor__c);
        this.goalsAgainst = Integer.valueOf(competitor.GoalsAgainst__c);
        this.goalsDraw = Integer.valueOf(competitor.GoalsDraw__c);
        this.points = Integer.valueOf(competitor.Points__c);
    }

    public Integer compareTo(Object toCompare) {
        BL_DTO_Team toCompareTeam = (BL_DTO_Team) toCompare;

        if(this.points > toCompareTeam.points) {
            return -1;
        } else if(this.points < toCompareTeam.points) {
            return 1;
        } else {
            return 0;
        }
    }
}