src/objects/BL_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Competitor__c/fields/Competition__c.field-meta.xml
<CustomField>
    <fullName>Competition__c</fullName>
    <label>Competition</label>
    <referenceTo>BL_Competition__c</referenceTo>
    <relationshipLabel>Competitors</relationshipLabel>
    <relationshipName>Competitors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/BL_Match__c.object
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>M-{0000000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Match__c/fields/Competition__c.field-meta.xml
<CustomField>
    <fullName>Competition__c</fullName>
    <label>Competition</label>
    <referenceTo>BL_Competition__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/BL_Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <recordTypes>
        <fullName>Classic</fullName>
        <active>true</active>
        <label>Classic</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BL_TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BL_BattleRoyaleMatchGenerator.cls
public with sharing class BL_BattleRoyaleMatchGenerator implements BL_MatchGenerator {

    public List<BL_Match__c> generateMatches(List<Id> competitorsIds, Id leagueId, Integer rounds) {

        // TODO: Less queries

        // get competitors for parent teams
        List<BL_Competitor__c> battleRoyaleCompetitors = [SELECT Team__r.Id FROM BL_Competitor__c WHERE Id IN :competitorsIds AND Team__r.RecordType.DeveloperName = :BL_Constants.TEAM_RT_BATTLE_ROYALE];
        Map<Id, Id> teamToParentComp = new Map<Id, Id>();
        for (BL_Competitor__c comp : battleRoyaleCompetitors) {
            teamToParentComp.put(comp.Team__r.Id, comp.Id);
        }

        // get competitors for classic teams
        List<BL_Competitor__c> memberCompetitors = [SELECT Id, Team__r.Name FROM BL_Competitor__c WHERE Competition__c = :leagueId AND Team__c IN (SELECT Member__c FROM BL_TeamMember__c WHERE Team__r.Id In :teamToParentComp.keySet())];
        Map<Id, Id> teamToMemberComp = new Map<Id, Id>();
        for (BL_Competitor__c comp : memberCompetitors) {
            teamToMemberComp.put(comp.Team__r.Id, comp.Id);
        }

        List<BL_TeamMember__c> teamMembers = [select id, Team__r.Id, Member__c from bl_teammember__c where Member__r.Id IN :teamToMemberComp.keyset() AND Team__c IN :teamToParentComp.keySet()];
        Map<Id, List<Id>> parentToMembersIds = new Map<Id, List<Id>>();
        for (BL_TeamMember__c tm : teamMembers) {
            if (parentToMembersIds.get(tm.Team__c) == null) {
                parentToMembersIds.put(tm.Team__c, new List<Id>());
            }
            parentToMembersIds.get(tm.Team__r.Id).add(teamToMemberComp.get(tm.Member__c));
        }

        List<BL_Match__c> generatedMatches = new List<BL_Match__c>();

        // TODO: Less loops
        List<List<Id>> teamsCompetitors = parentToMembersIds.values();
        Integer parentTeamsCount = teamsCompetitors.size();
        for (Integer parentTeamIndex = 0; parentTeamIndex < parentTeamsCount - 1; parentTeamIndex++) {
            for (Integer memberTeamIndex = 0; memberTeamIndex < teamsCompetitors[parentTeamIndex].size(); memberTeamIndex++) {
                for (Integer opponentParentTeamIndex = parentTeamIndex + 1; opponentParentTeamIndex < parentTeamsCount; opponentParentTeamIndex++) {
                    for (Integer opponentTeamMemberIndex = 0; opponentTeamMemberIndex < teamsCompetitors[opponentParentTeamIndex].size(); opponentTeamMemberIndex++) {
                        for (Integer round = 1; round <= rounds; round++) {
                            generatedMatches.add(new BL_MatchBuilder()
                                    .setCompetition(leagueId)
                                    .setRound(round)
                                    .setTeam1(Math.mod(round, 2) == 0 ? teamsCompetitors[parentTeamIndex][memberTeamIndex] : teamsCompetitors[opponentParentTeamIndex][opponentTeamMemberIndex])
                                    .setTeam2(Math.mod(round, 2) == 0 ? teamsCompetitors[opponentParentTeamIndex][opponentTeamMemberIndex] : teamsCompetitors[parentTeamIndex][memberTeamIndex])
                                    .build());
                        }
                    }
                }
            }
        }
        return generatedMatches;
    }
}