src/objects/BL_Competition__c.object
<CustomObject>
    <fields>
        <fullName>TeamSize__c</fullName>
        <label>Team Size</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single Player</fullName>
                </value>
                <value>
                    <fullName>Two Players</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Competition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BL_Match__c.object
<CustomObject>
    <fields>
        <fullName>Team1_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Team1 Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team1</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Matches</relationshipLabel>
        <relationshipName>Matches1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team2_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Team2 Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team2</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Matches (Team2)</relationshipLabel>
        <relationshipName>Matches2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Winner__c</fullName>
        <formula>IF( Team1_Score__c &gt; Team2_Score__c,  Team1__r.Id ,  Team2__r.Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Winner</label>
        <type>Text</type>
    </fields>
    <label>Match</label>
    <nameField>
        <displayFormat>M-{0000000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Match__c/fields/Competition__c.field-meta.xml
<CustomField>
    <fullName>Competition__c</fullName>
    <label>Competition</label>
    <referenceTo>BL_Competition__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/isResolved__c.field-meta.xml
<CustomField>
    <fullName>isResolved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If match isResolved that means all rounds was played and match should be included in score tables, otherwise, statistics are not counted</description>
    <label>isResolved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/MatchDate__c.field-meta.xml
<CustomField>
    <fullName>MatchDate__c</fullName>
    <description>Datetime when match was resolved</description>
    <label>Match Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <label>Round</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Team1Round1Goals__c.field-meta.xml
<CustomField>
    <fullName>Team1Round1Goals__c</fullName>
    <label>Team1 Round1 Goals</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Team1Round2Goals__c.field-meta.xml
<CustomField>
    <fullName>Team1Round2Goals__c</fullName>
    <label>Team1 Round2 Goals</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Team1Round3Goals__c.field-meta.xml
<CustomField>
    <fullName>Team1Round3Goals__c</fullName>
    <label>Team1 Round3 Goals</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Team1TotalGoalsScored__c.field-meta.xml
<CustomField>
    <fullName>Team1TotalGoalsScored__c</fullName>
    <formula>Team1Round1Goals__c +  Team1Round2Goals__c +  Team1Round3Goals__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Team1 Total Goals Scored</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Team2Round1Goals__c.field-meta.xml
<CustomField>
    <fullName>Team2Round1Goals__c</fullName>
    <label>Team2 Round1 Goals</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Team2Round2Goals__c.field-meta.xml
<CustomField>
    <fullName>Team2Round2Goals__c</fullName>
    <label>Team2 Round2 Goals</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Team2Round3Goals__c.field-meta.xml
<CustomField>
    <fullName>Team2Round3Goals__c</fullName>
    <label>Team2 Round3 Goals</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Team2TotalGoalsScored__c.field-meta.xml
<CustomField>
    <fullName>Team2TotalGoalsScored__c</fullName>
    <formula>Team2Round1Goals__c + Team2Round2Goals__c + Team2Round3Goals__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Team2 Total Goals Scored</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/BL_Team__c.object
<CustomObject>
    <fields>
        <fullName>Player1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Player2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams (Player2)</relationshipLabel>
        <relationshipName>Teams2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BL_DAO_Match.cls
public without sharing class BL_DAO_Match {

    public BL_Match__c getMatchById(Id matchId) {
        List<BL_Match__c> matches = [
                SELECT
                        Id,
                        isResolved__c,
                        MatchDate__c,
                        Team1_Score__c,
                        Team2_Score__c,
                        Team1TotalGoalsScored__c,
                        Team2TotalGoalsScored__c,
                        Team1Round1Goals__c,
                        Team1Round2Goals__c,
                        Team1Round3Goals__c,
                        Team2Round1Goals__c,
                        Team2Round2Goals__c,
                        Team2Round3Goals__c,
                        Competition__c,
                        Competition__r.RecordType.DeveloperName,
                        Team1__c,
                        Team1__r.Team__c,
                        Team1__r.GoalsFor__c,
                        Team1__r.GoalsAgainst__c,
                        Team1__r.GamesWon__c,
                        Team1__r.GamesLost__c,
                        Team1__r.GamesDrawn__c,
                        Team2__c,
                        Team2__r.Team__c,
                        Team2__r.GoalsFor__c,
                        Team2__r.GoalsAgainst__c,
                        Team2__r.GamesWon__c,
                        Team2__r.GamesLost__c,
                        Team2__r.GamesDrawn__c
                FROM BL_Match__c
                WHERE Id = :matchId
                LIMIT 1
        ];
        return matches.isEmpty() ? null : matches[0];
    }

    public List<BL_Match__c> getMatchesForCompetition(Id competitionId) {
        return [
                SELECT
                        Id,
                        Name,
                        Competition__r.RecordType.DeveloperName,
                        Competition__r.TeamSize__c,
                        Round__c,
                        Team1_Score__c,
                        Team2_Score__c,
                        Team1Round1Goals__c,
                        Team1Round2Goals__c,
                        Team1Round3Goals__c,
                        Team2Round1Goals__c,
                        Team2Round2Goals__c,
                        Team2Round3Goals__c,
                        Team1__r.Team__c,
                        Team1__r.Team__r.Name,
                        Team1__r.Team__r.Player1__c,
                        Team1__r.Team__r.Player1__r.Name,
                        Team1__r.Team__r.Player1__r.ImageUrl__c,
                        Team1__r.Team__r.Player2__c,
                        Team1__r.Team__r.Player2__r.Name,
                        Team1__r.Team__r.Player2__r.ImageUrl__c,
                        Team2__r.Team__c,
                        Team2__r.Team__r.Name,
                        Team2__r.Team__r.Player1__c,
                        Team2__r.Team__r.Player1__r.Name,
                        Team2__r.Team__r.Player1__r.ImageUrl__c,
                        Team2__r.Team__r.Player2__c,
                        Team2__r.Team__r.Player2__r.Name,
                        Team2__r.Team__r.Player2__r.ImageUrl__c
                FROM BL_Match__c
                WHERE Competition__c = :competitionId
                ORDER BY Round__c ASC, Team1__r.Team__r.Name ASC, Team2__r.Team__r.Name ASC
        ];
    }

    public List<BL_Match__c> getMatchesForCompetitionAndCompetitor(Id competitionId, Id competitorId) {
        return [
                SELECT
                        Id,
                        Name,
                        Team1_Score__c,
                        Team1Round1Goals__c,
                        Team1Round2Goals__c,
                        Team1Round3Goals__c,
                        Team2_Score__c,
                        Team2Round1Goals__c,
                        Team2Round2Goals__c,
                        Team2Round3Goals__c,
                        Competition__r.RecordType.DeveloperName,
                        Competition__r.TeamSize__c, Round__c,
                        Team1__r.Team__c,
                        Team1__r.Team__r.Name,
                        Team1__r.Team__r.Player1__c,
                        Team1__r.Team__r.Player1__r.Name,
                        Team1__r.Team__r.Player1__r.ImageUrl__c,
                        Team1__r.Team__r.Player2__c,
                        Team1__r.Team__r.Player2__r.Name,
                        Team1__r.Team__r.Player2__r.ImageUrl__c,
                        Team2__r.Team__c,
                        Team2__r.Team__r.Name,
                        Team2__r.Team__r.Player1__c,
                        Team2__r.Team__r.Player1__r.Name,
                        Team2__r.Team__r.Player1__r.ImageUrl__c,
                        Team2__r.Team__r.Player2__c,
                        Team2__r.Team__r.Player2__r.Name,
                        Team2__r.Team__r.Player2__r.ImageUrl__c
                FROM BL_Match__c
                WHERE Competition__c = :competitionId
                AND (
                        Team1__c = :competitorId
                        OR Team2__c = :competitorId
                )
                ORDER BY Round__c
        ];
    }

    public List<BL_Match__c> getResolvedMatchesForCompetition(Id competitionId) {
        return [
                SELECT
                        Id,
                        LastModifiedDate,
                        MatchDate__c,
                        Team1_Score__c,
                        Team2_Score__c,
                        Team1TotalGoalsScored__c,
                        Team2TotalGoalsScored__c,
                        Winner__c,
                        Team1__c,
                        Team1__r.Team__r.Name,
                        Team2__c,
                        Team2__r.Team__r.Name
                FROM BL_Match__c
                WHERE Competition__c = :competitionId
                AND isResolved__c = TRUE
                ORDER BY MatchDate__c ASC, LastModifiedDate ASC
        ];
    }
}