src/objects/BL_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>League__c</fullName>
        <label>League</label>
        <referenceTo>BL_League__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BL_Match__c.object
<CustomObject>
    <fields>
        <fullName>League__c</fullName>
        <label>League</label>
        <referenceTo>BL_League__c</referenceTo>
        <relationshipLabel>Matches</relationshipLabel>
        <relationshipName>Matches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team1</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Matches</relationshipLabel>
        <relationshipName>Matches1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team2</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Matches (Team2)</relationshipLabel>
        <relationshipName>Matches2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Match</label>
    <nameField>
        <displayFormat>M-{0000000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BL_MatchService.cls
public with sharing class BL_MatchService {
    public static void generateMatchesAfterLeagueStarted(String leagueId){
        List<BL_Competitor__c> competitors = [
                SELECT Id, Team__c
                FROM BL_Competitor__c
                WHERE League__c =: leagueId
        ];
        if(competitors.size() >= 2){
            List<Id> competitorsIds = new List<Id>();
            List<BL_Match__c> generatedMatches = new List<BL_Match__c>();
            competitorsIds.addAll(new Map<Id,BL_Competitor__c>(competitors).keySet());
            Integer numberOfTeams = competitorsIds.size();
            Boolean isNumberOfTeamsEven = Math.mod(competitorsIds.size(),2) == 0;
            List<Id> competitorIdsForDraw = competitorsIds.clone();

            if(isNumberOfTeamsEven){
                Id lastTeamOnTheList = competitorsIds[numberOfTeams-1];
                for(Integer ii=0; ii < competitors.size()-1; ii++){
                    for(Integer jj=0; jj < numberOfTeams/2; jj++){
                        BL_Match__c newMatch = new BL_Match__c();
                        newMatch.Team1__c = competitorIdsForDraw[jj];
                        newMatch.Team2__c = competitorIdsForDraw[numberOfTeams-jj-1];
                        generatedMatches.add(newMatch);
                    }
                    competitorIdsForDraw.remove(numberOfTeams-1);
                    competitorIdsForDraw.add(competitorIdsForDraw[0]);
                    competitorIdsForDraw.remove(0);
                    competitorIdsForDraw.add(lastTeamOnTheList);
                }
            }else{
                for(Integer ii=0; ii < competitors.size(); ii++){
                    for(Integer jj=0; jj < numberOfTeams/2; jj++){
                        BL_Match__c newMatch = new BL_Match__c();
                        newMatch.Team1__c = competitorIdsForDraw[jj];
                        newMatch.Team2__c = competitorIdsForDraw[numberOfTeams-jj-2];
                        generatedMatches.add(newMatch);
                    }
                    competitorIdsForDraw.add(competitorIdsForDraw[0]);
                    competitorIdsForDraw.remove(0);
                }
            }
        }
    }

    public static Integer getRandomInteger(Integer fromRange, Integer toRange){
        system.debug(fromRange+' - '+toRange);

        Integer numberToReturn;
        do{
            numberToReturn = Math.round(Math.random()*100);
        }while(numberToReturn < fromRange || numberToReturn > toRange);

        return numberToReturn;
    }
}