src/objects/BL_Competition__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Match_No__c</fullName>
        <label>Match No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Teams__c</fullName>
        <description>0 = unlimited</description>
        <label>Max Teams</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assembling teams</fullName>
                    <default>true</default>
                    <label>Assembling teams</label>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Finished</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TeamSize__c</fullName>
        <label>Team Size</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single Player</fullName>
                </value>
                <value>
                    <fullName>Two Players</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Teams_Joined__c</fullName>
        <label>Teams Joined</label>
        <summaryForeignKey>BL_Competitor__c.League__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>isPrivate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Private League</label>
        <type>Checkbox</type>
    </fields>
    <label>Competition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BL_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Competitor__c/fields/Competition__c.field-meta.xml
<CustomField>
    <fullName>Competition__c</fullName>
    <label>Competition</label>
    <referenceTo>BL_Competition__c</referenceTo>
    <relationshipLabel>Competitors</relationshipLabel>
    <relationshipName>Competitors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GamesDrawn__c.field-meta.xml
<CustomField>
    <fullName>GamesDrawn__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesDrawn</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GamesLost__c.field-meta.xml
<CustomField>
    <fullName>GamesLost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesLost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GamesWon__c.field-meta.xml
<CustomField>
    <fullName>GamesWon__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesWon</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsAgainst__c.field-meta.xml
<CustomField>
    <fullName>GoalsAgainst__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GoalsAgainst</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsDraw__c.field-meta.xml
<CustomField>
    <fullName>GoalsDraw__c</fullName>
    <formula>GoalsFor__c -  GoalsAgainst__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GoalsDraw</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsFor__c.field-meta.xml
<CustomField>
    <fullName>GoalsFor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GoalsFor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <formula>(3 *  GamesWon__c) + (1  *  GamesDrawn__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/BL_Match__c.object
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>M-{0000000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BL_Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/ImageUrl__c.field-meta.xml
<CustomField>
    <fullName>ImageUrl__c</fullName>
    <label>ImageUrl</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/BL_LeagueDetailsController.cls
public without sharing class BL_LeagueDetailsController {

    @AuraEnabled
    public static BL_Competition__c loadCompetitionWithCompetitors(String competitionId) {
        List<BL_Competition__c> competitions = [
                SELECT
                    Id,
                    Name,
                    Start_Date__c,
                    End_Date__c,
                    Match_No__c,
                    Max_Teams__c,
                    Teams_Joined__c,
                    isPrivate__c,
                    CreatedBy.Name,
                    OwnerId,
                    Status__c,
                    TeamSize__c, (
                        SELECT
                            Id,
                            Team__c,
                            Team__r.Player1__c, Team__r.Player2__c, Team__r.Name,
                            Team__r.Player1__r.LastName, Team__r.Player1__r.Name, Team__r.Player2__r.LastName,
                            Team__r.Player2__r.Name,
                                GamesWon__c, GamesLost__c, GamesDrawn__c, GoalsFor__c, GoalsAgainst__c, GoalsDraw__c, Points__c,
                                Team__r.Player1__r.ImageUrl__c, Team__r.Player2__r.ImageUrl__c
                        FROM Competitors__r
                        ORDER BY Points__c DESC, GoalsDraw__c DESC, GoalsFor__c DESC, GoalsAgainst__c ASC, Team__r.Name ASC
                )
                FROM BL_Competition__c
                WHERE Id = :competitionId
        ];
        return competitions.size() > 0 ? competitions[0] : new BL_Competition__c();
    }

    @AuraEnabled
    public static List<BL_Match__c> loadCompetitionMatches(String competitionId, String competitorId) {
        List<BL_Match__c> matches;
        BL_DAO_Match daoMatch = new BL_DAO_Match();
        if (competitorId == null) {
            matches = daoMatch.getMatchesForCompetition(competitionId);
        } else {
            matches = daoMatch.getMatchesForCompetitionAndCompetitor(competitionId, competitorId);
        }
        return matches;
    }

    @AuraEnabled
    public static BL_Competition__c startLeagueNow(String competitionId) {
        BL_Competition__c competition = loadCompetitionWithCompetitors(competitionId);

        if (competition == null || competition.Status__c == BL_Constants.LEAGUE_STATUS_STARTED) {
            throw new AuraHandledException(Label.BL_League_already_started);
        }

        try {
            competition.Start_Date__c = System.now();
            competition.Status__c = BL_Constants.LEAGUE_STATUS_STARTED;
            update competition;
            BL_MatchService.generateMatches(competitionId);
            return competition;
        } catch (DmlException e) {
            for (Integer i = 0; i < e.getNumDml(); i++) {
                System.debug(e.getDmlMessage(i));
            }
            throw new AuraHandledException(Label.BL_Cannot_start_league);
        }
    }

    @AuraEnabled
    public static User getCurrentUser() {
        return BL_Utils.getCurrentUser();
    }
}