src/objects/BL_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>League__c</fullName>
        <label>League</label>
        <referenceTo>BL_League__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Competitor__c/fields/GamesDrawn__c.field-meta.xml
<CustomField>
    <fullName>GamesDrawn__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesDrawn</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GamesLost__c.field-meta.xml
<CustomField>
    <fullName>GamesLost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesLost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GamesWon__c.field-meta.xml
<CustomField>
    <fullName>GamesWon__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesWon</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsAgainst__c.field-meta.xml
<CustomField>
    <fullName>GoalsAgainst__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GoalsAgainst</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsDraw__c.field-meta.xml
<CustomField>
    <fullName>GoalsDraw__c</fullName>
    <formula>GoalsFor__c -  GoalsAgainst__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GoalsDraw</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsFor__c.field-meta.xml
<CustomField>
    <fullName>GoalsFor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GoalsFor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <formula>(3 *  GamesWon__c) + (1  *  GamesDrawn__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/BL_League__c.object
<CustomObject>
    <label>League</label>
    <nameField>
        <label>League Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leagues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BL_Team__c.object
<CustomObject>
    <fields>
        <fullName>Player1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Player2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams (Player2)</relationshipLabel>
        <relationshipName>Teams2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BL_LeagueEndEmailContentController.cls
public with sharing class BL_LeagueEndEmailContentController {
    public Id recordId {get; set {initializeCompetitorDetails(value);}}
    public String competitionUrl {get; set;}
    public Integer positionInLeague {get; set;}
    public String winnerTeamName {get; set;}
    public BL_Competitor__c competitor {get; set;}
    public List<BL_Competitor__c> leagueCompetitors {get; set;}

    private void initializeCompetitorDetails(String competitorId){
        system.debug(competitorId);
        List<BL_Competitor__c> competitors = [
            SELECT Id, Team__r.Name, GoalsFor__c, GoalsAgainst__c, Points__c, League__r.Name, League__c
            FROM BL_Competitor__c
            WHERE Id =: competitorId
        ];
        if(!competitors.isEmpty()){
            competitor = competitors[0];
            competitionUrl = BL_Utils.getBLCommunityUrl('League Page');

            Map<Id, BL_Competitor__c> competitorsMap = new Map<Id, BL_Competitor__c>([
                SELECT Id, Team__r.Name, Team__r.Player1__r.Name, Team__r.Player2__r.Name, GamesWon__c, GamesLost__c, GamesDrawn__c, GoalsFor__c, GoalsAgainst__c, GoalsDraw__c, Points__c
                FROM BL_Competitor__c
                WHERE League__c =: competitor.League__c
                ORDER BY Points__c DESC, GoalsDraw__c DESC, GoalsFor__c DESC, GoalsAgainst__c ASC
            ]);

            leagueCompetitors = competitorsMap.values();
            Integer index = 0;
            for (BL_Competitor__c cmp : [
                    SELECT Id, Team__r.Name
                    FROM BL_Competitor__c
                    WHERE League__c =: competitor.League__c
                    ORDER BY Points__c DESC
            ]) {
                if (index == 0) {
                    winnerTeamName = cmp.Team__r.Name;
                }
                if (cmp.Id == competitorId) {
                    positionInLeague = index + 1;
                    break;
                }
                index++;
            }
        }
    }
}