src/objects/BL_Competitor__c.object
<CustomObject>
    <label>Competitor</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Competitor__c/fields/GamesDrawn__c.field-meta.xml
<CustomField>
    <fullName>GamesDrawn__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesDrawn</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GamesLost__c.field-meta.xml
<CustomField>
    <fullName>GamesLost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesLost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GamesWon__c.field-meta.xml
<CustomField>
    <fullName>GamesWon__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesWon</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsAgainst__c.field-meta.xml
<CustomField>
    <fullName>GoalsAgainst__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GoalsAgainst</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsFor__c.field-meta.xml
<CustomField>
    <fullName>GoalsFor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GoalsFor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/RoundsLost__c.field-meta.xml
<CustomField>
    <fullName>RoundsLost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RoundsLost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/RoundsWon__c.field-meta.xml
<CustomField>
    <fullName>RoundsWon__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RoundsWon</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/classes/BL_MatchScoreService.cls
public without sharing class BL_MatchScoreService {
    public void setScoresForTeams(BL_Competitor__c competitor1, BL_Competitor__c competitor2, Decimal competitor1Score, Decimal competitor2Score, List<Decimal> team1GoalsInRound, List<Decimal> team2GoalsInRound) {
        Decimal team1TotalGoalsScored = 0;
        Decimal team2TotalGoalsScored = 0;

        for (Integer round = 0; round < team1GoalsInRound.size(); round++) {
            team1TotalGoalsScored += team1GoalsInRound[round];
            team2TotalGoalsScored += team2GoalsInRound[round];
        }

        if (competitor1Score > competitor2Score) {
            competitor1.GamesWon__c += 1;
            competitor2.GamesLost__c += 1;
        } else if (competitor1Score < competitor2Score) {
            competitor2.GamesWon__c += 1;
            competitor1.GamesLost__c += 1;
        } else if (competitor1Score == competitor2Score) {
            competitor2.GamesDrawn__c += 1;
            competitor1.GamesDrawn__c += 1;
        }

        competitor1.GoalsFor__c += team1TotalGoalsScored;
        competitor1.GoalsAgainst__c += team2TotalGoalsScored;
        competitor2.GoalsFor__c += team2TotalGoalsScored;
        competitor2.GoalsAgainst__c += team1TotalGoalsScored;
        competitor1.RoundsWon__c += competitor1Score;
        competitor1.RoundsLost__c += competitor2Score;
        competitor2.RoundsWon__c += competitor2Score;
        competitor2.RoundsLost__c += competitor1Score;
    }
}