src/objects/BL_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>League__c</fullName>
        <label>League</label>
        <referenceTo>BL_League__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Competitor__c/fields/GamesDrawn__c.field-meta.xml
<CustomField>
    <fullName>GamesDrawn__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesDrawn</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GamesLost__c.field-meta.xml
<CustomField>
    <fullName>GamesLost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesLost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GamesWon__c.field-meta.xml
<CustomField>
    <fullName>GamesWon__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesWon</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsAgainst__c.field-meta.xml
<CustomField>
    <fullName>GoalsAgainst__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GoalsAgainst</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsFor__c.field-meta.xml
<CustomField>
    <fullName>GoalsFor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GoalsFor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/RoundsLost__c.field-meta.xml
<CustomField>
    <fullName>RoundsLost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RoundsLost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/RoundsWon__c.field-meta.xml
<CustomField>
    <fullName>RoundsWon__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RoundsWon</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/BL_Match__c.object
<CustomObject>
    <fields>
        <fullName>League__c</fullName>
        <label>League</label>
        <referenceTo>BL_League__c</referenceTo>
        <relationshipLabel>Matches</relationshipLabel>
        <relationshipName>Matches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team1_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Team1 Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team1</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Matches</relationshipLabel>
        <relationshipName>Matches1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team2_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Team2 Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team2</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Matches (Team2)</relationshipLabel>
        <relationshipName>Matches2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Match</label>
    <nameField>
        <displayFormat>M-{0000000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Match__c/fields/isResolved__c.field-meta.xml
<CustomField>
    <fullName>isResolved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If match isResolved that means all rounds was played and match should be included in score tables, otherwise, statistics are not counted</description>
    <label>isResolved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/MatchDate__c.field-meta.xml
<CustomField>
    <fullName>MatchDate__c</fullName>
    <description>Datetime when match was resolved</description>
    <label>Match Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Team1Round1Goals__c.field-meta.xml
<CustomField>
    <fullName>Team1Round1Goals__c</fullName>
    <label>Team1 Round1 Goals</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Team1Round2Goals__c.field-meta.xml
<CustomField>
    <fullName>Team1Round2Goals__c</fullName>
    <label>Team1 Round2 Goals</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Team1Round3Goals__c.field-meta.xml
<CustomField>
    <fullName>Team1Round3Goals__c</fullName>
    <label>Team1 Round3 Goals</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Team1TotalGoalsScored__c.field-meta.xml
<CustomField>
    <fullName>Team1TotalGoalsScored__c</fullName>
    <formula>Team1Round1Goals__c +  Team1Round2Goals__c +  Team1Round3Goals__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Team1 Total Goals Scored</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Team2Round1Goals__c.field-meta.xml
<CustomField>
    <fullName>Team2Round1Goals__c</fullName>
    <label>Team2 Round1 Goals</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Team2Round2Goals__c.field-meta.xml
<CustomField>
    <fullName>Team2Round2Goals__c</fullName>
    <label>Team2 Round2 Goals</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Team2Round3Goals__c.field-meta.xml
<CustomField>
    <fullName>Team2Round3Goals__c</fullName>
    <label>Team2 Round3 Goals</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Team2TotalGoalsScored__c.field-meta.xml
<CustomField>
    <fullName>Team2TotalGoalsScored__c</fullName>
    <formula>Team2Round1Goals__c + Team2Round2Goals__c + Team2Round3Goals__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Team2 Total Goals Scored</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/BL_Team__c.object
<CustomObject>
    <fields>
        <fullName>Player1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BL_SinglePlayerScoreProviderController.cls
public with sharing class BL_SinglePlayerScoreProviderController {
    @AuraEnabled
    public static BL_Match__c getMatchDetails(String matchId) {
        system.debug(matchId);
        List<BL_Match__c> matchDetails = [
                SELECT  Id,isResolved__c,MatchDate__c, Team1__c, Team2__c, Team1__r.Team__r.Player1__r.Name, Team2__r.Team__r.Player1__r.Name, Team1_Score__c,Team2_Score__c, Team1TotalGoalsScored__c, Team2TotalGoalsScored__c,
                        Team1__r.GoalsFor__c,Team1__r.GoalsAgainst__c,Team1__r.GamesWon__c,Team1__r.GamesLost__c,Team1__r.GamesDrawn__c,
                        Team2__r.GoalsFor__c,Team2__r.GoalsAgainst__c,Team2__r.GamesWon__c,Team2__r.GamesLost__c,Team2__r.GamesDrawn__c, Team1Round1Goals__c,
                        Team1Round2Goals__c, Team1Round3Goals__c, Team2Round1Goals__c,Team2Round2Goals__c,Team2Round3Goals__c, Team1__r.Team__r.Player1__r.ImageUrl__c, Team2__r.Team__r.Player1__r.ImageUrl__c
                FROM BL_Match__c
                WHERE Id =: matchId
        ];
        return !matchDetails.isEmpty() ? matchDetails[0] : new BL_Match__c();
    }

    @AuraEnabled
    public static String saveMatchScoreAndUpdateCompetitorsStatistics(BL_Match__c match) {
        match.isResolved__c = true;
        try{
            update match;
            updateCompetitorsStatistics(match);
            return 'SUCCESS';
        }catch (DmlException e){
            for (Integer i = 0; i < e.getNumDml(); i++) {
                System.debug(e.getDmlMessage(i));
            }
            throw new AuraHandledException('Cannot save match score!');
        }
    }

    private static void updateCompetitorsStatistics(BL_Match__c match){
        Map<Id, BL_Competitor__c> matchCompetitorsMap = new Map<Id, BL_Competitor__c>([
                SELECT Id, GamesLost__c,GamesDrawn__c,GamesWon__c,GoalsAgainst__c,GoalsFor__c, RoundsWon__c, RoundsLost__c
                FROM BL_Competitor__c
                WHERE League__c =: match.League__c AND (Id =: match.Team1__c OR Id =: match.Team2__c)
        ]);
        matchCompetitorsMap.get(match.Team1__c).GamesLost__c += match.Team1_Score__c < match.Team2_Score__c ? 1 : 0;
        matchCompetitorsMap.get(match.Team1__c).GamesDrawn__c += match.Team1_Score__c == match.Team2_Score__c ? 1 : 0;
        matchCompetitorsMap.get(match.Team1__c).GamesWon__c += match.Team1_Score__c > match.Team2_Score__c ? 1 : 0;
        matchCompetitorsMap.get(match.Team1__c).RoundsWon__c += match.Team1_Score__c > match.Team2_Score__c ? 1 : 0;
        matchCompetitorsMap.get(match.Team1__c).RoundsLost__c += match.Team1_Score__c < match.Team2_Score__c ? 1 : 0;
        matchCompetitorsMap.get(match.Team1__c).GoalsFor__c += match.Team1_Score__c;
        matchCompetitorsMap.get(match.Team1__c).GoalsAgainst__c += match.Team2_Score__c;

        matchCompetitorsMap.get(match.Team2__c).GamesLost__c += match.Team2_Score__c < match.Team1_Score__c ? 1 : 0;
        matchCompetitorsMap.get(match.Team2__c).GamesDrawn__c += match.Team1_Score__c == match.Team2_Score__c ? 1 : 0;
        matchCompetitorsMap.get(match.Team2__c).GamesWon__c += match.Team2_Score__c > match.Team1_Score__c ? 1 : 0;
        matchCompetitorsMap.get(match.Team2__c).RoundsWon__c += match.Team2_Score__c > match.Team1_Score__c ? 1 : 0;
        matchCompetitorsMap.get(match.Team2__c).RoundsLost__c += match.Team2_Score__c < match.Team1_Score__c ? 1 : 0;
        matchCompetitorsMap.get(match.Team2__c).GoalsFor__c += match.Team2_Score__c;
        matchCompetitorsMap.get(match.Team2__c).GoalsAgainst__c += match.Team1_Score__c;

        update matchCompetitorsMap.values();
    }
}