src/objects/BL_Competition__c.object
<CustomObject>
    <fields>
        <fullName>Match_No__c</fullName>
        <label>Match No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Competition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BL_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Competitor__c/fields/Competition__c.field-meta.xml
<CustomField>
    <fullName>Competition__c</fullName>
    <label>Competition</label>
    <referenceTo>BL_Competition__c</referenceTo>
    <relationshipLabel>Competitors</relationshipLabel>
    <relationshipName>Competitors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GamesLost__c.field-meta.xml
<CustomField>
    <fullName>GamesLost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesLost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GamesWon__c.field-meta.xml
<CustomField>
    <fullName>GamesWon__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesWon</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsAgainst__c.field-meta.xml
<CustomField>
    <fullName>GoalsAgainst__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GoalsAgainst</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsFor__c.field-meta.xml
<CustomField>
    <fullName>GoalsFor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GoalsFor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/RoundsLost__c.field-meta.xml
<CustomField>
    <fullName>RoundsLost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RoundsLost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/RoundsWon__c.field-meta.xml
<CustomField>
    <fullName>RoundsWon__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RoundsWon</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/BL_Match__c.object
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>M-{0000000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Match__c/fields/Competition__c.field-meta.xml
<CustomField>
    <fullName>Competition__c</fullName>
    <label>Competition</label>
    <referenceTo>BL_Competition__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/isResolved__c.field-meta.xml
<CustomField>
    <fullName>isResolved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If match isResolved that means all rounds was played and match should be included in score tables, otherwise, statistics are not counted</description>
    <label>isResolved</label>
    <type>Checkbox</type>
</CustomField>

src/objects/BL_Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BL_TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BL_MatchScoreProviderControllerTest.cls
@IsTest
private class BL_MatchScoreProviderControllerTest {

    @IsTest
    static void testClassicLeagueMatchScore() {
        SetupDataClass setupData = new SetupDataClass();
        setupData.insertCompetition(BL_Constants.LEAGUE_RT_LEAGUE);
        setupData.insertClassicTeams();
        setupData.insertCompetitors();
        setupData.insertMatch();

        Test.startTest();
        BL_MatchScoreProviderController.updateMatchScore(
                setupData.testMatch.Id,
                2,
                0,
                new List<Decimal> {10, 10},
                new List<Decimal> {3, 3},
                Datetime.now()
        );
        Test.stopTest();

        setupData.requeryData();

        System.assertEquals(true, setupData.testMatch.isResolved__c);
        System.assertEquals(20, setupData.testCompetitors[0].GoalsFor__c);
        System.assertEquals(6, setupData.testCompetitors[0].GoalsAgainst__c);
        System.assertEquals(2, setupData.testCompetitors[0].RoundsWon__c);
        System.assertEquals(0, setupData.testCompetitors[0].RoundsLost__c);
        System.assertEquals(1, setupData.testCompetitors[0].GamesWon__c);
        System.assertEquals(1, setupData.testCompetitors[1].GamesLost__c);
    }

    @IsTest
    static void testCupMatchScore() {
        SetupDataClass setupData = new SetupDataClass();
        setupData.insertCompetition(BL_Constants.LEAGUE_RT_CUP);
        setupData.insertClassicTeams();
        setupData.insertCompetitors();
        setupData.insertMatch();

        Test.startTest();
        BL_MatchScoreProviderController.updateMatchScore(
                setupData.testMatch.Id,
                2,
                1,
                new List<Decimal> {10, 3, 10},
                new List<Decimal> {3, 10, 3},
                Datetime.now()
        );
        Test.stopTest();

        setupData.requeryData();

        System.assertEquals(true, setupData.testMatch.isResolved__c);
        System.assertEquals(23, setupData.testCompetitors[0].GoalsFor__c);
        System.assertEquals(16, setupData.testCompetitors[0].GoalsAgainst__c);
        System.assertEquals(2, setupData.testCompetitors[0].RoundsWon__c);
        System.assertEquals(1, setupData.testCompetitors[0].RoundsLost__c);
        System.assertEquals(1, setupData.testCompetitors[0].GamesWon__c);
        System.assertEquals(1, setupData.testCompetitors[1].GamesLost__c);
    }

    @IsTest
    static void testBattleRoyaleLeagueMatchScore() {
        SetupDataClass setupData = new SetupDataClass();
        setupData.insertCompetition(BL_Constants.LEAGUE_RT_BATTLE_ROYALE);
        setupData.insertBattleRoyaleAndMemberTeams();
        setupData.insertCompetitors();
        setupData.insertMatch();

        Test.startTest();
        BL_MatchScoreProviderController.updateMatchScore(
                setupData.testMatch.Id,
                2,
                0,
                new List<Decimal> {10, 10},
                new List<Decimal> {3, 3},
                Datetime.now()
        );
        Test.stopTest();

        setupData.requeryData();

        System.assertEquals(true, setupData.testMatch.isResolved__c);
        System.assertEquals(20, setupData.testCompetitors[2].GoalsFor__c);
        System.assertEquals(6, setupData.testCompetitors[2].GoalsAgainst__c);
        System.assertEquals(2, setupData.testCompetitors[2].RoundsWon__c);
        System.assertEquals(0, setupData.testCompetitors[2].RoundsLost__c);
        System.assertEquals(1, setupData.testCompetitors[2].GamesWon__c);
        System.assertEquals(1, setupData.testCompetitors[3].GamesLost__c);
    }

    class SetupDataClass {
        BL_Competition__c testLeague;
        List<BL_Team__c> testTeams = new List<BL_Team__c>();
        List<BL_Competitor__c> testCompetitors = new List<BL_Competitor__c>();
        BL_Match__c testMatch;

        public void insertCompetition(String recordTypeName) {
            testLeague = new BL_Competition__c(
                    Match_No__c = 1,
                    RecordTypeId = BL_Utils.getRecordTypeIdByDeveloperName('BL_Competition__c', recordTypeName)
            );
            insert testLeague;
        }

        public void insertClassicTeams() {
            for(Integer i = 0; i < 2; i++) {
                testTeams.add(new BL_Team__c(
                        Name = 'Test Team ' + i
                ));
            }
            insert testTeams;
        }

        public void insertBattleRoyaleAndMemberTeams() {
            List<BL_TeamMember__c> teamMembers = new List<BL_TeamMember__c>();
            for(Integer i = 0; i < 2; i++) {
                testTeams.add(new BL_Team__c(
                        Name = 'Test Team ' + i
                ));
            }
            for(Integer BRCount = 0; BRCount < 2; BRCount++) {
                testTeams.add(new BL_Team__c(
                        Name = 'Test Team ' + (2 + BRCount),
                        RecordTypeId = BL_Utils.getRecordTypeIdByDeveloperName('BL_Team__c', BL_Constants.TEAM_RT_BATTLE_ROYALE)
                ));
            }
            insert testTeams;
            for(Integer i = 0; i < 2; i++) {
                teamMembers.add(new BL_TeamMember__c(
                        Member__c = testTeams[i].Id,
                        Team__c = testTeams[i + 2].Id
                ));
            }
            insert teamMembers;
        }

        public void insertCompetitors() {
            for(Integer i = 0; i < testTeams.size(); i++) {
                testCompetitors.add(new BL_Competitor__c(
                        Competition__c = testLeague.Id,
                        Team__c = testTeams[i].Id
                ));
            }
            insert testCompetitors;
        }

        public void insertMatch() {
            testMatch = new BL_MatchBuilder()
                    .setCompetition(testLeague.Id)
                    .setTeam1(testCompetitors[0].Id)
                    .setTeam2(testCompetitors[1].Id)
                    .build();
            insert testMatch;
        }

        public void requeryData() {
            testCompetitors = [SELECT Id, GoalsFor__c, GoalsAgainst__c, RoundsLost__c, RoundsWon__c, GamesWon__c, GamesLost__c FROM BL_Competitor__c ORDER BY Team__r.Name ASC];
            testMatch = [SELECT isResolved__c FROM BL_Match__c WHERE Id = :testMatch.Id LIMIT 1];
        }
    }
}