src/objects/BL_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>League__c</fullName>
        <label>League</label>
        <referenceTo>BL_League__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BL_League__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>isCup__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isCup</label>
        <type>Checkbox</type>
    </fields>
    <label>League</label>
    <nameField>
        <label>League Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leagues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BL_Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Team__c/fields/Total_Games_Drawn__c.field-meta.xml
<CustomField>
    <fullName>Total_Games_Drawn__c</fullName>
    <label>Total Games Drawn</label>
    <summarizedField>BL_Competitor__c.GamesDrawn__c</summarizedField>
    <summaryForeignKey>BL_Competitor__c.Team__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BL_Team__c/fields/Total_Games_Lost__c.field-meta.xml
<CustomField>
    <fullName>Total_Games_Lost__c</fullName>
    <label>Total Games Lost</label>
    <summarizedField>BL_Competitor__c.GamesLost__c</summarizedField>
    <summaryForeignKey>BL_Competitor__c.Team__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BL_Team__c/fields/Total_Games_Won__c.field-meta.xml
<CustomField>
    <fullName>Total_Games_Won__c</fullName>
    <label>Total Games Won</label>
    <summarizedField>BL_Competitor__c.GamesWon__c</summarizedField>
    <summaryForeignKey>BL_Competitor__c.Team__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BL_Team__c/fields/Total_Goals_Lost__c.field-meta.xml
<CustomField>
    <fullName>Total_Goals_Lost__c</fullName>
    <label>Total Goals Lost</label>
    <summarizedField>BL_Competitor__c.GoalsAgainst__c</summarizedField>
    <summaryForeignKey>BL_Competitor__c.Team__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BL_Team__c/fields/Total_Goals_Scored__c.field-meta.xml
<CustomField>
    <fullName>Total_Goals_Scored__c</fullName>
    <label>Total Goals Scored</label>
    <summarizedField>BL_Competitor__c.GoalsFor__c</summarizedField>
    <summaryForeignKey>BL_Competitor__c.Team__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BL_Team__c/fields/TotalRoundsLost__c.field-meta.xml
<CustomField>
    <fullName>TotalRoundsLost__c</fullName>
    <label>TotalRoundsLost</label>
    <summarizedField>BL_Competitor__c.RoundsLost__c</summarizedField>
    <summaryForeignKey>BL_Competitor__c.Team__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BL_Team__c/fields/TotalRoundsWon__c.field-meta.xml
<CustomField>
    <fullName>TotalRoundsWon__c</fullName>
    <label>TotalRoundsWon</label>
    <summarizedField>BL_Competitor__c.RoundsWon__c</summarizedField>
    <summaryForeignKey>BL_Competitor__c.Team__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/classes/BL_TeamRecordDetailController.cls
public with sharing class BL_TeamRecordDetailController {
    @AuraEnabled
    public static String getUserContactId() {
        return BL_Utils.getCurrentUser().ContactId;
    }

    @AuraEnabled
    public static BL_Team__c loadTeamStatistics(String teamId) {
        List<BL_Team__c> teamStatistics = [
                SELECT Id, Total_Games_Won__c, Total_Games_Drawn__c, Total_Games_Lost__c, Total_Goals_Scored__c, Total_Goals_Lost__c, TotalRoundsWon__c, TotalRoundsLost__c
                FROM BL_Team__c
                WHERE Id =: teamId
        ];
        return teamStatistics.isEmpty() ? new BL_Team__c() : teamStatistics[0];
    }

    @AuraEnabled
    public static List<BL_League__c> getTeamCompetitions(String teamId) {
        List<String> compsIds = new List<String>();
        for (BL_Competitor__c comp : [SELECT Id, League__c FROM BL_Competitor__c WHERE Team__c = :teamId]) {
            compsIds.add(comp.League__c);
        }
        return [SELECT isCup__c, Start_Date__c, End_Date__c, Name FROM BL_League__c WHERE Id IN :compsIds];
    }

    @AuraEnabled
    public static Attachment getProfilePicture(Id parentId) {
        List<Attachment> att = [
                SELECT Id, Name, LastModifiedDate, ContentType
                FROM Attachment
                WHERE parentid = :ParentId AND ContentType IN ('image/png', 'image/jpeg', 'image/gif')
                ORDER BY LastModifiedDate DESC
                LIMIT 1
        ];
        if(att.size() > 0) {
            return att[0];
        } else return new Attachment();
    }

    @AuraEnabled
    public static void savePicture(Id parentId, String fileName, String base64Data, String contentType) {
        List<Attachment> oldAttachments = [SELECT Id FROM Attachment WHERE ParentId=:parentId];
        delete oldAttachments;
        Attachment attachment = new Attachment();
        attachment.parentId = parentId;
        attachment.body = EncodingUtil.base64Decode(base64Data);
        attachment.name = fileName;
        attachment.contentType = contentType;
        insert attachment;
    }
}