src/objects/BL_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BL_League__c.object
<CustomObject>
    <label>League</label>
    <nameField>
        <label>League Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leagues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BL_Team__c.object
<CustomObject>
    <fields>
        <fullName>Player1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Player2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams (Player2)</relationshipLabel>
        <relationshipName>Teams2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BL_UserSettings.cls
public class BL_UserSettings {

    @AuraEnabled
    public Id userId;
    @AuraEnabled
    public Id playerId;
    @AuraEnabled
    public Id leagueId;
    @AuraEnabled
    public Boolean isLeagueOwner;
    @AuraEnabled
    public Boolean isLeagueCompetitor;

    public BL_UserSettings() {
        this.userId = UserInfo.getUserId();
        populatePlayerId();
    }

    public BL_UserSettings populateSettingsForLeague(Id leagueId) {
        this.leagueId = leagueId;

        BL_DAO_League daoLeague = new BL_DAO_League();
        BL_League__c league = daoLeague.getLeagueById(leagueId);
        populateIsLeagueOwner(league);

        BL_DAO_Competitor daoCompetitor = new BL_DAO_Competitor();
        List<BL_Competitor__c> competitors = daoCompetitor.getCompetitorsByLeagueId(leagueId);
        populateIsLeagueCompetitor(competitors);

        return this;
    }

    private void populatePlayerId() {
        User user = BL_Utils.getCurrentUser();
        this.playerId = user.ContactId;
    }

    private void populateIsLeagueOwner(BL_League__c league) {
        this.isLeagueOwner = league.OwnerId == this.userId;
    }

    private void populateIsLeagueCompetitor(List<BL_Competitor__c> competitors) {
        Boolean result = false;

        for(BL_Competitor__c competitor : competitors) {
            if(competitor.Team__r.Player1__c == playerId || competitor.Team__r.Player2__c == playerId) {
                result = true;
                break;
            }
        }

        this.isLeagueCompetitor = result;
    }
}