src/objects/BL_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>League__c</fullName>
        <label>League</label>
        <referenceTo>BL_League__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BL_League__c.object
<CustomObject>
    <fields>
        <fullName>Match_No__c</fullName>
        <label>Match No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>League</label>
    <nameField>
        <label>League Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leagues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BL_Match__c.object
<CustomObject>
    <fields>
        <fullName>League__c</fullName>
        <label>League</label>
        <referenceTo>BL_League__c</referenceTo>
        <relationshipLabel>Matches</relationshipLabel>
        <relationshipName>Matches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team1</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Matches</relationshipLabel>
        <relationshipName>Matches1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team2</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Matches (Team2)</relationshipLabel>
        <relationshipName>Matches2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Match</label>
    <nameField>
        <displayFormat>M-{0000000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Match__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <label>Round</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/BL_Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BL_TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BL_LeagueMatchesServiceTest.cls
@isTest
private class BL_LeagueMatchesServiceTest {
    @isTest
    static void testMatchGenerationForClassicLeagueEvenNumberOfTeams() {
        SetupDataClass setupData = new SetupDataClass();
        setupData.insertLeague(BL_Constants.LEAGUE_RT_CLASSIC, 1);
        setupData.insertClassicTeamsForLeague(setupData.testLeague.Id, 4);

        Test.startTest();
        BL_LeagueMatchesService.generateMatchesAfterLeagueStarted(setupData.testLeague.Id);
        Test.stopTest();

        List<BL_Match__c> matches = [SELECT Id FROM BL_Match__c];

        System.assertEquals(6, matches.size());
    }

    @isTest
    static void testMatchGenerationForClassicLeagueOddNumberOfTeams() {
        SetupDataClass setupData = new SetupDataClass();
        setupData.insertLeague(BL_Constants.LEAGUE_RT_CLASSIC, 1);
        setupData.insertClassicTeamsForLeague(setupData.testLeague.Id, 5);

        Test.startTest();
        BL_LeagueMatchesService.generateMatchesAfterLeagueStarted(setupData.testLeague.Id);
        Test.stopTest();

        List<BL_Match__c> matches = [SELECT Id FROM BL_Match__c];

        System.assertEquals(10, matches.size());
    }

    @isTest
    static void testMatchGenerationForBattleRoyaleLeague() {
        SetupDataClass setupData = new SetupDataClass();
        setupData.insertLeague(BL_Constants.LEAGUE_RT_BATTLE_ROYALE, 2);

        setupData.insertBattleRoyaleTeamsForLeague(setupData.testLeague.Id, 3, 2);

        Test.startTest();
        BL_LeagueMatchesService.generateMatchesAfterLeagueStarted(setupData.testLeague.Id);
        Test.stopTest();

        List<BL_Match__c> generatedMatches = [SELECT Id, Round__c, Team1__r.Name, Team2__r.Name FROM BL_Match__c];
        System.assertEquals(24, generatedMatches.size());

        Integer roundOneMatches = 0;
        Integer roundTwoMatches = 0;
        for (BL_Match__c match : generatedMatches) {
            if (match.Round__c == 1) {
                roundOneMatches++;
            } else if (match.Round__c == 2) {
                roundTwoMatches++;
            }
        }
        System.assertEquals(12, roundOneMatches);
        System.assertEquals(12, roundTwoMatches);
    }

    class SetupDataClass {
        public BL_League__c testLeague;

        public void insertLeague(String recordTypeDevName, Integer rounds) {
            testLeague = new BL_League__c(
                    RecordTypeId = BL_Utils.getRecordTypeIdByDeveloperName('BL_League__c', recordTypeDevName),
                    Match_No__c = rounds
            );
            insert testLeague;
        }

        public void insertClassicTeamsForLeague(Id leagueId, Integer numberOfTeams) {
            List<BL_Team__c> teams = new List<BL_Team__c>();
            List<BL_Competitor__c> competitors = new List<BL_Competitor__c>();

            for (Integer i = 0; i < numberOfTeams; i++) {
                BL_Team__c team = new BL_Team__c(Name = 'test team ' + i);
                teams.add(new BL_Team__c(Name = 'test team ' + i));
            }
            insert teams;
            for (Integer i = 0; i < numberOfTeams; i++) {
                BL_Competitor__c competitor = new BL_Competitor__c(League__c = leagueId, Team__c = teams[i].Id);
                competitors.add(new BL_Competitor__c(League__c = leagueId, Team__c = teams[i].Id));
            }
            insert competitors;
        }

        public void insertBattleRoyaleTeamsForLeague(Id leagueId, Integer parentTeams, Integer memberTeams) {
            List<BL_Team__c> teams = new List<BL_Team__c>();
            List<BL_TeamMember__c> teamMembers = new List<BL_TeamMember__c>();
            List<BL_Competitor__c> competitors = new List<BL_Competitor__c>();
            Id battleRoyaleTeamRTId = BL_Utils.getRecordTypeIdByDeveloperName('BL_Team__c', BL_Constants.TEAM_RT_BATTLE_ROYALE);

            for (Integer i = 0; i < parentTeams; i++) {
                teams.add(new BL_Team__c(Name = 'test Battle Royale team ' + i, RecordTypeId = battleRoyaleTeamRTId));
            }
            for (Integer j = 0; j < memberTeams*parentTeams; j++) {
                teams.add(new BL_Team__c(Name = 'test team ' + j));
            }

            insert teams;

            System.debug(teams.size());
            for (Integer i = 0; i < parentTeams; i++) {
                for (Integer j = parentTeams + memberTeams * i ; j < parentTeams + memberTeams * (i+1); j++) {
                    teamMembers.add(new BL_TeamMember__c(Team__c = teams[i].Id, Member__c = teams[j].Id));
                }
            }
            insert teamMembers;

            for (Integer i = 0; i < teams.size(); i++) {
                competitors.add(new BL_Competitor__c(League__c = leagueId, Team__c = teams[i].Id));
            }
            insert competitors;
        }
    }
}