src/objects/BL_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>League__c</fullName>
        <label>League</label>
        <referenceTo>BL_League__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Competitor__c/fields/GamesDrawn__c.field-meta.xml
<CustomField>
    <fullName>GamesDrawn__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesDrawn</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GamesLost__c.field-meta.xml
<CustomField>
    <fullName>GamesLost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesLost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GamesWon__c.field-meta.xml
<CustomField>
    <fullName>GamesWon__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GamesWon</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsAgainst__c.field-meta.xml
<CustomField>
    <fullName>GoalsAgainst__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GoalsAgainst</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsDraw__c.field-meta.xml
<CustomField>
    <fullName>GoalsDraw__c</fullName>
    <formula>GoalsFor__c -  GoalsAgainst__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GoalsDraw</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/GoalsFor__c.field-meta.xml
<CustomField>
    <fullName>GoalsFor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GoalsFor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/Is_Direct_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Is_Direct_Competitor__c</fullName>
    <formula>IF(
  Competition__r.RecordType.DeveloperName != &quot;Battle_Royale&quot;,
  true,
  Team__r.RecordType.DeveloperName = &apos;Battle_Royale&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Direct Competitor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <formula>(3 *  GamesWon__c) + (1  *  GamesDrawn__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/RoundsLost__c.field-meta.xml
<CustomField>
    <fullName>RoundsLost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RoundsLost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BL_Competitor__c/fields/RoundsWon__c.field-meta.xml
<CustomField>
    <fullName>RoundsWon__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RoundsWon</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/BL_Team__c.object
<CustomObject>
    <fields>
        <fullName>Player1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Player2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams (Player2)</relationshipLabel>
        <relationshipName>Teams2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BL_TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BL_DAO_Competitor.cls
public class BL_DAO_Competitor {

    public List<BL_Competitor__c> getCompetitorsByLeagueId(Id leagueId) {
        return [
                SELECT
                        Id,
                        GamesWon__c,
                        GamesDrawn__c,
                        GamesLost__c,
                        GoalsFor__c,
                        GoalsAgainst__c,
                        GoalsDraw__c,
                        Is_Direct_Competitor__c,
                        Points__c,
                        Team__r.Player1__c,
                        Team__r.Player2__c,
                        Team__r.RecordType.DeveloperName
                FROM BL_Competitor__c
                WHERE League__c = :leagueId
        ];
    }

    public BL_Competitor__c getCompetitorByPlayerIdAndLeagueId(Id playerId, Id leagueId) {
        return [
                SELECT
                        Id,
                        GamesWon__c,
                        GamesDrawn__c,
                        GamesLost__c,
                        GoalsFor__c,
                        GoalsAgainst__c,
                        GoalsDraw__c,
                        Is_Direct_Competitor__c,
                        Points__c,
                        Team__r.Player1__c,
                        Team__r.Player2__c,
                        Team__r.RecordType.DeveloperName
                FROM BL_Competitor__c
                WHERE League__c = :leagueId
                AND (
                        Team__r.Player1__c = :playerId
                        OR Team__r.Player2__c = :playerId
                )
                LIMIT 1
        ];
    }

    public BL_Competitor__c getCompetitorByPlayerIdAndLeagueIdAndTeamRecordTypeDevName(Id playerId, Id leagueId, String teamRecordType) {
        return [
                SELECT
                        Id,
                        GamesWon__c,
                        GamesDrawn__c,
                        GamesLost__c,
                        GoalsFor__c,
                        GoalsAgainst__c,
                        GoalsDraw__c,
                        Is_Direct_Competitor__c,
                        Points__c,
                        Team__r.Player1__c,
                        Team__r.Player2__c,
                        Team__r.RecordType.DeveloperName
                FROM BL_Competitor__c
                WHERE League__c = :leagueId
                AND (
                        Team__r.Player1__c = :playerId
                        OR Team__r.Player2__c = :playerId
                )
                AND Team__r.RecordType.DeveloperName = :teamRecordType
                LIMIT 1
        ];
    }

    public List<BL_Competitor__c> getCompetitorsByLeagueIdAndParentTeamId(Id leagueId, Id parentTeamId) {
        return [
                SELECT
                        Id,
                        GamesWon__c,
                        GamesDrawn__c,
                        GamesLost__c,
                        GoalsFor__c,
                        GoalsAgainst__c,
                        GoalsDraw__c,
                        Is_Direct_Competitor__c,
                        Points__c,
                        Team__r.Player1__c,
                        Team__r.Player2__c,
                        Team__r.RecordType.DeveloperName
                FROM BL_Competitor__c
                WHERE League__c = :leagueId
                AND Team__c IN (
                        SELECT Member__c
                        FROM BL_TeamMember__c
                        WHERE Team__c = :parentTeamId
                )
        ];
    }

    public BL_Competitor__c getParentCompetitorByMemberTeamIdAndLeagueId(Id memberTeamId, Id leagueId) {
        List<BL_Competitor__c> competitor = [
                SELECT Id, GamesLost__c, GamesWon__c, GamesDrawn__c, RoundsWon__c, RoundsLost__c, GoalsAgainst__c, GoalsFor__c, GoalsDraw__c
                FROM bl_competitor__c
                WHERE League__c = :leagueId
                AND Team__c IN (
                        SELECT Team__c
                        FROM BL_TeamMember__c
                        WHERE Member__c = :memberTeamId
                )
                LIMIT 1
        ];
        return competitor.isEmpty() ? null : competitor[0];
    }

    public Map<Id, BL_Competitor__c> getCompetitorsMapByIds(List<Id> ids) {
        return new Map<ID, BL_Competitor__c>([
                SELECT
                        Id,
                        Team__c,
                        GamesLost__c,
                        GamesDrawn__c,
                        GamesWon__c,
                        GoalsAgainst__c,
                        GoalsFor__c,
                        RoundsWon__c,
                        RoundsLost__c
                FROM BL_Competitor__c
                WHERE Id IN :ids
        ]);
    }
}