src/objects/BL_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Competitor__c/fields/Competition__c.field-meta.xml
<CustomField>
    <fullName>Competition__c</fullName>
    <label>Competition</label>
    <referenceTo>BL_Competition__c</referenceTo>
    <relationshipLabel>Competitors</relationshipLabel>
    <relationshipName>Competitors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/BL_Team__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Player1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Team__c/fields/IsSinglePlayer__c.field-meta.xml
<CustomField>
    <fullName>IsSinglePlayer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Single Player</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BL_Create1PlayerCompetitorController.cls
public with sharing class BL_Create1PlayerCompetitorController {
    @AuraEnabled
    public static String insertCompetitor(BL_Competitor__c competitor) {
        User currentUser = BL_Utils.getCurrentUser();
        competitor.Team__c = getPlayerSinglePlayerTeamId(currentUser.ContactId);

        if(competitor.Team__c == null){
            competitor.Team__c = createTeamForSinglePlayerAndGetId();
        }
        if (String.isNotBlank(competitor.Competition__c)) {
            insert competitor;
            return 'SUCCESS';
        } else {
            throw new AuraHandledException(Label.BL_League_Full);
        }

    }

    private static String createTeamForSinglePlayerAndGetId(){
        User currentUser = [SELECT Id, Name, ContactId FROM User WHERE Id =: UserInfo.getUserId()];
        BL_Team__c team = new BL_Team__c();
        team.Name = currentUser.Name;
        team.Player1__c = currentUser.ContactId;
        team.IsSinglePlayer__c = true;
        team.IsActive__c = true;
        insert team;
        return team.Id;
    }

    private static String getPlayerSinglePlayerTeamId(String playerId){
        List<BL_Team__c> team = [
                SELECT Id
                FROM BL_Team__c
                WHERE Player1__c =: playerId AND IsSinglePlayer__c = true
        ];
        return team.isEmpty() ? null : team[0].Id;
    }
}