src/objects/BL_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BL_Team__c.object
<CustomObject>
    <fields>
        <fullName>Player1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Player2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams (Player2)</relationshipLabel>
        <relationshipName>Teams2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BL_TournamentEmailService.cls
public with sharing class BL_TournamentEmailService {

    public static void notifyPlayersAfterCompetitionStartOrEnd(String competitionId, String templateId) {
        BL_DAO_Competitor daoCompetitor = new BL_DAO_Competitor();
        List<BL_Competitor__c> competitors = daoCompetitor.getCompetitorsByCompetitionId(competitionId);
        List<Messaging.SingleEmailMessage> emails = createSingleMessagesListForPlayers(competitors, templateId, competitionId);

        try {
            Messaging.sendEmail(emails);
        } catch(EmailException e) {
            throw new EmailException('Error ' + e.getMessage());
        }
    }

    private static List<Messaging.SingleEmailMessage> createSingleMessagesListForPlayers(List<BL_Competitor__c> competitors, String templateId, String leagueId) {
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        Set<String> playersIds = new Set<String>();
        for(BL_Competitor__c competitor : competitors) {
            if(competitor.Team__r.Player1__c != null && !playersIds.contains(competitor.Team__r.Player1__c)) {
                emails.add(createSingleMessageForPlayer(competitor.Team__r.Player1__c, templateId, leagueId, competitor.Id));
                playersIds.add(competitor.Team__r.Player1__c);
            }
            if(competitor.Team__r.Player2__c != null && !playersIds.contains(competitor.Team__r.Player2__c)) {
                emails.add(createSingleMessageForPlayer(competitor.Team__r.Player2__c, templateId, leagueId, competitor.Id));
                playersIds.add(competitor.Team__r.Player2__c);
            }
        }
        return emails;
    }

    private static Messaging.SingleEmailMessage createSingleMessageForPlayer(String playerId, String templateId, String leagueId, String competitorId) {
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.setTargetObjectId(playerId);
        message.setWhatId(competitorId);
        message.setTemplateId(templateId);
        return message;
    }

}