src/objects/BL_Competition__c.object
<CustomObject>
    <fields>
        <fullName>Match_No__c</fullName>
        <label>Match No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Competition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Competition__c/recordTypes/League.recordType-meta.xml
<RecordType>
    <fullName>League</fullName>
    <active>true</active>
    <description>Classic round-robin tournament</description>
    <label>League</label>
</RecordType>

src/objects/BL_Competitor__c.object
<CustomObject>
    <label>Competitor</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BL_Match__c.object
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>M-{0000000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BL_MatchService.cls
public without sharing class BL_MatchService {

    public static void generateMatches(String competitionId) {
        List<BL_Competitor__c> competitors = new BL_DAO_Competitor().getCompetitorsByCompetitionId(competitionId);
        BL_Competition__c league = new BL_DAO_Competition().getCompetitionById(competitionId);

        if (competitors.size() >= 2) {
            BL_MatchGenerator matchGenerator;
            if (league.RecordType.DeveloperName == BL_Constants.LEAGUE_RT_BATTLE_ROYALE) {
                matchGenerator = new BL_BattleRoyaleMatchGenerator();
            } else {
                matchGenerator = new BL_ClassicMatchGenerator();
            }

            List<Id> competitorsIds = new List<Id>();
            List<BL_Match__c> generatedMatches = new List<BL_Match__c>();
            competitorsIds.addAll(new Map<Id, BL_Competitor__c>(competitors).keySet());

            generatedMatches = matchGenerator.generateMatches(
                    competitorsIds,
                    (Id) competitionId,
                    (Integer) league.Match_No__c
            );

            insertGeneratedMatches(generatedMatches);
        }
    }

    private static void insertGeneratedMatches(List<BL_Match__c> generatedMatches) {
        try {
            insert generatedMatches;
        } catch (DmlException e) {
            for (Integer i = 0; i < e.getNumDml(); i++) {
                System.debug(e.getDmlMessage(i));
            }
        }
    }
}