src/objects/BL_League__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Match_No__c</fullName>
        <label>Match No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Teams__c</fullName>
        <description>0 = unlimited</description>
        <label>Max Teams</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Teams_Joined__c</fullName>
        <label>Teams Joined</label>
        <summaryForeignKey>BL_Competitor__c.League__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>isPrivate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Private League</label>
        <type>Checkbox</type>
    </fields>
    <label>League</label>
    <nameField>
        <label>League Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leagues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BL_Match__c.object
<CustomObject>
    <fields>
        <fullName>League__c</fullName>
        <label>League</label>
        <referenceTo>BL_League__c</referenceTo>
        <relationshipLabel>Matches</relationshipLabel>
        <relationshipName>Matches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team1_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Team1 Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team1</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Matches</relationshipLabel>
        <relationshipName>Matches1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team2_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Team2 Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team2</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Matches (Team2)</relationshipLabel>
        <relationshipName>Matches2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Match</label>
    <nameField>
        <displayFormat>M-{0000000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Match__c/fields/CupStage__c.field-meta.xml
<CustomField>
    <fullName>CupStage__c</fullName>
    <description>Number of matches played at this cup stage</description>
    <label>Cup Stage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/BL_Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BL_CupDetailsController.cls
public with sharing class BL_CupDetailsController {
    @AuraEnabled
    public static BL_League__c loadCupDetails(String cupId) {
        List<BL_League__c> cup = [
                SELECT Id, Name, Start_Date__c, End_Date__c, Match_No__c, Max_Teams__c,Teams_Joined__c, isPrivate__c, CreatedBy.Name, isStarted__c, OwnerId
                FROM BL_League__c
                WHERE Id =: cupId
        ];
        return cup.size() > 0 ? cup[0] : new BL_League__c();
    }

    @AuraEnabled
    public static Map<Decimal, List<BL_Match__c>> loadCupRoundToMatchesMap(String cupId) {
        List<BL_Match__c> cupMatches = [
                SELECT Id, Name, Team1__r.Team__c, Team2__r.Team__c, Team1__r.Team__r.Name, Team2__r.Team__r.Name, CupStage__c, Team1_Score__c, Team2_Score__c
                FROM BL_Match__c
                WHERE League__c =: cupId
        ];
        Map<Decimal, List<BL_Match__c>> roundToMatchMap = new Map<Decimal, List<BL_Match__c>>();
        for(BL_Match__c match : cupMatches){
            if(roundToMatchMap.keySet().contains(match.CupStage__c)){
                roundToMatchMap.get(match.CupStage__c).add(match);
            }else{
                List<BL_Match__c> roundMatchesList = new List<BL_Match__c>();
                roundMatchesList.add(match);
                roundToMatchMap.put(match.CupStage__c, roundMatchesList);
            }
        }
        return roundToMatchMap;
    }

    @AuraEnabled
    public static BL_League__c startCupNow(String cupId) {
        BL_League__c cup = loadCupDetails(cupId);
        System.debug(cup);

        if(cup == null || cup.isStarted__c){
            throw new AuraHandledException('Cup already started');
        }
        try{
            cup.Start_Date__c = Date.today();
            cup.isStarted__c = true;
            update cup;
            BL_CupMatchesService.generateMatchesAfterCupStarted(cupId);
            return cup;
        }catch (DmlException e){
            for (Integer i = 0; i < e.getNumDml(); i++) {
                System.debug(e.getDmlMessage(i));
            }
            throw new AuraHandledException('Cannot start cup');
        }
    }

    @AuraEnabled
    public static String getCurrentUserId() {
        return UserInfo.getUserId();
    }
}