src/objects/BL_Match__c.object
<CustomObject>
    <fields>
        <fullName>Team1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team1</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Matches</relationshipLabel>
        <relationshipName>Matches1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team2</label>
        <referenceTo>BL_Team__c</referenceTo>
        <relationshipLabel>Matches (Team2)</relationshipLabel>
        <relationshipName>Matches2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Match</label>
    <nameField>
        <displayFormat>M-{0000000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Match__c/fields/Competition__c.field-meta.xml
<CustomField>
    <fullName>Competition__c</fullName>
    <label>Competition</label>
    <referenceTo>BL_Competition__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BL_Match__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <label>Round</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BL_MatchBuilder.cls
public without sharing class BL_MatchBuilder {
    private BL_Match__c record;

    public BL_MatchBuilder() {
        record = new BL_Match__c();
    }

    public BL_MatchBuilder setTeam1(Id teamId) {
        record.Team1__c = teamId;
        return this;
    }

    public BL_MatchBuilder setTeam2(Id teamId) {
        record.Team2__c = teamId;
        return this;
    }

    public BL_MatchBuilder setCompetition(Id competitionId) {
        record.Competition__c = competitionId;
        return this;
    }

    public BL_MatchBuilder setRound(Integer round) {
        record.Round__c = round;
        return this;
    }

    public BL_Match__c build() {
        return record;
    }
}