src/objects/BL_Team__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Player1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Player2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teams (Player2)</relationshipLabel>
        <relationshipName>Teams2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BL_CreateTeamController.cls
public with sharing class BL_CreateTeamController {
    @AuraEnabled
    public static void saveTeam(BL_Team__c team, sObject player, Boolean isBattleRoyale) {
        Id currentPlayer = BL_Utils.getCurrentUser().ContactId;
        if (isBattleRoyale == true) {
            team.Player1__c = currentPlayer;
            team.RecordTypeId = BL_Utils.getRecordTypeIdByDeveloperName('BL_Team__c', BL_Constants.TEAM_RT_BATTLE_ROYALE);
            team.IsActive__c = true;
            Database.insert(team);
        } else {
            Contact secondPlayer = (Contact) player;
            List<BL_Team__c> existingTeams = [
                    SELECT Id, Name
                    FROM BL_Team__c
                    WHERE (Player1__c = :currentPlayer AND Player2__c = :secondPlayer.Id)
                    OR (Player1__c = :secondPlayer.Id AND Player2__c = :currentPlayer)
            ];

            if (existingTeams.isEmpty()){
                team.Player1__c = currentPlayer;
                team.Player2__c = secondPlayer.Id;
                team.RecordTypeId = BL_Utils.getRecordTypeIdByDeveloperName('BL_Team__c', BL_Constants.TEAM_RT_CLASSIC);
                Database.insert(team);
            } else {
                throw new AuraHandledException('Team already existed.');
            }
        }
    }
}