src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/SurveyTemplate__c.object-meta.xml
<CustomObject>
    <label>Survey Template</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplate__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <label>Api Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/Config__c.field-meta.xml
<CustomField>
    <fullName>Config__c</fullName>
    <label>Config</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/Importance__c.field-meta.xml
<CustomField>
    <fullName>Importance__c</fullName>
    <label>Importance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/MultiSurvey__c.field-meta.xml
<CustomField>
    <fullName>MultiSurvey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multi survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/Private__c.field-meta.xml
<CustomField>
    <fullName>Private__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Private</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/QuestionSearchOptions__c.field-meta.xml
<CustomField>
    <fullName>QuestionSearchOptions__c</fullName>
    <label>Question Search Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rated</fullName>
            </value>
            <value>
                <fullName>Not rated</fullName>
            </value>
            <value>
                <fullName>Rated in self-survey</fullName>
            </value>
            <value>
                <fullName>Rated by co-workers</fullName>
            </value>
            <value>
                <fullName>Rated in self-survey or by co-workers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <label>Service Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/Submittable__c.field-meta.xml
<CustomField>
    <fullName>Submittable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submittable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/SurveyHandler__c.field-meta.xml
<CustomField>
    <fullName>SurveyHandler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Survey Handler</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SurveyConfiguration__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Survey_Handler</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SurveyConfiguration__c</referenceTo>
    <relationshipLabel>Surveys Templates</relationshipLabel>
    <relationshipName>SurveysTemplates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateAccesses__c/SurveyTemplateAccesses__c.object-meta.xml
<CustomObject>
    <label>Survey Template Access</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SurveyTemplateAccesses Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Template Accesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplateAccesses__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Template Accesses</relationshipLabel>
    <relationshipName>SurveyTemplateAccesses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateAccesses__c/fields/OnlyLeaders__c.field-meta.xml
<CustomField>
    <fullName>OnlyLeaders__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Only Leaders</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateAccesses__c/fields/SurveyTemplate__c.field-meta.xml
<CustomField>
    <fullName>SurveyTemplate__c</fullName>
    <label>Survey Template</label>
    <referenceTo>SurveyTemplate__c</referenceTo>
    <relationshipLabel>Survey Template Accesses</relationshipLabel>
    <relationshipName>SurveyTemplateAccesses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/SurveyTemplateItem__c.object-meta.xml
<CustomObject>
    <label>Survey Template Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplateItem__c/fields/IsSystem__c.field-meta.xml
<CustomField>
    <fullName>IsSystem__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is System</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/fields/QuestionId__c.field-meta.xml
<CustomField>
    <fullName>QuestionId__c</fullName>
    <label>Question Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/fields/QuestionProvider__c.field-meta.xml
<CustomField>
    <fullName>QuestionProvider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Question Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SurveyConfiguration__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Survey_Question_Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SurveyConfiguration__c</referenceTo>
    <relationshipLabel>Survey Template Items</relationshipLabel>
    <relationshipName>SurveyTemplateItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/fields/SurveyTemplate__c.field-meta.xml
<CustomField>
    <fullName>SurveyTemplate__c</fullName>
    <label>Survey Template</label>
    <referenceTo>SurveyTemplate__c</referenceTo>
    <relationshipLabel>Survey Template Items</relationshipLabel>
    <relationshipName>SurveyTemplateItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/fields/UniqueOrder__c.field-meta.xml
<CustomField>
    <fullName>UniqueOrder__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Unique Order</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SurveyTemplateExtension.cls
/**
*@author Michał Banasik
*/
public with sharing class SurveyTemplateExtension {

    public SurveyTemplate__c template {get; set;}
    public SurveyTemplateItem__c templateItem {get; set;}
    public SurveyTemplateAccesses__c templateAccess {get; set;}
    public List<TemplateQuestion> questionList {get; set;}
    public List<SeciurityContact> contactList {get; set;}
    public Boolean isClonning {get; set;}
    private Map<ID, Contact> contacts;
    private SurveyUtils.SurveyQuestionProvider achievementQuestionProvider;

    public SurveyTemplateExtension(ApexPages.StandardController stdCtrl) {
        SurveyTemplate__c oldTemplate = (SurveyTemplate__c)stdCtrl.getRecord();
        templateItem = new SurveyTemplateItem__c();
        templateAccess = new SurveyTemplateAccesses__c();
        isClonning = ApexPages.currentPage().getParameters().get('clone') == '1';
        oldTemplate = loadSurveyTemplate(oldTemplate);
        contacts = new Map<ID, Contact>([SELECT Id, Name, FirstName, LastName FROM Contact]);

        if (isClonning) {
            template = oldTemplate.clone();
            template.Name = null;
            template.ApiName__c = null;
        } else {
            template = oldTemplate;
        }

        prepareTemplateItems(oldTemplate);
        prepareAccessContacts(oldTemplate);
    }

    public class TemplateQuestion {
        public Integer index {get;set;}
        public SurveyTemplateItem__c data {get; set;}
        private SurveyTemplateExtension ext;

        public TemplateQuestion(Integer index, SurveyTemplateItem__c item, SurveyTemplateExtension ext) {
            this.ext = ext;
            this.index =  index;
            
            if (item.Id != null && ext.isClonning) {
                this.data = item.clone();
                this.data.SurveyTemplate__c = null;
            } else {
                this.data = item;
            }
            this.data.Order__c = index;
            this.data.UniqueOrder__c = ext.template.ExternalId__c + '#' + String.valueOf(index);
        }

        public void remove() {
            ext.questionList.remove(index);
            Integer i = 0;
            for (TemplateQuestion question : ext.questionList) {
                question.index = i++;
                question.data.Order__c = question.index;
                question.data.UniqueOrder__c = ext.template.ExternalId__c + '#' + String.valueOf(question.index);
            }
        }
    }

    public class SeciurityContact {
        public Integer index {get;set;}
        public SurveyTemplateAccesses__c data {get; set;}
        public String contactName {get; set;}
        private SurveyTemplateExtension ext;

        public SeciurityContact(Integer index, SurveyTemplateAccesses__c accessContact, SurveyTemplateExtension ext, Map<ID, Contact> contacts) {
            this.ext = ext;
            this.index =  index;
            this.contactName = contacts.containsKey(accessContact.Contact__c) ? contacts.get(accessContact.Contact__c).Name : System.Label.OnlyLeaders;
            if (SurveyTemplateAccesses__c.Id != null && ext.isClonning) {
                this.data = accessContact.clone();
            } else {
                this.data = accessContact;
            }
        }

        public void remove() {
            ext.contactList.remove(index);
            Integer i = 0;
            for (SeciurityContact accessContact : ext.contactList) {
                accessContact.index = i++;
            }
        }
    }

    public void addQuestion() {
        String regExp = '[/\\s+/g]';
        String configSignature = !String.isBlank(getQuestionProviderConfigSignature()) ? getQuestionProviderConfigSignature() : ' ';
        if (validateQuestion()){
            if (templateItem.Config__c.replaceAll(regExp, '') == configSignature.replaceAll(regExp, '')){
                templateItem.Config__c = '';
            }
            questionList.add(new TemplateQuestion(questionList.size(), templateItem, this));
            if (!String.isBlank(templateItem.Config__c)){
                Map<String, Object> cfg = new Map<String, Object>((Map<String, Object>)JSON.deserializeUntyped(templateItem.Config__c));
                //if (!String.isBlank((String)cfg.get(AchievementSurveyUtils.ACHIEVMENT_ID_CONF_KEY)) && cfg.get(AchievementSurveyUtils.ACHIEVMENT_ID_CONF_KEY) != null){
                //    questionList.get(questionList.size() - 1).data.Name = AchievementUtils.getAllAchievements().get((ID)cfg.get(AchievementSurveyUtils.ACHIEVMENT_ID_CONF_KEY)).Name;
                if (!String.isBlank((String)cfg.get(AchievementSurveyUtils.ACHIEVMENT_EXTERNALID_CONF_KEY)) && cfg.get(AchievementSurveyUtils.ACHIEVMENT_EXTERNALID_CONF_KEY) != null){
                    questionList.get(questionList.size() - 1).data.Name = AchievementUtils.getExternalIdAllAchievements().get((String)cfg.get(AchievementSurveyUtils.ACHIEVMENT_EXTERNALID_CONF_KEY)).Name;
                //} else if (!String.isBlank((String)cfg.get(AchievementSurveyUtils.CATEGORY_ID_CONF_KEY)) && cfg.get(AchievementSurveyUtils.CATEGORY_ID_CONF_KEY) != null) {
                    //questionList.get(questionList.size() - 1).data.Name = System.Label.Category + ': ' + AchievementService.getCategoriesMap().get((Id)cfg.get(AchievementSurveyUtils.CATEGORY_ID_CONF_KEY));
                } else if (!String.isBlank((String)cfg.get(AchievementSurveyUtils.CATEGORY_EXTERNALID_CONF_KEY)) && cfg.get(AchievementSurveyUtils.CATEGORY_EXTERNALID_CONF_KEY) != null) {
                    questionList.get(questionList.size() - 1).data.Name = System.Label.Category + ': ' + AchievementService.getExternalIdCategoriesMap().get((String)cfg.get(AchievementSurveyUtils.CATEGORY_EXTERNALID_CONF_KEY));
                } else if (cfg.get(AchievementSurveyUtils.ACHIEVMENT_GET_ALL_CONF) == 'true') {
                    questionList.get(questionList.size() - 1).data.Name = System.Label.All_Questions;
                } else if (cfg.get(AchievementSurveyUtils.ACHIEVMENT_EMAIL_CONF) == 'true'){
                    questionList.get(questionList.size() - 1).data.Name = System.Label.Question_Who;
                }
            }
            
            templateItem = new SurveyTemplateItem__c();
        }
        else {
            addError(System.Label.QuestionProviderError);
        }
    }

    public void addContact() {
        if (validateAccessContact()) {
            contactList.add(new SeciurityContact(contactList.size(), templateAccess, this, contacts));
            templateAccess = new SurveyTemplateAccesses__c();
        } else {
            addError(System.Label.SurveyTemplateAccesses_AddContactAccess_Error);
        }
    }

    public void setTemplateItemConfig(){
        templateItem.Config__c = getQuestionProviderConfigSignature();
    }

    public void setTemplateConfig(){
        template.Config__c = getSurveyHandlerConfigSignature();
    }

    public PageReference save() {
        String regExp = '[/\\s+/g]';
        SavePoint sp = Database.setSavePoint();
        Boolean isNew = template.Id == null;
        String configSignature = !String.isBlank(getSurveyHandlerConfigSignature()) ? getSurveyHandlerConfigSignature() : ' ';

        if (template.Config__c.replaceAll(regExp, '') == configSignature.replaceAll(regExp, '')){
            template.Config__c = '';
        }
        try {
            upsert template;

            Map<ID, SurveyTemplateItem__c> oldItems = new Map<ID, SurveyTemplateItem__c>([SELECT Id FROM SurveyTemplateItem__c WHERE SurveyTemplate__c = :template.Id]);
            Map<ID, SurveyTemplateAccesses__c> oldAccess = new Map<ID, SurveyTemplateAccesses__c>([SELECT Id FROM SurveyTemplateAccesses__c WHERE SurveyTemplate__c = :template.Id]);

            List<SurveyTemplateItem__c> itemsToUpdate = new List<SurveyTemplateItem__c>();
            List<SurveyTemplateItem__c> itemsToInsert = new List<SurveyTemplateItem__c>();
            List<SurveyTemplateItem__c> itemsToDelete = new List<SurveyTemplateItem__c>();

            List<SurveyTemplateAccesses__c> accessToUpdate = new List<SurveyTemplateAccesses__c>();
            List<SurveyTemplateAccesses__c> accessToInsert = new List<SurveyTemplateAccesses__c>();
            List<SurveyTemplateAccesses__c> accessToDelete = new List<SurveyTemplateAccesses__c>();

            for (TemplateQuestion question : questionList) {
                if (question.data.Id == null) {
                    question.data.SurveyTemplate__c = template.Id;
                    itemsToInsert.add(question.data);
                } else if (oldItems.containsKey(question.data.Id)) {
                    itemsToUpdate.add(question.data);
                    oldItems.remove(question.data.Id);
                }
            }

            for (SurveyTemplateItem__c question : oldItems.values()) {
                itemsToDelete.add(question);
            }

            for (SeciurityContact contact : contactList) {
                if (contact.data.Id == null) {
                    contact.data.SurveyTemplate__c = template.Id;
                    accessToInsert.add(contact.data);
                } else if (oldAccess.containsKey(contact.data.Id)) {
                    accessToUpdate.add(contact.data);
                    oldAccess.remove(contact.data.Id);
                }
            }

            for (SurveyTemplateAccesses__c contact : oldAccess.values()) {
                accessToDelete.add(contact);
            }

            delete accessToDelete;
            insert accessToInsert;
            update accessToUpdate;

            delete itemsToDelete;
            insert itemsToInsert;
            update itemsToUpdate;

        } catch (Exception e) {
            ApexPages.addMessages(e);
            Database.rollback(sp);
            if (isNew){
                template = template.clone();
            }
            return null;
        }

        return cancel();
    }

    public PageReference cancel() {
        return new ApexPages.StandardController(template).view();
    }

    public List<SelectOption> getContacts() {
        List<SelectOption> options = new List<SelectOption>();

        options.add(new SelectOption('', Label.None));
        for (Contact c : contacts.values()) {
            options.add(new SelectOption(c.Id, c.LastName+' '+c.FirstName));
        }
        
        return options;
    }

    public void clearContactList() {
        contactList.clear();
    }

    public PageReference checkedRequired() {
        if (templateItem.IsSystem__c) {
            templateItem.Required__c = true;
        }
        return null;
    }

    private SurveyTemplate__c loadSurveyTemplate(SurveyTemplate__c temp) {
        if (temp.Id != null) {
        return [SELECT Id, Name, Description__c, ApiName__c, Active__c, Private__c, Submittable__c, MultiSurvey__c, Importance__c, StartDate__c, EndDate__c, ServiceName__c, SurveyHandler__c, Config__c, QuestionSearchOptions__c, ExternalId__c,
                    (SELECT Id, Name, Order__c, QuestionId__c, SurveyTemplate__c, QuestionProvider__c, Required__c, IsSystem__c, Config__c FROM SurveyTemplateItems__r),
                    (SELECT Id, Name, SurveyTemplate__c, Contact__c, OnlyLeaders__c FROM SurveyTemplateAccesses__r)
                FROM SurveyTemplate__c 
                WHERE Id =:temp.Id
                LIMIT 1];
        }
        return temp;
    }

    private void prepareTemplateItems(SurveyTemplate__c temp) {
        questionList = new List<TemplateQuestion>();
        Integer i = 0;
        for (SurveyTemplateItem__c item : temp.SurveyTemplateItems__r) {
            questionList.add(new TemplateQuestion(i++, item, this));
        }
    }

    private void prepareAccessContacts(SurveyTemplate__c temp) {
        contactList = new List<SeciurityContact>();
        Integer i = 0;
        for (SurveyTemplateAccesses__c item : temp.SurveyTemplateAccesses__r) {
            contactList.add(new SeciurityContact(i++, item, this, contacts));
        }
    }

    private Boolean validateQuestion(){
        if (String.isBlank(templateItem.QuestionProvider__c)) {
            return false;
        }
        return true;
    }

    private Boolean validateAccessContact(){
        if ((templateAccess.Contact__c == null && !templateAccess.OnlyLeaders__c) ||
            (templateAccess.Contact__c != null && templateAccess.OnlyLeaders__c)) {
            return false;
        }
        return true;
    }


    private static void addError(String message){
        ApexPages.addMessage(
            new ApexPages.Message(ApexPages.Severity.ERROR, message)
        );
    }

    private String getSurveyHandlerConfigSignature(){
        if (!String.isBlank(template.SurveyHandler__c)){
            return SurveyUtils.getConfigSignature(template.SurveyHandler__c);
        }
        return '';
    }

    private String getQuestionProviderConfigSignature(){
        if (!String.isBlank(templateItem.QuestionProvider__c)){
            return SurveyUtils.getConfigSignature(templateItem.QuestionProvider__c);
        }
        return '';
    }
}