src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsLeader__c.field-meta.xml
<CustomField>
    <fullName>IsLeader__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Leader</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyConfiguration__c/SurveyConfiguration__c.object-meta.xml
<CustomObject>
    <label>Survey Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplate__c/SurveyTemplate__c.object-meta.xml
<CustomObject>
    <label>Survey Template</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplate__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <label>Api Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/Config__c.field-meta.xml
<CustomField>
    <fullName>Config__c</fullName>
    <label>Config</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/Importance__c.field-meta.xml
<CustomField>
    <fullName>Importance__c</fullName>
    <label>Importance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/MultiSurvey__c.field-meta.xml
<CustomField>
    <fullName>MultiSurvey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multi survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/Private__c.field-meta.xml
<CustomField>
    <fullName>Private__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Private</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/Submittable__c.field-meta.xml
<CustomField>
    <fullName>Submittable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submittable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/SurveyHandler__c.field-meta.xml
<CustomField>
    <fullName>SurveyHandler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Survey Handler</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SurveyConfiguration__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Survey_Handler</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SurveyConfiguration__c</referenceTo>
    <relationshipLabel>Surveys Templates</relationshipLabel>
    <relationshipName>SurveysTemplates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateAccesses__c/SurveyTemplateAccesses__c.object-meta.xml
<CustomObject>
    <label>Survey Template Access</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SurveyTemplateAccesses Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Template Accesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplateAccesses__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Template Accesses</relationshipLabel>
    <relationshipName>SurveyTemplateAccesses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateAccesses__c/fields/OnlyLeaders__c.field-meta.xml
<CustomField>
    <fullName>OnlyLeaders__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Only Leaders</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateAccesses__c/fields/SurveyTemplate__c.field-meta.xml
<CustomField>
    <fullName>SurveyTemplate__c</fullName>
    <label>Survey Template</label>
    <referenceTo>SurveyTemplate__c</referenceTo>
    <relationshipLabel>Survey Template Accesses</relationshipLabel>
    <relationshipName>SurveyTemplateAccesses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SurveyFrontController.cls
global with sharing class SurveyFrontController {

    private static SurveyFrontController instance = null;
    private Map<String, SurveyTemplate__c> templates = new Map<String, SurveyTemplate__c>();

    global static SurveyFrontController getInstance() {
        if (instance == null) {
            instance = new SurveyFrontController();
        }
        return instance;
    }

    private SurveyFrontController() {
        getAllVaiableTemplates();
    }

    global List<SurveyModel.TemplateInfo> getTemplatesInfo(SurveyUtils.Request request) {
        validateRequest(request);
        List<SurveyModel.TemplateInfo> templatesInfo = new List<SurveyModel.TemplateInfo>();
        for (SurveyTemplate__c template : templates.values()) {
            if (!template.Private__c || (template.Private__c && checkTemplateAccess(request.userId, template.SurveyTemplateAccesses__r))) {
                SurveyModel.TemplateInfo templateInfo = new SurveyModel.TemplateInfo(template);
                SurveyUtils.SurveyConfig cfg = new SurveyUtils.SurveyConfig(template);
                templateInfo.surveys.addAll(SurveyUtils.getSurveyHandler(template.SurveyHandler__r.Name).getSurveyToTemplateInfo(cfg, templateInfo, request));
                templatesInfo.add(templateInfo);
            }
        }
        return templatesInfo;
    }


    global SurveyModel.Template getTemplate(SurveyUtils.TemplateRequest request) {
        validateTemplateRequest(request);
        SurveyUtils.TemplateContext templateContext = new SurveyUtils.TemplateContext(request);
        SurveyModel.Template template = templateContext.getTemplate();
        validateTamplateQuestions(template);
        return template;
    }


    global SurveyModel.Survey getSurvey(SurveyUtils.SurveyRequest request) {
        validateSurveyRequest(request);
        SurveyUtils.SurveyContext templateContext = new SurveyUtils.SurveyContext(request);
        SurveyModel.Survey survey = templateContext.getSurvey();
        return survey;
    }

    global SurveyModel.Survey saveSurvey(String rawSurvey) {
        SurveyModel.Survey survey = parseSurvey(rawSurvey);
        SurveyUtils.SurveyRequest request = new SurveyUtils.SurveyRequest(survey);
        validateSurveyRequest(request);
        SurveyUtils.SurveyContext surveyContext = new SurveyUtils.SurveyContext(request, survey);
        surveyContext.saveSurvey();
        return getSurvey(request);
    }

    private Map<String, SurveyTemplate__c> getAllVaiableTemplates() {
        if (templates.values().isEmpty()) {
            for (SurveyTemplate__c item : [SELECT Id, Name, ApiName__c, StartDate__c, EndDate__c, Importance__c, Description__c, Private__c, Submittable__c, MultiSurvey__c, Active__c, SurveyHandler__r.Name, Config__c,
                                               (SELECT  OnlyLeaders__c, Contact__r.Email FROM SurveyTemplateAccesses__r)
                                               FROM SurveyTemplate__c
                                               WHERE Active__c = true
                                                    AND (StartDate__c = null OR StartDate__c <= TODAY)
                                                    AND (EndDate__c = null OR EndDate__c >= TODAY)
                                                ORDER BY Name]) {
                templates.put(item.ApiName__c, item);
            }
        }
        return templates;
    }

    public List<SurveyModel.Survey> getSurveysToCompare(SurveyUtils.SurveyRequest request) {
        return null;
    }

    private void validateRequest(SurveyUtils.Request request) {
        if (String.isBlank(request.userId)) {
            throw new SurveyFrontControllerException(System.Label.UserIdFieldValueIsMandatory);
        }

    }

    private void validateTemplateRequest(SurveyUtils.TemplateRequest request) {
        validateRequest(request);
        validateTemplateApiNameAndAccessLevel(request);
        if (String.isBlank(request.templateApiName)) {
            throw new SurveyFrontControllerException(System.Label.TemplateApiNameFieldValueIsMandatory);
        }
    }

    private void validateSurveyRequest(SurveyUtils.SurveyRequest request) {
        validateTemplateRequest(request);
        /*
        if (String.isBlank(request.surveyId)) {
            throw new SurveyFrontControllerException('surveyId field value is mandatory!');
        }
        */
    }

    private void validateTemplateApiNameAndAccessLevel(SurveyUtils.TemplateRequest request) {
        if (templates.get(request.templateApiName) == null) {
            throw new SurveyFrontControllerException(String.format(System.Label.NotFoundTemplate, new List<String>{request.templateApiName}));
        }

        if (!checkTemplateAccess(request.userId, templates.get(request.templateApiName).SurveyTemplateAccesses__r) && templates.get(request.templateApiName).Private__c) {
            throw new SurveyFrontControllerException(System.Label.YouNotHavePermission);
        }
    }

    private void validateTamplateQuestions(SurveyModel.Template template) {
        validateTamplateDates(template);
        if (template.questions.isEmpty()) {
            throw new SurveyFrontControllerException(String.format(System.Label.DosentContainAnyQuestions, new List<String>{template.Name}));
        }
    }

    private void validateTamplateDates(SurveyModel.Template template) {
        if (!(template.startDate <= System.today() && template.endDate >= System.today()) && (template.startDate != null && template.endDate != null)) {
            throw new SurveyFrontControllerException(String.format(System.Label.TemplateNameIsNotUnavailable, new List<String>{template.Name}));
        }
    }

    private SurveyModel.Survey parseSurvey(String rawSurvey) {
        if (String.isBlank(rawSurvey)) {
            throw new SurveyFrontControllerException(System.Label.SurveyResponseCannotBeBlank);
        }
        return (SurveyModel.Survey)JSON.deserialize(rawSurvey, SurveyModel.Survey.class);
    }

    private Boolean checkTemplateAccess(String userId, List<SurveyTemplateAccesses__c> templateAccesses) {
        if (isUserHasAccess(templateAccesses, userId) || isLeader(userId)) {
            return true;
        } else {
            return false;
        }
    }

    private Boolean isUserHasAccess(List<SurveyTemplateAccesses__c> templateAccesses, String userId) {
        Boolean access = false;
        for (SurveyTemplateAccesses__c item : templateAccesses) {
            if (!item.OnlyLeaders__c && item.Contact__r.Email == userId) {
                access = true;
                break;
            }
        }
        return access;
    }

    private Boolean isLeader(String userId) {
        List<Contact> contacts = new List<Contact>();
        contacts.addAll([SELECT IsLeader__c FROM Contact WHERE Email= :userId LIMIT 1]);
        if (!contacts.isEmpty()) {
            return contacts[0].IsLeader__c;
        } else {
            return false;
        }
    }

    public class SurveyFrontControllerException extends SurveyUtils.SurveyException {}
}