force-app/main/default/objects/SurveyTemplate__c/SurveyTemplate__c.object-meta.xml
<CustomObject>
    <label>Survey Template</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplate__c/fields/Config__c.field-meta.xml
<CustomField>
    <fullName>Config__c</fullName>
    <label>Config</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/SurveyTemplateItem__c.object-meta.xml
<CustomObject>
    <label>Survey Template Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplateItem__c/fields/SurveyTemplate__c.field-meta.xml
<CustomField>
    <fullName>SurveyTemplate__c</fullName>
    <label>Survey Template</label>
    <referenceTo>SurveyTemplate__c</referenceTo>
    <relationshipLabel>Survey Template Items</relationshipLabel>
    <relationshipName>SurveyTemplateItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SurveyTemplateItemExtensionTest.cls
@isTest
private class SurveyTemplateItemExtensionTest {
    
    @isTest 
    private static void shouldEditTemplateItemConfig() {
        SurveyTemplate__c template = new SurveyTestUtils.TemplateBuilder('surveyTemplateTest').buildAndSave();
        SurveyTemplateItem__c templateItem = SurveyTestUtils.buildDefaultTemplateItem(template).buildAndSave();
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(templateItem);
        SurveyTemplateItemExtensions ext = new SurveyTemplateItemExtensions(stdCtrl);

        ext.setConfig();

        System.assertEquals(SurveyTestUtils.DEFAULT_SURVEY_CONFIGURATION_SIGNATURE, ext.templateItem.Config__c);
    }

    @isTest
    private static void shouldSaveTemplateItem() {
        SurveyTemplate__c template = new SurveyTestUtils.TemplateBuilder('surveyTemplateTest').buildAndSave();
        SurveyTemplateItem__c templateItem = SurveyTestUtils.buildDefaultTemplateItem(template).build();
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(templateItem);
        SurveyTemplateItemExtensions ext = new SurveyTemplateItemExtensions(stdCtrl);

        ext.templateItem.SurveyTemplate__c = template.Id;
        System.assertNotEquals(null, ext.save());

        System.assertEquals(1, [SELECT Count() FROM SurveyTemplateItem__c]);
    }

    @isTest
    private static void shouldSaveAndNewTemplateItem() {
        SurveyTemplate__c template = new SurveyTestUtils.TemplateBuilder('surveyTemplateTest').buildAndSave();
        SurveyTemplateItem__c templateItem = SurveyTestUtils.buildDefaultTemplateItem(template).build();
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(templateItem);
        SurveyTemplateItemExtensions ext = new SurveyTemplateItemExtensions(stdCtrl);

        ext.templateItem.SurveyTemplate__c = template.Id;
        System.assertNotEquals(null, ext.saveNew());
        
        System.assertEquals(1, [SELECT Count() FROM SurveyTemplateItem__c]);
    }

    @isTest
    private static void shouldGetExceptionWhenSaveWithoutTemplate() {
        SurveyTemplate__c template = new SurveyTestUtils.TemplateBuilder('surveyTemplateTest').buildAndSave();
        SurveyTemplateItem__c templateItem = SurveyTestUtils.buildDefaultTemplateItem(template).build();
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(templateItem);
        SurveyTemplateItemExtensions ext = new SurveyTemplateItemExtensions(stdCtrl);

        try {
            ext.save();
        } catch(DmlException e) {
            System.assert(false, 'Should throw exception when request data are invalid!');
        }
    }

    @isTest
    private static void shouldGetExceptionWhenSaveNewWithoutTemplate() {
        SurveyTemplate__c template = new SurveyTestUtils.TemplateBuilder('surveyTemplateTest').buildAndSave();
        SurveyTemplateItem__c templateItem = SurveyTestUtils.buildDefaultTemplateItem(template).build();
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(templateItem);
        SurveyTemplateItemExtensions ext = new SurveyTemplateItemExtensions(stdCtrl);

        try {
            ext.saveNew();
        } catch(DmlException e) {
            System.assert(false, 'Should throw exception when request data are invalid!');
        }
    }
}