force-app/main/default/objects/SurveyTemplate__c/SurveyTemplate__c.object-meta.xml
<CustomObject>
    <label>Survey Template</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplate__c/fields/Config__c.field-meta.xml
<CustomField>
    <fullName>Config__c</fullName>
    <label>Config</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/SurveyTemplateItem__c.object-meta.xml
<CustomObject>
    <label>Survey Template Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplateItem__c/fields/IsSystem__c.field-meta.xml
<CustomField>
    <fullName>IsSystem__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is System</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/fields/QuestionId__c.field-meta.xml
<CustomField>
    <fullName>QuestionId__c</fullName>
    <label>Question Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/fields/QuestionProvider__c.field-meta.xml
<CustomField>
    <fullName>QuestionProvider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Question Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SurveyConfiguration__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Survey_Question_Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SurveyConfiguration__c</referenceTo>
    <relationshipLabel>Survey Template Items</relationshipLabel>
    <relationshipName>SurveyTemplateItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/fields/SurveyTemplate__c.field-meta.xml
<CustomField>
    <fullName>SurveyTemplate__c</fullName>
    <label>Survey Template</label>
    <referenceTo>SurveyTemplate__c</referenceTo>
    <relationshipLabel>Survey Template Items</relationshipLabel>
    <relationshipName>SurveyTemplateItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/fields/UniqueOrder__c.field-meta.xml
<CustomField>
    <fullName>UniqueOrder__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Unique Order</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SurveyTemplateItemExtensions.cls
public with sharing class SurveyTemplateItemExtensions {

    public static final String TEMPLATE_ID_PARAM = 'templateId';
    public SurveyTemplateItem__c templateItem {get; set;}
    private ApexPages.StandardController stdCtrl;
    private AchievementSurveyUtils.AchievementQuestionProvider achievementQuestionProvider = new AchievementSurveyUtils.AchievementQuestionProvider();
    private Map<Id, String> categories;

    public SurveyTemplateItemExtensions(ApexPages.StandardController stdController) {
        if(!test.isRunningTest()) {
            stdController.addFields(new List<String>{
                'Config__c', 'Order__c', 'QuestionId__c', 'QuestionProvider__c', 'SurveyTemplate__c', 'UniqueOrder__c', 'Required__c', 'IsSystem__c'
            });
        }
        stdCtrl = stdController;
        templateItem = (SurveyTemplateItem__c)stdCtrl.getRecord();
        if (templateItem.Id == null) {
            templateItem.SurveyTemplate__c = ApexPages.currentPage().getParameters().get(TEMPLATE_ID_PARAM);
        }
    }

    public PageReference saveNew() {
        SavePoint sp = Database.setSavePoint();
        PageReference ref = null;

        setNameAndConfigItem();

        try {
            upsert templateItem;

            ref = new Pagereference(('/' + templateItem.Id).subString(0, 4) + '/e');
            ref.getParameters().put(TEMPLATE_ID_PARAM, templateItem.SurveyTemplate__c);

        } catch (System.DMLException e) {
            Database.rollback(sp);
            ApexPages.addMessages(e);
            return null;
        }

        return ref;
    }

    public PageReference save() {
        SavePoint sp = Database.setSavePoint();

        setNameAndConfigItem();

        try {
            upsert templateItem;
        } catch (System.DMLException e) {
            Database.rollback(sp);
            ApexPages.addMessages(e);
            return null;
        }

        return new Pagereference('/' + templateItem.SurveyTemplate__c);
    }

    public void setConfig() {
        templateItem.Config__c = getConfigSignature();
    }

    public PageReference checkedRequired() {
        if (templateItem.IsSystem__c) {
            templateItem.Required__c = true;
        }
        return null;
    }

    private String getConfigSignature() {
        if (!String.isBlank(templateItem.QuestionProvider__c)) {
            return SurveyUtils.getConfigSignature(templateItem.QuestionProvider__c);
        }
        return '';
    }

    private void setNameAndConfigItem() {
        String regExp = '[/\\s+/g]';

        if (templateItem.Config__c.replaceAll(regExp, '') == getConfigSignature().replaceAll(regExp, '')) {
            templateItem.Config__c = '';
        }

        if (!String.isBlank(templateItem.Config__c)) {
            Map<String, Object> cfg = new Map<String, Object>((Map<String, Object>)JSON.deserializeUntyped(templateItem.Config__c));
            //if (!String.isBlank((String)cfg.get(AchievementSurveyUtils.ACHIEVMENT_ID_CONF_KEY)) && cfg.get(AchievementSurveyUtils.ACHIEVMENT_ID_CONF_KEY) != null) {
            //    templateItem.Name = AchievementUtils.getAllAchievements().get((ID)cfg.get(AchievementSurveyUtils.ACHIEVMENT_ID_CONF_KEY)).Name;
            if (!String.isBlank((String)cfg.get(AchievementSurveyUtils.ACHIEVMENT_EXTERNALID_CONF_KEY)) && cfg.get(AchievementSurveyUtils.ACHIEVMENT_EXTERNALID_CONF_KEY) != '') {
                templateItem.Name = AchievementUtils.getExternalIdAllAchievements().get((String)cfg.get(AchievementSurveyUtils.ACHIEVMENT_EXTERNALID_CONF_KEY)).Name;
            //} else if (!String.isBlank((String)cfg.get(AchievementSurveyUtils.CATEGORY_ID_CONF_KEY)) && cfg.get(AchievementSurveyUtils.CATEGORY_ID_CONF_KEY) != null) {
                //templateItem.Name = System.Label.Category + ': ' + AchievementService.getCategoriesMap().get((Id)cfg.get(AchievementSurveyUtils.CATEGORY_ID_CONF_KEY));
            } else if (!String.isBlank((String)cfg.get(AchievementSurveyUtils.CATEGORY_EXTERNALID_CONF_KEY)) && cfg.get(AchievementSurveyUtils.CATEGORY_EXTERNALID_CONF_KEY) != '') {
                templateItem.Name = System.Label.Category + ': ' + AchievementService.getExternalIdCategoriesMap().get((String)cfg.get(AchievementSurveyUtils.CATEGORY_EXTERNALID_CONF_KEY));
            } else if (cfg.get(AchievementSurveyUtils.ACHIEVMENT_GET_ALL_CONF) == 'true') {
                templateItem.Name = System.Label.All_Questions;
            } else if (cfg.get(AchievementSurveyUtils.ACHIEVMENT_EMAIL_CONF) == 'true') {
                templateItem.Name = System.Label.Question_Who;
            }
        }
    }
}