force-app/main/default/objects/SurveyTemplate__c/SurveyTemplate__c.object-meta.xml
<CustomObject>
    <label>Survey Template</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplate__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <label>Api Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SurveyTemplateTriggerTest.cls
/**
 *  SurveyTemplate Trigger Test
 * @author Michał Banasik
 */
@isTest
private class SurveyTemplateTriggerTest {

    @isTest
    private static void shouldSetApiNameSpacesToUnderline() {
        SurveyTemplate__c template = new SurveyTestUtils.TemplateBuilder('test template name with s p a c e s').buildAndSave();

        System.assertEquals('test_template_name_with_s_p_a_c_e_s', [SELECT ApiName__c FROM SurveyTemplate__c LIMIT 1].ApiName__c);
    }

    @isTest
    private static void shouldSetApiNameCharactersToLowerCase() {
        SurveyTemplate__c template = new SurveyTestUtils.TemplateBuilder('TESTAPINAMEUPPERCASE').buildAndSave();

        System.assertEquals('testapinameuppercase', [SELECT ApiName__c FROM SurveyTemplate__c LIMIT 1].ApiName__c);
    }

    @isTest
    private static void shouldDeleteApiNamesSpecialCharacters() {
        SurveyTemplate__c template = new SurveyTestUtils.TemplateBuilder('special%name@characters#yoo!@#$%^&*()_-+=?/.,|;:]}[{').buildAndSave();

        System.assertEquals('specialnamecharactersyoo', [SELECT ApiName__c FROM SurveyTemplate__c LIMIT 1].ApiName__c);
    }
}