force-app/main/default/objects/Account/recordTypes/Britenet.recordType-meta.xml
<RecordType>
    <fullName>Britenet</fullName>
    <active>true</active>
    <description>Britenet Internal</description>
    <label>Britenet</label>
</RecordType>

force-app/main/default/objects/BTN_BriteCRM_settings__c/BTN_BriteCRM_settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>BriteCRM settings</label>
</CustomObject>

force-app/main/default/objects/BTN_Contract__c/BTN_Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>C{0000000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Contract__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/ContractLength__c.field-meta.xml
<CustomField>
    <fullName>ContractLength__c</fullName>
    <inlineHelpText>Np. określony na rok</inlineHelpText>
    <label>Contract Length</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/ContractType__c.field-meta.xml
<CustomField>
    <fullName>ContractType__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B2B</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi - 90%</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi ...</fullName>
            </value>
            <value>
                <fullName>Umowa o Dzieło</fullName>
            </value>
            <value>
                <fullName>Umowa Zlecenie</fullName>
            </value>
            <value>
                <fullName>Inny rodzaj umowy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/NoticePeriod__c.field-meta.xml
<CustomField>
    <fullName>NoticePeriod__c</fullName>
    <inlineHelpText>Standardowo przy B2B powinien być 2 mies.</inlineHelpText>
    <label>Notice Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Od zaraz</fullName>
            </value>
            <value>
                <fullName>3 dni robocze</fullName>
            </value>
            <value>
                <fullName>2 tygodnie</fullName>
            </value>
            <value>
                <fullName>1 miesiąc</fullName>
            </value>
            <value>
                <fullName>2 miesiące</fullName>
            </value>
            <value>
                <fullName>3 miesiące</fullName>
            </value>
            <value>
                <fullName>Inne</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Responsibilities__c</fullName>
    <label>Responsibilities</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/SalaryB2B__c.field-meta.xml
<CustomField>
    <fullName>SalaryB2B__c</fullName>
    <inlineHelpText>Stawka za godzinę, netto</inlineHelpText>
    <label>Salary B2B</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/SalaryUoP__c.field-meta.xml
<CustomField>
    <fullName>SalaryUoP__c</fullName>
    <inlineHelpText>Kwota za miesięczne wynagrodzenie, brutto</inlineHelpText>
    <label>Salary UoP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <label>Contract</label>
</RecordType>

force-app/main/default/objects/Case/fields/ContractLength__c.field-meta.xml
<CustomField>
    <fullName>ContractLength__c</fullName>
    <inlineHelpText>Np. określony na rok</inlineHelpText>
    <label>Contract Length</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ContractType__c.field-meta.xml
<CustomField>
    <fullName>ContractType__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2B</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi - 90%</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi ...</fullName>
            </value>
            <value>
                <fullName>Umowa o Dzieło</fullName>
            </value>
            <value>
                <fullName>Umowa Zlecenie</fullName>
            </value>
            <value>
                <fullName>Inny rodzaj umowy</fullName>
            </value>
            <value>
                <fullName>B2B (stawka netto za godzinę)</fullName>
                <isActive>false</isActive>
                <label>B2B (stawka netto za godzinę)</label>
            </value>
            <value>
                <fullName>UoP</fullName>
                <isActive>false</isActive>
                <label>UoP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <formula>IF(RecordType.Name = &apos;External Offboarding&apos;, AssignmentEndDate__c, 
IF(RecordType.Name = &apos;Internal Offboarding&apos;, ContactLastDayAtWork__c, WorkEndDate__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Guardian__c.field-meta.xml
<CustomField>
    <fullName>Guardian__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guardian</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Guardian)</relationshipLabel>
    <relationshipName>GuardianCases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Leader__c.field-meta.xml
<CustomField>
    <fullName>Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserProjectRole__c.field-meta.xml
<CustomField>
    <fullName>NewUserProjectRole__c</fullName>
    <description>BS Project Role is converted to Id during process</description>
    <label>Project Role</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Notice_Period_Comment__c.field-meta.xml
<CustomField>
    <fullName>Notice_Period_Comment__c</fullName>
    <label>Notice Period Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NoticePeriod__c.field-meta.xml
<CustomField>
    <fullName>NoticePeriod__c</fullName>
    <inlineHelpText>Standardowo przy B2B powinien być 2 mies.</inlineHelpText>
    <label>Notice Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Od zaraz</fullName>
            </value>
            <value>
                <fullName>3 dni robocze</fullName>
            </value>
            <value>
                <fullName>2 tygodnie</fullName>
            </value>
            <value>
                <fullName>1 miesiąc</fullName>
            </value>
            <value>
                <fullName>2 miesiące</fullName>
            </value>
            <value>
                <fullName>3 miesiące</fullName>
            </value>
            <value>
                <fullName>Zgodnie z kodeksem pracy</fullName>
            </value>
            <value>
                <fullName>Inne</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Responsibilities__c</fullName>
    <label>Responsibilities</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/SalaryB2B__c.field-meta.xml
<CustomField>
    <fullName>SalaryB2B__c</fullName>
    <inlineHelpText>Stawka za godzinę, netto</inlineHelpText>
    <label>Salary (za godzinę netto)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/SalaryUoP__c.field-meta.xml
<CustomField>
    <fullName>SalaryUoP__c</fullName>
    <inlineHelpText>Kwota za miesięczne wynagrodzenie, brutto</inlineHelpText>
    <label>Salary (miesięcznie brutto)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/WorkEndDate__c.field-meta.xml
<CustomField>
    <fullName>WorkEndDate__c</fullName>
    <label>Work End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/WorkStartDate__c.field-meta.xml
<CustomField>
    <fullName>WorkStartDate__c</fullName>
    <label>Work Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/WorkStartDateComment__c.field-meta.xml
<CustomField>
    <fullName>WorkStartDateComment__c</fullName>
    <label>Work Start Date Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Guardian__c.field-meta.xml
<CustomField>
    <fullName>Guardian__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guardian</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Guarded Employees</relationshipLabel>
    <relationshipName>GuardedEmployees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Leader__c.field-meta.xml
<CustomField>
    <fullName>Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Managed Employees</relationshipLabel>
    <relationshipName>ManagedEmployees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Recruit.recordType-meta.xml
<RecordType>
    <fullName>Recruit</fullName>
    <active>true</active>
    <description>Recruits</description>
    <label>Recruit</label>
</RecordType>

force-app/main/default/classes/BTN_ContractUtils_Test.cls
@isTest
private class BTN_ContractUtils_Test {
    private static final String PROJECT_ROLE_SALESFORCE = 'Salesforce';
    private static final String NOTICE_PERIOD_IMMEDIATE = 'Od zaraz';
    private static final String CONTRACT_LENGTH_UNDEFINED = 'Nieokreślony';
    private static final String CONTRACT_TYPE_B2B = 'B2B';

    private static Account britenet;
    private static Account customer;
    private static Contact recruit;
    private static Contact leader;
    private static Contact guardian;
    private static Case onboarding;

    @testSetup static void createDataStructure() {
        BTN_TestDataFactory.getHRCollaborationGroup();
        britenet = BTN_TestDataFactory.getBriteNetAccount();
        customer = BTN_AccountBuilderHelper.buildWithPrivateSectorRecordType().save();
        recruit = BTN_TestDataFactory.getRecruitContact(britenet.Id);
        leader = BTN_ContactBuilderHelper.buildWithInternalRecordType()
                .withFirstName('Test')
                .withLastName('Leader')
                .withAccount(britenet.Id)
                .withEmail('test.leader@britenet.com.pl')
                .save();
        guardian = BTN_ContactBuilderHelper.buildWithInternalRecordType()
                .withFirstName('Test')
                .withLastName('Guardian')
                .withAccount(britenet.Id)
                .withEmail('test.guardian@britenet.com.pl')
                .save();
        recruit.Leader__c = leader.Id;
        recruit.Guardian__c = guardian.Id;
        update recruit;

        onboarding = BTN_CaseBuilderHelper.buildWithExternalOnBoardingRecordType().get();
        onboarding.AccountId = customer.Id;
        onboarding.ContactId = recruit.Id;
        onboarding.NewUserProjectRole__c = PROJECT_ROLE_SALESFORCE;
        onboarding.SalaryB2B__c = 40.0;
        onboarding.ContractLength__c = CONTRACT_LENGTH_UNDEFINED;
        onboarding.ContractType__c = CONTRACT_TYPE_B2B;
        onboarding.WorkStartDate__c = Date.today().addDays(7);
        onboarding.NoticePeriod__c = NOTICE_PERIOD_IMMEDIATE;
        onboarding.Description = 'Test Description';
        onboarding.Status = BTN_ConstantRepo.CASE_STATUS_OPEN;
        insert onboarding;

        BTN_BriteCRM_settings__c setting = new BTN_BriteCRM_settings__c(
                Name = 'Default Contract Company',
                Value__c = britenet.Id
        );
        insert setting;
    }

    @isTest
    static void testCreateContractFromonboarding() {
        getTestData();

        Database.SaveResult result = BTN_ContractUtils.createContractFromOnboardingCase(onboarding);
        System.assert(result.isSuccess());

        Integer contractsCount = [
                SELECT COUNT()
                FROM BTN_Contract__c
                WHERE Contact__c = :recruit.Id
                    AND ContractLength__c = :CONTRACT_LENGTH_UNDEFINED
                    AND ContractType__c = :CONTRACT_TYPE_B2B
                    AND NoticePeriod__c = :NOTICE_PERIOD_IMMEDIATE
                    AND SalaryB2B__c = 40.0
                    AND StartDate__c = :onboarding.WorkStartDate__c
        ];
        System.assertEquals(1, contractsCount);
    }

    private static void getTestData() {
        onboarding = [
                SELECT Id, AccountId, ContactId, NewUserProjectRole__c, SalaryB2B__c, SalaryUoP__c, ContractLength__c,
                        ContractType__c, WorkStartDate__c, WorkStartDateComment__c, NoticePeriod__c, Notice_Period_Comment__c,
                        Description, EndDate__c, WorkEndDate__c, Responsibilities__c
                FROM Case
                LIMIT 1
        ][0];
        recruit = [
                SELECT Id
                FROM Contact
                WHERE RecordType.Name = :BTN_RecordTypeUtils.CONTACT_RECRUIT_RECORDTYPE
                LIMIT 1
        ][0];
        leader = [
                SELECT Id
                FROM Contact
                WHERE RecordType.Name = :BTN_RecordTypeUtils.CONTACT_INTERNAL_RECORDTYPE
                    AND LastName = 'Leader'
        ][0];
    }
}