force-app/main/default/objects/Account/recordTypes/Britenet.recordType-meta.xml
<RecordType>
    <fullName>Britenet</fullName>
    <active>true</active>
    <description>Britenet Internal</description>
    <label>Britenet</label>
</RecordType>

force-app/main/default/objects/BTN_Project__c/BTN_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Project__c/fields/BritesheetProjectId__c.field-meta.xml
<CustomField>
    <fullName>BritesheetProjectId__c</fullName>
    <externalId>true</externalId>
    <label>Britesheet Project Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BTN_Project__c/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <label>Project Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Project__c/fields/ProjectType__c.field-meta.xml
<CustomField>
    <fullName>ProjectType__c</fullName>
    <label>Project Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BTN_ProjectUtils.cls
/**
 * @author Mateusz Przywara
 * @date   2016-08-09
 * @description BTN_ProjectUtils Utils methods for BTN_Project__c sObject
 */
public with sharing class BTN_ProjectUtils {
    private static final String BS_ACCOUNT_NAME = 'Britenet';
    /**
     * @author Mateusz Przywara
     * @date   2016-08-09
     * @description Method parse List of BSS Projects to List of BTN_Projects.
     * @param bssProjects List of deserialized Projects from BSS
     * @param accounts List of SFDC Accounts.
     * @return List<BTN_Project__c> List of Salesforce Projects
    */
    public static List<BTN_Project__c> parseDTOProjectsFromBSSToSObjects(
            List<BTN_BSS_DTO.Project> bssProjects,
            List<Account> accounts
    ) {
        List<BTN_Project__c> projects = new List<BTN_Project__c>();
        Id matchedAccountId;
        for (BTN_BSS_DTO.Project projectDTOItem : bssProjects) {
            matchedAccountId = null;
            if (projectDTOItem.company_name == BS_ACCOUNT_NAME) {
                projectDTOItem.company_name = BTN_ConstantRepo.BRITENET_ACCOUNT_NAME;
            }
            try {
                if (BTN_ValidationHandler.isBSSProjectValid(projectDTOItem)) {
                    //Match valid Account by BSS company_name
                    for (Account accountItem : accounts) {
                        if (accountItem.Name == projectDTOItem.company_name) {
                            matchedAccountId = accountItem.Id;
                            break;
                        }
                    }

                    projects.add(
                            new BTN_Project__c(
                                    Name = projectDTOItem.project_name,
                                    BritesheetProjectId__c = projectDTOItem.project_id,
                                    ProjectCode__c = projectDTOItem.project_code,
                                    ProjectType__c = projectDTOItem.project_type,
                                    Account__c = matchedAccountId
                            )
                    );
                }
            } catch (Exception ex) {
                BTN_LogUtils logSystem = new BTN_LogUtils('BTN_ProjectUtils');
                logSystem.error(ex.getMessage(), BTN_Utils.getCurrentUser().Id);
                System.debug(System.Label.ExceptionInProjectProcessing);
                System.debug(ex.getMessage());
            }
        }
        return projects;
    }
}