force-app/main/default/objects/Account/recordTypes/Britenet.recordType-meta.xml
<RecordType>
    <fullName>Britenet</fullName>
    <active>true</active>
    <description>Britenet Internal</description>
    <label>Britenet</label>
</RecordType>

force-app/main/default/objects/BTN_CV__c/BTN_CV__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CID{00000000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_CV__c/fields/Account_frm__c.field-meta.xml
<CustomField>
    <fullName>Account_frm__c</fullName>
    <formula>ResourceRequest__r.Account_frm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Recruit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidates (Contact)</relationshipLabel>
    <relationshipName>Candidates1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/DateApproved__c.field-meta.xml
<CustomField>
    <fullName>DateApproved__c</fullName>
    <label>Date Approved</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/DeliveryDeadline_frm__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDeadline_frm__c</fullName>
    <formula>ResourceRequest__r.DeliveryDeadline_frm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/ResourceRequest__c.field-meta.xml
<CustomField>
    <fullName>ResourceRequest__c</fullName>
    <label>Resource request</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Resource request must not be closed</errorMessage>
        <filterItems>
            <field>BTN_ResourceRequest__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Closed Delivered, Closed Rejected</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BTN_ResourceRequest__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>CVs_lkp</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/BTN_ResourceRequest__c.object-meta.xml
<CustomObject>
    <label>Resource request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Account_frm__c.field-meta.xml
<CustomField>
    <fullName>Account_frm__c</fullName>
    <formula>IF(RecordType.DeveloperName == &apos;Auto&apos;, Opportunity__r.Account.Name,  CustomerAccount__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TS</fullName>
            </value>
            <value>
                <fullName>FIX</fullName>
            </value>
            <value>
                <fullName>SUP</fullName>
            </value>
            <value>
                <fullName>LM</fullName>
            </value>
            <value>
                <fullName>Unbillable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/ContractStart_frm__c.field-meta.xml
<CustomField>
    <fullName>ContractStart_frm__c</fullName>
    <formula>IF(RecordType.DeveloperName == &apos;Auto&apos;, TEXT(Opportunity__r.ContractStart__c), ContractStart__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Start</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Resource_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/CVsAllInFinal__c.field-meta.xml
<CustomField>
    <fullName>CVsAllInFinal__c</fullName>
    <formula>TEXT(NumberOfCVs__c) + &apos;/&apos; + TEXT(FinalCandidates__c)</formula>
    <label>CVs All / in Final</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/CVsApprovedRequested__c.field-meta.xml
<CustomField>
    <fullName>CVsApprovedRequested__c</fullName>
    <formula>IF (
  RecordType.DeveloperName = &apos;Auto&apos;,
  (TEXT(NumberOfCVsApproved__c)+ &apos;/&apos; + Placement_frm__c),
  (TEXT(NumberOfCVsApproved__c)+ &apos;/&apos; + TEXT(Placement__c))
)</formula>
    <label>CVs Approved / Requested</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/DeliveryDeadline_frm__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDeadline_frm__c</fullName>
    <formula>IF(RecordType.DeveloperName == &apos;Auto&apos;, Opportunity__r.CloseDate,  DeliveryDeadline__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Project Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kielce</fullName>
            </value>
            <value>
                <fullName>Lublin</fullName>
            </value>
            <value>
                <fullName>Poznań</fullName>
            </value>
            <value>
                <fullName>Warszawa</fullName>
            </value>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/MainSkills__c.field-meta.xml
<CustomField>
    <fullName>MainSkills__c</fullName>
    <label>Main Skills</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/NumberOfCVs1__c.field-meta.xml
<CustomField>
    <fullName>NumberOfCVs1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of CVs 1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Resource_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/OpportunityName_frm__c.field-meta.xml
<CustomField>
    <fullName>OpportunityName_frm__c</fullName>
    <formula>Opportunity__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Position_frm__c.field-meta.xml
<CustomField>
    <fullName>Position_frm__c</fullName>
    <formula>IF(RecordType.DeveloperName == &apos;Auto&apos;, Opportunity__r.Name,  Position__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Position Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/RequestorContact__c.field-meta.xml
<CustomField>
    <fullName>RequestorContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>.Requestor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.Id</field>
            <operation>equals</operation>
            <value>Current User: Contact ID</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Resource Requests (Requestor)</relationshipLabel>
    <relationshipName>Resource_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/RequestorEmail_frm__c.field-meta.xml
<CustomField>
    <fullName>RequestorEmail_frm__c</fullName>
    <formula>IF(RecordType.DeveloperName == &apos;Auto&apos;, Opportunity__r.Owner.Email, RequestorUser__r.Email)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requestor Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/RequestorUser__c.field-meta.xml
<CustomField>
    <fullName>RequestorUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>.Requestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resource_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Resource_Manager__c.field-meta.xml
<CustomField>
    <fullName>Resource_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.Name_frm__c</field>
            <operation>contains</operation>
            <value>Codello</value>
        </filterItems>
        <filterItems>
            <field>Contact.Name_frm__c</field>
            <operation>contains</operation>
            <value>Łukaszewski</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Resource_Requests_RM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/SecondarySkills__c.field-meta.xml
<CustomField>
    <fullName>SecondarySkills__c</fullName>
    <label>Secondary Skills</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/ZOHOUrl_frm__c.field-meta.xml
<CustomField>
    <fullName>ZOHOUrl_frm__c</fullName>
    <formula>IF(ISBLANK(ZohoUrl__c), &apos;&apos;, HYPERLINK(ZohoUrl__c, &apos;Link&apos;))</formula>
    <label>ZOHO</label>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Other Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>ZOHO</description>
    <label>Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <description>Business contact</description>
    <label>Business</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Internal employees</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kielce</fullName>
            </value>
            <value>
                <fullName>Lublin</fullName>
            </value>
            <value>
                <fullName>Poznań</fullName>
            </value>
            <value>
                <fullName>Warszawa</fullName>
            </value>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Support monthly</fullName>
            </value>
            <value>
                <fullName>Support OnCall</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Fixed price project</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BTN_DAO_ResourceRequest.cls
/**
 * Created by britenet on 2016-07-05.
 * @description DAO class for BTN_ResourceRequest__c - Data Access Object
 */
public class BTN_DAO_ResourceRequest extends BTN_DAO {
    /**
     * @author Mateusz Przywara
     * @date   2016-07-05
     * @description Constructor
    */
    public BTN_DAO_ResourceRequest() {
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-07-05
     * @description Constructor setting custom List of fields
    */
    public BTN_DAO_ResourceRequest(List<Schema.SObjectField> customFields) {
        setCustomFields(customFields);
    }

    public override Schema.SObjectType getSObjectType() {
        return BTN_ResourceRequest__c.sObjectType;
    }

    public override List<Schema.SObjectField> getSObjectFields() {
        return new List<Schema.SObjectField>{
                BTN_ResourceRequest__c.Id,
                BTN_ResourceRequest__c.Name,
                BTN_ResourceRequest__c.Position_frm__c,
                BTN_ResourceRequest__c.Opportunity__c,
                BTN_ResourceRequest__c.OpportunityName_frm__c,
                BTN_ResourceRequest__c.RequestorContact__c,
                BTN_ResourceRequest__c.RequestorUser__c,
                BTN_ResourceRequest__c.Position__c,
                BTN_ResourceRequest__c.Account_frm__c,
                BTN_ResourceRequest__c.CreatedDate,
                BTN_ResourceRequest__c.ZOHOUrl_frm__c,
                BTN_ResourceRequest__c.Location__c,
                BTN_ResourceRequest__c.DeliveryDeadline_frm__c,
                BTN_ResourceRequest__c.CVsAllInFinal__c,
                BTN_ResourceRequest__c.CVsApprovedRequested__c,
                BTN_ResourceRequest__c.CustomerAccount__c,
                BTN_ResourceRequest__c.Billing_Type__c,
                BTN_ResourceRequest__c.ContractStart_frm__c,
                BTN_ResourceRequest__c.NumberOfCVs1__c,
                BTN_ResourceRequest__c.RequestorEmail_frm__c,
                BTN_ResourceRequest__c.Resource_Manager__c
        };
    }

        /**
         * @author Mateusz Przywara
         * @date   2016-07-05
         * @description find all Resource Requests connected with Opportunity opportunityId
         * @param  sObjectIds - collection of Id to search for
         * @return            - collection of found sObjectsDAO.query
         */
    public List<BTN_ResourceRequest__c> findResourceRequestsByOpportunity(Id opportunityId) {
        return findSObjectsBy(new List<SearchCondition>{
                new SearchCondition('Opportunity__c', '=', opportunityId)
        });
    }

        /**
         * @author Mateusz Przywara
         * @date   2016-07-05
         * @description find all Resource Requests connected with Opportunity opportunityId
         * @param  sObjectIds - collection of Id to search for
         * @return            - collection of found sObjectsDAO.query
         */
    public List<BTN_ResourceRequest__c> findAutoResourceRequests() {
        return findSObjectsBy(new List<SearchCondition>{
                new SearchCondition('RecordType.Name', '=', BTN_ConstantRepo.RESOURCE_REQUEST_RECORD_TYPE_AUTO)
        });
    }
    
    /**
         * @author Wojciech Mazur
         * @date   2016-09-16
         * @description find all Resource Requests with Billing type = Unbillable
         * 
         * @return            - collection of found sObjectsDAO.query
         */
    public List<BTN_ResourceRequest__c> findUnbillableRequests() {
        return findSObjectsBy(new List<SearchCondition>{
                new SearchCondition('Billing_Type__c', '=', BTN_ConstantRepo.BILLING_TYPE_UNBILLABLE)
        });
    }

        /**
         * @author Mateusz Przywara
         * @date   2016-07-05
         * @description find Resource Request
         * @param  resourceRequestId - collection of Id to search for
         * @return     BTN_ResourceRequest__c       - collection of found Resource Requests
         */
    public BTN_ResourceRequest__c findResourceRequestsById(Id resourceRequestId) {
        return (BTN_ResourceRequest__c) findSObjectById(resourceRequestId);
    }
    
       /**
         * @author Wojciech Mazur
         * @date   2016-09-14
         * @description find all Resource Requests connected with Account (Business) and Contact (Internal)
         * @param  businessId - Business Account id
         * @param  contactId - internal contact id
         * @return            - collection of found sObjectsDAO.query
         */
    public List<BTN_ResourceRequest__c> findByBusinessAndContact(Id businessId, Id contactId) {
    	
    	BTN_DAO_Candidate daoCandidate = new BTN_DAO_Candidate();
    	List<BTN_CV__c> candidates = daoCandidate.findCandidatesBuContact(contactId);
    	Set<Id> affectedResourceRequests = new Set<Id>();
    	for(BTN_CV__c c:candidates){
    		affectedResourceRequests.add(c.ResourceRequest__c);
    	}
        return findSObjectsBy(new List<SearchCondition>{
                new SearchCondition('CustomerAccount__c', '=', businessId),
                new SearchCondition(' AND Id', 'IN', affectedResourceRequests)
        });
    }
    
        /**
         * @author Mateusz Przywara
         * @date   2016-07-05
         * @description add RequestorContact fields to Query
         * @return void
         */
    public void addRequestorContactFields() {
        currentFields.addAll(new List<String>{
                'RequestorContact__r.Name',
                'RequestorContact__r.Email'
        });
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-22
     * @description add RequestorUser fields to Query
     * @return void
     */
    public void addRequestorUserFields() {
        currentFields.addAll(new List<String>{
                'RequestorUser__r.Email', 'RequestorUser__r.Name'});
    }
        /**
         * @author Mateusz Przywara
         * @date   2016-07-05
         * @description add Record Type fields to Query
         * @return void
         */
    public void addRecordTypeFields() {
        currentFields.add('RecordType.DeveloperName');
        currentFields.add('RecordType.Name');
    }
    /**
     * @author Piotr Pitera
     * @date 2016-09-08
     * @description adds Rich Text fields to the Query
     * @return void
     */
    public void addRichTextFields() {
        currentFields.addAll(new List<String>{
                'MainSkills__c', 'SecondarySkills__c', 'Description__c'});
    }
    
     /**
     * @author Wojciech Mazur
     * @date 2016-09-16
     * @description adds Candidates to the Query
     * @return void
     */
    public void addCandidates() {
        currentFields.add('(SELECT id,Contact__c,DateApproved__c from CVs_lkp__r)');
    }
    
       
}