force-app/main/default/objects/BTN_Assignment__c/BTN_Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Assignment__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Last day of Assignment</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BTN_Assignment__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>First day of Assignment</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/BTN_CV__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CID{00000000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_CV__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Recruit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidates (Contact)</relationshipLabel>
    <relationshipName>Candidates1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/DateApproved__c.field-meta.xml
<CustomField>
    <fullName>DateApproved__c</fullName>
    <label>Date Approved</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/ResourceRequest__c.field-meta.xml
<CustomField>
    <fullName>ResourceRequest__c</fullName>
    <label>Resource request</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Resource request must not be closed</errorMessage>
        <filterItems>
            <field>BTN_ResourceRequest__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Closed Delivered, Closed Rejected</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BTN_ResourceRequest__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>CVs_lkp</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/BTN_ResourceRequest__c.object-meta.xml
<CustomObject>
    <label>Resource request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignment</label>
    <referenceTo>BTN_Assignment__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contract_Start__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start__c</fullName>
    <label>Contract Start</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MonthsGlobalPicklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Deal_Close__c.field-meta.xml
<CustomField>
    <fullName>Deal_Close__c</fullName>
    <label>Deal Close</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MonthsGlobalPicklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <formula>IF(RecordType.Name = &apos;External Offboarding&apos;, AssignmentEndDate__c, 
IF(RecordType.Name = &apos;Internal Offboarding&apos;, ContactLastDayAtWork__c, WorkEndDate__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Resource_Request__c.field-meta.xml
<CustomField>
    <fullName>Resource_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Request</label>
    <referenceTo>BTN_ResourceRequest__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/MonthsGlobalPicklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>January</fullName>
    </customValue>
    <customValue>
        <fullName>February</fullName>
    </customValue>
    <customValue>
        <fullName>March</fullName>
    </customValue>
    <customValue>
        <fullName>April</fullName>
    </customValue>
    <customValue>
        <fullName>May</fullName>
    </customValue>
    <customValue>
        <fullName>June</fullName>
    </customValue>
    <customValue>
        <fullName>July</fullName>
    </customValue>
    <customValue>
        <fullName>August</fullName>
    </customValue>
    <customValue>
        <fullName>September</fullName>
    </customValue>
    <customValue>
        <fullName>October</fullName>
    </customValue>
    <customValue>
        <fullName>November</fullName>
    </customValue>
    <customValue>
        <fullName>December</fullName>
    </customValue>
    <masterLabel>Months Global Picklist</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BTN_ResourceRequestSelectorController.cls
public with sharing class BTN_ResourceRequestSelectorController {
	public Case aCase; 
	public List<BTN_ResourceRequest__c> resourceRequests{get;set;}
	public String selectedResourceRequest {get;set;}
	
	public BTN_ResourceRequestSelectorController(ApexPages.StandardController stdController){
		stdController.addFields(new List<String>{'Contact',
												'Account',
												'Assignment__r.EndDate__c',
												'Assignment__r.StartDate__c',
												'RecordType.DeveloperName'});
		aCase = (Case)stdController.getRecord();
		
		BTN_DAO_ResourceRequest rrDao = new BTN_DAO_ResourceRequest();
		rrDao.addCandidates();
		resourceRequests = rrDao.findByBusinessAndContact(aCase.Account.Id, aCase.Contact.Id);
		//add all non billable RR
		resourceRequests.addAll(rrDao.findUnbillableRequests());
		
	}
	
	/**
         * @author Wojciech Mazur
         * @date   2016-09-14
         * @description saves selected RR on the case record
         * @param  selectedResourceRequest - indirect set by apex:commandLink from VF
         */
	public PageReference selectResourceRequest() {
		if (selectedResourceRequest !=null && selectedResourceRequest.trim()!=''){
			aCase.Resource_request__c = selectedResourceRequest;
		}else{
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Parameter not received'));
			return null;
		}
		// BRITCRM-162 - fill relevant fields
		Map<Id, BTN_ResourceRequest__c> resourceRequestsMap = new Map<Id, BTN_ResourceRequest__c>();
		resourceRequestsMap.putAll(resourceRequests);
		if(aCase.RecordType.DeveloperName.equals(BTN_ConstantRepo.CASE_EXTERNAL_OFFBOARDING_RECORDTYPE)){
			aCase.Contract_Start__c = BTN_DateUtils.getMonthName(aCase.Assignment__r.EndDate__c);
		}else if(aCase.RecordType.DeveloperName.equals(BTN_ConstantRepo.CASE_EXTERNAL_ONBOARDING_RECORDTYPE)){
			aCase.Contract_Start__c = BTN_DateUtils.getMonthName(aCase.Assignment__r.StartDate__c);
		}
		boolean dealCloseDateFound = false;
		for (BTN_CV__c cv:resourceRequestsMap.get(selectedResourceRequest).CVs_lkp__r){
			if(cv.Contact__c == aCase.Contact.Id && cv.DateApproved__c!=null){
				aCase.Deal_Close__c = BTN_DateUtils.getMonthName(cv.DateApproved__c);
				dealCloseDateFound = true;
				break;
			}
		}
		if(!dealCloseDateFound)
			aCase.Deal_Close__c = null;
		update aCase;
	    return new PageReference('/'+aCase.Id);
	    
	}
    
}