force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Potential</fullName>
                <default>true</default>
                <label>Potential</label>
            </value>
            <value>
                <fullName>Trusted</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_BriteCRM_settings__c/BTN_BriteCRM_settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>BriteCRM settings</label>
</CustomObject>

force-app/main/default/objects/BTN_CV__c/BTN_CV__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CID{00000000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_CV__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted to external</fullName>
            </value>
            <value>
                <fullName>Interview-in-progress</fullName>
            </value>
            <value>
                <fullName>Approved by external</fullName>
            </value>
            <value>
                <fullName>Contract signed</fullName>
            </value>
            <value>
                <fullName>Contract signed with different external</fullName>
            </value>
            <value>
                <fullName>Rejected by external</fullName>
            </value>
            <value>
                <fullName>Rejected by us</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Offer expired</fullName>
            </value>
            <value>
                <fullName>Closed in ZOHO</fullName>
                <isActive>false</isActive>
                <label>Closed in ZOHO</label>
            </value>
            <value>
                <fullName>Rejected by internal</fullName>
                <isActive>false</isActive>
                <label>Rejected by internal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Event__c/BTN_Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E{00000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Event__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>BTN_CV__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description (HR)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Interviewed__c.field-meta.xml
<CustomField>
    <fullName>Interviewed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewed</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Events (Interviewed)</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/PostOnRelatedCandidates__c.field-meta.xml
<CustomField>
    <fullName>PostOnRelatedCandidates__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Post on Related Candidates</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/recordTypes/Interview.recordType-meta.xml
<RecordType>
    <fullName>Interview</fullName>
    <active>true</active>
    <description>Interview with potential employee</description>
    <label>Interview</label>
</RecordType>

force-app/main/default/objects/BTN_ResourceRequest__c/BTN_ResourceRequest__c.object-meta.xml
<CustomObject>
    <label>Resource request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Project Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <label>.Requestor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Resource_Manager__c.field-meta.xml
<CustomField>
    <fullName>Resource_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.Name_frm__c</field>
            <operation>contains</operation>
            <value>Codello</value>
        </filterItems>
        <filterItems>
            <field>Contact.Name_frm__c</field>
            <operation>contains</operation>
            <value>Łukaszewski</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Resource_Requests_RM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Waiting for client</fullName>
            </value>
            <value>
                <fullName>On shelf</fullName>
            </value>
            <value>
                <fullName>Closed - Success</fullName>
            </value>
            <value>
                <fullName>Closed - Failure</fullName>
            </value>
            <value>
                <fullName>Opportunity Closed</fullName>
            </value>
            <value>
                <fullName>Closed - We resign</fullName>
            </value>
            <value>
                <fullName>Closed - Blood in the sand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/BSexternalId__c.field-meta.xml
<CustomField>
    <fullName>BSexternalId__c</fullName>
    <externalId>true</externalId>
    <label>Britesheet ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Internal employees</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Recruit.recordType-meta.xml
<RecordType>
    <fullName>Recruit</fullName>
    <active>true</active>
    <description>Recruits</description>
    <label>Recruit</label>
</RecordType>

force-app/main/default/objects/Event/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/classes/BTN_ChatterUtils_Test.cls
/**
 * @author Mateusz Przywara
 * @date   2016-10-12
 * @description BTN_ChatterUtils_Test test class for Chatter Utility methods
*/
@isTest
private class BTN_ChatterUtils_Test {
    private static String TEST_STRING = 'dzordz';
    private static String FIELD_SET_ERROR = 'FIELD SET ON CONTACT EMPTY';
    private static final String PHONE_TEST_VALUE = '0700';
    private static final String PHONE_TEST_VALUE_2 = '0800';
    private static final String CONTACT_TEST_FIELD_API_NAME = 'FirstName';
    private static final String CONTACT_TEST_FIELD_NEW_VALUE = 'krasnal team';
    private static String TEST_TEXT = 'TEST_REICHSNER';

    /**
     * @author Mateusz Przywara
     * @date   2016-10-12
     * @description Prepare data for tests
    */
    @testSetup
    static void createDataStructure() {

        System.RunAs(BTN_Utils.getCurrentUser()) {
            // prepare Group for HR
            BTN_TestDataFactory.getHRCollaborationGroup();
            Account britenetAcc = BTN_TestDataFactory.getBriteNetAccount();
            Contact internalCont = BTN_TestDataFactory.getRequestorInternalContact(britenetAcc.Id);
            BTN_ResourceRequest__c rr = BTN_ResourceRequestBuilderHelper.buildWithManualRecordType().save();
            rr.Resource_Manager__c = internalCont.Id;
            update rr;
        }
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-10-12
     * @description Method test insertion of Feed Items with Event
    */
    @isTest
    static void testPostOnContactAndRelatedCandidates() {
        //internal Contact on his feed msg will be posted
        Contact internalContact = new BTN_DAO_Contact().findInternals().get(0);
        // Resource Request required to connect Candidates to Contact
        BTN_ResourceRequest__c resourceRequest =
                (BTN_ResourceRequest__c) new BTN_DAO_ResourceRequest().findSObjects().get(0);
        BTN_Event__c event;

        //Prepare user for this test
        User currUser = getCommunityUser(internalContact.BSexternalId__c+1);
        insert currUser;
        //assign HR permset
        BTN_PermissionSetUtils.assignPermissionSetToUser(BTN_ConstantRepo.PERM_SET_NAME_HR, currUser);

        //Share ResourceRequest - required for Candidate
        insert new BTN_ResourceRequest__Share(
                UserOrGroupId = currUser.Id,
                RowCause = BTN_ResourceRequest__Share.RowCause.Requestor__c,
                ParentId = resourceRequest.Id,
                AccessLevel = 'Edit'
        );

        // Candidates
        BTN_CV__c dummyCandidate1;
        BTN_CV__c dummyCandidate2;

        System.RunAs(currUser) {
            Test.startTest();
                //Candidates are private
                dummyCandidate1 = BTN_TestDataFactory.getCV(resourceRequest.Id, internalContact.Id);
                event = BTN_TestDataFactory.getGeneralEvent(internalContact.Id, true);
            Test.stopTest();
        }

        System.assertEquals(1, [SELECT count() FROM FeedItem WHERE ParentId = :internalContact.Id]);
        System.assertEquals(1, [SELECT count() FROM FeedItem WHERE ParentId = :dummyCandidate1.Id]);
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-10-17
     * @description Test processContactInsertsToFeedItems Method from chatter utils - post info on community Chatter
     * feed for new Recruits
    */
    @isTest
    static void testProcessContactInsertsToFeedItemsMethod() {
        Contact recruit = new BTN_ContactBuilderHelper()
                .buildWithRecruitRecordType()
                .buildWithDefaultAddress()
                .withLastName(TEST_STRING)
                .withFirstName(TEST_STRING)
                .withEmail(TEST_STRING + BTN_ConstantRepo.BRITENET_MAIL_SUFFIX_PL)
                .withAccount(new BTN_DAO_Account().findAccountByName(BTN_ConstantRepo.BRITENET_ACCOUNT_NAME).Id)
                                .save();
        Test.startTest();
            System.assertEquals(
                1,
                BTN_ChatterUtils.postInsertsOnHumanResourcesGroup(
                        new Map<Id, Contact>{recruit.Id => recruit},
                        CONTACT_TEST_FIELD_API_NAME
                ).size());
        Test.stopTest();
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-10-17
     * @description Test processContactUpdatesToFeedItems Method from chatter utils - post info on community Chatter
     * feed for updated Recruits
    */
    @isTest
    static void testProcessContactUpdatesToFeedItemsMethod() {
        Contact recruitTestContactOld =
                        new BTN_ContactBuilderHelper()
                                .buildWithRecruitRecordType()
                                .buildWithDefaultAddress()
                                .withLastName(TEST_STRING)
                                .withEmail(TEST_STRING + BTN_ConstantRepo.BRITENET_MAIL_SUFFIX_PL)
                                .withAccount(new BTN_DAO_Account().findAccountByName(BTN_ConstantRepo.BRITENET_ACCOUNT_NAME).Id)
                                .save();
        // Cloning to stay with 2 same sObject with differenct reference.
        Contact recruitTestContactNew = recruitTestContactOld.clone();
        // Add Id
        recruitTestContactNew.Id = recruitTestContactOld.Id;
        // Create list with ref. to records before changes
        List<Contact> oldContacts = new List<Contact>{
                recruitTestContactOld
        };
        // Create Map with ref. to records after changes
        Map<Id, Contact> newContactMap = new Map<Id, Contact>(new List<Contact>{recruitTestContactNew});
        //No Selected field changes do standard update info
        Id feedItemId = BTN_ChatterUtils.postChangesOnHumanResourcesGroup(
                oldContacts,
                newContactMap,
                new Set<String> {CONTACT_TEST_FIELD_API_NAME},
                CONTACT_TEST_FIELD_API_NAME
        ).get(0).getId();
        System.assert([SELECT Body FROM FeedItem WHERE Id = :feedItemId].Body.contains(System.Label.hasBeenUpdated));
        // change selected field.
        recruitTestContactNew.put(
                CONTACT_TEST_FIELD_API_NAME,
                CONTACT_TEST_FIELD_NEW_VALUE
        );
        feedItemId = BTN_ChatterUtils.postChangesOnHumanResourcesGroup(
                oldContacts,
                newContactMap,
                new Set<String> {CONTACT_TEST_FIELD_API_NAME},
                CONTACT_TEST_FIELD_API_NAME
        ).get(0).getId();
        System.assert([SELECT Body FROM FeedItem WHERE Id = :feedItemId].Body.contains(CONTACT_TEST_FIELD_NEW_VALUE));
    }


    @isTest
    static void shouldNotChangeStatusWhenInterviewCreatedFromContactPage() {
        //internal Contact on his feed msg will be posted
        Contact internalContact = new BTN_DAO_Contact().findInternals().get(0);
        //Prepare user for this test
        User currUser = getCommunityUser(internalContact.BSexternalId__c+1);
        insert currUser;
        // Resource Request required to connect Candidates to Contact
        BTN_ResourceRequest__c resourceRequest = prepareResourceRequest(currUser);
        //Event
        BTN_Event__c event;
        // Candidates
        BTN_CV__c dummyCandidate;

        System.RunAs(currUser) {
            Test.startTest();
                //Candidates are private
                dummyCandidate = BTN_TestDataFactory.getCV(resourceRequest.Id, internalContact.Id);

                System.assert([SELECT Id, Status__c FROM  BTN_CV__c where Id = :dummyCandidate.Id].Status__c == 'Open');
                event = getInterviewWithCandidate(internalContact.Id, true,null);
                System.assert([SELECT Id,Status__c FROM  BTN_CV__c where Id = :dummyCandidate.Id].Status__c == 'Open');
            Test.stopTest();
        }
    }
    @isTest
    static void shouldNotChangeStatusWhenGeneralCreated() {
        //internal Contact on his feed msg will be posted
        Contact internalContact = new BTN_DAO_Contact().findInternals().get(0);
        //Prepare user for this test
        User currUser = getCommunityUser(internalContact.BSexternalId__c+1);
        insert currUser;
        // Resource Request required to connect Candidates to Contact
        BTN_ResourceRequest__c resourceRequest = prepareResourceRequest(currUser);
        //Event
        BTN_Event__c event;
        // Candidates
        BTN_CV__c dummyCandidate;

        System.RunAs(currUser) {
            Test.startTest();
                //Candidates are private
                dummyCandidate = BTN_TestDataFactory.getCV(resourceRequest.Id, internalContact.Id);
                System.assert([SELECT Id, Status__c FROM  BTN_CV__c where Id = :dummyCandidate.Id].Status__c == 'Open');
                event = getGeneralEvent(internalContact.Id, true);
                System.assert([SELECT Id,Status__c FROM  BTN_CV__c where Id = :dummyCandidate.Id].Status__c == 'Open');
            Test.stopTest();
        }

    }
    @isTest
    static void shouldNotChangeStatusWhenGeneralCreatedWithCandidate() {
        //internal Contact on his feed msg will be posted
        Contact internalContact = new BTN_DAO_Contact().findInternals().get(0);
        //Prepare user for this test
        User currUser = getCommunityUser(internalContact.BSexternalId__c+1);
        insert currUser;
        // Resource Request required to connect Candidates to Contact
        BTN_ResourceRequest__c resourceRequest = prepareResourceRequest(currUser);
        //Event
        BTN_Event__c event;
        // Candidates
        BTN_CV__c dummyCandidate;

        System.RunAs(currUser) {
            Test.startTest();
            //Candidates are private
            dummyCandidate = BTN_TestDataFactory.getCV(resourceRequest.Id, internalContact.Id);
            System.assert([SELECT Id, Status__c FROM  BTN_CV__c where Id = :dummyCandidate.Id].Status__c == 'Open');
            event = getGeneralEvent(internalContact.Id, true, dummyCandidate.Id );
            System.assert([SELECT Id,Status__c FROM  BTN_CV__c where Id = :dummyCandidate.Id].Status__c == 'Open');
            Test.stopTest();
        }

    }
    @isTest
    static void shouldChangeStatusWhenInterviewCreatedFromCandidatePage() {
        //internal Contact on his feed msg will be posted
        Contact internalContact = new BTN_DAO_Contact().findInternals().get(0);
        //Prepare user for this test
        User currUser = getCommunityUser(internalContact.BSexternalId__c+1);
        insert currUser;
        // Resource Request required to connect Candidates to Contact
        BTN_ResourceRequest__c resourceRequest = prepareResourceRequest(currUser);
        //Event
        BTN_Event__c event;
        // Candidates
        BTN_CV__c dummyCandidate;

        System.RunAs(currUser) {
            Test.startTest();
                //Candidates are private
                dummyCandidate = BTN_TestDataFactory.getCV(resourceRequest.Id, internalContact.Id);
                System.assert([SELECT Id, Status__c FROM  BTN_CV__c where Id = :dummyCandidate.Id].Status__c == 'Open');
                //when
                event = getInterviewWithCandidate(internalContact.Id, true,dummyCandidate.Id);
                //then
                System.assert([SELECT Id, Name, Candidate__c FROM  BTN_Event__c where Id = :event.Id].Candidate__c != null);
                System.assert([SELECT Id,Status__c FROM  BTN_CV__c where Id = :dummyCandidate.Id].Status__c == 'Interview-in-progress');
            Test.stopTest();
        }
    }

    @isTest
    static void shouldAddLinkAtTheEndWhenObjectInSetting() {
        BTN_BriteCRM_settings__c setting = new BTN_BriteCRM_settings__c();
        setting.Name = 'ObjectsWithChatterLink';
        setting.Value__c = 'Contact';
        insert setting;
        Contact recruitTestContactOld =
        new BTN_ContactBuilderHelper()
        .buildWithRecruitRecordType()
        .buildWithDefaultAddress()
        .withLastName(TEST_STRING)
        .withEmail(TEST_STRING + BTN_ConstantRepo.BRITENET_MAIL_SUFFIX_PL)
        .withAccount(new BTN_DAO_Account().findAccountByName(BTN_ConstantRepo.BRITENET_ACCOUNT_NAME).Id)
        .save();
        // Cloning to stay with 2 same sObject with differenct reference.
        Contact recruitTestContactNew = recruitTestContactOld.clone();
        // Add Id
        recruitTestContactNew.Id = recruitTestContactOld.Id;
        // Create list with ref. to records before changes
        List<Contact> oldContacts = new List<Contact>{
                recruitTestContactOld
        };
        // Create Map with ref. to records after changes
        Map<Id, Contact> newContactMap = new Map<Id, Contact>(new List<Contact>{recruitTestContactNew});
        //No Selected field changes do standard update info
        Id feedItemId = BTN_ChatterUtils.postChangesOnHumanResourcesGroup(
                oldContacts,
                newContactMap,
                new Set<String> {CONTACT_TEST_FIELD_API_NAME},
                CONTACT_TEST_FIELD_API_NAME
        ).get(0).getId();
        FeedItem fItem = [SELECT Body FROM FeedItem WHERE Id = :feedItemId];
        System.assert(fItem.Body.contains(System.Label.hasBeenUpdated));
        System.assert(fItem.Body.contains(recruitTestContactNew.Id));
    }
    @isTest
    static void shouldNotAddLinkAtTheEndWhenObjectNotInSetting() {
        BTN_BriteCRM_settings__c setting = new BTN_BriteCRM_settings__c();
        setting.Name = 'ObjectsWithChatterLink';
        setting.Value__c = 'Not Contact';
        insert setting;
        Contact recruitTestContactOld =
        new BTN_ContactBuilderHelper()
        .buildWithRecruitRecordType()
        .buildWithDefaultAddress()
        .withLastName(TEST_STRING)
        .withEmail(TEST_STRING + BTN_ConstantRepo.BRITENET_MAIL_SUFFIX_PL)
        .withAccount(new BTN_DAO_Account().findAccountByName(BTN_ConstantRepo.BRITENET_ACCOUNT_NAME).Id)
        .save();
        // Cloning to stay with 2 same sObject with differenct reference.
        Contact recruitTestContactNew = recruitTestContactOld.clone();
        // Add Id
        recruitTestContactNew.Id = recruitTestContactOld.Id;
        // Create list with ref. to records before changes
        List<Contact> oldContacts = new List<Contact>{
                recruitTestContactOld
        };
        // Create Map with ref. to records after changes
        Map<Id, Contact> newContactMap = new Map<Id, Contact>(new List<Contact>{recruitTestContactNew});
        //No Selected field changes do standard update info
        Id feedItemId = BTN_ChatterUtils.postChangesOnHumanResourcesGroup(
                oldContacts,
                newContactMap,
                new Set<String> {CONTACT_TEST_FIELD_API_NAME},
                CONTACT_TEST_FIELD_API_NAME
        ).get(0).getId();
        FeedItem fItem = [SELECT Body FROM FeedItem WHERE Id = :feedItemId];
        System.assert(fItem.Body.contains(System.Label.hasBeenUpdated));
        System.assert(!fItem.Body.contains(recruitTestContactNew.Id));
    }
    private static User  getCommunityUser(Decimal bSexternalId ){
        Contact relatedContact =  BTN_TestDataFactory.getRequestorInternalContact(
                new BTN_DAO_Account().findAccountByName(BTN_ConstantRepo.BRITENET_ACCOUNT_NAME).Id,(Integer)bSexternalId);
        return BTN_TestDataFactory.getCommunityUser(relatedContact.Id, relatedContact.Email);
    }
    private static BTN_ResourceRequest__c  prepareResourceRequest(User currUser ){

        // Resource Request required to connect Candidates to Contact
        BTN_ResourceRequest__c resourceRequest =
                (BTN_ResourceRequest__c) new BTN_DAO_ResourceRequest().findSObjects().get(0);

        //assign HR permset
        BTN_PermissionSetUtils.assignPermissionSetToUser(BTN_ConstantRepo.PERM_SET_NAME_HR, currUser);
        //Share ResourceRequest - required for Candidate
        insert new BTN_ResourceRequest__Share(
                UserOrGroupId = currUser.Id,
                RowCause = BTN_ResourceRequest__Share.RowCause.Requestor__c,
                ParentId = resourceRequest.Id,
                AccessLevel = 'Edit'
        );
        return resourceRequest;

    }
    public static BTN_Event__c getGeneralEvent(Id contactId, Boolean postOnCandidates) {
        return getGeneralEvent(contactId, postOnCandidates,null );
    }
    public static BTN_Event__c getGeneralEvent(Id contactId, Boolean postOnCandidates,Id candidateId ) {
        BTN_Event__c result = creatEvent(contactId,postOnCandidates);
        result.RecordTypeId = BTN_RecordTypeUtils.getRecordTypeCustomEventGeneral().Id;
        result.Candidate__c = candidateId;
        insert result;
        return result;
    }
    public static BTN_Event__c getInterviewWithCandidate(Id contactId, Boolean postOnCandidates, Id candidateId) {
        BTN_Event__c result = creatEvent(contactId,postOnCandidates);
        result.RecordTypeId = BTN_RecordTypeUtils.getRecordTypeCustomEventInterview().Id;
        result.Candidate__c = candidateId;
        insert result;
        return result;
    }
    private static BTN_Event__c creatEvent(Id contactId,Boolean postOnCandidates) {
        return new BTN_Event__c( Interviewed__c = contactId, Description__c = TEST_TEXT, PostOnRelatedCandidates__c = postOnCandidates);
    }
}