force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Potential</fullName>
                <default>true</default>
                <label>Potential</label>
            </value>
            <value>
                <fullName>Trusted</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Britenet.recordType-meta.xml
<RecordType>
    <fullName>Britenet</fullName>
    <active>true</active>
    <description>Britenet Internal</description>
    <label>Britenet</label>
</RecordType>

force-app/main/default/objects/BTN_CV__c/BTN_CV__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CID{00000000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_CV__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Recruit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidates (Contact)</relationshipLabel>
    <relationshipName>Candidates1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/ResourceRequest__c.field-meta.xml
<CustomField>
    <fullName>ResourceRequest__c</fullName>
    <label>Resource request</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Resource request must not be closed</errorMessage>
        <filterItems>
            <field>BTN_ResourceRequest__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Closed Delivered, Closed Rejected</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BTN_ResourceRequest__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>CVs_lkp</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted to external</fullName>
            </value>
            <value>
                <fullName>Interview-in-progress</fullName>
            </value>
            <value>
                <fullName>Approved by external</fullName>
            </value>
            <value>
                <fullName>Contract signed</fullName>
            </value>
            <value>
                <fullName>Contract signed with different external</fullName>
            </value>
            <value>
                <fullName>Rejected by external</fullName>
            </value>
            <value>
                <fullName>Rejected by us</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Offer expired</fullName>
            </value>
            <value>
                <fullName>Closed in ZOHO</fullName>
                <isActive>false</isActive>
                <label>Closed in ZOHO</label>
            </value>
            <value>
                <fullName>Rejected by internal</fullName>
                <isActive>false</isActive>
                <label>Rejected by internal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/BTN_ResourceRequest__c.object-meta.xml
<CustomObject>
    <label>Resource request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/ContractStart__c.field-meta.xml
<CustomField>
    <fullName>ContractStart__c</fullName>
    <label>Contract Start</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kielce</fullName>
            </value>
            <value>
                <fullName>Lublin</fullName>
            </value>
            <value>
                <fullName>Poznań</fullName>
            </value>
            <value>
                <fullName>Warszawa</fullName>
            </value>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Resource_Manager__c.field-meta.xml
<CustomField>
    <fullName>Resource_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.Name_frm__c</field>
            <operation>contains</operation>
            <value>Codello</value>
        </filterItems>
        <filterItems>
            <field>Contact.Name_frm__c</field>
            <operation>contains</operation>
            <value>Łukaszewski</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Resource_Requests_RM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Waiting for client</fullName>
            </value>
            <value>
                <fullName>On shelf</fullName>
            </value>
            <value>
                <fullName>Closed - Success</fullName>
            </value>
            <value>
                <fullName>Closed - Failure</fullName>
            </value>
            <value>
                <fullName>Opportunity Closed</fullName>
            </value>
            <value>
                <fullName>Closed - We resign</fullName>
            </value>
            <value>
                <fullName>Closed - Blood in the sand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Other Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ResourceRequestor__c.field-meta.xml
<CustomField>
    <fullName>ResourceRequestor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Resource Requestor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Internal employees</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Recruit.recordType-meta.xml
<RecordType>
    <fullName>Recruit</fullName>
    <active>true</active>
    <description>Recruits</description>
    <label>Recruit</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ContractEnd__c.field-meta.xml
<CustomField>
    <fullName>ContractEnd__c</fullName>
    <inlineHelpText>Specify the end date of the contract</inlineHelpText>
    <label>Contract end</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ContractStart__c.field-meta.xml
<CustomField>
    <fullName>ContractStart__c</fullName>
    <inlineHelpText>Specify the start date of the contract</inlineHelpText>
    <label>Contract start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kielce</fullName>
            </value>
            <value>
                <fullName>Lublin</fullName>
            </value>
            <value>
                <fullName>Poznań</fullName>
            </value>
            <value>
                <fullName>Warszawa</fullName>
            </value>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NextStep__c.field-meta.xml
<CustomField>
    <fullName>NextStep__c</fullName>
    <inlineHelpText>Next Step Description</inlineHelpText>
    <label>Next Step</label>
    <length>60000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NextStepDeadline__c.field-meta.xml
<CustomField>
    <fullName>NextStepDeadline__c</fullName>
    <label>Next Step Deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Main_Skills__c.field-meta.xml
<CustomField>
    <fullName>Product_Main_Skills__c</fullName>
    <label>Main Skills (Technology)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Secondary_Skills__c.field-meta.xml
<CustomField>
    <fullName>Product_Secondary_Skills__c</fullName>
    <label>Secondary Skills (Technology)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/BTN_CloseResourceRequestController_Test.cls
/**
 * Created by Adam on 12/20/2017.
 */

@IsTest(seeAllData=false)
private class BTN_CloseResourceRequestController_Test
{
	static final Integer CONTACT_REQUESTOR = 0;
	static final Integer CONTACT_INTERNAL = 1;
	static final Integer CONTACT_RECRUIT = 2;

	static final String INITIAL_RR_STATUS = 'Open';
	static final String UPDATED_RR_STATUS = 'Closed - Success';
	static final String INITIAL_CANDIDATE_STATUS = 'Open';
	static final String UPDATED_CANDIDATE_1_STATUS = 'Contract signed';
	static final String UPDATED_CANDIDATE_2_STATUS = 'Rejected by us';

	static final String COLLABORATION_GROUP_NAME = 'BlahGroup';

	static Account britenetAccount;
	static Account clientAccount;

	static List<Contact> britenetContacts;
	static Contact clientContact;

	static BTN_ResourceRequest__c resourceRequest;
	static List<BTN_CV__c> resourceRequestCandidates;
	static BTN_CloseResourceRequestController controllerExtension;

	static Contact requestor;

	@TestSetup
	static void createDataModel(){
		BTN_TestDataFactory.getTriggerSkipperCustomSetting();

		setCollaborationGroup();
		setBritenetAccount();
		setClientAccount();
		setBritenetContacts();
		setClientContacts();
		setOpportunity();
		setResourceRequest();
		setCandidates();
	}

	static testMethod void testGetCandidates(){
		prepControllerExtension();

		Test.startTest();

		List<BTN_CV__c> queriedCandidates = controllerExtension.getCandidates();

		Test.stopTest();

		System.assertEquals(resourceRequestCandidates.size(), queriedCandidates.size());
	}

	static testMethod void testGetCandidatesUnsuccessful(){
		prepControllerExtension();

		controllerExtension.resourceRequest = null;

		Test.startTest();

		List<BTN_CV__c> queriedCandidates = controllerExtension.getCandidates();

		Test.stopTest();

		System.assertEquals(null, queriedCandidates);
	}

	static testMethod void testSaveSuccessful(){
		prepControllerExtension();

		controllerExtension.getCandidates();

		controllerExtension.resourceRequest.Status__c = UPDATED_RR_STATUS;
		controllerExtension.candidates[0].Status__c = UPDATED_CANDIDATE_1_STATUS;
		controllerExtension.candidates[1].Status__c = UPDATED_CANDIDATE_2_STATUS;

		Test.startTest();

		PageReference returnedReference = controllerExtension.save();

		Test.stopTest();

		System.assertNotEquals(null, returnedReference);

		resourceRequest = [SELECT Status__c FROM BTN_ResourceRequest__c WHERE Id = :resourceRequest.Id][0];
		System.assertEquals(UPDATED_RR_STATUS, resourceRequest.Status__c);

		List<BTN_CV__c> candidates = new BTN_DAO_Candidate().findCandidatesByResourceRequest(resourceRequest.Id);
		System.assertEquals(resourceRequestCandidates.size(), candidates.size());
		System.assertNotEquals(INITIAL_CANDIDATE_STATUS, candidates[0].Status__c);
		System.assertNotEquals(INITIAL_CANDIDATE_STATUS, candidates[1].Status__c);
	}

	static testMethod void testSaveUnsuccessful(){
		prepControllerExtension();

		controllerExtension.getCandidates();

		controllerExtension.resourceRequest.Status__c = UPDATED_RR_STATUS;

		Test.startTest();

		PageReference returnedReference = controllerExtension.save();

		Test.stopTest();

		System.assertEquals(null, returnedReference);
	}

	static testMethod void testCancel(){
		prepControllerExtension();

		Test.startTest();

		PageReference returnedReference = controllerExtension.cancel();

		Test.stopTest();

		System.assertNotEquals(null, returnedReference);
	}

	static void setCollaborationGroup(){
		BTN_TestDataFactory.getHRCollaborationGroup();
	}

	static void setBritenetAccount(){
		britenetAccount = new Account(
				Name = BTN_ConstantRepo.BRITENET_ACCOUNT_NAME,
				CurrencyIsoCode = BTN_TestDataFactory.TESTCURRENCY,
				RecordTypeId = BTN_RecordTypeUtils.getRecordTypeAccountBritenet().Id
		);
		insert britenetAccount;
	}

	static void setClientAccount(){
		clientAccount = new Account(
				Name = BTN_ConstantRepo.ACCOUNT_PRIVATE_NAME,
				CurrencyIsoCode = BTN_TestDataFactory.TESTCURRENCY,
				RecordTypeId = BTN_RecordTypeUtils.getRecordTypeAccountPrivateSector().Id
		);
		insert clientAccount;
	}

	static void setBritenetContacts(){
		requestor = new Contact(
				AccountId = britenetAccount.Id,
				FirstName = 'Britenet',
				LastName = 'Requestor',
				ResourceRequestor__c = true,
				Email = 'requestor' + BTN_ConstantRepo.BRITENET_MAIL_SUFFIX_PL,
				RecordTypeId = BTN_RecordTypeUtils.getRecordTypeContactInternal().Id
		);
		
		Contact internal = new Contact(
				AccountId = britenetAccount.Id,
				FirstName = 'Britenet',
				LastName = 'Internal',
				ResourceRequestor__c = true,
				Email = 'internal' + BTN_ConstantRepo.BRITENET_MAIL_SUFFIX_PL,
				RecordTypeId = BTN_RecordTypeUtils.getRecordTypeContactInternal().Id
		);

		Contact recruit = new Contact(
				AccountId = britenetAccount.Id,
				FirstName = 'Britenet',
				LastName = 'Recruit',
				ResourceRequestor__c = true,
				Email = 'recruit' + BTN_ConstantRepo.BRITENET_MAIL_SUFFIX_PL,
				RecordTypeId = BTN_RecordTypeUtils.getRecordTypeContactRecruit().Id
		);

		britenetContacts = new List<Contact>{ requestor, internal, recruit };
		insert britenetContacts;
	}

	static void setClientContacts(){
		clientContact = new Contact(
				AccountId = clientAccount.Id,
				FirstName = 'Some',
				LastName = 'Client',
				ResourceRequestor__c = true,
				Email = 'some@client.com',
				RecordTypeId = BTN_RecordTypeUtils.getRecordTypeContactBusiness().Id
		);
		insert clientContact;
	}

	static void setOpportunity(){
		Opportunity opportunity = new Opportunity(
				AccountId = clientAccount.Id,
				ContactId__c = clientContact.Id,
				Name = 'clientOpportunity',
				StageName = 'Draft',
				CloseDate = (System.today() + 15),
				CurrencyIsoCode = BTN_TestDataFactory.testCurrency,
				Pricebook2Id = Test.getStandardPricebookId(),
				NextStep__c = 'dummy stepping',
				NextStepDeadline__c = (System.today() + 10),
				ContractStart__c = Date.newInstance(2000, 1, 1),
				ContractEnd__c = Date.newInstance(2010, 1, 1),
				Description = 'sample Description',
				Location__c = 'Lublin',
				Product_Main_Skills__c = 'main skillzz',
				Product_Secondary_Skills__c = 'sec600',
				Type = 'T&M'
		);
		insert opportunity;

		opportunity.StageName = 'In progress';
		update opportunity;
	}

	static void setResourceRequest(){
		resourceRequest = new BTN_DAO_ResourceRequest().findAutoResourceRequests()[0];
		resourceRequest.Resource_Manager__c = requestor.Id;
		update resourceRequest;
	}

	static void setCandidates(){
		BTN_CV__c internalCandidate = new BTN_CV__c(
				ResourceRequest__c = resourceRequest.Id,
				Contact__c = britenetContacts.get(CONTACT_INTERNAL).Id,
				Status__c = INITIAL_CANDIDATE_STATUS
		);

		BTN_CV__c recruitCandidate = new BTN_CV__c(
				ResourceRequest__c = resourceRequest.Id,
				Contact__c = britenetContacts.get(CONTACT_RECRUIT).Id,
				Status__c = INITIAL_CANDIDATE_STATUS
		);

		resourceRequestCandidates = new List<BTN_CV__c>{ internalCandidate, recruitCandidate };
		insert resourceRequestCandidates;
	}

	static void prepControllerExtension(){
		resourceRequest = new BTN_DAO_ResourceRequest().findAutoResourceRequests()[0];
		resourceRequestCandidates = new BTN_DAO_Candidate().findCandidatesByResourceRequest(resourceRequest.Id);

		PageReference closeResourceRequestPage = Page.BTN_CloseResourceRequest;
		closeResourceRequestPage.getParameters().put('id', resourceRequest.Id);
		Test.setCurrentPage(closeResourceRequestPage);

		ApexPages.StandardController standardController = new ApexPages.StandardController(resourceRequest);
		controllerExtension = new BTN_CloseResourceRequestController(standardController);
	}
}