force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Potential</fullName>
                <default>true</default>
                <label>Potential</label>
            </value>
            <value>
                <fullName>Trusted</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/BTN_ResourceRequest__c.object-meta.xml
<CustomObject>
    <label>Resource request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/AssignedTo__c.field-meta.xml
<CustomField>
    <fullName>AssignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Assigned_To_Resource_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/ContractDuration__c.field-meta.xml
<CustomField>
    <fullName>ContractDuration__c</fullName>
    <label>Contract Duration</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/ContractStart__c.field-meta.xml
<CustomField>
    <fullName>ContractStart__c</fullName>
    <label>Contract Start</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Resource_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/DeliveryDeadline__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDeadline__c</fullName>
    <label>Delivery deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Project Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Polish</fullName>
                <default>true</default>
                <label>Polish</label>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Polish or English</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <inlineHelpText>Junior, Professional, Senior</inlineHelpText>
    <label>.Experience Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kielce</fullName>
            </value>
            <value>
                <fullName>Lublin</fullName>
            </value>
            <value>
                <fullName>Poznań</fullName>
            </value>
            <value>
                <fullName>Warszawa</fullName>
            </value>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/MainSkills__c.field-meta.xml
<CustomField>
    <fullName>MainSkills__c</fullName>
    <label>Main Skills</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Resource_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/OpportunityType__c.field-meta.xml
<CustomField>
    <fullName>OpportunityType__c</fullName>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed price</fullName>
            </value>
            <value>
                <fullName>Time &amp; Material</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Placement__c.field-meta.xml
<CustomField>
    <fullName>Placement__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Customer Rate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/RequestorContact__c.field-meta.xml
<CustomField>
    <fullName>RequestorContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>.Requestor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.Id</field>
            <operation>equals</operation>
            <value>Current User: Contact ID</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Resource Requests (Requestor)</relationshipLabel>
    <relationshipName>Resource_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/RequestorUser__c.field-meta.xml
<CustomField>
    <fullName>RequestorUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>.Requestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resource_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/SecondarySkills__c.field-meta.xml
<CustomField>
    <fullName>SecondarySkills__c</fullName>
    <label>Secondary Skills</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Seniority__c.field-meta.xml
<CustomField>
    <fullName>Seniority__c</fullName>
    <inlineHelpText>Junior, Professional, Senior</inlineHelpText>
    <label>Seniority</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Waiting for client</fullName>
            </value>
            <value>
                <fullName>On shelf</fullName>
            </value>
            <value>
                <fullName>Closed - Success</fullName>
            </value>
            <value>
                <fullName>Closed - Failure</fullName>
            </value>
            <value>
                <fullName>Opportunity Closed</fullName>
            </value>
            <value>
                <fullName>Closed - We resign</fullName>
            </value>
            <value>
                <fullName>Closed - Blood in the sand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/ZohoUrl__c.field-meta.xml
<CustomField>
    <fullName>ZohoUrl__c</fullName>
    <label>ZOHO Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/recordTypes/Auto.recordType-meta.xml
<RecordType>
    <fullName>Auto</fullName>
    <active>true</active>
    <description>Automatic resource request</description>
    <label>Auto</label>
</RecordType>

force-app/main/default/objects/BTN_ResourceRequest__c/recordTypes/Manual.recordType-meta.xml
<RecordType>
    <fullName>Manual</fullName>
    <active>true</active>
    <description>Manual resource request</description>
    <label>Manual</label>
</RecordType>

force-app/main/default/classes/BTN_ResourceRequestBuilderHelper.cls
/*
 * @author Dariusz Chmiela
 * @date 2016-08-18
 * @description BTN_ResourceRequestBuilderHelper Builder for BTN_ResourceRequest__c
*/
public with sharing class BTN_ResourceRequestBuilderHelper implements BTN_BuilderHelper{
    private static BTN_DAO_Account daoAccount = new BTN_DAO_Account();
    private BTN_ResourceRequest__c record;
    public static final String DEFAULT_CONTRACT_START = String.valueOf(Date.today());
    public static final String DEFAULT_CONTRACT_DURATION = '2';
    public static final String DEFAULT_RATE = '1';
    public static final Date DEFAULT_DELIVERY_DEADLINE = Date.today().addDays(1);
    public static final String DEFAULT_LEVEL = 'BEGINER';
    public static final String DEFAULT_LANGUAGE = BTN_ResourceRequest__c.Language__c.getDescribe().getPicklistValues().get(0).value;
    public static final String DEFAULT_LOCATION = BTN_ResourceRequest__c.Location__c.getDescribe().getPicklistValues().get(0).value;
    public static final String DEFAULT_MAIN_SKILLS = 'JAVA';
    public static final String DEFAULT_OPPORTUNITY_TYPE = BTN_ResourceRequest__c.OpportunityType__c.getDescribe().getPicklistValues().get(0).value;
    public static final String DEFAULT_POSITION = 'Java Developer';
    public static final String DEFAULT_DESCRIPTION = 'Fluent in english';
    public static final Decimal DEFAULT_QUANTITY = 100;
    public static final String DEFAULT_SECONDARY_SKILLS = 'C++';
    public static final String DEFAULT_SENIORITY = 'Pan';
    public static final String DEFAULT_STATUS = BTN_ResourceRequest__c.Status__c.getDescribe().getPicklistValues().get(0).value;
    public static final String DEFAULT_TECHNOLOGY = 'JAVA';
    public static final String DEFAULT_ZOHOURL = 'https://www.zoho.pl/129321';
    public static final RecordType DEFAULT_RECORDTYPE = BTN_RecordTypeUtils.getRecordTypeResourceRequestManual();
    /**
     * @author Dariusz Chmiela
     * @date 2016-09-20
     * @description buildWithAutoRecordType Method builds BTN_ResourceRequest__c sObject with Auto record type
     * @return BTN_ResourceRequestBuilderHelper - current instance
    */
    public static BTN_ResourceRequestBuilderHelper buildWithAutoRecordType() {
        return buildWith(BTN_RecordTypeUtils.getRecordTypeResourceRequestAuto().Id);
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-09-20
     * @description buildWithManualRecordType Method builds BTN_ResourceRequest__c sObject with Manual record type
     * @return BTN_ResourceRequestBuilderHelper - current instance
    */
    public static BTN_ResourceRequestBuilderHelper buildWithManualRecordType() {
        return buildWith(BTN_RecordTypeUtils.getRecordTypeResourceRequestManual().Id);
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-09-20
     * @description buildWith Method builds BTN_ResourceRequest__c with given Record Type
     * @param String - given record type to set
     * @return BTN_ResourceRequestBuilderHelper - current instance
    */
    private static BTN_ResourceRequestBuilderHelper buildWith(String recordTypeId){
        BTN_ResourceRequestBuilderHelper resourceRequestBuilderHelper = new BTN_ResourceRequestBuilderHelper();
        resourceRequestBuilderHelper.record = applyDefaults(recordTypeId);
        return resourceRequestBuilderHelper;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-09-20
     * @description applyDefaults Method applies default values to record for given Record Type
     * @param String - Record Type Id to set
     * @return Account
    */
    private static BTN_ResourceRequest__c applyDefaults(String recordTypeId) {
        return new BTN_ResourceRequest__c(
                ContractStart__c = DEFAULT_CONTRACT_START,
                ContractDuration__c = DEFAULT_CONTRACT_DURATION,
                Rate__c = DEFAULT_RATE,
                DeliveryDeadline__c = DEFAULT_DELIVERY_DEADLINE,
                Level__c = DEFAULT_LEVEL,
                Language__c = DEFAULT_LANGUAGE,
                Location__c = DEFAULT_LOCATION,
                MainSkills__c = DEFAULT_MAIN_SKILLS,
                OpportunityType__c = DEFAULT_OPPORTUNITY_TYPE,
                Position__c = DEFAULT_POSITION,
                Description__c = DEFAULT_DESCRIPTION,
                Placement__c = DEFAULT_QUANTITY,
                SecondarySkills__c = DEFAULT_SECONDARY_SKILLS,
                Seniority__c = DEFAULT_SENIORITY,
                Status__c = DEFAULT_STATUS,
                Technology__c = DEFAULT_TECHNOLOGY,
                ZohoUrl__c = DEFAULT_ZOHOURL,
                RecordTypeId = recordTypeId
        );
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withContractDuration Method set up BTN_ResourceRequest__c ContractDuration__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withContractDuration(String duration) {
        record.ContractDuration__c = duration;
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withOpportunityType Method set up BTN_ResourceRequest__c OpportunityType__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withOpportunityType(String opportunityType) {
        record.OpportunityType__c = opportunityType;
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withOpportunityType Method set up BTN_ResourceRequest__c OpportunityType__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withOpportunity(String oppId) {
        record.Opportunity__c = oppId;
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withRequestorContact Method set up BTN_ResourceRequest__c RequestorContact__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withRequestorContact(String requestorContactId) {
        record.RequestorContact__c = requestorContactId;
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withRequestorUser Method set up BTN_ResourceRequest__c RequestorUser__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withRequestorUser(String requestorUserId) {
        record.RequestorUser__c = requestorUserId;
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withCustomerAccount Method set up BTN_ResourceRequest__c CustomerAccount__c
     * @param String Account Id
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withCustomerAccount(String customerAccountId) {
        record.CustomerAccount__c = customerAccountId;
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withCustomerAccount Method set up BTN_ResourceRequest__c Position__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withPosition(String position) {
        record.Position__c = position;
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withLocation Method set up BTN_ResourceRequest__c Location__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withLocation(String location) {
        record.Location__c = location;
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withDeliveryDeadline Method set up BTN_ResourceRequest__c DeliveryDeadline__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withDeliveryDeadline(Date deliveryDeadline) {
        record.DeliveryDeadline__c = deliveryDeadline;
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withDescription Method set up BTN_ResourceRequest__c Description__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withDescription(String description) {
        record.Description__c = description;
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withAssignedTo Method set up BTN_ResourceRequest__c AssignedTo__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withAssignedTo(String assignedToId) {
        record.AssignedTo__c = assignedToId;
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withSecondarySkills Method set up BTN_ResourceRequest__c SecondarySkills__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withSecondarySkills(String secondarySkills) {
        record.SecondarySkills__c = secondarySkills;
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withContractStart Method set up BTN_ResourceRequest__c ContractStart__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withContractStart(Date contractStart) {
        record.ContractStart__c = String.valueOf(contractStart);
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withContractStart Method set up BTN_ResourceRequest__c ContractStart__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withContractStart(String contractStart) {
        record.ContractStart__c = contractStart;
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withCustomerRate Method set up BTN_ResourceRequest__c Rate__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withCustomerRate(Decimal customerRate) {
        record.Rate__c = String.valueOf(customerRate);
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withCustomerRate Method set up BTN_ResourceRequest__c Rate__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withCustomerRate(String customerRate) {
        record.Rate__c = customerRate;
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withQuantity Method set up BTN_ResourceRequest__c Placement__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withQuantity(Integer quantity) {
        record.Placement__c = quantity;
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withLanguage Method set up BTN_ResourceRequest__c Language__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withLanguage(String language) {
        record.Language__c = language;
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-08-18
     * @description withExpirienceLevel Method set up BTN_ResourceRequest__c Level__c
     * @return BTN_ResourceRequestBuilderHelper - instance of Builder
    */
    public BTN_ResourceRequestBuilderHelper withExpirienceLevel(String expirienceLevel) {
        record.Level__c = expirienceLevel;
        return this;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-09-09
     * @inherited from interface
    */
    public BTN_ResourceRequest__c get() {
        return record;
    }
    /**
     * @author Dariusz Chmiela
     * @date 2016-09-09
     * @inherited from interface
    */
    public BTN_ResourceRequest__c save(){
        insert record;
        return record;
    }
}