force-app/main/default/objects/Achievement_Category__c/Achievement_Category__c.object-meta.xml
<CustomObject>
    <description>Achievement Category</description>
    <label>Achievement Category</label>
    <nameField>
        <label>Achievement Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Category__c/fields/Number_of_Achievements__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Achievements__c</fullName>
    <label>Number of Achievements</label>
    <summaryForeignKey>Achievement__c.Achievement_Category__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/Achievement_Set__c.object-meta.xml
<CustomObject>
    <description>Achievement Set</description>
    <label>Achievement Set</label>
    <nameField>
        <label>Achievement Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set__c/fields/AboutWho__c.field-meta.xml
<CustomField>
    <fullName>AboutWho__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>About Who</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Surveys About Me</relationshipLabel>
    <relationshipName>SurveysAboutMe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact field is valid only for Contact Survey and Contact Profile record types</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Number_Of_Achievements__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Achievements__c</fullName>
    <label>Number Of Achievements</label>
    <summaryForeignKey>Achievement_Set_Item__c.Achievement_Set__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Parent_Profile__c.field-meta.xml
<CustomField>
    <fullName>Parent_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Profile</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select the Profile Achievement set</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Position Profile, Specialization</value>
        </filterItems>
        <filterItems>
            <field>Achievement_Set__c.Career_Path__c</field>
            <operation>equals</operation>
            <valueField>$Source.Career_Path__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Score_Minimal_Value__c.field-meta.xml
<CustomField>
    <fullName>Score_Minimal_Value__c</fullName>
    <defaultValue>0.5</defaultValue>
    <description>Minimalne dopasowanie po jakim Profil zostanie przypisany do Pracownika</description>
    <inlineHelpText>Minimalne dopasowanie po jakim Profil zostanie przypisany do Pracownika</inlineHelpText>
    <label>Score Minimal Value</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/SelfSurvey__c.field-meta.xml
<CustomField>
    <fullName>SelfSurvey__c</fullName>
    <formula>NOT(ISBLANK(AboutWho__c)) &amp;&amp; NOT(ISBLANK(Who__c)) &amp;&amp; AboutWho__c = Who__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Self-Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Skip_Score_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Skip_Score_Calculation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Score Calculation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Who__c.field-meta.xml
<CustomField>
    <fullName>Who__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Who</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>My Surveys</relationshipLabel>
    <relationshipName>MySurveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/Achievement_Set_Item__c.object-meta.xml
<CustomObject>
    <description>Achievement Set Item</description>
    <label>Achievement Set Item</label>
    <nameField>
        <displayFormat>ASI{00000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Set Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Achievement_Set__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Set__c</fullName>
    <label>Achievement Set</label>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Career_Path__c/Career_Path__c.object-meta.xml
<CustomObject>
    <label>Career Path</label>
    <nameField>
        <label>Career Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Career Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AchievementSetPageExtension.cls
/**
 * Visualforce page controller extension for the Achievements Set record manipulations
 * @author Adam Siwek
 */
public with sharing virtual class AchievementSetPageExtension {

    public Achievement_Set__c achievementSet {get; set;}
    private Id achievementSetId;
    protected Id achievementSetToCmpId;

    public String searchAchievementName {get; set;}
    private List<CategoryWrapper> categoryFilters = new List<CategoryWrapper>();


    private List<SelectOption> achievementLevels = new List<SelectOption>();
    private List<AchievementUtils.AchievementGroup> achievementGroups = new List<AchievementUtils.AchievementGroup>();

    public AchievementSetPageExtension(ApexPages.StandardController ctr) {
        SObject record = getContextRecord(ctr, System.currentPageReference().getParameters());

        if (System.currentPageReference().getParameters().containsKey('RecordType')) {
            Id recordTypeId = System.currentPageReference().getParameters().get('RecordType');
            record.put('RecordTypeId', recordTypeId);
        }

        loadFirstAchievementSet(record, ApexPages.currentPage().getParameters());
        loadSecondAchievementSet(record, ApexPages.currentPage().getParameters());

        achievementSetId = achievementSet.Id;
    }

    protected virtual SObject getContextRecord(ApexPages.StandardController ctr, Map<String, String> pageParams) {
        try {
            return ctr.getRecord();
        } catch (Exception e) {
        }
        Id recordId = System.currentPageReference().getParameters().get('id');
        SObject record = new Achievement_Set__c();
        record.put('Id', recordId);
        return record;
    }

    protected virtual void loadFirstAchievementSet(SObject scopeRecord, Map<String, String> pageParams) {
        if (scopeRecord.Id != null) {
            achievementSet = [SELECT Id, Name, RecordTypeId, Score_Minimal_Value__c, Contact__c, Career_Path__c, Number_Of_Achievements__c, Parent_Profile__c, Who__c, AboutWho__c, SelfSurvey__c, Skip_Score_Calculation__c FROM Achievement_Set__c WHERE Id = :scopeRecord.Id AND IsDeleted = false LIMIT 1 ALL ROWS];
        } else {
            achievementSet = (Achievement_Set__c)scopeRecord;
        }
    }

    protected virtual void loadSecondAchievementSet(SObject scopeRecord, Map<String, String> pageParams) {
        if (pageParams.containsKey('achievementSetToCmp')) {
            achievementSetToCmpId = pageParams.get('achievementSetToCmp');
        }
    }

    public Boolean getCanEditAchievementSetName() {
        return achievementSet.RecordTypeId != AchievementUtils.getAchievementSetContactProfileRecordType().Id &&
                achievementSet.RecordTypeId != AchievementUtils.getAchievementSetSurveyRecordType().Id;
    }

    public Boolean getShowWhoField() {
        return achievementSet.RecordTypeId == AchievementUtils.getAchievementSetSurveyRecordType().Id;
    }

    public Boolean getShowAchievementSetContact() {
        return achievementSet.RecordTypeId == AchievementUtils.getAchievementSetContactProfileRecordType().Id;
    }

    public Boolean getShowAchievementSetMinScoreValue() {
        return achievementSet.RecordTypeId == AchievementUtils.getAchievementSetProfileRecordType().Id ||
                achievementSet.RecordTypeId == AchievementUtils.getAchievementSetPositionRecordType().Id;
    }

    public Boolean getShowCareerPath() {
        return achievementSet.RecordTypeId == AchievementUtils.getAchievementSetProfileRecordType().Id ||
                achievementSet.RecordTypeId == AchievementUtils.getAchievementSetPositionRecordType().Id;
    }

    public Boolean getShowGroups() {
        return achievementSet.RecordTypeId == AchievementUtils.getAchievementSetProfileRecordType().Id ||
                achievementSet.RecordTypeId == AchievementUtils.getAchievementSetPositionRecordType().Id;
    }

    public Boolean getShowSpecializations() {
        return achievementSet.RecordTypeId == AchievementUtils.getAchievementSetPositionRecordType().Id;
    }

    public Boolean getShowSpecializationGroups() {
        return achievementSet.RecordTypeId == AchievementUtils.getAchievementSetPositionRecordType().Id;
    }

    public SelectOption[] getAchievementLevels() {
        if (achievementLevels.isEmpty()) {
            List<Schema.PicklistEntry> ple = Achievement_Set_Item__c.Level__c.getDescribe().getPicklistValues();

            achievementLevels.add(new SelectOption('', System.Label.None));
            for (Schema.PicklistEntry pe : ple) {
                achievementLevels.add(new SelectOption(pe.getValue(), pe.getLabel()));
            }
        }
        return achievementLevels;
    }

    public List<AchievementUtils.AchievementGroup> getAchievementGroups() {
        if (achievementGroups.isEmpty()) {
            achievementGroups = AchievementService.getAchievementGroups(achievementSetId, achievementSetToCmpId);
        }
        return applyFilter(achievementGroups);
    }

    private List<AchievementUtils.AchievementGroup> applyFilter(List<AchievementUtils.AchievementGroup> data) {
        List<AchievementUtils.AchievementGroup> filteredData = new List<AchievementUtils.AchievementGroup>();

        Set<String> categories = new Set<String>();
        for (CategoryWrapper cw : categoryFilters) {
            if (cw.selected) {
                categories.add(cw.category.Name.toLowerCase());
            }
        }

        for (AchievementUtils.AchievementGroup grp : data) {
            if (categories.contains(grp.name.toLowerCase())) {
                filteredData.add(grp);
            }
        }

        return filteredData;
    }

    public List<CategoryWrapper> getCategoryFilters() {
        if (categoryFilters.isEmpty()) {
            for (Achievement_Category__c ac : AchievementService.getAllAchievementCategories()) {
                categoryFilters.add(new CategoryWrapper(ac));
            }
        }
        return categoryFilters;
    }

    public void selectAllCategories() {
        for (CategoryWrapper cw : categoryFilters) {
            cw.selected = true;
        }
    }

    public void unselectAllCategories() {
        for (CategoryWrapper cw : categoryFilters) {
            cw.selected = false;
        }
    }

    public PageReference saveAchievementSet() {
        System.Savepoint sp = Database.setSavepoint();
        try {
            if (achievementSet.Id == null) {
                insert achievementSet;
                achievementSetId = achievementSet.Id;
                AchievementService.applyAchievementsToSet(achievementSet.Id, achievementGroups);
            } else {
                update achievementSet;
            }
            if (achievementSet.Skip_Score_Calculation__c != null && achievementSet.Skip_Score_Calculation__c) {
                achievementSet.Score_Minimal_Value__c = 0;
            }
            AchievementService.save(achievementGroups);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, System.Label.Saved_Successfully));
            if (ApexPages.currentPage().getParameters().get('saveURL') != null) {
                return new PageReference(ApexPages.currentPage().getParameters().get('saveURL')).setRedirect(true);
            } else {
                return new PageReference('/' + achievementSet.Id).setRedirect(true);
            }
        } catch (Exception e) {
            ApexPages.addMessages(e);
            Database.rollback(sp);
        }
        return null;
    }

    public with sharing class CategoryWrapper {
        public Boolean selected {get; set;}
        public Achievement_Category__c category {get; private set;}

        public CategoryWrapper(Achievement_Category__c category) {
            this.category = category;
            selected = true;
        }
    }
}