force-app/main/default/objects/BTN_Event__c/BTN_Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E{00000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Event__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>BTN_CV__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Career_path__c.field-meta.xml
<CustomField>
    <fullName>Career_path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>for periodic assessment</description>
    <label>Career path</label>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipName>Events2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Current_Position__c.field-meta.xml
<CustomField>
    <fullName>Current_Position__c</fullName>
    <description>Asessment module (requires snapshot on creation time and not the live lookup)</description>
    <label>Current Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description (HR)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/DescriptionTechnical__c.field-meta.xml
<CustomField>
    <fullName>DescriptionTechnical__c</fullName>
    <label>Description (Technical)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/General_assessment__c.field-meta.xml
<CustomField>
    <fullName>General_assessment__c</fullName>
    <description>for periodic assessment</description>
    <label>General assessment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Below average</fullName>
            </value>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>Above average</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/GoogleId__c.field-meta.xml
<CustomField>
    <fullName>GoogleId__c</fullName>
    <label>GoogleId</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Interviewed__c.field-meta.xml
<CustomField>
    <fullName>Interviewed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewed</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Events (Interviewed)</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Interviewer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Interviewer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer (HR)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Interviewer_user__c.field-meta.xml
<CustomField>
    <fullName>Interviewer_user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lublin Hamleta</fullName>
            </value>
            <value>
                <fullName>Lublin Morwowa</fullName>
            </value>
            <value>
                <fullName>Warszawa Bukowińska</fullName>
            </value>
            <value>
                <fullName>Warszawa Wołoska</fullName>
            </value>
            <value>
                <fullName>Kielce IX Wieków</fullName>
            </value>
            <value>
                <fullName>Poznań Strzelecka</fullName>
            </value>
            <value>
                <fullName>Zdalnie</fullName>
            </value>
            <value>
                <fullName>U klienta [Other location is mandatory]</fullName>
            </value>
            <value>
                <fullName>Inne [Other location is mandatory]</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
                <isActive>false</isActive>
                <label>Call</label>
            </value>
            <value>
                <fullName>Meeting</fullName>
                <isActive>false</isActive>
                <label>Meeting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Meeting_Room__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Room__c</fullName>
    <label>Meeting Room</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In person</fullName>
            </value>
            <value>
                <fullName>Telephonic</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Technical_Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Technical_Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technical Interviewer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Events2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Technical_Interviewer_User__c.field-meta.xml
<CustomField>
    <fullName>Technical_Interviewer_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technical Interviewer (User)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Events2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal Interview</fullName>
            </value>
            <value>
                <fullName>External Interview</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Periodic Assessment</fullName>
            </value>
            <value>
                <fullName>Notes</fullName>
                <isActive>false</isActive>
                <label>Notes</label>
            </value>
            <value>
                <fullName>Others</fullName>
                <isActive>false</isActive>
                <label>Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/UserUsedForGoogleIntegration__c.field-meta.xml
<CustomField>
    <fullName>UserUsedForGoogleIntegration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserUsedForGoogleIntegration</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Events1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_PersonalTarget__c/BTN_PersonalTarget__c.object-meta.xml
<CustomObject>
    <label>Target</label>
    <nameField>
        <displayFormat>PT-{0000000}</displayFormat>
        <label>Target</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_PersonalTarget__c/fields/Achieved_percent__c.field-meta.xml
<CustomField>
    <fullName>Achieved_percent__c</fullName>
    <label>Achieved %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/BTN_PersonalTarget__c/fields/Certificate__c.field-meta.xml
<CustomField>
    <fullName>Certificate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Certificate</label>
    <referenceTo>BTN_Certificate__c</referenceTo>
    <relationshipLabel>Targets</relationshipLabel>
    <relationshipName>Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_PersonalTarget__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_PersonalTarget__c/fields/Due_date__c.field-meta.xml
<CustomField>
    <fullName>Due_date__c</fullName>
    <label>Due date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BTN_PersonalTarget__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>BTN_Event__c</referenceTo>
    <relationshipLabel>Targets</relationshipLabel>
    <relationshipName>BTN_PersonalTarget</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BTN_PersonalTarget__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Target</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_PersonalTarget__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>CV Improvement</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Certificate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Career_Path__c/Career_Path__c.object-meta.xml
<CustomObject>
    <label>Career Path</label>
    <nameField>
        <label>Career Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Career Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_Position__c.field-meta.xml
<CustomField>
    <fullName>Current_Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Position</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select Achievement Set that describe position profile and Position form selected Career Path</errorMessage>
        <filterItems>
            <field>Achievement_Set__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Position Profile</value>
        </filterItems>
        <filterItems>
            <field>Achievement_Set__c.Career_Path__c</field>
            <operation>equals</operation>
            <valueField>$Source.Career_Path__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Other Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Analytic</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/GoogleAccessToken__c.field-meta.xml
<CustomField>
    <fullName>GoogleAccessToken__c</fullName>
    <label>GoogleAccessToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/GoogleAuthCode__c.field-meta.xml
<CustomField>
    <fullName>GoogleAuthCode__c</fullName>
    <label>GoogleAuthCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/GoogleRefreshToken__c.field-meta.xml
<CustomField>
    <fullName>GoogleRefreshToken__c</fullName>
    <label>GoogleRefreshToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/GoogleTokenDate__c.field-meta.xml
<CustomField>
    <fullName>GoogleTokenDate__c</fullName>
    <label>GoogleTokenDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User/fields/GoogleTokenExpiresIn__c.field-meta.xml
<CustomField>
    <fullName>GoogleTokenExpiresIn__c</fullName>
    <label>GoogleTokenExpiresIn</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BTN_DAO_Event.cls
public class BTN_DAO_Event extends BTN_DAO{

/**
     * @author Wojciech Mazur
     * @date   2016-11-08
     * @description Constructor
    */
    public BTN_DAO_Event () {
    }
    
    public override Schema.SObjectType getSObjectType() {
        return BTN_Event__c.sObjectType;
    }
    
    public override List<Schema.SObjectField> getSObjectFields() {
        return new List<Schema.SObjectField>{
                BTN_Event__c.Id,
                BTN_Event__c.Name,
                BTN_Event__c.Candidate__c,
                BTN_Event__c.Description__c,
                BTN_Event__c.DescriptionTechnical__c,
                BTN_Event__c.End_Time__c,
                BTN_Event__c.Location__c,
                BTN_Event__c.Start_Time__c,
                BTN_Event__c.SubType__c,
                BTN_Event__c.Title__c,
                BTN_Event__c.GoogleId__c,
                BTN_Event__c.UserUsedForGoogleIntegration__c,
                BTN_Event__c.RecordTypeId,
                BTN_Event__c.Interviewer_Contact__c,
                BTN_Event__c.Technical_Interviewer__c,
                BTN_Event__c.CreatedDate,
                BTN_Event__c.Meeting_Room__c
        };
    }

   
        /**
         * @author Wojciech Mazur
         * @date   2016-11-08
         * @description find Event
         * @param  userName - Name of User to search for
         * @return     User       - found User
         */
    public BTN_Event__c findEventById(Id eventId) {
        return (BTN_Event__c) findSObjectById(eventId);
    }
    
     /**
     * @author Wojciech Mazur
     * @date   2016-11-08
     * @description find by Ids
     * @return List<Contact>
    */
    public List<BTN_Event__c> findEventsByIds(Set<Id> ids) {
        return findSObjectsBy(
                new List<SearchCondition>{
                        new SearchCondition(
                                'Id',
                                'in',
                                ids
                        )
                }
        );
    }
    
    /**
     * @author Wojciech Mazur
     * @date   2016-12-14
     * @description get previos periodic assessment
     * @return BTN_Event__c
    */
    public BTN_Event__c findPreviousAssessment(Id contactId, Id currentAssessmentId, DateTime currentAssessmentDate) {
    	if(currentAssessmentDate ==null){
    		currentAssessmentDate = system.now();
    	}
        List<BTN_Event__c> objects = findSObjectsBy(
                new List<SearchCondition>{
                        new SearchCondition('Interviewed__c', '=', contactId),
                        new SearchCondition('AND RecordTypeid', '=', BTN_RecordTypeUtils.getRecordTypeCustomEventPeriodicAssessment().Id),
                        new SearchCondition('And id', '<>', currentAssessmentId),
                        new SearchCondition('And createdDate < '+ currentAssessmentDate.formatGMT('YYYY-MM-dd')+'T'+currentAssessmentDate.formatGMT('HH:mm:ss')+'Z'),
                        new SearchCondition('order by createdDate desc LIMIT 1')
                        
                }
        );
        return objects.isEmpty() ? null : (BTN_Event__c) objects.get(0);
    }
    
    /**
     * @author Wojciech Mazur
     * @date   2016-11-08
     * @description add Interviewer fields
     * @return void
    */
    public BTN_DAO_Event addInterviewerUsersFields() {
        currentFields.add('Technical_Interviewer_User__r.GoogleTokenExpiresIn__c');
        currentFields.add('Technical_Interviewer_User__r.GoogleTokenDate__c');
        currentFields.add('Technical_Interviewer_User__r.GoogleRefreshToken__c');
        currentFields.add('Technical_Interviewer_User__r.GoogleAccessToken__c');
        currentFields.add('Technical_Interviewer_User__r.GoogleAuthCode__c');
        currentFields.add('Technical_Interviewer_User__r.Email');
        currentFields.add('Technical_Interviewer_User__r.Name');
        currentFields.add('Technical_Interviewer_User__r.FirstName');
        currentFields.add('Technical_Interviewer_User__r.LastName');
        currentFields.add('Technical_Interviewer_User__r.Id');
        currentFields.add('Interviewer_user__r.GoogleTokenExpiresIn__c');
        currentFields.add('Interviewer_user__r.GoogleTokenDate__c');
        currentFields.add('Interviewer_user__r.GoogleRefreshToken__c');
        currentFields.add('Interviewer_user__r.GoogleAccessToken__c');
        currentFields.add('Interviewer_user__r.GoogleAuthCode__c');
        currentFields.add('Interviewer_user__r.Email');
        currentFields.add('Interviewer_user__r.Name');
        currentFields.add('Interviewer_user__r.FirstName');
        currentFields.add('Interviewer_user__r.LastName');
        currentFields.add('Interviewer_user__r.Id');
        currentFields.add('Technical_Interviewer__r.Email');
        currentFields.add('Interviewer_Contact__r.Email');
        currentFields.add('CreatedBy.Id');
        currentFields.add('CreatedBy.Email');
        currentFields.add('CreatedBy.GoogleAccessToken__c');
        return this;
    }
    
    /**
     * @author Wojciech Mazur
     * @date   2016-11-08
     * @description add integrated user  fields
     * @return void
    */
    public BTN_DAO_Event addIntegratedUserFields() {
        currentFields.add('UserUsedForGoogleIntegration__r.GoogleTokenExpiresIn__c');
        currentFields.add('UserUsedForGoogleIntegration__r.GoogleTokenDate__c');
        currentFields.add('UserUsedForGoogleIntegration__r.GoogleRefreshToken__c');
        currentFields.add('UserUsedForGoogleIntegration__r.GoogleAccessToken__c');
        currentFields.add('UserUsedForGoogleIntegration__r.GoogleAuthCode__c');
        currentFields.add('UserUsedForGoogleIntegration__r.Email');
        currentFields.add('UserUsedForGoogleIntegration__r.Name');
        currentFields.add('UserUsedForGoogleIntegration__r.FirstName');
        currentFields.add('UserUsedForGoogleIntegration__r.LastName');
        currentFields.add('UserUsedForGoogleIntegration__r.Id');
        return this;
    }
    
    /**
     * @author Wojciech Mazur
     * @date   2016-11-08
     * @description add Interviewed contact fields
     * @return void
    */
    public BTN_DAO_Event addInterviewedContactFields() {
        currentFields.add('Interviewed__r.Email');
        currentFields.add('Interviewed__r.Name');
        currentFields.add('Interviewed__r.FirstName');
        currentFields.add('Interviewed__r.LastName');
        currentFields.add('Interviewed__c');
        return this;
    }
    
    /**
     * @author Wojciech Mazur
     * @date   2016-12-14
     * @description add Periodic assessment fields
     * @return void
    */
    public BTN_DAO_Event addPeriodicAssessmentFields() {
        currentFields.add('Current_Position__c');
        currentFields.add('Career_path__c');
        currentFields.add('General_assessment__c');
        currentFields.add('(select id, name, Type__c, Target__c, Comments__c, Achieved_percent__c, Event__c, Due_date__c, Certificate__c from BTN_PersonalTarget__r)');
        
        
        return this;
    }

}