force-app/main/default/objects/BTN_Event__c/BTN_Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E{00000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Event__c/fields/Interviewed__c.field-meta.xml
<CustomField>
    <fullName>Interviewed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewed</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Events (Interviewed)</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/NextAssessmentDate__c.field-meta.xml
<CustomField>
    <fullName>NextAssessmentDate__c</fullName>
    <label>Next Assessment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal Interview</fullName>
            </value>
            <value>
                <fullName>External Interview</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Periodic Assessment</fullName>
            </value>
            <value>
                <fullName>Notes</fullName>
                <isActive>false</isActive>
                <label>Notes</label>
            </value>
            <value>
                <fullName>Others</fullName>
                <isActive>false</isActive>
                <label>Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Analytic</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BTN_EventPeriodicController_Test.cls
@isTest
private class BTN_EventPeriodicController_Test {

	/**
     * @author Wojciech Mazur
     * @date   2016-12-28
     * @description Prepare data for tests
    */
    @TestSetup static void createDataStructure() {
        CollaborationGroup cg = BTN_TestDataFactory.getHRCollaborationGroup();
        BTN_TestDataFactory.getNewBssDummyConnections();
        Account acc = BTN_TestDataFactory.getBriteNetAccount();
        //Contact internalCon = BTN_TestDataFactory.getRequestorInternalContact(acc.Id);
        /*BTN_TestDataFactory.getCV(
                BTN_ResourceRequestBuilderHelper.buildWithManualRecordType().save().Id,
                internalCon.Id
        );*/
    }

	/**
     * @author Wojciech Mazur
     * @date   2016-12-28
     * @description test constructor
    */
    static testMethod void testConstructor() {
        PageReference pageTest = Page.BTN_EventPeriodic;
        Test.setCurrentPage(pageTest);
        Contact hrContact = BTN_ContactBuilderHelper.buildWithInternalRecordType()
                .withAccount(new BTN_DAO_Account().findAccountByName(BTN_ConstantRepo.BRITENET_ACCOUNT_NAME).Id)
                .withEmail('hruser' + BTN_ConstantRepo.BRITENET_MAIL_SUFFIX_PL)
                .withFirstName('Donald')
                .withLastName('Tusk')
                .get();
        insert hrContact;
        Contact internalCon = BTN_TestDataFactory.getRequestorInternalContact(new BTN_DAO_Account().findAccountByName(BTN_ConstantRepo.BRITENET_ACCOUNT_NAME).Id);

         pageTest.getParameters().put(
                BTN_EventPeriodicController.URL_PARAM_CONTACT_ID,
                internalCon.Id
        );
        ApexPages.StandardController stdController = new ApexPages.StandardController(new BTN_Event__c());
        BTN_EventPeriodicController controller = new BTN_EventPeriodicController(stdController);
        system.assert(controller.assessment.interviewed__c==internalCon.Id);

    }

    /**
     * @author Wojciech Mazur
     * @date   2016-12-28
     * @description test save method
    */
    static testmethod void testSave(){
    	PageReference pageTest = Page.BTN_EventPeriodic;
        Test.setCurrentPage(pageTest);
        Contact internalCon = BTN_TestDataFactory.getRequestorInternalContact(new BTN_DAO_Account().findAccountByName(BTN_ConstantRepo.BRITENET_ACCOUNT_NAME).Id);
        Contact hrContact = BTN_ContactBuilderHelper.buildWithInternalRecordType()
                .withAccount(new BTN_DAO_Account().findAccountByName(BTN_ConstantRepo.BRITENET_ACCOUNT_NAME).Id)
                .withEmail('hruser' + BTN_ConstantRepo.BRITENET_MAIL_SUFFIX_PL)
                .withFirstName('Donald')
                .withLastName('Tusk')
                .get();
        hrcontact.ReportsToId = internalCon.Id;
        internalCon.ReportsToId =hrcontact.Id;
        upsert internalCon;
        insert hrContact;
        User internalUser = BTN_TestDataFactory.getCommunityUser(internalCon.Id, internalCon.Email);

        insert internalUser;
        User hrUser = BTN_TestDataFactory.getCommunityUser(hrContact.Id, hrContact.Email);
        insert hrUser;
        //BTN_PermissionSetUtils.assignPermissionSetToUser(BTN_ConstantRepo.PERM_SET_NAME_HR, hrUser);
        //system.runAs(hrUser){

	         pageTest.getParameters().put(
	                BTN_EventPeriodicController.URL_PARAM_CONTACT_ID,
	                internalCon.Id
	        );
	        ApexPages.StandardController stdController = new ApexPages.StandardController(new BTN_Event__c());
	        BTN_EventPeriodicController controller = new BTN_EventPeriodicController(stdController);
	        controller.assessment.NextAssessmentDate__c = system.today()+10;
	        controller.addCurrentTarget();
	        system.assertEquals(1,controller.currentTargets.size());
	        controller.currentTargets.get(0).Type__c = 'Technical';
	        controller.currentTargets.get(0).Target__c = 'test target1';
	        controller.currentTargets.get(0).Due_date__c = system.today()+20;
	        controller.currentTargets.get(0).Achieved_percent__c = 10;
            controller.addCurrentTarget();
            system.assertEquals(2,controller.currentTargets.size());
	        controller.currentTargets.get(1).Type__c = 'Technical';
	        controller.currentTargets.get(1).Target__c = 'test target2';
	        controller.currentTargets.get(1).Due_date__c = system.today()+20;
	        controller.currentTargets.get(1).Achieved_percent__c = 10;
	        controller.targetToDel = '1'; //remove first from the list
	        controller.delCurrentTarget();

	        system.assertEquals(1,controller.currentTargets.size());
			system.assertEquals('test target2',controller.currentTargets.get(0).Target__c);

			system.assert(controller.save()!=null);
        //}


    }
}