force-app/main/default/objects/BTN_Event__c/BTN_Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E{00000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Event__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>BTN_CV__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/BTN_ResourceRequest__c.object-meta.xml
<CustomObject>
    <label>Resource request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <inlineHelpText>Junior, Professional, Senior</inlineHelpText>
    <label>.Experience Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Resource_Manager__c.field-meta.xml
<CustomField>
    <fullName>Resource_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.Name_frm__c</field>
            <operation>contains</operation>
            <value>Codello</value>
        </filterItems>
        <filterItems>
            <field>Contact.Name_frm__c</field>
            <operation>contains</operation>
            <value>Łukaszewski</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Resource_Requests_RM</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/CityLocation__c.field-meta.xml
<CustomField>
    <fullName>CityLocation__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lublin</fullName>
            </value>
            <value>
                <fullName>Warszawa</fullName>
            </value>
            <value>
                <fullName>Kielce</fullName>
            </value>
            <value>
                <fullName>Poznań</fullName>
            </value>
            <value>
                <fullName>Łódź</fullName>
            </value>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Language_1__c.field-meta.xml
<CustomField>
    <fullName>Language_1__c</fullName>
    <label>Main Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Language_level_1__c.field-meta.xml
<CustomField>
    <fullName>Language_level_1__c</fullName>
    <label>Main Language level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A1</fullName>
            </value>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>B1</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>ZOHO</description>
    <label>Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BTN_ContactsSearchController_Test.cls
/**
 * @author Mateusz Przywara
 * @date   2016-10-25
 * @description BTN_ContactsSearchController_Test
*/
@isTest
private class BTN_ContactsSearchController_Test {
    private static final String TEST_SKILLS = 'wiedźmak halina zając pyłek';
    private static final String TEST_SKILLS2 = 'niagara shpongle granatowa kula bób flamastry i mazaki lsd';
    private static final String TEST_SEARCH_CONDITION = 'wiedźmak, halina';
    private static final String TEST_SEARCH_CONDITION_IMPOSSIBLE = 'hałwa,werter';
    /**
     * @author Mateusz Przywara
     * @date   2016-10-25
     * @description Prepare data for tests
    */
    @testSetup static void createDataStructure() {
        BTN_TestDataFactory.getHRCollaborationGroup();
        BTN_TestDataFactory.getBriteNetAccount();
        BTN_TestDataFactory.getRecruitContactWithSkills(
                new BTN_DAO_Account().findAccountByName(BTN_ConstantRepo.BRITENET_ACCOUNT_NAME).Id,
                TEST_SKILLS
        );
        BTN_TestDataFactory.getRecruitContactWithSkills(
                new BTN_DAO_Account().findAccountByName(BTN_ConstantRepo.BRITENET_ACCOUNT_NAME).Id,
                TEST_SKILLS2
        );
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-10-25
     * @description searchForAllRecruitContacts No search conditions so Page will show all Recruits with Skills
    */
    testMethod static void searchForAllRecruitContacts() {
        PageReference pageTest = Page.BTN_ContactsSearchPage;
        Test.setCurrentPage(pageTest);
        // init
        BTN_ContactsSearchController controller = new BTN_ContactsSearchController();
        // get Contacts from View - all Recruits with Skills
        System.assert(!controller.getFoundContacts().isEmpty());
        controller.resetSearch();
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-10-25
     * @description searchForNonExistingRecruit No search results
    */
    testMethod static void searchForNonExistingRecruit() {
        PageReference pageTest = Page.BTN_ContactsSearchPage;
        Test.setCurrentPage(pageTest);
        // init
        BTN_ContactsSearchController controller = new BTN_ContactsSearchController();
        controller.searchConditions = TEST_SEARCH_CONDITION_IMPOSSIBLE;
        // get Contacts from View - should be empty.
        System.assert(controller.getFoundContacts().isEmpty());
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-10-25
     * @description searchFoNonExistingRecruit No search results
    */
    testMethod static void searchForExistingRecruit() {

        Contact ct = [SELECT Id FROM Contact LIMIT 1];

        Id [] fixedSearchResults= new Id[1];
        fixedSearchResults[0] = ct.Id;
        Test.setFixedSearchResults(fixedSearchResults);
        PageReference pageTest = Page.BTN_ContactsSearchPage;
        Test.setCurrentPage(pageTest);
        // init
        BTN_ContactsSearchController controller = new BTN_ContactsSearchController();
        controller.searchConditions = TEST_SEARCH_CONDITION;
        controller.searchAnyone = TEST_SEARCH_CONDITION;
        controller.searchNone = TEST_SEARCH_CONDITION_IMPOSSIBLE;
        // get Contacts from View - result should contain one Contact due to criteria
        System.assertEquals(1, controller.getFoundContacts().size());

        Boolean hasValue = controller.hasNext;
        hasValue = controller.hasPrevious;
        Integer pageNumber = controller.pageNumber;
        controller.first();
        controller.last();
        controller.next();
        controller.previous();
        controller.refresh();
    }
    testMethod static void searchInContact() {

        Contact ct = [SELECT Id,Position__c,Level__c,CityLocation__c,Language_1__c,Language_level_1__c,RecordType.Name FROM Contact LIMIT 1];
        ct.Level__c = 'Junior';
        ct.CityLocation__c = 'Lublin';
        ct.Language_1__c = 'English';
        ct.Language_level_1__c = 'A1';
        ct.Position__c = 'Recruitment Specialist';
        update ct;

        BTN_Event__c event  = new BTN_Event__c();
        event.RecordTypeId = BTN_RecordTypeUtils.getRecordTypeCustomEventPeriodicAssessment().Id;

        BTN_ResourceRequest__c rr = BTN_ResourceRequestBuilderHelper.buildWithManualRecordType().save();
        rr.Resource_Manager__c = ct.Id;
        update rr;

        event.Candidate__c = BTN_TestDataFactory.getCV(rr.Id, ct.Id).Id;
        insert event;

        Id [] fixedSearchResults= new Id[2];
        fixedSearchResults[0] = ct.Id;
        fixedSearchResults[1] = event.Id;
        Test.setFixedSearchResults(fixedSearchResults);
        PageReference pageTest = Page.BTN_ContactsSearchPage;
        Test.setCurrentPage(pageTest);


        BTN_ContactsSearchController controller = new BTN_ContactsSearchController();
        System.assert(controller.getFoundContacts().size()>1);
        System.assert(controller.getRecordTypes().size()>1);
        controller.resetSearch();

        controller.searchContact = ct;
        controller.searchContactRecordType = ct.RecordTypeId;
        controller.searchConditions = ct.Position__c;

        List<Contact> results = controller.getFoundContacts();
        System.assert([SELECT Id FROM Contact].size()>1);
        System.assertEquals(1, controller.getFoundContacts().size());
        Contact result = results[0];
        System.assertEquals(ct.Id, result.Id);
    }
    testMethod static void searchForExistingRecruitWithOneWord() {

        Contact ct = [SELECT Id FROM Contact LIMIT 1];

        Id [] fixedSearchResults= new Id[1];
        fixedSearchResults[0] = ct.Id;
        Test.setFixedSearchResults(fixedSearchResults);
        PageReference pageTest = Page.BTN_ContactsSearchPage;
        Test.setCurrentPage(pageTest);
        // init
        BTN_ContactsSearchController controller = new BTN_ContactsSearchController();
        controller.searchConditions = 'test';
        controller.searchAnyone = 'test';
        controller.searchNone = 'xyz';
        // get Contacts from View - result should contain one Contact due to criteria
        System.assertEquals(1, controller.getFoundContacts().size());
    }
    testMethod static void testErrorOnPage() {
        Contact ct = [SELECT Id FROM Contact LIMIT 1];
        Id [] fixedSearchResults= new Id[1];
        fixedSearchResults[0] = ct.Id;
        Test.setFixedSearchResults(fixedSearchResults);
        PageReference pageTest = Page.BTN_ContactsSearchPage;
        Test.setCurrentPage(pageTest);
        // init
        BTN_ContactsSearchController controller = new BTN_ContactsSearchController();
        controller.searchConditions = '\'';
        System.assertEquals(0, controller.getFoundContacts().size());
        System.assert(ApexPages.getMessages().size()>0);
    }
}