force-app/main/default/objects/PricebookEntry/fields/FixedPrice__c.field-meta.xml
<CustomField>
    <fullName>FixedPrice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fixed Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>.NET_C#</fullName>
            </value>
            <value>
                <fullName>.NET_VB</fullName>
            </value>
            <value>
                <fullName>ABAP</fullName>
            </value>
            <value>
                <fullName>Android</fullName>
            </value>
            <value>
                <fullName>Automated Testing</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>Business Analysis</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>CQ5</fullName>
            </value>
            <value>
                <fullName>ETL</fullName>
            </value>
            <value>
                <fullName>fullstack</fullName>
            </value>
            <value>
                <fullName>Groovie</fullName>
            </value>
            <value>
                <fullName>HTML_CSS</fullName>
            </value>
            <value>
                <fullName>IOS</fullName>
            </value>
            <value>
                <fullName>JAVA</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>Liferay</fullName>
            </value>
            <value>
                <fullName>Manual Testing</fullName>
            </value>
            <value>
                <fullName>MicrosoftDynamics</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>PL/SQL</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>Qt</fullName>
            </value>
            <value>
                <fullName>Ruby</fullName>
            </value>
            <value>
                <fullName>Salesforce.com</fullName>
            </value>
            <value>
                <fullName>Sharepoint</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>System Analysis</fullName>
            </value>
            <value>
                <fullName>T-SQL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BTN_ProductSelectionWrapper_Test.cls
@isTest
private class BTN_ProductSelectionWrapper_Test {
	
	@isTest static void productSelectionWrapperContructionTester() {
		Id pbId = Test.getStandardPricebookId();
		Product2 prod = new Product2(ProductCode = 'amelinium', Name = 'tmpTestProduct2', Level__c = 'Junior', Family = 'Developer', Technology__c = 'Android');
		insert prod;
		PricebookEntry pbEntry = new PricebookEntry(CurrencyIsoCode = 'PLN', UnitPrice = 50, FixedPrice__c = 0, Product2Id = prod.Id, Pricebook2Id = pbId, IsActive = true);
		insert pbEntry;

		BTN_ProductSelectionWrapper wrappedProduct2 = new BTN_ProductSelectionWrapper(prod
			, 25, 0, pbEntry.Id, 'PLN', 1);
		System.assert(true);
	}
}