force-app/main/default/objects/Achievement_Set__c/Achievement_Set__c.object-meta.xml
<CustomObject>
    <description>Achievement Set</description>
    <label>Achievement Set</label>
    <nameField>
        <label>Achievement Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact field is valid only for Contact Survey and Contact Profile record types</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/SkillAssessment__c.field-meta.xml
<CustomField>
    <fullName>SkillAssessment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skill Assessment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ContactAchievementSetPageExtensionTest.cls
@isTest
private class ContactAchievementSetPageExtensionTest {

    @isTest
    private static void shouldGetAchievementSet() {
        //GIVEN
        Contact c = new Contact(FirstName = 'test', LastName = 'test', Email='test@test.com.pl', SkillAssessment__c=true);
        insert c;
        Map<ID, Achievement_Set__c> contactIdToAchievementSetMap  = new Map<ID, Achievement_Set__c>();
        for (Achievement_Set__c cpp : [SELECT Contact__c, Name FROM Achievement_Set__c WHERE Contact__c =: c.Id]) {
            contactIdToAchievementSetMap.put(cpp.Contact__c, cpp);
        }
        Achievement_Set__c achievementSet = new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(c.Id)).buildAndSave();

        PageReference pageRef = Page.ContactDetailsPage;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', c.Id);

        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(achievementSet);

        //WHEN
        ContactAchievementSetPageExtension ext = new ContactAchievementSetPageExtension(stdCtrl);

        //THEN
        System.assertEquals('test' + ' ' + 'test'+ ' - Employee Profile', ext.achievementSet.Name);
    }

}