force-app/main/default/objects/Achievement_Set__c/Achievement_Set__c.object-meta.xml
<CustomObject>
    <description>Achievement Set</description>
    <label>Achievement Set</label>
    <nameField>
        <label>Achievement Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set__c/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/BTN_Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E{00000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Event__c/fields/Additional_Carrer_path__c.field-meta.xml
<CustomField>
    <fullName>Additional_Carrer_path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Additional Carrer path</label>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Assessment_comments__c.field-meta.xml
<CustomField>
    <fullName>Assessment_comments__c</fullName>
    <description>for periodic assessment</description>
    <label>Assessment comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Assessment_trend__c.field-meta.xml
<CustomField>
    <fullName>Assessment_trend__c</fullName>
    <label>Assessment trend</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Declining</fullName>
            </value>
            <value>
                <fullName>Stagnation</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/BriteSkills_updated__c.field-meta.xml
<CustomField>
    <fullName>BriteSkills_updated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for periodic assessment module</description>
    <label>BriteSkills updated?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/BS_skills_updated__c.field-meta.xml
<CustomField>
    <fullName>BS_skills_updated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for periodic assessment module</description>
    <label>BS skills updated?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Career_path__c.field-meta.xml
<CustomField>
    <fullName>Career_path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>for periodic assessment</description>
    <label>Career path</label>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipName>Events2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/career_path_comments__c.field-meta.xml
<CustomField>
    <fullName>career_path_comments__c</fullName>
    <description>for periodic assessment module</description>
    <label>Career path comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Coworkers_feedback__c.field-meta.xml
<CustomField>
    <fullName>Coworkers_feedback__c</fullName>
    <description>for periodic assessment module</description>
    <label>Coworkers feedback</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Current_Position__c.field-meta.xml
<CustomField>
    <fullName>Current_Position__c</fullName>
    <description>Asessment module (requires snapshot on creation time and not the live lookup)</description>
    <label>Current Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Customer_feedback_summary__c.field-meta.xml
<CustomField>
    <fullName>Customer_feedback_summary__c</fullName>
    <description>for periodic assessment module</description>
    <label>Customer feedback summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Customer_survey_updated__c.field-meta.xml
<CustomField>
    <fullName>Customer_survey_updated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for periodic assessment module</description>
    <label>Customer survey updated?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/CV_updated__c.field-meta.xml
<CustomField>
    <fullName>CV_updated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for periodic assessment module</description>
    <label>CV updated?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Feedback_company__c.field-meta.xml
<CustomField>
    <fullName>Feedback_company__c</fullName>
    <description>for periodic assessment module</description>
    <label>Feedback company</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Feedback_department__c.field-meta.xml
<CustomField>
    <fullName>Feedback_department__c</fullName>
    <description>for periodic assessment module</description>
    <label>Feedback department</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Feedback_other_departments__c.field-meta.xml
<CustomField>
    <fullName>Feedback_other_departments__c</fullName>
    <description>for periodic assessment module</description>
    <label>Feedback other departments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/General_assessment__c.field-meta.xml
<CustomField>
    <fullName>General_assessment__c</fullName>
    <description>for periodic assessment</description>
    <label>General assessment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Below average</fullName>
            </value>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>Above average</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Interviewed__c.field-meta.xml
<CustomField>
    <fullName>Interviewed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewed</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Events (Interviewed)</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/NextAssessmentDate__c.field-meta.xml
<CustomField>
    <fullName>NextAssessmentDate__c</fullName>
    <label>Next Assessment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Requests_complaints__c.field-meta.xml
<CustomField>
    <fullName>Requests_complaints__c</fullName>
    <description>for periodic assessment module</description>
    <label>Requests, complaints</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Strong_spots__c.field-meta.xml
<CustomField>
    <fullName>Strong_spots__c</fullName>
    <description>for periodc assessment module</description>
    <label>Strong spots</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal Interview</fullName>
            </value>
            <value>
                <fullName>External Interview</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Periodic Assessment</fullName>
            </value>
            <value>
                <fullName>Notes</fullName>
                <isActive>false</isActive>
                <label>Notes</label>
            </value>
            <value>
                <fullName>Others</fullName>
                <isActive>false</isActive>
                <label>Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Weak_spots__c.field-meta.xml
<CustomField>
    <fullName>Weak_spots__c</fullName>
    <description>for periodic assessment module</description>
    <label>Weak spots</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_PersonalTarget__c/BTN_PersonalTarget__c.object-meta.xml
<CustomObject>
    <label>Target</label>
    <nameField>
        <displayFormat>PT-{0000000}</displayFormat>
        <label>Target</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_PersonalTarget__c/fields/Achieved_percent__c.field-meta.xml
<CustomField>
    <fullName>Achieved_percent__c</fullName>
    <label>Achieved %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/BTN_PersonalTarget__c/fields/Certificate__c.field-meta.xml
<CustomField>
    <fullName>Certificate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Certificate</label>
    <referenceTo>BTN_Certificate__c</referenceTo>
    <relationshipLabel>Targets</relationshipLabel>
    <relationshipName>Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_PersonalTarget__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_PersonalTarget__c/fields/Due_date__c.field-meta.xml
<CustomField>
    <fullName>Due_date__c</fullName>
    <label>Due date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BTN_PersonalTarget__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>BTN_Event__c</referenceTo>
    <relationshipLabel>Targets</relationshipLabel>
    <relationshipName>BTN_PersonalTarget</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BTN_PersonalTarget__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Target</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_PersonalTarget__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>CV Improvement</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Certificate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Career_Path__c/Career_Path__c.object-meta.xml
<CustomObject>
    <label>Career Path</label>
    <nameField>
        <label>Career Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Career Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_Position__c.field-meta.xml
<CustomField>
    <fullName>Current_Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Position</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select Achievement Set that describe position profile and Position form selected Career Path</errorMessage>
        <filterItems>
            <field>Achievement_Set__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Position Profile</value>
        </filterItems>
        <filterItems>
            <field>Achievement_Set__c.Career_Path__c</field>
            <operation>equals</operation>
            <valueField>$Source.Career_Path__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>ZOHO</description>
    <label>Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Analytic</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BTN_EventPeriodicController.cls
public with sharing class BTN_EventPeriodicController {
	public BTN_Event__c assessment {get;set;}
	public BTN_Event__c previousAssessment {get;set;}
	private Contact aContact {get;set;}
	public static String URL_PARAM_CONTACT_ID = 'cId';
	public static String EVENT_TYPE_PERIODIC_ASSESSMENT = 'Periodic Assessment';
	public static String CERTIFICATE_TYPE_NAME = 'Certificate';
	public List<BTN_PersonalTarget__c> currentTargets {get;set;}
	public List<BTN_PersonalTarget__c> previousTargets {get;set;}
	private List<BTN_PersonalTarget__c> targetsToDel;
	private BTN_DAO_Event eventDAO = new BTN_DAO_Event();
	private BTN_DAO_Contact contactDAO = new BTN_DAO_Contact();
	private ApexPages.StandardController stdController;
	public String targetToDel {get;set;}

	public BTN_EventPeriodicController(ApexPages.StandardController stdController) {
		this.stdController = stdController;
		eventDAO.addInterviewedContactFields();
		eventDAO.addPeriodicAssessmentFields();
		contactDao.addCurrentPositionFields();
		if (!Test.isRunningTest()) {
			stdController.addFields(new List<String> {
					String.valueOF(BTN_Event__c.Interviewed__c),
					String.valueOF(BTN_Event__c.Current_Position__c),
					String.valueOF(BTN_Event__c.CreatedDate),
					String.valueOF(BTN_Event__c.NextAssessmentDate__c),
					String.valueOF(BTN_Event__c.CV_updated__c),
					String.valueOF(BTN_Event__c.BS_skills_updated__c),
					String.valueOF(BTN_Event__c.BriteSkills_updated__c),
					String.valueOF(BTN_Event__c.Customer_survey_updated__c),
					String.valueOF(BTN_Event__c.Career_path__c),
					String.valueOF(BTN_Event__c.career_path_comments__c),
					String.valueOF(BTN_Event__c.Additional_Carrer_path__c),
					String.valueOF(BTN_Event__c.Customer_feedback_summary__c),
					String.valueOF(BTN_Event__c.Coworkers_feedback__c),
					String.valueOF(BTN_Event__c.Weak_spots__c),
					String.valueOF(BTN_Event__c.Strong_spots__c),
					String.valueOF(BTN_Event__c.General_assessment__c),
					String.valueOF(BTN_Event__c.Assessment_trend__c),
					String.valueOF(BTN_Event__c.Assessment_comments__c),
					String.valueOF(BTN_Event__c.Feedback_department__c),
					String.valueOF(BTN_Event__c.Feedback_company__c),
					String.valueOF(BTN_Event__c.Feedback_other_departments__c),
					String.valueOF(BTN_Event__c.Requests_complaints__c)
			});
		}
		assessment = (BTN_Event__c)stdController.getrecord();
		assessment.Type__c = EVENT_TYPE_PERIODIC_ASSESSMENT;
		if(assessment.RecordTypeId == null){
			assessment.RecordType = BTN_RecordTypeUtils.getRecordTypeCustomEventPeriodicAssessment();
			assessment.recordTypeId = assessment.RecordType.Id;
		}
		Id contactId = assessment.Interviewed__c;
		if(contactId == null){
			String urlContactId = ApexPages.currentPage().getParameters().get(URL_PARAM_CONTACT_ID);
			if(urlContactId == null){
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'{Can\' get contact information, aborting.}'));
				return;
			}
			contactId = urlContactId;
		}
		if(contactId!=null){
			aContact = contactDAO.findContactById(contactId);
			assessment.interviewed__c = contactId;
			assessment.interviewed__r = aContact;
		}
		if(assessment.Id == null){
			//new record fill defaults
			currentTargets = new List<BTN_PersonalTarget__c>();
			//assessment.Current_Position__c = aContact.Current_Position__r.Name; to jest z brite skilli
			assessment.Current_Position__c = aContact.Position__c;
			currentTargets = new List<BTN_PersonalTarget__c>();
		}else{
			currentTargets = [select id, name, Type__c, Target__c, Comments__c, Achieved_percent__c, Event__c, Due_date__c, Certificate__c from BTN_PersonalTarget__c where Event__c =:assessment.Id];
		}

		//get the previos assessment and targets
		try{
			previousAssessment = eventDAO.findPreviousAssessment(contactId, assessment.Id, assessment.createdDate);
			previousTargets = previousAssessment.BTN_PersonalTarget__r;
		}catch (Exception e){
		}


	}

	public PageReference save(){
		//PageReference retRef = stdController.save();
		if (!validateTargets()){
			return null;
		}
		Boolean isNew = assessment.id==null;
		upsert assessment;
		User interviewdUser = new User(); // just to make sure it is not null
		try{
			interviewdUser = [select id, Contact.ReportsToId from User where contactId =:assessment.interviewed__c limit 1];
		}catch(Exception e){

		}
		if(targetsToDel!=null){
			List<BTN_PersonalTarget__c> toHardDel = new List<BTN_PersonalTarget__c>();
			for(BTN_PersonalTarget__c t:targetsToDel){
				if(t.Id!=null){
					toHardDel.add(t);
				}
			}
			if(toHardDel.size()>0){
				delete toHardDel;
			}
		}
		if(currentTargets != null && currentTargets.size()>0){
			List<Task> targetTasks = new List<Task>();
			for(BTN_PersonalTarget__c t: currentTargets){
				if(t.Event__c == null){
					t.Event__c = assessment.Id;
				}
				if(t.Id==null && interviewdUser!=null && interviewdUser.Id!=null){
					Task aTask = new Task();
					aTask.WhoId = assessment.interviewed__c;
					aTask.OwnerId = interviewdUser.Id;
					aTask.Status = 'Open';
					aTask.Subject = t.Target__c;
					aTask.Whatid = assessment.Id;
					aTask.IsReminderSet = true;
					aTask.ReminderDateTime = t.Due_date__c - 7;
					aTask.ActivityDate = t.Due_date__c ;
					targetTasks.add(aTask);
				}
			}
			if(targetTasks.size()>0){
				insert targetTasks;
			}
			upsert currentTargets;
		}
		if(previousTargets != null && previousTargets.size()>0){
			upsert previousTargets;
		}

		if(isNew && interviewdUser!=null && interviewdUser.Contact.ReportsToId!=null){
			User interviewrSupervisor = new User();// just to make sure it is not null
			try{
				interviewrSupervisor = [select id, Contact.ReportsToId from User where contactId =:interviewdUser.Contact.ReportsToId limit 1];
			}catch(Exception e){

			}
			Task aTask = new Task();
			aTask.WhoId = interviewdUser.Contact.ReportsToId;
			aTask.OwnerId = interviewrSupervisor.Id;
			aTask.Status = 'Open';
			//aTask.Subject = 'Periodic assessment for '+aContact.FirstName + ' ' + aContact.LastName +' due date is'+ assessment.NextAssessmentDate__c;
			aTask.Subject = System.Label.PeriodicAssessmentTaskNotification.replace('{0}',aContact.FirstName + ' ' + aContact.LastName).replace('{1}',assessment.NextAssessmentDate__c.format());
			aTask.Whatid = assessment.Id;
			aTask.IsReminderSet = true;
			aTask.ReminderDateTime = assessment.NextAssessmentDate__c - 7;
			aTask.ActivityDate = assessment.NextAssessmentDate__c;
			insert aTask;
		}

		//tasks for targets
		return new PageReference('/'+assessment.Id);
	}

	public PageReference delCurrentTarget(){
		if(targetsToDel==null){
			targetsToDel = new List<BTN_PersonalTarget__c>();
		}
		if(targetToDel!=null){
			Integer idx = Integer.valueOf(targetToDel)-1;
			currentTargets.get(idx).Comments__c = currentTargets.get(idx).Comments__c + ', del# '+targetToDel;
			targetsToDel.add(currentTargets.get(idx));
			currentTargets.remove(idx);
		}
		return null;
	}

	public PageReference addCurrentTarget(){
		if (validateTargets()) {
			currentTargets.add(new BTN_PersonalTarget__c(
					Due_date__c = assessment.NextAssessmentDate__c,
					Achieved_percent__c = 0
			));
		}
		return null;
	}

	private Boolean validateTargets(){
		Boolean isValid = true;
		if (currentTargets != null) {
			for (BTN_PersonalTarget__c target : currentTargets) {
				if (BTN_ValidationHandler.isEmpty(target.Type__c)) {
					target.Type__c.addError(System.Label.MustEnterValue);
					isValid = false;
				}
				if (target.Due_date__c == null) {
					target.Due_date__c.addError(System.Label.MustEnterValue);
					isValid = false;
				}
				if (target.Achieved_percent__c == null) {
					target.Achieved_percent__c.addError(System.Label.MustEnterValue);
					isValid = false;
				}
				if (target.Type__c == CERTIFICATE_TYPE_NAME && BTN_ValidationHandler.isEmpty(target.Certificate__c)) {
					target.Certificate__c.addError(System.Label.MustEnterValue);
					isValid = false;
				}
				if (target.Type__c != CERTIFICATE_TYPE_NAME && BTN_ValidationHandler.isEmpty(target.Target__c)) {
					target.Target__c.addError(System.Label.MustEnterValue);
					isValid = false;
				}
			}
		}
		return isValid;
	}



}