force-app/main/default/objects/Achievement_Set__c/Achievement_Set__c.object-meta.xml
<CustomObject>
    <description>Achievement Set</description>
    <label>Achievement Set</label>
    <nameField>
        <label>Achievement Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_CV__c/BTN_CV__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CID{00000000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Event__c/BTN_Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E{00000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Event__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>BTN_CV__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Current_Position__c.field-meta.xml
<CustomField>
    <fullName>Current_Position__c</fullName>
    <description>Asessment module (requires snapshot on creation time and not the live lookup)</description>
    <label>Current Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description (HR)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Interviewed__c.field-meta.xml
<CustomField>
    <fullName>Interviewed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewed</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Events (Interviewed)</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Interviewer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Interviewer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer (HR)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lublin Hamleta</fullName>
            </value>
            <value>
                <fullName>Lublin Morwowa</fullName>
            </value>
            <value>
                <fullName>Warszawa Bukowińska</fullName>
            </value>
            <value>
                <fullName>Warszawa Wołoska</fullName>
            </value>
            <value>
                <fullName>Kielce IX Wieków</fullName>
            </value>
            <value>
                <fullName>Poznań Strzelecka</fullName>
            </value>
            <value>
                <fullName>Zdalnie</fullName>
            </value>
            <value>
                <fullName>U klienta [Other location is mandatory]</fullName>
            </value>
            <value>
                <fullName>Inne [Other location is mandatory]</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
                <isActive>false</isActive>
                <label>Call</label>
            </value>
            <value>
                <fullName>Meeting</fullName>
                <isActive>false</isActive>
                <label>Meeting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal Interview</fullName>
            </value>
            <value>
                <fullName>External Interview</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Periodic Assessment</fullName>
            </value>
            <value>
                <fullName>Notes</fullName>
                <isActive>false</isActive>
                <label>Notes</label>
            </value>
            <value>
                <fullName>Others</fullName>
                <isActive>false</isActive>
                <label>Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BSexternalId__c.field-meta.xml
<CustomField>
    <fullName>BSexternalId__c</fullName>
    <externalId>true</externalId>
    <label>Britesheet ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/CityLocation__c.field-meta.xml
<CustomField>
    <fullName>CityLocation__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lublin</fullName>
            </value>
            <value>
                <fullName>Warszawa</fullName>
            </value>
            <value>
                <fullName>Kielce</fullName>
            </value>
            <value>
                <fullName>Poznań</fullName>
            </value>
            <value>
                <fullName>Łódź</fullName>
            </value>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_Position__c.field-meta.xml
<CustomField>
    <fullName>Current_Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Position</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select Achievement Set that describe position profile and Position form selected Career Path</errorMessage>
        <filterItems>
            <field>Achievement_Set__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Position Profile</value>
        </filterItems>
        <filterItems>
            <field>Achievement_Set__c.Career_Path__c</field>
            <operation>equals</operation>
            <valueField>$Source.Career_Path__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Freelancer__c.field-meta.xml
<CustomField>
    <fullName>Freelancer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the contact a freelancer?</description>
    <label>Freelancer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Guardian__c.field-meta.xml
<CustomField>
    <fullName>Guardian__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guardian</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Guarded Employees</relationshipLabel>
    <relationshipName>GuardedEmployees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsLeader__c.field-meta.xml
<CustomField>
    <fullName>IsLeader__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Leader</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/joinDateBS__c.field-meta.xml
<CustomField>
    <fullName>joinDateBS__c</fullName>
    <label>BriteSheet join date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Leader__c.field-meta.xml
<CustomField>
    <fullName>Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Managed Employees</relationshipLabel>
    <relationshipName>ManagedEmployees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Other Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Name_frm__c.field-meta.xml
<CustomField>
    <fullName>Name_frm__c</fullName>
    <formula>FirstName + &apos; &apos; + LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PersonalEmail__c.field-meta.xml
<CustomField>
    <fullName>PersonalEmail__c</fullName>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PersonalPhone__c.field-meta.xml
<CustomField>
    <fullName>PersonalPhone__c</fullName>
    <label>Personal Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>ZOHO</description>
    <label>Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ResourceRequestor__c.field-meta.xml
<CustomField>
    <fullName>ResourceRequestor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Resource Requestor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SkillAssessment__c.field-meta.xml
<CustomField>
    <fullName>SkillAssessment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skill Assessment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>ZOHO</description>
    <label>Skills</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TargetPosition__c.field-meta.xml
<CustomField>
    <fullName>TargetPosition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target Position</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Achievement_Set__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Position Profile</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Contacts (Target Position)</relationshipLabel>
    <relationshipName>TargetPositions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <label>Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Analytic</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Internal employees</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Recruit.recordType-meta.xml
<RecordType>
    <fullName>Recruit</fullName>
    <active>true</active>
    <description>Recruits</description>
    <label>Recruit</label>
</RecordType>

force-app/main/default/classes/BTN_DAO_Contact.cls
/**
 * @author Mateusz Przywara
 * @date   2016-07-05
 * @description DAO class - Data Access Object for Contact
 */
public class BTN_DAO_Contact extends BTN_DAO {
    /**
     * @author Mateusz Przywara
     * @date   2016-07-05
     * @description Constructor
    */
    public BTN_DAO_Contact() {
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-07-05
     * @description Constructor setting custom List of fields
    */
    public BTN_DAO_Contact(List<Schema.SObjectField> customFields) {
        setCustomFields(customFields);
    }

    public override Schema.SObjectType getSObjectType() {
        return Contact.sObjectType;
    }

    public override List<Schema.SObjectField> getSObjectFields() {
        return new List<Schema.SObjectField>{
                Contact.Id,
                Contact.Email,
                Contact.AccountId,
                Contact.FirstName,
                Contact.PersonalPhone__c,
                Contact.PersonalEmail__c,
                Contact.LastName,
                Contact.Phone,
                Contact.CreatedDate,
                Contact.Comment__c,
                Contact.Position__c,
                Contact.Location__c,
                Contact.CityLocation__c,
                Contact.Title,
                Contact.Token__c,
                Contact.BSexternalId__c,
                Contact.Skills__c,
                Contact.Name_frm__c,
                Contact.Level__c,
                Contact.Name,
                Contact.RecordTypeId,
                Contact.Current_Position__c,
                Contact.TargetPosition__c,
                Contact.Freelancer__c,
                Contact.Sex__c,
                Contact.joinDateBS__c,
                Contact.ReportsToId,
                Contact.Leader__c,
                Contact.Guardian__c,
                Contact.SkillAssessment__c
        };
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-07-05
     * @description find Contact
     * @param  contactId - collection of Id to search for
     * @return     Contact       - collection of found Contacts
    */
    public Contact findContactById(Id contactId) {
        return (Contact) findSObjectById(contactId);
    }

    public List<Contact> findContactsByIds(Set<Id> contactIds) {
        return findSObjectsBy(new List<SearchCondition> {
                new SearchCondition('Id', 'IN', contactIds)
        });
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-07-05
     * @description add Record Type fields to Query
     * @return void
    */
    public void addRecordTypeFields() {
        currentFields.add('RecordType.DeveloperName');
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-07-06
     * @description find Requestor matching unique token
     * @return List<Contact>
    */
    public List<Contact> findRequestorsMatchingToken(String token) {
        return findSObjectsBy(
                new List<SearchCondition>{
                    new SearchCondition('ResourceRequestor__c', '=', true),
                    new SearchCondition('AND Token__c', '=', token)
                }
        );
    }

    /**
      * @author Mateusz Przywara
      * @date   2016-08-24
      * @description findContacByBSExternalId find Contact with specified Britesheet Id
      * @return Contact
    */
    public Contact findContacByBSExternalId(Integer briteSheetExternalId) {
        List<Object> objects = findSObjectsBy(
                new List<SearchCondition>{
                        new SearchCondition('BSexternalId__c', '=', briteSheetExternalId)
                }
        );
        return objects.isEmpty() ? null : (Contact) objects.get(0);
    }

    public List<Contact> findContactsByBSExternalIds(Set<Integer> briteSheetExternalIds) {
        return findSObjectsBy(
                new List<SearchCondition> {
                        new SearchCondition(
                                'BSexternalId__c',
                                'IN',
                                briteSheetExternalIds
                        )
                }
        );
    }

    /**
     * @author Dariusz Chmiela
     * @date 2016-09-15
     * @description findContacByEmail find Contacts with given email
     * @return List<Contact>
     */
    public List<Contact> findContacByEmail(String email) {
        return findSObjectsBy(
                new List<SearchCondition>{
                        new SearchCondition(
                                'Active__c',
                                '=',
                                true
                        ),
                        new SearchCondition(
                                'AND Email',
                                '=',
                                email
                        )
                }
        );
    }

    /**
     * @author Mateusz Przywara
     * @date 2016-11-24
     * @description findContactByBritenetEmail find Contacts with given Britenet Email
     * @return Contact - Email is unique
    */
    public Contact findContactByBritenetEmail(String email) {
        List<sObject> objects = findSObjectsBy(
                new List<SearchCondition>{
                        new SearchCondition(
                                'Email',
                                '=',
                                email
                        )
                }
        );
        return objects.isEmpty() ? null : (Contact) objects.get(0);
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-07-06
     * @description find all Internal Requestors // to DCh double SOQL!!! Method name obvious
     * @return List<Contact>
    */
    public List<Contact> findRequestors() {
        List<PermissionSetAssignment> permissionSetsList = [
                SELECT Assignee.ContactId
                FROM PermissionSetAssignment
                WHERE PermissionSet.Name = :BTN_ConstantRepo.PERM_SET_NAME_HR
                ];
        List<Id> assigneeIdsSet = new List<Id>();
        for(PermissionSetAssignment ps: permissionSetsList){
            assigneeIdsSet.add(ps.Assignee.ContactId);
        }
        List<Contact> contacts = [SELECT Id, Name FROM Contact WHERE Id IN :assigneeIdsSet];
        return contacts;
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-08-18
     * @description find all Internal Requestors
     * @return List<Contact>
    */
    public List<Contact> findInternals() {
        return findSObjectsBy(
                new List<SearchCondition>{
                        new SearchCondition(
                                'RecordType.DeveloperName',
                                '=',
                                BTN_ConstantRepo.INTERNAL_CONTACT_RECORDTYPE_NAME
                        )
                }
        );
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-08-04
     * @description findBSSContacts search for active BSS Contacts
     * @return List<Contact>
    */
    public List<Contact> findBSSContacts() {
        return findSObjectsBy(
                new List<SearchCondition>{
                        new SearchCondition(
                                'Active__c',
                                '=',
                                true
                        )
                }
        );
    }

    /**
     * @author Dariusz Chmiela
     * @date 2016-09-15
     * @description findBSSContacts search for active BSS Contacts
     * @return List<Contact>
     */
    public List<Contact> getAllContacts() {
        return findSObjectsBy(
                new List<SearchCondition>{
                        new SearchCondition(
                                'Active__c',
                                '=',
                                true
                        )
                }
        );
    }

    /**
     * @author Mateusz Przywara
     * @date 2016-11-08
     * @description findRecruits get all Contacts with Recruit Record Type
     * @return List<Contact>
     */
    public List<Contact> findRecruits() {
        return findSObjectsBy(
                new List<SearchCondition>{
                        new SearchCondition(
                                'RecordType.Id',
                                '=',
                                BTN_RecordTypeUtils.getRecordTypeContactRecruit().Id
                        )
                }
        );
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-10-24
     * @description findContactsInIdSet
     * @return List<Contact>
    */
    public List<Contact> findContactsInIdSet(Set<Id> ids) {
        return findSObjectsBy(
                new List<SearchCondition>{
                        new SearchCondition(
                                'Id',
                                'IN',
                                ids
                        )
                }
        );
    }
    
    /**
     * @author Wojciech Mazur
     * @date   2016-10-28
     * @description add ailing Fields to Query
     * @return BTN_DAO_Contact
    */
    public BTN_DAO_Contact addMailingFields() {
        currentFields.add('MailingCity');
        currentFields.add('MailingPostalCode');
        currentFields.add('MailingStreet');
        return this;
    }
    
    /**
     * @author Wojciech Mazur
     * @date   2016-12-14
     * @description add Position Fields to Query
     * @return BTN_DAO_Contact
    */
    public BTN_DAO_Contact addCurrentPositionFields() {
        currentFields.add('Current_Position__r.Name');
        return this;
    }

    /**
     * @author Wojciech Mazur
     * @date   2016-12-01
     * @description add ailing Fields to Query
     * @return void
    */
    public BTN_DAO_Contact addInterviews() {
        currentFields.add('(select id, name, Type__c, Start_Time__c, Candidate__c, Candidate__r.name, Title__c, Interviewer_Contact__c, Interviewer_Contact__r.name, Location__c, Description__c, CreatedDate, OwnerId, Owner.Name from Interviews__r ORDER BY ' +
                'Start_Time__c desc nulls last)');
        return this;
    }

    /**
     * @author Adam Jedrys
     * @date   2018-05-23
     * @description get list of leaders
     * @return list of contacts
    */
    public List<Contact> findLeaders() {
        return findSObjectsBy(
                new List<SearchCondition>{
                        new SearchCondition(
                                'IsLeader__c',
                                '=',
                                true
                        )
                }
        );
    }

    /**
     * @author Adam Jedrys
     * @date   2018-05-23
     * @description get leaders by name
     * @return map of contacts by name
    */
    public Map<String, Contact> getLeadersByName() {
        Map<String, Contact> leadersByNameMap = new Map<String, Contact>();
        List<Contact> leaders = findLeaders();

        for(Contact leader : leaders){
            leadersByNameMap.put(leader.Name, leader);
        }

        return leadersByNameMap;
    }
}