force-app/main/default/objects/Achievement_Set__c/Achievement_Set__c.object-meta.xml
<CustomObject>
    <description>Achievement Set</description>
    <label>Achievement Set</label>
    <nameField>
        <label>Achievement Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set__c/fields/AboutWho__c.field-meta.xml
<CustomField>
    <fullName>AboutWho__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>About Who</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Surveys About Me</relationshipLabel>
    <relationshipName>SurveysAboutMe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact field is valid only for Contact Survey and Contact Profile record types</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Number_Of_Achievements__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Achievements__c</fullName>
    <label>Number Of Achievements</label>
    <summaryForeignKey>Achievement_Set_Item__c.Achievement_Set__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Parent_Profile__c.field-meta.xml
<CustomField>
    <fullName>Parent_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Profile</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select the Profile Achievement set</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Position Profile, Specialization</value>
        </filterItems>
        <filterItems>
            <field>Achievement_Set__c.Career_Path__c</field>
            <operation>equals</operation>
            <valueField>$Source.Career_Path__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Score_Minimal_Value__c.field-meta.xml
<CustomField>
    <fullName>Score_Minimal_Value__c</fullName>
    <defaultValue>0.5</defaultValue>
    <description>Minimalne dopasowanie po jakim Profil zostanie przypisany do Pracownika</description>
    <inlineHelpText>Minimalne dopasowanie po jakim Profil zostanie przypisany do Pracownika</inlineHelpText>
    <label>Score Minimal Value</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/SelfSurvey__c.field-meta.xml
<CustomField>
    <fullName>SelfSurvey__c</fullName>
    <formula>NOT(ISBLANK(AboutWho__c)) &amp;&amp; NOT(ISBLANK(Who__c)) &amp;&amp; AboutWho__c = Who__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Self-Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Who__c.field-meta.xml
<CustomField>
    <fullName>Who__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Who</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>My Surveys</relationshipLabel>
    <relationshipName>MySurveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Career_Path__c/Career_Path__c.object-meta.xml
<CustomObject>
    <label>Career Path</label>
    <nameField>
        <label>Career Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Career Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Achievement_Profile__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Achievement Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Achievement_Set__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee Profile</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Achievement_Set__c.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Contacts (Achievement Profile)</relationshipLabel>
    <relationshipName>Contact_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Number_Of_Achievements__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Achievements__c</fullName>
    <formula>Achievement_Profile__r.Number_Of_Achievements__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number Of Achievements</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact_Profile_Score__c/Contact_Profile_Score__c.object-meta.xml
<CustomObject>
    <description>Employee Profile Score</description>
    <label>Employee Profile Probe</label>
    <nameField>
        <displayFormat>EPP{00000000}</displayFormat>
        <label>Profile Probe ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Profile Probes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Profile_Score__c/fields/Achievement_Profile__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Profile__c</fullName>
    <label>Achievement Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Achievement_Set__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Specialization, Position Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Employee Profile Probes (Achievement Profile)</relationshipLabel>
    <relationshipName>Achievement_Profiles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Profile_Score__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Profile Probes</relationshipLabel>
    <relationshipName>Contact_Position_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Profile_Score__c/fields/Contact_Profile__c.field-meta.xml
<CustomField>
    <fullName>Contact_Profile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Achievement_Set__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee Profile</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contact__c</field>
            <operation>equals</operation>
            <valueField>Achievement_Set__c.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Employee Profile Probes (Employee Profile)</relationshipLabel>
    <relationshipName>Contact_Profile_Scores</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactAchievementSetScorePageExtension.cls
/**
 * Contact Profile Score standard controller extension for the Achievements Set record manipulations.
 * @author Adam Siwek
 */
public with sharing virtual class ContactAchievementSetScorePageExtension extends AchievementSetPageExtension {

    public ContactAchievementSetScorePageExtension(ApexPages.StandardController stdCtrl) {
        super(stdCtrl);
    }

    protected override void loadFirstAchievementSet(SObject scopeRecord, Map<String, String> pageParams) {
        achievementSet = [SELECT Id, Name, RecordTypeId, Contact__c, Score_Minimal_Value__c, Career_Path__c, Number_Of_Achievements__c, Parent_Profile__c, Who__c, AboutWho__c, SelfSurvey__c FROM Achievement_Set__c WHERE Id = :((Contact_Profile_Score__c)scopeRecord).Contact_Profile__c AND IsDeleted = false LIMIT 1 ALL ROWS];
    }

    protected override void loadSecondAchievementSet(SObject scopeRecord, Map<String, String> pageParams) {
        achievementSetToCmpId = ((Contact_Profile_Score__c)scopeRecord).Achievement_Profile__c;
    }
}