force-app/main/default/objects/BTN_Equipment__c/BTN_Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <displayFormat>EQ{000000}</displayFormat>
        <label>Equipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Equipment__c/fields/Britenet_ID__c.field-meta.xml
<CustomField>
    <fullName>Britenet_ID__c</fullName>
    <externalId>true</externalId>
    <label>Britenet ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Equipment</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Selected Equipment must be owned by the selected Contact</errorMessage>
        <filterItems>
            <field>BTN_Equipment__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Equipment</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contact__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>BTN_Equipment__c.Contact__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BTN_Equipment__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DataCenter</fullName>
            </value>
            <value>
                <fullName>Lublin Hamleta</fullName>
            </value>
            <value>
                <fullName>Kielce IX Wieków</fullName>
            </value>
            <value>
                <fullName>Klient</fullName>
            </value>
            <value>
                <fullName>Lublin Morwowa</fullName>
            </value>
            <value>
                <fullName>Poznań Strzelecka</fullName>
            </value>
            <value>
                <fullName>Warszawa Bukowińska</fullName>
            </value>
            <value>
                <fullName>Warszawa Wołoska</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <description>Sprzęt - komputery, monitory, telefony, tablety, karty SIM, routery, switche, access pointy i inne</description>
    <label>Equipment</label>
</RecordType>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Other Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BTN_EquipmentExtension_Test.cls
@isTest
private class BTN_EquipmentExtension_Test {

    private static final String CONTACT_PHONE_NUMBER = '123456789';
    private static final String CONTACT_LOCATION = 'Lublin Morwowa';
    private static final String EQUIPMENT_SERIAL_NUMBER = 'ABCD-EFGH-IJKL-MNOP';
    private static final String EQUIPMENT_BRITENET_ID = 'BTN 1234';

    @testSetup static void createDataStructure() {
        BTN_TestDataFactory.getHRCollaborationGroup();
        Account britenetAccount = BTN_TestDataFactory.getBriteNetAccount();
        Contact internalContact = BTN_TestDataFactory.getInternalContact(britenetAccount.Id);
        internalContact.MobilePhone = CONTACT_PHONE_NUMBER;
        internalContact.Location__c = CONTACT_LOCATION;
        update internalContact;
    }

    @isTest static void testSavingEquipmentWithoutContactAssigned() {
        BTN_Equipment__c baseEquipment = BTN_TestDataFactory.getEquipment(BTN_RecordTypeUtils.getRecordTypeEquipmentEquipment().Id);

        Test.startTest();
        BTN_EquipmentExtension extension = new BTN_EquipmentExtension(new ApexPages.StandardController(baseEquipment));
        extension.equipment.Location__c = CONTACT_LOCATION;
        extension.stdController.save();
        Test.stopTest();

        Integer equipmentCount = new BTN_DAO_Equipment().countSObjectsBy(new List<BTN_DAO.SearchCondition>{
                new BTN_DAO.SearchCondition(String.valueOf(BTN_Equipment__c.Location__c), '=', CONTACT_LOCATION)
        });
        System.assertEquals(1, equipmentCount, 'Equipment should have Location from Contact');
    }

    @isTest static void testSavingEquipmentWithContactAssigned() {
        Contact internalContact = (Contact) new BTN_DAO_Contact(new List<SObjectField>{
                Contact.Id, Contact.Name
        }).findSObjectsBy(new List<BTN_DAO.SearchCondition>{
                new BTN_DAO.SearchCondition(String.valueOf(Contact.Location__c), '=', CONTACT_LOCATION)
        }).get(0);
        BTN_Equipment__c baseEquipment = BTN_TestDataFactory.getEquipment(BTN_RecordTypeUtils.getRecordTypeEquipmentEquipment().Id);

        Test.startTest();
        BTN_EquipmentExtension extension = new BTN_EquipmentExtension(new ApexPages.StandardController(baseEquipment));
        extension.equipment.Contact__c = internalContact.Id;
        extension.queryContactLocationAndPhone();
        extension.stdController.save();
        Test.stopTest();

        Integer equipmentCount = new BTN_DAO_Equipment().countSObjectsBy(new List<BTN_DAO.SearchCondition>{
                new BTN_DAO.SearchCondition(String.valueOf(BTN_Equipment__c.Location__c), '=', CONTACT_LOCATION)
        });
        System.assertEquals(1, equipmentCount);
    }

    @isTest static void testSavingEquipmentWithDuplicatedBritenetId() {
        BTN_Equipment__c baseEquipment = BTN_TestDataFactory.getEquipment(BTN_RecordTypeUtils.getRecordTypeEquipmentEquipment().Id);

        Test.startTest();
        BTN_EquipmentExtension extension = new BTN_EquipmentExtension(new ApexPages.StandardController(baseEquipment));
        extension.equipment.Britenet_ID__c = EQUIPMENT_BRITENET_ID;
        extension.stdController.save();
        Test.stopTest();

        Integer equipmentCount = new BTN_DAO_Equipment().countSObjectsBy(new List<BTN_DAO.SearchCondition>{
                new BTN_DAO.SearchCondition(String.valueOf(BTN_Equipment__c.Britenet_ID__c), '=', EQUIPMENT_BRITENET_ID)
        });
        System.assertEquals(1, equipmentCount);
    }

    @isTest static void testSavingEquipmentWithDuplicatedSerialNumber() {
        BTN_Equipment__c baseEquipment = BTN_TestDataFactory.getEquipment(BTN_RecordTypeUtils.getRecordTypeEquipmentEquipment().Id);

        Test.startTest();
        BTN_EquipmentExtension extension = new BTN_EquipmentExtension(new ApexPages.StandardController(baseEquipment));
        extension.equipment.Serial_Number__c = EQUIPMENT_SERIAL_NUMBER;
        extension.stdController.save();
        Test.stopTest();

        Integer equipmentCount = new BTN_DAO_Equipment().countSObjectsBy(new List<BTN_DAO.SearchCondition>{
                new BTN_DAO.SearchCondition(String.valueOf(BTN_Equipment__c.Serial_Number__c), '=', EQUIPMENT_SERIAL_NUMBER)
        });
        System.assertEquals(1, equipmentCount);
    }

    @isTest static void testSavingLicenseWithEquipmentAssigned() {
        BTN_Equipment__c baseEquipment = BTN_TestDataFactory.getEquipment(BTN_RecordTypeUtils.getRecordTypeEquipmentLicense().Id);
        BTN_Equipment__c parentEquipment = BTN_TestDataFactory.getEquipment(BTN_RecordTypeUtils.getRecordTypeEquipmentEquipment().Id);

        Test.startTest();
        BTN_EquipmentExtension extension = new BTN_EquipmentExtension(new ApexPages.StandardController(baseEquipment));
        extension.equipment.Equipment__c = parentEquipment.Id;
        extension.stdController.save();
        Test.stopTest();

        Integer equipmentCount = new BTN_DAO_Equipment().countSObjectsBy(new List<BTN_DAO.SearchCondition>{
                new BTN_DAO.SearchCondition(String.valueOf(BTN_Equipment__c.Equipment__c), '=', parentEquipment.Id),
                new BTN_DAO.SearchCondition(String.valueOf(BTN_Equipment__c.Contact__c), '=', parentEquipment.Contact__c)
        }, '{0} AND {1}');
        System.assertEquals(1, equipmentCount);
    }

    @isTest static void testSavingPhoneContractWithContactAssigned() {
        Contact internalContact = (Contact) new BTN_DAO_Contact(new List<SObjectField>{
                Contact.Id, Contact.Name, Contact.MobilePhone, Contact.Location__c
        }).findSObjectsBy(new List<BTN_DAO.SearchCondition>{
                new BTN_DAO.SearchCondition(String.valueOf(Contact.MobilePhone), '=', CONTACT_PHONE_NUMBER),
                new BTN_DAO.SearchCondition(String.valueOf(Contact.Location__c), '=', CONTACT_LOCATION)
        }, '{0} AND {1}').get(0);
        Id equipmentRecordTypeId = BTN_RecordTypeUtils.getRecordTypeEquipmentPhoneContract().Id;
        BTN_Equipment__c baseEquipment = BTN_TestDataFactory.getEquipment(equipmentRecordTypeId);

        Test.startTest();
        BTN_EquipmentExtension extension = new BTN_EquipmentExtension(new ApexPages.StandardController(baseEquipment));
        extension.equipment.Contact__c = internalContact.Id;
        extension.equipment.Phone_Number__c = '';
        extension.queryContactLocationAndPhone();
        extension.stdController.save();
        Test.stopTest();

        Integer equipmentCount = new BTN_DAO_Equipment().countSObjectsBy(new List<BTN_DAO.SearchCondition>{
                new BTN_DAO.SearchCondition(String.valueOf(BTN_Equipment__c.Phone_Number__c), '=', CONTACT_PHONE_NUMBER),
                new BTN_DAO.SearchCondition(String.valueOf(BTN_Equipment__c.Location__c), '=', CONTACT_LOCATION)
        }, '{0} AND {1}');
        System.assertEquals(1, equipmentCount);
    }

    @isTest static void testSavingPhoneContractWithoutContactAssigned() {
        BTN_Equipment__c baseEquipment = BTN_TestDataFactory.getEquipment(BTN_RecordTypeUtils.getRecordTypeEquipmentPhoneContract().Id);

        Test.startTest();
        BTN_EquipmentExtension extension = new BTN_EquipmentExtension(new ApexPages.StandardController(baseEquipment));
        extension.stdController.save();
        Test.stopTest();

        Integer equipmentCount = new BTN_DAO_Equipment().countSObjects();
        System.assertEquals(1, equipmentCount);
    }

    @isTest static void testSaveAndNew() {
        BTN_Equipment__c baseEquipment = BTN_TestDataFactory.getEquipment(BTN_RecordTypeUtils.getRecordTypeEquipmentPhoneContract().Id);

        Test.startTest();
        BTN_EquipmentExtension extension = new BTN_EquipmentExtension(new ApexPages.StandardController(baseEquipment));
        PageReference result = extension.saveAndNew();
        Test.stopTest();

        Integer equipmentCount = new BTN_DAO_Equipment().countSObjects();
        System.assertEquals(1, equipmentCount);
        System.assertEquals(result.getUrl(), Page.BTN_EquipmentEdit.getUrl());
    }

}