force-app/main/default/objects/BTN_Equipment__c/BTN_Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <displayFormat>EQ{000000}</displayFormat>
        <label>Equipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Equipment__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Czy sprzęt nie jest zezłomowany lub licencja jest aktywna?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Britenet_ID__c.field-meta.xml
<CustomField>
    <fullName>Britenet_ID__c</fullName>
    <externalId>true</externalId>
    <label>Britenet ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Equipment</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Selected Equipment must be owned by the selected Contact</errorMessage>
        <filterItems>
            <field>BTN_Equipment__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Equipment</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contact__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>BTN_Equipment__c.Contact__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BTN_Equipment__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Equipment_Request__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment Request</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You can select only an Equipment Request for the selected contact</errorMessage>
        <filterItems>
            <field>$Source.Contact__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Contact__c</field>
            <operation>equals</operation>
            <valueField>BTN_Equipment_Request__c.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BTN_Equipment_Request__c</referenceTo>
    <relationshipLabel>Equipment</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <label>License Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Oem</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>Serial</fullName>
            </value>
            <value>
                <fullName>Floating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DataCenter</fullName>
            </value>
            <value>
                <fullName>Lublin Hamleta</fullName>
            </value>
            <value>
                <fullName>Kielce IX Wieków</fullName>
            </value>
            <value>
                <fullName>Klient</fullName>
            </value>
            <value>
                <fullName>Lublin Morwowa</fullName>
            </value>
            <value>
                <fullName>Poznań Strzelecka</fullName>
            </value>
            <value>
                <fullName>Warszawa Bukowińska</fullName>
            </value>
            <value>
                <fullName>Warszawa Wołoska</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Phone_Contract__c.field-meta.xml
<CustomField>
    <fullName>Phone_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phone Contract</label>
    <referenceTo>BTN_Phone_Contract__c</referenceTo>
    <relationshipLabel>Equipment</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Reserved__c.field-meta.xml
<CustomField>
    <fullName>Reserved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reserved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Subscription Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Miesięczna</fullName>
            </value>
            <value>
                <fullName>Roczna</fullName>
            </value>
            <value>
                <fullName>Dożywotnia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Komputer</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>Telefon</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Karta SIM</fullName>
            </value>
            <value>
                <fullName>Router</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
            <value>
                <fullName>Access Point</fullName>
            </value>
            <value>
                <fullName>Licencja</fullName>
            </value>
            <value>
                <fullName>Inne</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sparx</fullName>
            </value>
            <value>
                <fullName>OVH</fullName>
            </value>
            <value>
                <fullName>Partner Microsoft</fullName>
            </value>
            <value>
                <fullName>Inny</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <description>Sprzęt - komputery, monitory, telefony, tablety, karty SIM, routery, switche, access pointy i inne</description>
    <label>Equipment</label>
</RecordType>

force-app/main/default/objects/BTN_Equipment_Request__c/BTN_Equipment_Request__c.object-meta.xml
<CustomObject>
    <label>Equipment Request</label>
    <nameField>
        <displayFormat>ER{000000}</displayFormat>
        <label>Equipment Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Equipment_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Equipment Requests</relationshipLabel>
    <relationshipName>Equipment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Other Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Analytic</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Company.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Britenet</fullName>
        <default>true</default>
        <label>Britenet</label>
    </customValue>
    <customValue>
        <fullName>Britenet Operations</fullName>
    </customValue>
    <customValue>
        <fullName>Britenet Polska</fullName>
    </customValue>
    <masterLabel>Company</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BTN_EquipmentExtension.cls
public with sharing class BTN_EquipmentExtension {

    public BTN_Equipment__c equipment { get; set; }
    public ApexPages.StandardController stdController;

    public BTN_EquipmentExtension(ApexPages.StandardController stdController) {
        this.stdController = stdController;
        if (!Test.isRunningTest()) {
            stdController.addFields(new List<String> {
                    String.valueOf(BTN_Equipment__c.Name),
                    String.valueOf(BTN_Equipment__c.Type__c),
                    String.valueOf(BTN_Equipment__c.Contact__c),
                    String.valueOf(BTN_Equipment__c.Serial_Number__c),
                    String.valueOf(BTN_Equipment__c.Contact__c),
                    String.valueOf(BTN_Equipment__c.Company__c),
                    String.valueOf(BTN_Equipment__c.Equipment__c),
                    String.valueOf(BTN_Equipment__c.Equipment_Request__c),
                    String.valueOf(BTN_Equipment__c.Location__c),
                    String.valueOf(BTN_Equipment__c.Manufacturer__c),
                    String.valueOf(BTN_Equipment__c.Model__c),
                    String.valueOf(BTN_Equipment__c.Britenet_ID__c),
                    String.valueOf(BTN_Equipment__c.Description__c),
                    String.valueOf(BTN_Equipment__c.Reserved__c),
                    String.valueOf(BTN_Equipment__c.Active__c),
                    String.valueOf(BTN_Equipment__c.Vendor__c),
                    String.valueOf(BTN_Equipment__c.License_Type__c),
                    String.valueOf(BTN_Equipment__c.License_Name__c),
                    String.valueOf(BTN_Equipment__c.Subscription_Type__c),
                    String.valueOf(BTN_Equipment__c.Phone_Number__c),
                    String.valueOf(BTN_Equipment__c.Phone_Contract__c),
                    String.valueOf(BTN_Equipment__c.Expiration_Date__c)
            });
        }
        this.equipment = (BTN_Equipment__c) stdController.getRecord();
        equipment.Active__c = true;
        queryContactFromEquipment();
        queryContactLocationAndPhone();
        queryContactFromEquipmentRequest();
    }

    public Boolean getIsEquipment() {
        return BTN_RecordTypeUtils.isEquipmentEquipment(equipment);
    }

    public Boolean getIsLicense() {
        return BTN_RecordTypeUtils.isEquipmentLicense(equipment);
    }

    public Boolean getIsPhoneContract() {
        return BTN_RecordTypeUtils.isEquipmentPhoneContract(equipment);
    }

    public void queryContactLocationAndPhone() {
        if (equipment.Contact__c != null) {
            Contact relatedContact = new BTN_DAO_Contact(new List<SObjectField> {
                    Contact.Location__c,
                    Contact.MobilePhone
            }).findContactById(equipment.Contact__c);
            equipment.Location__c = relatedContact.Location__c;
            if (getIsPhoneContract() && String.isBlank(equipment.Phone_Number__c) && String.isNotBlank(relatedContact.MobilePhone)) {
                equipment.Phone_Number__c = relatedContact.MobilePhone;
            }
        }
    }

    public void queryContactFromEquipment() {
        if (equipment.Equipment__c != null) {
            BTN_Equipment__c relatedEquipment = new BTN_DAO_Equipment(new List<SObjectField> {
                    BTN_Equipment__c.Contact__c
            }).findEquipmentById(equipment.Equipment__c);
            equipment.Contact__c = relatedEquipment.Contact__c;
        }
    }

    public void queryContactFromEquipmentRequest() {
        if (equipment.Equipment_Request__c != null) {
            BTN_Equipment_Request__c relatedEquipmentRequest = new BTN_DAO_Equipment_Request(new List<SObjectField> {
                    BTN_Equipment_Request__c.Contact__c
            }).findEquipmentRequestById(equipment.Equipment_Request__c);
            equipment.Contact__c = relatedEquipmentRequest.Contact__c;
        }
    }

    public PageReference saveAndNew() {
        if (stdController.save() == null) {
            return null;
        }
        equipment = new BTN_Equipment__c(
                RecordTypeId = equipment.RecordTypeId,
                Type__c = equipment.Type__c,
                Active__c = true
        );
        return Page.BTN_EquipmentEdit;
    }

}