force-app/main/default/objects/BTN_Equipment__c/BTN_Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <displayFormat>EQ{000000}</displayFormat>
        <label>Equipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Equipment__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Czy sprzęt nie jest zezłomowany lub licencja jest aktywna?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Britenet_ID__c.field-meta.xml
<CustomField>
    <fullName>Britenet_ID__c</fullName>
    <externalId>true</externalId>
    <label>Britenet ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Equipment</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Selected Equipment must be owned by the selected Contact</errorMessage>
        <filterItems>
            <field>BTN_Equipment__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Equipment</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contact__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>BTN_Equipment__c.Contact__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BTN_Equipment__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <label>License Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Oem</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>Serial</fullName>
            </value>
            <value>
                <fullName>Floating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Phone_Contract__c.field-meta.xml
<CustomField>
    <fullName>Phone_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phone Contract</label>
    <referenceTo>BTN_Phone_Contract__c</referenceTo>
    <relationshipLabel>Equipment</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Reserved__c.field-meta.xml
<CustomField>
    <fullName>Reserved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reserved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Komputer</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>Telefon</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Karta SIM</fullName>
            </value>
            <value>
                <fullName>Router</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
            <value>
                <fullName>Access Point</fullName>
            </value>
            <value>
                <fullName>Licencja</fullName>
            </value>
            <value>
                <fullName>Inne</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <description>Sprzęt - komputery, monitory, telefony, tablety, karty SIM, routery, switche, access pointy i inne</description>
    <label>Equipment</label>
</RecordType>

force-app/main/default/classes/BTN_EquipmentBuilderHelper.cls
public with sharing class BTN_EquipmentBuilderHelper implements BTN_BuilderHelper {

    private BTN_Equipment__c record;

    public static BTN_EquipmentBuilderHelper buildWithEquipmentRecordType() {
        return buildWith(BTN_RecordTypeUtils.getRecordTypeEquipmentEquipment().Id);
    }

    public static BTN_EquipmentBuilderHelper buildWithLicenseRecordType() {
        return buildWith(BTN_RecordTypeUtils.getRecordTypeEquipmentEquipment().Id);
    }

    public static BTN_EquipmentBuilderHelper buildWithPhoneContractRecordType() {
        return buildWith(BTN_RecordTypeUtils.getRecordTypeEquipmentPhoneContract().Id);
    }

    public BTN_Equipment__c get() {
        return record;
    }

    public BTN_Equipment__c save() {
        insert record;
        return record;
    }

    public static BTN_EquipmentBuilderHelper buildFrom(BTN_Equipment__c equipment) {
        BTN_EquipmentBuilderHelper equipmentBuilderHelper = new BTN_EquipmentBuilderHelper();
        equipmentBuilderHelper.record = equipment;
        return equipmentBuilderHelper;
    }

    private static BTN_EquipmentBuilderHelper buildWith(String recordTypeId) {
        BTN_EquipmentBuilderHelper equipmentBuilderHelper = new BTN_EquipmentBuilderHelper();
        equipmentBuilderHelper.record = new BTN_Equipment__c(
                RecordTypeId = recordTypeId
        );
        return equipmentBuilderHelper;
    }

    private BTN_EquipmentBuilderHelper buildWithDefaults(String recordTypeId) {
        BTN_EquipmentBuilderHelper equipmentBuilderHelper = buildWith(recordTypeId);
        applyDefaults();
        return equipmentBuilderHelper;
    }

    public BTN_EquipmentBuilderHelper applyDefaults() {
        record.Active__c = true;
        record.Reserved__c = false;
        return this;
    }

    public BTN_EquipmentBuilderHelper withType(String type) {
        record.Type__c = type;
        return this;
    }

    public BTN_EquipmentBuilderHelper withManufacturer(String manufacturer) {
        record.Manufacturer__c = manufacturer;
        return this;
    }

    public BTN_EquipmentBuilderHelper withModel(String model) {
        record.Model__c = model;
        return this;
    }

    public BTN_EquipmentBuilderHelper withSerialNumber(String serialNumber) {
        record.Serial_Number__c = serialNumber;
        return this;
    }

    public BTN_EquipmentBuilderHelper withBritenetId(String britenetId) {
        record.Britenet_ID__c = britenetId;
        return this;
    }

    public BTN_EquipmentBuilderHelper withLicenseName(String licenseName) {
        record.License_Name__c = licenseName;
        return this;
    }

    public BTN_EquipmentBuilderHelper withLicenseType(String licenseType) {
        record.License_Type__c = licenseType;
        return this;
    }

    public BTN_EquipmentBuilderHelper withExpirationDate(Date expirationDate) {
        record.Expiration_Date__c = expirationDate;
        return this;
    }

    public BTN_EquipmentBuilderHelper withPhoneNumber(String phoneNumber) {
        record.Phone_Number__c = phoneNumber;
        return this;
    }

    public BTN_EquipmentBuilderHelper withContact(Id contactId) {
        record.Contact__c = contactId;
        return this;
    }

    public BTN_EquipmentBuilderHelper withEquipment(Id equipmentId) {
        record.Equipment__c = equipmentId;
        return this;
    }

    public BTN_EquipmentBuilderHelper withPhoneContract(Id phoneContractId) {
        record.Phone_Contract__c = phoneContractId;
        return this;
    }

}