force-app/main/default/objects/BTN_Equipment__c/BTN_Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <displayFormat>EQ{000000}</displayFormat>
        <label>Equipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Equipment__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Czy sprzęt nie jest zezłomowany lub licencja jest aktywna?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Britenet_ID__c.field-meta.xml
<CustomField>
    <fullName>Britenet_ID__c</fullName>
    <externalId>true</externalId>
    <label>Britenet ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Equipment</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Selected Equipment must be owned by the selected Contact</errorMessage>
        <filterItems>
            <field>BTN_Equipment__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Equipment</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contact__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>BTN_Equipment__c.Contact__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BTN_Equipment__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <label>License Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Oem</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>Serial</fullName>
            </value>
            <value>
                <fullName>Floating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DataCenter</fullName>
            </value>
            <value>
                <fullName>Lublin Hamleta</fullName>
            </value>
            <value>
                <fullName>Kielce IX Wieków</fullName>
            </value>
            <value>
                <fullName>Klient</fullName>
            </value>
            <value>
                <fullName>Lublin Morwowa</fullName>
            </value>
            <value>
                <fullName>Poznań Strzelecka</fullName>
            </value>
            <value>
                <fullName>Warszawa Bukowińska</fullName>
            </value>
            <value>
                <fullName>Warszawa Wołoska</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Reserved__c.field-meta.xml
<CustomField>
    <fullName>Reserved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reserved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Subscription Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Miesięczna</fullName>
            </value>
            <value>
                <fullName>Roczna</fullName>
            </value>
            <value>
                <fullName>Dożywotnia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Komputer</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>Telefon</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Karta SIM</fullName>
            </value>
            <value>
                <fullName>Router</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
            <value>
                <fullName>Access Point</fullName>
            </value>
            <value>
                <fullName>Licencja</fullName>
            </value>
            <value>
                <fullName>Inne</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sparx</fullName>
            </value>
            <value>
                <fullName>OVH</fullName>
            </value>
            <value>
                <fullName>Partner Microsoft</fullName>
            </value>
            <value>
                <fullName>Inny</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Company.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Britenet</fullName>
        <default>true</default>
        <label>Britenet</label>
    </customValue>
    <customValue>
        <fullName>Britenet Operations</fullName>
    </customValue>
    <customValue>
        <fullName>Britenet Polska</fullName>
    </customValue>
    <masterLabel>Company</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BTN_DAO_Equipment.cls
public with sharing class BTN_DAO_Equipment extends BTN_DAO {

    public BTN_DAO_Equipment() {

    }

    public BTN_DAO_Equipment(List<SObjectField> customFields) {
        setCustomFields(customFields);
    }

    public override List<Schema.SObjectField> getSObjectFields() {
        return new List<Schema.SObjectField>{
                BTN_Equipment__c.Name,
                BTN_Equipment__c.Active__c,
                BTN_Equipment__c.Britenet_ID__c,
                BTN_Equipment__c.Company__c,
                BTN_Equipment__c.Contact__c,
                BTN_Equipment__c.Description__c,
                BTN_Equipment__c.Equipment__c,
                BTN_Equipment__c.Expiration_Date__c,
                BTN_Equipment__c.License_Name__c,
                BTN_Equipment__c.License_Type__c,
                BTN_Equipment__c.Location__c,
                BTN_Equipment__c.Manufacturer__c,
                BTN_Equipment__c.Model__c,
                BTN_Equipment__c.Reserved__c,
                BTN_Equipment__c.Serial_Number__c,
                BTN_Equipment__c.Subscription_Type__c,
                BTN_Equipment__c.Type__c,
                BTN_Equipment__c.Vendor__c
        };
    }

    public BTN_Equipment__c findEquipmentById(Id equipmentId) {
        return (BTN_Equipment__c) findSObjectById(equipmentId);
    }

    public override SObjectType getSObjectType() {
        return BTN_Equipment__c.SObjectType;
    }

}