force-app/main/default/objects/BTN_Equipment__c/BTN_Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <displayFormat>EQ{000000}</displayFormat>
        <label>Equipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Equipment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Komputer</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>Telefon</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Karta SIM</fullName>
            </value>
            <value>
                <fullName>Router</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
            <value>
                <fullName>Access Point</fullName>
            </value>
            <value>
                <fullName>Licencja</fullName>
            </value>
            <value>
                <fullName>Inne</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <description>Sprzęt - komputery, monitory, telefony, tablety, karty SIM, routery, switche, access pointy i inne</description>
    <label>Equipment</label>
</RecordType>

force-app/main/default/classes/BTN_EquipmentTriggerHandler_Test.cls
@isTest
private class BTN_EquipmentTriggerHandler_Test {

    testMethod static void testSendingNewGearToBSAfterInsertingEquipment() {
        BTN_BSS_DTO.GearResponseStatus response;
        System.runAs(BTN_Utils.getCurrentUser()) {
            Test.setMock(HttpCalloutMock.class, new BTN_BSS_Mockup(
                    BTN_BSS_Mockup.SET_NEW_GEAR_MODE,
                    BTN_BSS_Mockup.SUCCESS_STATUS_CODE)
            );
            BTN_Equipment__c equipment = BTN_TestDataFactory.getEquipment(BTN_RecordTypeUtils.getRecordTypeEquipmentEquipment().Id);
        }
    }

    testMethod static void testUpdatingGearToBSAfterInsertingEquipment() {
        BTN_BSS_DTO.GearResponseStatus response;
        System.runAs(BTN_Utils.getCurrentUser()) {
            Test.setMock(HttpCalloutMock.class, new BTN_BSS_Mockup(
                    BTN_BSS_Mockup.SET_NEW_GEAR_MODE,
                    BTN_BSS_Mockup.SUCCESS_STATUS_CODE)
            );
            BTN_Equipment__c equipment = BTN_TestDataFactory.getEquipment(BTN_RecordTypeUtils.getRecordTypeEquipmentEquipment().Id);
            equipment.Type__c = 'Monitor';
            update equipment;
        }
    }

}