force-app/main/default/objects/BTN_Equipment__c/BTN_Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <displayFormat>EQ{000000}</displayFormat>
        <label>Equipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Equipment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Equipment</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Komputer</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>Telefon</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Karta SIM</fullName>
            </value>
            <value>
                <fullName>Router</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
            <value>
                <fullName>Access Point</fullName>
            </value>
            <value>
                <fullName>Licencja</fullName>
            </value>
            <value>
                <fullName>Inne</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Equipment__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <description>Sprzęt - komputery, monitory, telefony, tablety, karty SIM, routery, switche, access pointy i inne</description>
    <label>Equipment</label>
</RecordType>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Analytic</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BTN_EquipmentFactory_Test.cls
@isTest
private class BTN_EquipmentFactory_Test {

    @testSetup static void createDataStructure() {
        BTN_TestDataFactory.getHRCollaborationGroup();
        BTN_TestDataFactory.getBriteNetAccount();
    }

    testMethod static void testCreateGearParamsFromEquipment() {
        Contact equipmentContact = BTN_TestDataFactory.getInternalContact(BTN_TestDataFactory.getBriteNetAccount().Id);
        BTN_Equipment__c equipment = BTN_TestDataFactory.getEquipment(BTN_RecordTypeUtils.getRecordTypeEquipmentEquipment().Id);
        equipment.Contact__c = equipmentContact.Id;

        Test.startTest();
        BTN_EquipmentFactory equipmentFactory = new BTN_EquipmentFactory(new List<BTN_Equipment__c> { equipment });
        Map<String, String> result = equipmentFactory.createGearParamsFromEquipment(equipment, true);
        Test.stopTest();

        System.assert(!result.isEmpty());
    }

    testMethod static void testCreateGearFromEquipment() {
        BTN_Equipment__c equipment = BTN_TestDataFactory.getEquipment(BTN_RecordTypeUtils.getRecordTypeEquipmentEquipment().Id);

        Test.startTest();
        BTN_EquipmentFactory equipmentFactory = new BTN_EquipmentFactory(new List<BTN_Equipment__c> { equipment });
        BTN_BSS_DTO.Gear result = equipmentFactory.createGearFromEquipment(equipment);
        Test.stopTest();

        System.assertNotEquals(null, result);
    }

    testMethod static void testCreateEquipmentFromGear() {
        Contact equipmentContact = BTN_TestDataFactory.getInternalContact(BTN_TestDataFactory.getBriteNetAccount().Id);
        BTN_Equipment__c equipment = BTN_TestDataFactory.getEquipment(BTN_RecordTypeUtils.getRecordTypeEquipmentEquipment().Id);
        equipment.Contact__c = equipmentContact.Id;

        Test.startTest();
        BTN_EquipmentFactory equipmentFactory = new BTN_EquipmentFactory();
        BTN_BSS_DTO.Gear gear = equipmentFactory.createGearFromEquipment(equipment);
        BTN_Equipment__c result = equipmentFactory.createEquipmentFromGear(gear);
        Test.stopTest();

        System.assertEquals(equipment.Type__c, result.Type__c);
    }

}