force-app/main/default/objects/Opportunity/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>.Experience Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>.NET_C#</fullName>
            </value>
            <value>
                <fullName>.NET_VB</fullName>
            </value>
            <value>
                <fullName>ABAP</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>Android</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>CQ5</fullName>
            </value>
            <value>
                <fullName>ETL</fullName>
            </value>
            <value>
                <fullName>fullstack</fullName>
            </value>
            <value>
                <fullName>Groovie</fullName>
            </value>
            <value>
                <fullName>HTML_CSS</fullName>
            </value>
            <value>
                <fullName>IOS</fullName>
            </value>
            <value>
                <fullName>JAVA</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>Liferay</fullName>
            </value>
            <value>
                <fullName>MicrosoftDynamics</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>PL/SQL</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>Qt</fullName>
            </value>
            <value>
                <fullName>Ruby</fullName>
            </value>
            <value>
                <fullName>Salesforce.com</fullName>
            </value>
            <value>
                <fullName>Sharepoint</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>T-SQL</fullName>
            </value>
            <value>
                <fullName>WindowsPhone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/FixedPrice__c.field-meta.xml
<CustomField>
    <fullName>FixedPrice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fixed Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>.NET_C#</fullName>
            </value>
            <value>
                <fullName>.NET_VB</fullName>
            </value>
            <value>
                <fullName>ABAP</fullName>
            </value>
            <value>
                <fullName>Android</fullName>
            </value>
            <value>
                <fullName>Automated Testing</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>Business Analysis</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>CQ5</fullName>
            </value>
            <value>
                <fullName>ETL</fullName>
            </value>
            <value>
                <fullName>fullstack</fullName>
            </value>
            <value>
                <fullName>Groovie</fullName>
            </value>
            <value>
                <fullName>HTML_CSS</fullName>
            </value>
            <value>
                <fullName>IOS</fullName>
            </value>
            <value>
                <fullName>JAVA</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>Liferay</fullName>
            </value>
            <value>
                <fullName>Manual Testing</fullName>
            </value>
            <value>
                <fullName>MicrosoftDynamics</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>PL/SQL</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>Qt</fullName>
            </value>
            <value>
                <fullName>Ruby</fullName>
            </value>
            <value>
                <fullName>Salesforce.com</fullName>
            </value>
            <value>
                <fullName>Sharepoint</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>System Analysis</fullName>
            </value>
            <value>
                <fullName>T-SQL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BTN_ProductSelectionExtension_Test.cls
@isTest
private class BTN_ProductSelectionExtension_Test {
//
//	@isTest static void productListSetConAndGettersSettersTester() {
//		BTN_TestDataFactory.getPricebook();
//		Id pbId = Test.getStandardPricebookId();
//		Pricebook2 myPB = BTN_TestDataFactory.getPricebook();
//		List<Product2> prods = BTN_TestDataFactory.getProduct();
//		BTN_TestDataFactory.getPriceBookEntries(myPB, prods);
//		Opportunity newOppo = BTN_TestDataFactory.getOpportunity(myPB.Id);
//
//		BTN_TestDataFactory.getUtilCS();
//		PageReference pageTest = Page.BTN_OpportunityProductEditAll;
//		Test.setCurrentPage(pageTest);
//		ApexPages.StandardController stdC = new ApexPages.StandardController(newOppo);
//		BTN_ProductSelectionExtension controller = new BTN_ProductSelectionExtension(stdC);
//		System.assertEquals(null, controller.goToStep2());
//		controller.first();
//		controller.last();
//		controller.previous();
//		controller.next();
//		controller.nullPagination();
//		controller.checkedItem = controller.checkedItem;
//		controller.productsOnView = controller.productsOnView;
//		controller.selectedProductsOnView = controller.selectedProductsOnView;
//		controller.changedLineItem = controller.changedLineItem;
//		controller.hasNext = controller.hasNext;
//		controller.hasPrevious = controller.hasPrevious;
//		controller.pageNumber = controller.pageNumber;
//		controller.priceItem = controller.priceItem;
//		controller.mysObject.Pricebook2Id = null;
//		controller.getStandardPricebook();
//		System.assertEquals('SELECT Id, Name, Description, Level__c, ProductCode, Family, Technology__c,(SELECT UnitPrice, FixedPrice__c, CurrencyIsoCode FROM PricebookEntries WHERE Pricebook2Id = \''+ controller.standardPricebook +'\') FROM Product2 WHERE Id IN (SELECT Product2Id FROM PricebookEntry WHERE Pricebook2Id = :standardPricebook AND IsActive = true) ORDER BY Name'
//			, controller.getbasicQuery());
//		System.assertEquals(String.format(System.Label.AddProductsFormSec, new String[]{String.valueOf(newOppo.Name), newOppo.Pricebook2.Name})
//			, controller.getdynTitle());
//		System.assertEquals('/'+newOppo.Id, controller.cancelToOppo().getURL());
//		System.assertEquals('/apex/BTN_ProductSelectionListView?addTo=' + newOppo.Id + '&id='+ newOppo.Id, controller.cancelFromStep2().getURL());
//	}
//
//	@isTest static void productListConstructorTester() {
//		List<BTN_ProductSelectionWrapper> products;
//		List<BTN_ProductSelectionWrapper> selectedProductsToAdd;
//		List<BTN_OpportunityLineItemWrapper> oppoProducts;
//
//		BTN_TestDataFactory.getPricebook();
//		Id pbId = Test.getStandardPricebookId();
//		Pricebook2 myPB = BTN_TestDataFactory.getPricebook();
//		List<Product2> prods = BTN_TestDataFactory.getProduct();
//		BTN_TestDataFactory.getPriceBookEntries(myPB, prods);
//		Opportunity newOppo = BTN_TestDataFactory.getOpportunity(myPB.Id);
//		BTN_TestDataFactory.getUtilCS();
//		// item selection 1 step scenario.
//		PageReference pageTest = Page.BTN_OpportunityProductEditAll;
//		Test.setCurrentPage(pageTest);
//		ApexPages.StandardController stdC = new ApexPages.StandardController(newOppo);
//		BTN_ProductSelectionExtension controller = new BTN_ProductSelectionExtension(stdC);
//		BTN_ProductSelectionExtension controllerDummy = new BTN_ProductSelectionExtension();
//
//		String standardPricebook = controller.standardPricebook;
//		System.assertEquals(controller.standardPricebook, myPB.Id);
//
//		controller.getselectedProducts();
//		System.assert(!controller.getProducts().isEmpty());
//		controller.selectedProductsToAdd.add(controller.productsOnView.get(0));
//		System.assertNotEquals(null, controller.goToStep2());
//
//		products = controller.productsOnView;
//		selectedProductsToAdd = controller.selectedProductsToAdd;
//		oppoProducts = controller.selectedProductsOnView;
//		controller.priceItem = 0;
//		controller.setNullFixedPrice();
//		controller.setNullUnitPrice();
//		System.assertEquals(0, controller.selectedProductsOnView.get(controller.priceItem).lineItem.FixedPrice__c);
//		System.assertEquals(0, controller.selectedProductsOnView.get(controller.priceItem).lineItem.Hourly_Rate__c);
//
//		for (BTN_OpportunityLineItemWrapper item : controller.selectedProductsOnView) {
//			item.lineItem.Hourly_Rate__c = 66;
//			item.lineItem.Quantity = 6;
//		}
//		System.assertEquals(new PageReference('/' + newOppo.Id).getURL(), controller.saveOpportunityLineItems().getURL());
//
//		System.assertEquals(null, controller.refresh());
//
//		pageTest = Page.BTN_OpportunityProductEditAll;
//		Test.setCurrentPage(pageTest);
//		pageTest.getParameters().put('oppId', newOppo.Id);
//		//pageTest.getParameters().put('singleEdit',  controller.selectedProductsOnView.get(0).lineItem.Id);
//		controller = new BTN_ProductSelectionExtension(stdC);
//		System.assertEquals(String.format(System.Label.EditProductsFormSec, new String[]{String.valueOf(controller.mysObject.Name), controller.mysObject.Pricebook2.Name})
//			, controller.getdynTitle());
//		controller.selectedProductsToAdd = selectedProductsToAdd;
//		controller.productsOnView = products;
//		controller.checkedItem = prods.get(1).Id;
//		//add element(id = controller.checkedItem) and remove from selectedProductsToAdd.
//		controller.toggleItem();
//		controller.toggleItem();
//		for (BTN_OpportunityLineItemWrapper item : controller.selectedProductsOnView) {
//			item.lineItem.FixedPrice__c = 100;
//			item.lineItem.Quantity = 2;
//		}
//		System.debug(controller.selectedProductsOnView);
//		System.assertEquals(new PageReference('/' + newOppo.Id).getURL(), controller.saveOpportunityLineItems().getURL());
//		// wrap product exception;
//		System.assert(controller.wrapProductList([SELECT Id, Name, Description, Level__c, ProductCode, Family, Technology__c
//			FROM Product2 LIMIT 25]).isEmpty());
//		System.assertEquals((new PageReference('/'+newOppo.Id).getURL()), controller.cancelFromStep2().getURL());
//	}
}