force-app/main/default/objects/BTN_Equipment_Request__c/BTN_Equipment_Request__c.object-meta.xml
<CustomObject>
    <label>Equipment Request</label>
    <nameField>
        <displayFormat>ER{000000}</displayFormat>
        <label>Equipment Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Equipment_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Equipment Requests</relationshipLabel>
    <relationshipName>Equipment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment_Request__c/fields/Ready__c.field-meta.xml
<CustomField>
    <fullName>Ready__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Czy całe zamówienie zostało skompletowane?</description>
    <label>Ready</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BTN_Equipment_Request__c/fields/Requested_Equipment__c.field-meta.xml
<CustomField>
    <fullName>Requested_Equipment__c</fullName>
    <label>Requested Equipment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Equipment_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Equipment_Request__c/fields/Requested_Equipment_Comments__c.field-meta.xml
<CustomField>
    <fullName>Requested_Equipment_Comments__c</fullName>
    <label>Requested Equipment Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Equipment_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Komputer</fullName>
    </customValue>
    <customValue>
        <fullName>Monitor</fullName>
    </customValue>
    <customValue>
        <fullName>Klawiatura</fullName>
    </customValue>
    <customValue>
        <fullName>Mysz</fullName>
    </customValue>
    <customValue>
        <fullName>Telefon</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet</fullName>
    </customValue>
    <customValue>
        <fullName>Licencja</fullName>
    </customValue>
    <customValue>
        <fullName>Karta SIM</fullName>
    </customValue>
    <customValue>
        <fullName>Router</fullName>
    </customValue>
    <customValue>
        <fullName>Switch</fullName>
    </customValue>
    <customValue>
        <fullName>Access Point</fullName>
    </customValue>
    <customValue>
        <fullName>Okablowanie</fullName>
    </customValue>
    <customValue>
        <fullName>Słuchawki</fullName>
    </customValue>
    <customValue>
        <fullName>Podstawka pod laptopa</fullName>
    </customValue>
    <customValue>
        <fullName>Listwa</fullName>
    </customValue>
    <customValue>
        <fullName>Inne</fullName>
    </customValue>
    <masterLabel>Equipment Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BTN_DAO_Equipment_Request.cls
public with sharing class BTN_DAO_Equipment_Request extends BTN_DAO {

    public BTN_DAO_Equipment_Request() {

    }

    public BTN_DAO_Equipment_Request(List<SObjectField> customFields) {
        setCustomFields(customFields);
    }

    public override List<Schema.SObjectField> getSObjectFields() {
        return new List<Schema.SObjectField>{
                BTN_Equipment_Request__c.Name,
                BTN_Equipment_Request__c.Contact__c,
                BTN_Equipment_Request__c.Due_Date__c,
                BTN_Equipment_Request__c.Requested_Equipment__c,
                BTN_Equipment_Request__c.Requested_Equipment_Comments__c,
                BTN_Equipment_Request__c.Ready__c
        };
    }

    public BTN_Equipment_Request__c findEquipmentRequestById(Id equipmentRequestId) {
        return (BTN_Equipment_Request__c) findSObjectById(equipmentRequestId);
    }

    public override SObjectType getSObjectType() {
        return BTN_Equipment_Request__c.SObjectType;
    }

}