force-app/main/default/objects/BTN_Contract__c/BTN_Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>C{0000000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Contract__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Internal Britenet Company</inlineHelpText>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Britenet</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/ContractLength__c.field-meta.xml
<CustomField>
    <fullName>ContractLength__c</fullName>
    <inlineHelpText>Np. określony na rok</inlineHelpText>
    <label>Contract Length</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/ContractType__c.field-meta.xml
<CustomField>
    <fullName>ContractType__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B2B</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi - 90%</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi ...</fullName>
            </value>
            <value>
                <fullName>Umowa o Dzieło</fullName>
            </value>
            <value>
                <fullName>Umowa Zlecenie</fullName>
            </value>
            <value>
                <fullName>Inny rodzaj umowy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/NoticePeriod__c.field-meta.xml
<CustomField>
    <fullName>NoticePeriod__c</fullName>
    <inlineHelpText>Standardowo przy B2B powinien być 2 mies.</inlineHelpText>
    <label>Notice Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Od zaraz</fullName>
            </value>
            <value>
                <fullName>3 dni robocze</fullName>
            </value>
            <value>
                <fullName>2 tygodnie</fullName>
            </value>
            <value>
                <fullName>1 miesiąc</fullName>
            </value>
            <value>
                <fullName>2 miesiące</fullName>
            </value>
            <value>
                <fullName>3 miesiące</fullName>
            </value>
            <value>
                <fullName>Inne</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/NoticePeriodComment__c.field-meta.xml
<CustomField>
    <fullName>NoticePeriodComment__c</fullName>
    <label>Notice Period Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Responsibilities__c</fullName>
    <label>Responsibilities</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/SalaryB2B__c.field-meta.xml
<CustomField>
    <fullName>SalaryB2B__c</fullName>
    <inlineHelpText>Stawka za godzinę, netto</inlineHelpText>
    <label>Salary B2B</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/SalaryUoP__c.field-meta.xml
<CustomField>
    <fullName>SalaryUoP__c</fullName>
    <inlineHelpText>Kwota za miesięczne wynagrodzenie, brutto</inlineHelpText>
    <label>Salary UoP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/StartDateComment__c.field-meta.xml
<CustomField>
    <fullName>StartDateComment__c</fullName>
    <label>Start Date Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <label>Contract</label>
</RecordType>

force-app/main/default/objects/Case/fields/ContractLength__c.field-meta.xml
<CustomField>
    <fullName>ContractLength__c</fullName>
    <inlineHelpText>Np. określony na rok</inlineHelpText>
    <label>Contract Length</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ContractType__c.field-meta.xml
<CustomField>
    <fullName>ContractType__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2B</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi - 90%</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi ...</fullName>
            </value>
            <value>
                <fullName>Umowa o Dzieło</fullName>
            </value>
            <value>
                <fullName>Umowa Zlecenie</fullName>
            </value>
            <value>
                <fullName>Inny rodzaj umowy</fullName>
            </value>
            <value>
                <fullName>B2B (stawka netto za godzinę)</fullName>
                <isActive>false</isActive>
                <label>B2B (stawka netto za godzinę)</label>
            </value>
            <value>
                <fullName>UoP</fullName>
                <isActive>false</isActive>
                <label>UoP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <formula>IF(RecordType.Name = &apos;External Offboarding&apos;, AssignmentEndDate__c, 
IF(RecordType.Name = &apos;Internal Offboarding&apos;, ContactLastDayAtWork__c, WorkEndDate__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Notice_Period_Comment__c.field-meta.xml
<CustomField>
    <fullName>Notice_Period_Comment__c</fullName>
    <label>Notice Period Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NoticePeriod__c.field-meta.xml
<CustomField>
    <fullName>NoticePeriod__c</fullName>
    <inlineHelpText>Standardowo przy B2B powinien być 2 mies.</inlineHelpText>
    <label>Notice Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Od zaraz</fullName>
            </value>
            <value>
                <fullName>3 dni robocze</fullName>
            </value>
            <value>
                <fullName>2 tygodnie</fullName>
            </value>
            <value>
                <fullName>1 miesiąc</fullName>
            </value>
            <value>
                <fullName>2 miesiące</fullName>
            </value>
            <value>
                <fullName>3 miesiące</fullName>
            </value>
            <value>
                <fullName>Zgodnie z kodeksem pracy</fullName>
            </value>
            <value>
                <fullName>Inne</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Responsibilities__c</fullName>
    <label>Responsibilities</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/SalaryB2B__c.field-meta.xml
<CustomField>
    <fullName>SalaryB2B__c</fullName>
    <inlineHelpText>Stawka za godzinę, netto</inlineHelpText>
    <label>Salary (za godzinę netto)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/SalaryUoP__c.field-meta.xml
<CustomField>
    <fullName>SalaryUoP__c</fullName>
    <inlineHelpText>Kwota za miesięczne wynagrodzenie, brutto</inlineHelpText>
    <label>Salary (miesięcznie brutto)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/WorkStartDate__c.field-meta.xml
<CustomField>
    <fullName>WorkStartDate__c</fullName>
    <label>Work Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/WorkStartDateComment__c.field-meta.xml
<CustomField>
    <fullName>WorkStartDateComment__c</fullName>
    <label>Work Start Date Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ContractLength__c.field-meta.xml
<CustomField>
    <fullName>ContractLength__c</fullName>
    <formula>CASE(MOD( ContractStart__c - DATE(1985,6,24),7), 
  0 , CASE( MOD( ContractEnd__c - ContractStart__c ,7),1,2,2,3,3,4,4,5,5,5,6,5,1), 
  1 , CASE( MOD( ContractEnd__c - ContractStart__c ,7),1,2,2,3,3,4,4,4,5,4,6,5,1), 
  2 , CASE( MOD( ContractEnd__c - ContractStart__c ,7),1,2,2,3,3,3,4,3,5,4,6,5,1), 
  3 , CASE( MOD( ContractEnd__c - ContractStart__c ,7),1,2,2,2,3,2,4,3,5,4,6,5,1), 
  4 , CASE( MOD( ContractEnd__c - ContractStart__c ,7),1,1,2,1,3,2,4,3,5,4,6,5,1), 
  5 , CASE( MOD( ContractEnd__c - ContractStart__c ,7),1,0,2,1,3,2,4,3,5,4,6,5,0), 
  6 , CASE( MOD( ContractEnd__c - ContractStart__c ,7),1,1,2,2,3,3,4,4,5,5,6,5,0), 
  999) 
  + 
  (FLOOR(( ContractEnd__c - ContractStart__c )/7)*5)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract length</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BTN_ContractUtils.cls
/**
 * @author Mateusz Przywara
 * @date   2016-12-14
 * @description BTN_ContractUtils Utility Class provides utils for BTN_Contract sObject - Contracts contains
 * employment details.
 */
public class BTN_ContractUtils {

    /**
     * @author Mateusz Przywara
     * @date   2016-12-14
     * @description createContractFromOnboardingCase
     * @param sourceInternalOnboarding Case with filled up Employment info section
     * @return Database.SaveResult Insert new BTN_Contract Result
    */
    public static Database.SaveResult createContractFromOnboardingCase(Case sourceInternalOnboarding) {
        BTN_Contract__c newContract = new BTN_Contract__c(
                Description__c = sourceInternalOnboarding.Description,
                Contact__c = sourceInternalOnboarding.ContactId,
                ContractLength__c = sourceInternalOnboarding.ContractLength__c,
                ContractType__c = sourceInternalOnboarding.ContractType__c,
                EndDate__c = sourceInternalOnboarding.EndDate__c,
                NoticePeriod__c = sourceInternalOnboarding.NoticePeriod__c,
                NoticePeriodComment__c = sourceInternalOnboarding.Notice_Period_Comment__c,
                Responsibilities__c = sourceInternalOnboarding.Responsibilities__c,
                SalaryB2B__c = sourceInternalOnboarding.SalaryB2B__c,
                SalaryUoP__c = sourceInternalOnboarding.SalaryUoP__c,
                StartDate__c = sourceInternalOnboarding.WorkStartDate__c,
                StartDateComment__c = sourceInternalOnboarding.WorkStartDateComment__c,
                Company__c = BTN_Utils.getBTNPropertyValue('Default Contract Company')
        );
        return Database.insert(newContract);
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-12-14
     * @description createTaskForContactLeader
     * @param List<BTN_Contract__c> Contracts created on Onboarding etc.
     * @return Database.SaveResult Insert new Task Result
    */
    public static List<Database.SaveResult> createTaskForContactLeader(List<BTN_Contract__c> sourceContracts) {
        List<Task> outputTasks = new List<Task>();
        Set<Id> contactIds = new Set<Id>();
        for (BTN_Contract__c item : sourceContracts) {
            contactIds.add(item.Contact__c);
        }
        List<User> leaderUsers = new List<User>(new BTN_DAO_User().findUsersByContactIds(contactIds));
        if (!leaderUsers.isEmpty()) {
            for (BTN_Contract__c contractItem : sourceContracts) {
                outputTasks.add(new Task(
                        ActivityDate = contractItem.EndDate__c,
                        OwnerId = getLeaderForTaskByContactId(contractItem.Contact__c, leaderUsers), //LEADER(User) of
                        // Contact of Contract
                        Priority = BTN_ConstantRepo.NEW_OPPORTUNITY_TASK_PRIORITY_NORMAL,
                        WhoId = contractItem.Contact__c,
                        Subject = System.Label.ContractTaskSubject,
                        Status = BTN_ConstantRepo.NEW_OPPORTUNITY_TASK_STATUS_OPEN,
                        Is_Automatically_Created__c = false, //flag for Opportunity Tasks(flow: Task Reminders)
                        WhatId = contractItem.Id
                ));
            }
        }
        return Database.insert(outputTasks);
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-12-14
     * @description createTaskForResourceManager
     * @param List<BTN_Contract__c> Contracts created on Onboarding etc.
     * @return Database.SaveResult Insert new Task Result
    */
    public static List<Database.SaveResult> createTaskForResourceManager(List<BTN_Contract__c> sourceContracts) {
        List<Task> outputTasks = new List<Task>();
        User rmUser = new BTN_DAO_User().findUserByName(BTN_ConstantRepo.RM_USERNAME);
        if (rmUser != null) {
            for (BTN_Contract__c contractItem : sourceContracts) {
                outputTasks.add(new Task(
                        ActivityDate = contractItem.EndDate__c,
                        OwnerId = rmUser.Id, // RM User
                        Priority = BTN_ConstantRepo.NEW_OPPORTUNITY_TASK_PRIORITY_NORMAL,
                        WhoId = contractItem.Contact__c,
                        Subject = System.Label.ContractTaskSubject,
                        Status = BTN_ConstantRepo.NEW_OPPORTUNITY_TASK_STATUS_OPEN,
                        Is_Automatically_Created__c = false, //flag for Opportunity Tasks(flow: Task Reminders)
                        WhatId = contractItem.Id
                ));
            }
        }
        return Database.insert(outputTasks);
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-12-15
     * @description getLeaderForTaskByContactId
     * @param List<BTN_Contract__c> Contracts created on Onboarding etc.
     * @return Id - found User Id
    */
    private static Id getLeaderForTaskByContactId(Id contactId, List<User> users) {
        Id result;
        for (User userItem : users) {
            if (userItem.ContactId.equals(contactId)) {
                result = userItem.Id;
                break;
            }
        }
        return result;
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-12-15
     * @description createTasks
     * @param List<BTN_Contract__c> Contracts created on Onboarding etc.
    */
    @InvocableMethod(label='Create Contract Tasks' description='Creates Tasks(2) for Contract')
    public static void createTasks(List<BTN_Contract__c> contracts) {
        createTaskForResourceManager(contracts);
        createTaskForContactLeader(contracts);
    }
}