force-app/main/default/objects/BTN_Contract__c/BTN_Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>C{0000000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Contract__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/ContractType__c.field-meta.xml
<CustomField>
    <fullName>ContractType__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B2B</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi - 90%</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi ...</fullName>
            </value>
            <value>
                <fullName>Umowa o Dzieło</fullName>
            </value>
            <value>
                <fullName>Umowa Zlecenie</fullName>
            </value>
            <value>
                <fullName>Inny rodzaj umowy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_CV__c/BTN_CV__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CID{00000000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_CV__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Recruit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidates (Contact)</relationshipLabel>
    <relationshipName>Candidates1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/Position_Name_frm__c.field-meta.xml
<CustomField>
    <fullName>Position_Name_frm__c</fullName>
    <formula>ResourceRequest__r.Position_frm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Position Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/Project_Manager_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager_Email__c</fullName>
    <label>Project Manager Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/ResourceRequest__c.field-meta.xml
<CustomField>
    <fullName>ResourceRequest__c</fullName>
    <label>Resource request</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Resource request must not be closed</errorMessage>
        <filterItems>
            <field>BTN_ResourceRequest__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Closed Delivered, Closed Rejected</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BTN_ResourceRequest__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>CVs_lkp</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case/fields/ContractType__c.field-meta.xml
<CustomField>
    <fullName>ContractType__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2B</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi - 90%</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi ...</fullName>
            </value>
            <value>
                <fullName>Umowa o Dzieło</fullName>
            </value>
            <value>
                <fullName>Umowa Zlecenie</fullName>
            </value>
            <value>
                <fullName>Inny rodzaj umowy</fullName>
            </value>
            <value>
                <fullName>B2B (stawka netto za godzinę)</fullName>
                <isActive>false</isActive>
                <label>B2B (stawka netto za godzinę)</label>
            </value>
            <value>
                <fullName>UoP</fullName>
                <isActive>false</isActive>
                <label>UoP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Freelancer__c.field-meta.xml
<CustomField>
    <fullName>Freelancer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the contact a freelancer?</description>
    <label>Freelancer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Guardian__c.field-meta.xml
<CustomField>
    <fullName>Guardian__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guardian</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Guardian)</relationshipLabel>
    <relationshipName>GuardianCases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Leader__c.field-meta.xml
<CustomField>
    <fullName>Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserB2B__c.field-meta.xml
<CustomField>
    <fullName>NewUserB2B__c</fullName>
    <defaultValue>false</defaultValue>
    <description>New BS User is on B2B</description>
    <inlineHelpText>Is new User on Business-to-business?</inlineHelpText>
    <label>On B2B?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserEmail__c.field-meta.xml
<CustomField>
    <fullName>NewUserEmail__c</fullName>
    <description>New BS User Email</description>
    <label>Britenet Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserFirstName__c.field-meta.xml
<CustomField>
    <fullName>NewUserFirstName__c</fullName>
    <description>New BS User First Name</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserLastName__c.field-meta.xml
<CustomField>
    <fullName>NewUserLastName__c</fullName>
    <description>New BS User Last Name</description>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserProjectRole__c.field-meta.xml
<CustomField>
    <fullName>NewUserProjectRole__c</fullName>
    <description>BS Project Role is converted to Id during process</description>
    <label>Project Role</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserProjectRoleId__c.field-meta.xml
<CustomField>
    <fullName>NewUserProjectRoleId__c</fullName>
    <description>BS Project Role Id</description>
    <label>Project Role Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserTitle__c.field-meta.xml
<CustomField>
    <fullName>NewUserTitle__c</fullName>
    <description>Title of New BS User</description>
    <label>Position</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PersonalEmail__c.field-meta.xml
<CustomField>
    <fullName>PersonalEmail__c</fullName>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/PersonalPhone__c.field-meta.xml
<CustomField>
    <fullName>PersonalPhone__c</fullName>
    <label>Personal Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Project_Manager_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager_Email__c</fullName>
    <label>Project Manager Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Resource_Request__c.field-meta.xml
<CustomField>
    <fullName>Resource_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Request</label>
    <referenceTo>BTN_ResourceRequest__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/BSexternalId__c.field-meta.xml
<CustomField>
    <fullName>BSexternalId__c</fullName>
    <externalId>true</externalId>
    <label>Britesheet ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/CityLocation__c.field-meta.xml
<CustomField>
    <fullName>CityLocation__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lublin</fullName>
            </value>
            <value>
                <fullName>Warszawa</fullName>
            </value>
            <value>
                <fullName>Kielce</fullName>
            </value>
            <value>
                <fullName>Poznań</fullName>
            </value>
            <value>
                <fullName>Łódź</fullName>
            </value>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Freelancer__c.field-meta.xml
<CustomField>
    <fullName>Freelancer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the contact a freelancer?</description>
    <label>Freelancer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Guardian__c.field-meta.xml
<CustomField>
    <fullName>Guardian__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guardian</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Guarded Employees</relationshipLabel>
    <relationshipName>GuardedEmployees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Leader__c.field-meta.xml
<CustomField>
    <fullName>Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Managed Employees</relationshipLabel>
    <relationshipName>ManagedEmployees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PersonalEmail__c.field-meta.xml
<CustomField>
    <fullName>PersonalEmail__c</fullName>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PersonalPhone__c.field-meta.xml
<CustomField>
    <fullName>PersonalPhone__c</fullName>
    <label>Personal Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>ZOHO</description>
    <label>Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Internal employees</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Recruit.recordType-meta.xml
<RecordType>
    <fullName>Recruit</fullName>
    <active>true</active>
    <description>Recruits</description>
    <label>Recruit</label>
</RecordType>

force-app/main/default/classes/BTN_NewInternalOnboardingController.cls
/**
 * Created by Adam on 4/22/2018.
 */

public class BTN_NewInternalOnboardingController {
	public Case newInternalOnboardingCase { set; get; }
	public Contact sourceRecruit { set; get; }
	public String ownerName {
		get {
			return BTN_Utils.getCurrentUser().Name;
		}
	}


	public BTN_NewInternalOnboardingController(ApexPages.StandardController stdController) {
		this.newInternalOnboardingCase = (Case) stdController.getRecord();

		//New Onboarding ContactId param exist
		Id candidateId = ApexPages.currentPage().getParameters().get(BTN_ConstantRepo.URL_PARAM_CANDIDATE_ID);
		initialiseInternalOnboardingCase(candidateId);
	}

	private void initialiseInternalOnboardingCase(Id candidateId){
		BTN_CV__c candidate = (BTN_CV__c) new BTN_DAO_Candidate().findSObjectById(candidateId);

		if(candidate != null) {
			sourceRecruit = new BTN_DAO_Contact().addMailingFields().findContactById(candidate.Contact__c);
			this.newInternalOnboardingCase.Project_Manager_Email__c = candidate.Project_Manager_Email__c;
			this.newInternalOnboardingCase.NewUserTitle__c = candidate.Position_Name_frm__c;
			this.newInternalOnboardingCase.Resource_Request__c = candidate.ResourceRequest__c;
		} else {
			sourceRecruit = new BTN_DAO_Contact().addMailingFields().findContactById(newInternalOnboardingCase.ContactId);
		}

		if (this.newInternalOnboardingCase.Status == null) {
			this.newInternalOnboardingCase.Status = BTN_ConstantRepo.CASE_STATUS_OPEN;
		}

		this.newInternalOnboardingCase.RecordTypeId = BTN_RecordTypeUtils.getRecordTypeCaseInternalOnBoarding().Id;
		this.newInternalOnboardingCase.ContactId = sourceRecruit.Id;
		this.newInternalOnboardingCase.NewUserTitle__c = sourceRecruit.Position__c;
		this.newInternalOnboardingCase.PersonalPhone__c = sourceRecruit.PersonalPhone__c;
		this.newInternalOnboardingCase.PersonalEmail__c = sourceRecruit.PersonalEmail__c;
		this.newInternalOnboardingCase.City__c = sourceRecruit.CityLocation__c;
		this.newInternalOnboardingCase.NewUserTitle__c = sourceRecruit.Position__c;
		this.newInternalOnboardingCase.NewUserEmail__c = BTN_ContactUtils.setBritenetEmailForInternalContact(sourceRecruit);
		this.newInternalOnboardingCase.OwnerId = new BTN_DAO_Group().findGroupByName(BTN_ConstantRepo.QUEUE_HUMAN_RESOURCES).Id;
		this.newInternalOnboardingCase.Freelancer__c = sourceRecruit.Freelancer__c;

		if(sourceRecruit.Sex__c != null){
			this.newInternalOnboardingCase.Sex__c = sourceRecruit.Sex__c;
		}

		this.newInternalOnboardingCase.NewUserFirstName__c = sourceRecruit.FirstName;
		this.newInternalOnboardingCase.NewUserLastName__c = sourceRecruit.LastName;
	}

	/**
	 * @author Mateusz Przywara
	 * @date   2016-09-07
	 * @description getPageRecordTypeName
	 * @return Internal Onboarding Record Type Name
	*/
	public String getPageRecordTypeName() {
		return BTN_RecordTypeUtils.CASE_INTERNAL_ONBOARDING_RECORDTYPE;
	}

	/**
	 * @author Mateusz Przywara
	 * @date   2016-09-07
	 * @description addPageError
	*/
	public void addPageError(BTN_BSS_DTO.ResponseStatus response, String msg) {
		ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL, System.Label.NewInternalOnboardingError));
		if ((!BTN_ValidationHandler.isNull(response)) && (!BTN_ValidationHandler.isNull(response.error))) {
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL, response.error));
		}
		if (!BTN_ValidationHandler.isEmpty(msg)) {
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL, msg));
		}
	}

	/**
	 * @author Adam Jedrys
	 * @date   2018-05-24
	 * @description saveInternalOnboardingCase
	*/
	public PageReference saveInternalOnboardingCase() {
		PageReference newCasesPageReference;

		if(newInternalOnboardingCase.NewUserProjectRoleId__c != null){
			newInternalOnboardingCase.NewUserProjectRole__c = BTN_ContactUtils.MAP_PROJECT_ROLE_DESC_BY_ID.get(Integer.valueOf(newInternalOnboardingCase.NewUserProjectRoleId__c));
		}

		newInternalOnboardingCase.NewUserB2B__c = newInternalOnboardingCase.ContractType__c != null && !newInternalOnboardingCase.ContractType__c.startsWith(BTN_ConstantRepo.CASE_CONTRACT_TYPE_UOP);

		// create user BS account
		if(sourceRecruit.BSexternalId__c == null){
			try {
				// get bs external ids for leader and guardian
				Map<Id, Decimal> leaderAndGuardianBSIdsBySalesforceIds = getRelatedContactsBSIds(newInternalOnboardingCase);

				// fill request body with data provided by user on the form
				Map<String, String> requestParamMap = BTN_CaseUtils.buildParamMapForNewBSUserFromCase(newInternalOnboardingCase, leaderAndGuardianBSIdsBySalesforceIds);

				// send request to BS to create new user
				BTN_BSS_DTO.ResponseStatus response = BTN_BSS_Service.sendToBSNewUser(requestParamMap);

				if (BTN_ValidationHandler.isUserAddedToBSWithSuccess(response)) {
					// update recruit contact to internal, save BS details
					BTN_ContactUtils.updateInternalContactWithBSAccountDetails(sourceRecruit.Id, response.user_id);
				} else {
					addPageError(response, null);
					notifyAboutFailure(response.error, null);
				}

			} catch(Exception e) {
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL, e.getMessage()));
				notifyAboutFailure(e.getMessage(), e.getStackTraceString());
			}
		}

		// upsert onboarding case
		try{
			upsert newInternalOnboardingCase;
		} catch(Exception e){
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL, e.getMessage()));
			notifyAboutFailure(e.getMessage(), e.getStackTraceString());
		}

		// update recruit to internal, add onboarding details
		try {
			BTN_ContactUtils.updateToInternalWithOnboardingDetails(sourceRecruit.Id, newInternalOnboardingCase);
		} catch(Exception e){
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL, e.getMessage()));
			notifyAboutFailure(e.getMessage(), e.getStackTraceString());
		}

		try {
			List<BTN_Contract__c> relatedContracts = new BTN_DAO_Contract().findByContactsIds(new Set<Id>{sourceRecruit.Id});
			if(relatedContracts.isEmpty()){
				BTN_ContractUtils.createContractFromOnboardingCase(newInternalOnboardingCase);
			}
		} catch (Exception e) {
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL, e.getMessage()));
			notifyAboutFailure(e.getMessage(), e.getStackTraceString());
		}

		if(newInternalOnboardingCase.Id != null){
			newCasesPageReference = new PageReference('/' + newInternalOnboardingCase.Id);
		}

		return newCasesPageReference;
	}


	/**
	 * @author Adam Jedrys
	 * @date   2018-03-26
	 * @description
	*/

	private Map<Id, Decimal> getRelatedContactsBSIds(Case newInternalOnboardingCase){
		Set<Id> contactsIds = new Set<Id>();

		if(newInternalOnboardingCase.Leader__c != null)
			contactsIds.add(newInternalOnboardingCase.Leader__c);

		if(newInternalOnboardingCase.Guardian__c != null)
			contactsIds.add(newInternalOnboardingCase.Guardian__c);

		BTN_DAO_Contact contactDao = new BTN_DAO_Contact(new List<Schema.SObjectField>{Contact.BSexternalId__c});
		List<Contact> contacts = contactDao.findContactsByIds(contactsIds);

		Map<Id, Decimal> relatedContactsBSIdsBySalesforceIds = new Map<Id, Decimal>();

		for(Contact c : contacts)
			relatedContactsBSIdsBySalesforceIds.put(c.Id, c.BSexternalId__c);

		return relatedContactsBSIdsBySalesforceIds;
	}

	/**
	 * @author Adam Jedrys
	 * @date   2018-05-23
	 * @description
	*/

	private void notifyAboutFailure(String errorMessage, String stackTrace){
		String emailBody = 'Message: ' + errorMessage;
		if(String.isNotBlank(stackTrace))
			emailBody += '\n\nStack trace: ' + stackTrace;
		BTN_Email_Utils.sendWarningEmailToAdmin('Failure on internal onboarding for contact: ' + sourceRecruit.Name + ', ' + sourceRecruit.Id, emailBody);
	}

	/**
	 * @author Mateusz Przywara
	 * @date   2016-09-28
	 * @description getProjectRoles
	*/
	public List<SelectOption> getProjectRoles() {
		List<SelectOption> result = new List<SelectOption>{
				BTN_Utils.getNullSelectOption()
		};
		for (Integer keyItem : BTN_ContactUtils.MAP_PROJECT_ROLE_DESC_BY_ID.keySet()) {
			result.add(
					new SelectOption(
							String.valueOf(keyItem),
							BTN_ContactUtils.MAP_PROJECT_ROLE_DESC_BY_ID.get(keyItem)
					)
			);
		}
		return result;
	}
}