force-app/main/default/objects/BTN_Contract__c/BTN_Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>C{0000000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Contract__c/fields/ContractLength__c.field-meta.xml
<CustomField>
    <fullName>ContractLength__c</fullName>
    <inlineHelpText>Np. określony na rok</inlineHelpText>
    <label>Contract Length</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/ContractType__c.field-meta.xml
<CustomField>
    <fullName>ContractType__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B2B</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi - 90%</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi ...</fullName>
            </value>
            <value>
                <fullName>Umowa o Dzieło</fullName>
            </value>
            <value>
                <fullName>Umowa Zlecenie</fullName>
            </value>
            <value>
                <fullName>Inny rodzaj umowy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/NoticePeriod__c.field-meta.xml
<CustomField>
    <fullName>NoticePeriod__c</fullName>
    <inlineHelpText>Standardowo przy B2B powinien być 2 mies.</inlineHelpText>
    <label>Notice Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Od zaraz</fullName>
            </value>
            <value>
                <fullName>3 dni robocze</fullName>
            </value>
            <value>
                <fullName>2 tygodnie</fullName>
            </value>
            <value>
                <fullName>1 miesiąc</fullName>
            </value>
            <value>
                <fullName>2 miesiące</fullName>
            </value>
            <value>
                <fullName>3 miesiące</fullName>
            </value>
            <value>
                <fullName>Inne</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Responsibilities__c</fullName>
    <label>Responsibilities</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/SalaryB2B__c.field-meta.xml
<CustomField>
    <fullName>SalaryB2B__c</fullName>
    <inlineHelpText>Stawka za godzinę, netto</inlineHelpText>
    <label>Salary B2B</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/BTN_ResourceRequest__c.object-meta.xml
<CustomObject>
    <label>Resource request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kielce</fullName>
            </value>
            <value>
                <fullName>Lublin</fullName>
            </value>
            <value>
                <fullName>Poznań</fullName>
            </value>
            <value>
                <fullName>Warszawa</fullName>
            </value>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/NumberOfCVs1__c.field-meta.xml
<CustomField>
    <fullName>NumberOfCVs1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of CVs 1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Resource_Manager__c.field-meta.xml
<CustomField>
    <fullName>Resource_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.Name_frm__c</field>
            <operation>contains</operation>
            <value>Codello</value>
        </filterItems>
        <filterItems>
            <field>Contact.Name_frm__c</field>
            <operation>contains</operation>
            <value>Łukaszewski</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Resource_Requests_RM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ContractLength__c.field-meta.xml
<CustomField>
    <fullName>ContractLength__c</fullName>
    <inlineHelpText>Np. określony na rok</inlineHelpText>
    <label>Contract Length</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ContractType__c.field-meta.xml
<CustomField>
    <fullName>ContractType__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2B</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi - 90%</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi ...</fullName>
            </value>
            <value>
                <fullName>Umowa o Dzieło</fullName>
            </value>
            <value>
                <fullName>Umowa Zlecenie</fullName>
            </value>
            <value>
                <fullName>Inny rodzaj umowy</fullName>
            </value>
            <value>
                <fullName>B2B (stawka netto za godzinę)</fullName>
                <isActive>false</isActive>
                <label>B2B (stawka netto za godzinę)</label>
            </value>
            <value>
                <fullName>UoP</fullName>
                <isActive>false</isActive>
                <label>UoP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Guardian__c.field-meta.xml
<CustomField>
    <fullName>Guardian__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guardian</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Guardian)</relationshipLabel>
    <relationshipName>GuardianCases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Leader__c.field-meta.xml
<CustomField>
    <fullName>Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <inlineHelpText>Np. oddział na ul. Morwowej 1 w Lublinie</inlineHelpText>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lublin Hamleta</fullName>
            </value>
            <value>
                <fullName>Lublin Morwowa</fullName>
            </value>
            <value>
                <fullName>Kielce IX Wieków</fullName>
            </value>
            <value>
                <fullName>Zdalnie</fullName>
            </value>
            <value>
                <fullName>U klienta [Other location is mandatory]</fullName>
            </value>
            <value>
                <fullName>Inne [Other location is mandatory]</fullName>
            </value>
            <value>
                <fullName>Warszawa Karolkowa</fullName>
            </value>
            <value>
                <fullName>Poznań Szyperska</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserEmail__c.field-meta.xml
<CustomField>
    <fullName>NewUserEmail__c</fullName>
    <description>New BS User Email</description>
    <label>Britenet Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserProjectRole__c.field-meta.xml
<CustomField>
    <fullName>NewUserProjectRole__c</fullName>
    <description>BS Project Role is converted to Id during process</description>
    <label>Project Role</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewUserTitle__c.field-meta.xml
<CustomField>
    <fullName>NewUserTitle__c</fullName>
    <description>Title of New BS User</description>
    <label>Position</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NoticePeriod__c.field-meta.xml
<CustomField>
    <fullName>NoticePeriod__c</fullName>
    <inlineHelpText>Standardowo przy B2B powinien być 2 mies.</inlineHelpText>
    <label>Notice Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Od zaraz</fullName>
            </value>
            <value>
                <fullName>3 dni robocze</fullName>
            </value>
            <value>
                <fullName>2 tygodnie</fullName>
            </value>
            <value>
                <fullName>1 miesiąc</fullName>
            </value>
            <value>
                <fullName>2 miesiące</fullName>
            </value>
            <value>
                <fullName>3 miesiące</fullName>
            </value>
            <value>
                <fullName>Zgodnie z kodeksem pracy</fullName>
            </value>
            <value>
                <fullName>Inne</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PersonalEmail__c.field-meta.xml
<CustomField>
    <fullName>PersonalEmail__c</fullName>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/PersonalPhone__c.field-meta.xml
<CustomField>
    <fullName>PersonalPhone__c</fullName>
    <label>Personal Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Responsibilities__c</fullName>
    <label>Responsibilities</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/SalaryB2B__c.field-meta.xml
<CustomField>
    <fullName>SalaryB2B__c</fullName>
    <inlineHelpText>Stawka za godzinę, netto</inlineHelpText>
    <label>Salary (za godzinę netto)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/WorkStartDate__c.field-meta.xml
<CustomField>
    <fullName>WorkStartDate__c</fullName>
    <label>Work Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/BSexternalId__c.field-meta.xml
<CustomField>
    <fullName>BSexternalId__c</fullName>
    <externalId>true</externalId>
    <label>Britesheet ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Guardian__c.field-meta.xml
<CustomField>
    <fullName>Guardian__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guardian</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Guarded Employees</relationshipLabel>
    <relationshipName>GuardedEmployees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/joinDateBS__c.field-meta.xml
<CustomField>
    <fullName>joinDateBS__c</fullName>
    <label>BriteSheet join date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Leader__c.field-meta.xml
<CustomField>
    <fullName>Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Managed Employees</relationshipLabel>
    <relationshipName>ManagedEmployees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Other Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PersonalEmail__c.field-meta.xml
<CustomField>
    <fullName>PersonalEmail__c</fullName>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PersonalPhone__c.field-meta.xml
<CustomField>
    <fullName>PersonalPhone__c</fullName>
    <label>Personal Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>ZOHO</description>
    <label>Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Recruit.recordType-meta.xml
<RecordType>
    <fullName>Recruit</fullName>
    <active>true</active>
    <description>Recruits</description>
    <label>Recruit</label>
</RecordType>

force-app/main/default/classes/BTN_NewInternalOnboardingController_Test.cls
/**
 * Created by Adam on 4/22/2018.
 */

@IsTest
private class BTN_NewInternalOnboardingController_Test
{
	@testSetup
	static void testSetup() {
		BTN_TestDataFactory.getTriggerSkipperCustomSetting();
		BTN_TestDataFactory.getHRCollaborationGroup();
		BTN_TestDataFactory.getNewBssDummyConnections();
		BTN_TestDataFactory.getProjectRolesCustomSetting();

		Account britenet = BTN_TestDataFactory.getBriteNetAccount();
		Contact requestor = BTN_TestDataFactory.getRequestorInternalContact(britenet.Id);
		Contact leader = BTN_TestDataFactory.getLeaderInternalContact(britenet.Id);
		Contact recruit = BTN_TestDataFactory.getRecruitContact(britenet.Id, '');

		BTN_BriteCRM_settings__c companySetting = new BTN_BriteCRM_settings__c(
				Name = BTN_ConstantRepo.CUSTOM_SETTING_DEFAULT_CONTRACT_COMPANY,
				Value__c = britenet.Id
		);
		insert companySetting;

		BTN_ResourceRequest__c resourceRequest = BTN_ResourceRequestBuilderHelper.buildWithManualRecordType().get();
		resourceRequest.NumberOfCVs1__c = 0;
		resourceRequest.Resource_Manager__c = requestor.Id;
		insert resourceRequest;

		BTN_DAO_ResourceRequest resourceRequestDao = new BTN_DAO_ResourceRequest();
		resourceRequest = resourceRequestDao.findResourceRequestsById(resourceRequest.id);
		System.assert(resourceRequest.NumberOfCVs1__c == 0);

		BTN_TestDataFactory.getCV(resourceRequest.Id, recruit.Id);
	}

	static void setupTestPage(){
		BTN_CV__c candidate = new BTN_DAO_Candidate().findCandidates()[0];
		PageReference testPage = Page.BTN_NewInternalOnboarding;
		testPage.getParameters().put(BTN_ConstantRepo.URL_PARAM_CANDIDATE_ID, candidate.Id);
		Test.setCurrentPage(testPage);
	}

	static BTN_NewInternalOnboardingController setupController(Contact recruit, Contact leader){
		ApexPages.StandardController stdController = new ApexPages.StandardController(new Case());
		BTN_NewInternalOnboardingController controller = new BTN_NewInternalOnboardingController(stdController);

		controller.newInternalOnboardingCase.NewUserProjectRole__c = 'Salesforce';
		controller.newInternalOnboardingCase.Leader__c = leader.Id;
		controller.newInternalOnboardingCase.Guardian__c = leader.Id;
		controller.newInternalOnboardingCase.Location__c = 'Lublin Morwowa';
		controller.newInternalOnboardingCase.PersonalEmail__c = recruit.PersonalEmail__c;
		controller.newInternalOnboardingCase.PersonalPhone__c = recruit.PersonalPhone__c;
		controller.newInternalOnboardingCase.ContractType__c = 'B2B';
		controller.newInternalOnboardingCase.SalaryB2B__c = 100;
		controller.newInternalOnboardingCase.ContractLength__c = '12';
		controller.newInternalOnboardingCase.NoticePeriod__c = '2 miesiące';
		controller.newInternalOnboardingCase.Responsibilities__c = 'Working';
		controller.newInternalOnboardingCase.WorkStartDate__c = Date.today().addDays(30);

		return controller;
	}

	@isTest
	static void saveInternalOnboarding_test(){
		Test.setMock(HttpCalloutMock.class, new BTN_BSS_SendToBSNewUser_Mock(BTN_BSS_SendToBSNewUser_Mock.STATUS_CODE_SUCCESS));

		setupTestPage();

		BTN_DAO_Contact contactDao = new BTN_DAO_Contact();
		Contact recruit = contactDao.findRecruits()[0];
		Contact leader = contactDao.findLeaders()[0];

		BTN_NewInternalOnboardingController controller = setupController(recruit, leader);

		Test.startTest();

		PageReference returnedReference = controller.saveInternalOnboardingCase();

		Test.stopTest();

		List<Case> existingCases = new BTN_DAO_Case().findCases();
		System.assertEquals(1, existingCases.size());

		Case insertedOnboardingCase = existingCases[0];

		System.assertNotEquals(null, returnedReference);
		System.assertEquals(new PageReference('/'+insertedOnboardingCase.Id).getUrl(), returnedReference.getUrl());

		List<Contact> existingRecruits = contactDao.findRecruits();
		System.assertEquals(true, existingRecruits.isEmpty());

		List<Contact> existingInternals = contactDao.findInternals();
		System.assertEquals(3, existingInternals.size());

		Contact convertedInternal = contactDao.addMailingFields().findContactById(recruit.Id);

		System.assertNotEquals(null, convertedInternal.BSexternalId__c);
		System.assertNotEquals(null, convertedInternal.joinDateBS__c);
		System.assertEquals(insertedOnboardingCase.NewUserProjectRole__c, convertedInternal.Title);
		System.assertEquals(insertedOnboardingCase.Leader__c, convertedInternal.ReportsToId);
		System.assertEquals(insertedOnboardingCase.Leader__c, convertedInternal.Leader__c);
		System.assertEquals(insertedOnboardingCase.Guardian__c, convertedInternal.Guardian__c);
		System.assertEquals(insertedOnboardingCase.NewUserEmail__c, convertedInternal.Email);
		System.assertEquals(insertedOnboardingCase.WorkStartDate__c, convertedInternal.joinDateBS__c);
		System.assertEquals(insertedOnboardingCase.ZipCode__c, convertedInternal.MailingPostalCode);
		System.assertEquals(insertedOnboardingCase.Street__c, convertedInternal.MailingStreet);
		System.assertEquals(insertedOnboardingCase.City__c, convertedInternal.MailingCity);
		System.assertEquals(insertedOnboardingCase.PersonalEmail__c, convertedInternal.PersonalEmail__c);
		System.assertEquals(insertedOnboardingCase.PersonalPhone__c, convertedInternal.PersonalPhone__c);
		System.assertEquals(insertedOnboardingCase.NewUserTitle__c, convertedInternal.Position__c);
		System.assertEquals(insertedOnboardingCase.Location__c, convertedInternal.Location__c);
		System.assertEquals(true, convertedInternal.SkillAssessment__c);
		System.assertEquals(insertedOnboardingCase.Freelancer__c, convertedInternal.Freelancer__c);

		List<BTN_Contract__c> existingContracts = new BTN_DAO_Contract().findByContactsIds(new Set<Id>{convertedInternal.Id});
		System.assertEquals(1, existingContracts.size());
	}

	@isTest
	static void saveInternalOnboarding_BSCalloutFailure_test(){
		Test.setMock(HttpCalloutMock.class, new BTN_BSS_SendToBSNewUser_Mock(BTN_BSS_SendToBSNewUser_Mock.STATUS_CODE_BAD_REQUEST));

		setupTestPage();

		BTN_DAO_Contact contactDao = new BTN_DAO_Contact();
		Contact recruit = contactDao.findRecruits()[0];
		Contact leader = contactDao.findLeaders()[0];

		BTN_NewInternalOnboardingController controller = setupController(recruit, leader);

		Test.startTest();

		PageReference returnedReference = controller.saveInternalOnboardingCase();

		Test.stopTest();

		List<Case> existingCases = new BTN_DAO_Case().findCases();
		System.assertEquals(1, existingCases.size());

		Case insertedOnboardingCase = existingCases[0];

		System.assertNotEquals(null, returnedReference);
		System.assertEquals(new PageReference('/'+insertedOnboardingCase.Id).getUrl(), returnedReference.getUrl());

		List<Contact> existingRecruits = contactDao.findRecruits();
		System.assertEquals(0, existingRecruits.size());

		List<Contact> existingInternals = contactDao.findInternals();
		System.assertEquals(3, existingInternals.size());

		Contact convertedInternal = contactDao.addMailingFields().findContactById(recruit.Id);

		System.assertEquals(null, convertedInternal.BSexternalId__c);

		List<BTN_Contract__c> existingContracts = new BTN_DAO_Contract().findByContactsIds(new Set<Id>{convertedInternal.Id});
		System.assertEquals(1, existingContracts.size());
	}

	@isTest
	static void saveInternalOnboarding_ExceptionCatchOnBsCallLevel_test(){
		Test.setMock(HttpCalloutMock.class, new BTN_BSS_SendToBSNewUser_Mock(BTN_BSS_SendToBSNewUser_Mock.STATUS_CODE_SUCCESS));

		setupTestPage();

		BTN_DAO_Contact contactDao = new BTN_DAO_Contact();
		Contact recruit = contactDao.findRecruits()[0];
		Contact leader = contactDao.findLeaders()[0];

		BTN_NewInternalOnboardingController controller = setupController(recruit, leader);

		controller.newInternalOnboardingCase.WorkStartDate__c = null;

		Test.startTest();

		PageReference returnedReference = controller.saveInternalOnboardingCase();

		Test.stopTest();

		List<Apexpages.Message> msgs = ApexPages.getMessages();
		System.assertEquals(1, msgs.size());

		List<Case> existingCases = new BTN_DAO_Case().findCases();
		System.assertEquals(1, existingCases.size());

		Case insertedOnboardingCase = existingCases[0];

		System.assertNotEquals(null, returnedReference);
		System.assertEquals(new PageReference('/'+insertedOnboardingCase.Id).getUrl(), returnedReference.getUrl());

		List<Contact> existingRecruits = contactDao.findRecruits();
		System.assertEquals(0, existingRecruits.size());

		List<Contact> existingInternals = contactDao.findInternals();
		System.assertEquals(3, existingInternals.size());

		Contact convertedInternal = contactDao.addMailingFields().findContactById(recruit.Id);

		System.assertEquals(null, convertedInternal.BSexternalId__c);

		List<BTN_Contract__c> existingContracts = new BTN_DAO_Contract().findByContactsIds(new Set<Id>{convertedInternal.Id});
		System.assertEquals(1, existingContracts.size());
	}

	@isTest
	static void saveInternalOnboarding_ExceptionCatchOnContractCreation_test(){
		Test.setMock(HttpCalloutMock.class, new BTN_BSS_SendToBSNewUser_Mock(BTN_BSS_SendToBSNewUser_Mock.STATUS_CODE_SUCCESS));

		setupTestPage();

		BTN_BriteCRM_settings__c companySetting = BTN_BriteCRM_settings__c.getInstance(BTN_ConstantRepo.CUSTOM_SETTING_DEFAULT_CONTRACT_COMPANY);
		delete companySetting;

		BTN_DAO_Contact contactDao = new BTN_DAO_Contact();
		Contact recruit = contactDao.findRecruits()[0];
		Contact leader = contactDao.findLeaders()[0];

		BTN_NewInternalOnboardingController controller = setupController(recruit, leader);

		Test.startTest();

		PageReference returnedReference = controller.saveInternalOnboardingCase();

		Test.stopTest();

		List<Apexpages.Message> msgs = ApexPages.getMessages();
		System.assertEquals(1, msgs.size());

		List<Case> existingCases = new BTN_DAO_Case().findCases();
		System.assertEquals(1, existingCases.size());

		Case insertedOnboardingCase = existingCases[0];

		System.assertNotEquals(null, returnedReference);
		System.assertEquals(new PageReference('/'+insertedOnboardingCase.Id).getUrl(), returnedReference.getUrl());

		List<Contact> existingRecruits = contactDao.findRecruits();
		System.assertEquals(0, existingRecruits.size());

		List<Contact> existingInternals = contactDao.findInternals();
		System.assertEquals(3, existingInternals.size());

		Contact convertedInternal = contactDao.addMailingFields().findContactById(recruit.Id);

		System.assertNotEquals(null, convertedInternal.BSexternalId__c);

		List<BTN_Contract__c> existingContracts = new BTN_DAO_Contract().findByContactsIds(new Set<Id>{convertedInternal.Id});
		System.assertEquals(0, existingContracts.size());
	}

	@isTest
	static void getProjectRoles_test(){
		setupTestPage();

		ApexPages.StandardController stdController = new ApexPages.StandardController(new Case());
		BTN_NewInternalOnboardingController controller = new BTN_NewInternalOnboardingController(stdController);

		Test.startTest();

		List<SelectOption> projectRoles = controller.getProjectRoles();

		Test.stopTest();

		System.assertNotEquals(true, projectRoles.isEmpty());
	}
}