force-app/main/default/objects/BTN_Contract__c/BTN_Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>C{0000000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Contract__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Internal Britenet Company</inlineHelpText>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Britenet</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/ContractLength__c.field-meta.xml
<CustomField>
    <fullName>ContractLength__c</fullName>
    <inlineHelpText>Np. określony na rok</inlineHelpText>
    <label>Contract Length</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/ContractType__c.field-meta.xml
<CustomField>
    <fullName>ContractType__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B2B</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi - 90%</fullName>
            </value>
            <value>
                <fullName>Umowa o Pracę z kosztami autorskimi ...</fullName>
            </value>
            <value>
                <fullName>Umowa o Dzieło</fullName>
            </value>
            <value>
                <fullName>Umowa Zlecenie</fullName>
            </value>
            <value>
                <fullName>Inny rodzaj umowy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/NoticePeriod__c.field-meta.xml
<CustomField>
    <fullName>NoticePeriod__c</fullName>
    <inlineHelpText>Standardowo przy B2B powinien być 2 mies.</inlineHelpText>
    <label>Notice Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Od zaraz</fullName>
            </value>
            <value>
                <fullName>3 dni robocze</fullName>
            </value>
            <value>
                <fullName>2 tygodnie</fullName>
            </value>
            <value>
                <fullName>1 miesiąc</fullName>
            </value>
            <value>
                <fullName>2 miesiące</fullName>
            </value>
            <value>
                <fullName>3 miesiące</fullName>
            </value>
            <value>
                <fullName>Inne</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/NoticePeriodComment__c.field-meta.xml
<CustomField>
    <fullName>NoticePeriodComment__c</fullName>
    <label>Notice Period Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Responsibilities__c</fullName>
    <label>Responsibilities</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/Reviewed__c.field-meta.xml
<CustomField>
    <fullName>Reviewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reviewed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/SalaryB2B__c.field-meta.xml
<CustomField>
    <fullName>SalaryB2B__c</fullName>
    <inlineHelpText>Stawka za godzinę, netto</inlineHelpText>
    <label>Salary B2B</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/SalaryB2B_frm__c.field-meta.xml
<CustomField>
    <fullName>SalaryB2B_frm__c</fullName>
    <formula>IF (
  OR(Contact__r.Leader__c == $User.ContactId, Contact__c == $User.ContactId),
  SalaryB2B__c,
  NULL
)</formula>
    <label>Salary B2B</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/SalaryUoP__c.field-meta.xml
<CustomField>
    <fullName>SalaryUoP__c</fullName>
    <inlineHelpText>Kwota za miesięczne wynagrodzenie, brutto</inlineHelpText>
    <label>Salary UoP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/SalaryUoP_frm__c.field-meta.xml
<CustomField>
    <fullName>SalaryUoP_frm__c</fullName>
    <formula>IF (
  OR(Contact__r.Leader__c == $User.ContactId, Contact__c == $User.ContactId),
  SalaryUoP__c,
  NULL
)</formula>
    <label>Salary UoP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BTN_Contract__c/fields/StartDateComment__c.field-meta.xml
<CustomField>
    <fullName>StartDateComment__c</fullName>
    <label>Start Date Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BTN_DAO_Contract.cls
/**
 * Created by Adam on 5/24/2018.
 */

public class BTN_DAO_Contract extends BTN_DAO {

	public BTN_DAO_Contract(){}

	public BTN_DAO_Contract(List<Schema.SObjectField> customFields) {
		setCustomFields(customFields);
	}

	public override Schema.SObjectType getSObjectType() {
		return BTN_Contract__c.sObjectType;
	}

	public override List<Schema.SObjectField> getSObjectFields() {
		return new List<Schema.SObjectField>{
				BTN_Contract__c.Id,
				BTN_Contract__c.Description__c,
				BTN_Contract__c.Company__c,
				BTN_Contract__c.Contact__c,
				BTN_Contract__c.ContractLength__c,
				BTN_Contract__c.ContractType__c,
				BTN_Contract__c.EndDate__c,
				BTN_Contract__c.NoticePeriod__c,
				BTN_Contract__c.NoticePeriodComment__c,
				BTN_Contract__c.Responsibilities__c,
				BTN_Contract__c.Reviewed__c,
				BTN_Contract__c.SalaryB2B__c,
				BTN_Contract__c.SalaryB2B_frm__c,
				BTN_Contract__c.SalaryUoP__c,
				BTN_Contract__c.SalaryUoP_frm__c,
				BTN_Contract__c.StartDate__c,
				BTN_Contract__c.StartDateComment__c
		};
	}

	public List<BTN_Contract__c> findByContactsIds(Set<Id> contactIds) {
		return findSObjectsBy(new List<SearchCondition> {
				new SearchCondition('Contact__c', 'IN', contactIds)
		});
	}
}