force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>Achievement</description>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Level_1_Details__c.field-meta.xml
<CustomField>
    <fullName>Level_1_Details__c</fullName>
    <defaultValue>&quot;uczy się, brak samodzielnosci, wymaga kontroli i sprawdzania efektów pracy, ma kontakt z technologią w projekcie&quot;</defaultValue>
    <inlineHelpText>Jakie warunki trzeba spełnić aby osiągnąć pierwszy poziom umiejętności</inlineHelpText>
    <label>Level 1 Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Level_2_Details__c.field-meta.xml
<CustomField>
    <fullName>Level_2_Details__c</fullName>
    <defaultValue>&quot;samodzielna praca przynajmniej w jednym projekcie, nie wymaga kontroli&quot;</defaultValue>
    <inlineHelpText>Jakie warunki trzeba spełnić aby osiągnąć drugi poziom umiejętności</inlineHelpText>
    <label>Level 2 Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Level_3_Details__c.field-meta.xml
<CustomField>
    <fullName>Level_3_Details__c</fullName>
    <defaultValue>&quot;może uczyć innych oraz wyceniać funkcjionalości, wiedza potwierdzona pracą w kilku projektach, osoba kontaktowa w przypadku zapytań o daną umiejętność&quot;</defaultValue>
    <inlineHelpText>Jakie warunki trzeba spełnić aby osiągnąć trzeci poziom umiejętności</inlineHelpText>
    <label>Level 3 Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/Achievement_Set__c.object-meta.xml
<CustomObject>
    <description>Achievement Set</description>
    <label>Achievement Set</label>
    <nameField>
        <label>Achievement Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set__c/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Career_Path__c/Career_Path__c.object-meta.xml
<CustomObject>
    <label>Career Path</label>
    <nameField>
        <label>Career Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Career Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AchievementTriggerTest.cls
/**
 * Achievement Trigger Test
 * @author Michał Banasik
 */
@isTest
private class AchievementTriggerTest {

    @isTest
    private static void shouldNotCreateLevelDescriptionForBadgeRecordType() {
        Achievement__c achievement = new AchievementUtils.AchievementBuilder('achievement', new AchievementUtils.AchievementCategoryBuilder('category').buildAndSave()).asBadge().build();

        insert achievement;

        Achievement__c insertedAchievement = [SELECT Level_1_Details__c, Level_2_Details__c, Level_3_Details__c FROM Achievement__c WHERE Id=:achievement.Id];
        System.assertEquals(null, insertedAchievement.Level_1_Details__c);
        System.assertEquals(null, insertedAchievement.Level_2_Details__c);
        System.assertEquals(null, insertedAchievement.Level_3_Details__c);
    }

    @isTest
    private static void shouldNotCreateLevelDescriptionForCertificateRecordType() {
        Achievement__c achievement = new AchievementUtils.AchievementBuilder('achievement', new AchievementUtils.AchievementCategoryBuilder('category').buildAndSave()).asCert().build();

        insert achievement;

        Achievement__c insertedAchievement = [SELECT Level_1_Details__c, Level_2_Details__c, Level_3_Details__c FROM Achievement__c WHERE Id=:achievement.Id];
        System.assertEquals(null, insertedAchievement.Level_1_Details__c);
        System.assertEquals(null, insertedAchievement.Level_2_Details__c);
        System.assertEquals(null, insertedAchievement.Level_3_Details__c);
    }

    @isTest
    private static void shouldNotCreateLevelDescriptionForSpecializationRecordType() {
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath').buildAndSave();
        Achievement_Set__c achievementSet = new AchievementUtils.AchievementSetBuilder('Specjalization').asProfile(careerPath).buildAndSave();
        Achievement__c achievement = new AchievementUtils.AchievementBuilder('achievement', new AchievementUtils.AchievementCategoryBuilder('category').buildAndSave()).asSpecialization(achievementSet).build();

        insert achievement;

        Achievement__c insertedAchievement = [SELECT Level_1_Details__c, Level_2_Details__c, Level_3_Details__c FROM Achievement__c WHERE Id=:achievement.Id];
        System.assertEquals(null, insertedAchievement.Level_1_Details__c);
        System.assertEquals(null, insertedAchievement.Level_2_Details__c);
        System.assertEquals(null, insertedAchievement.Level_3_Details__c);
    }

    @isTest
    private static void shouldCreateLevelDescriptionForGroupRecordType() {
        Achievement__c achievement = new AchievementUtils.AchievementBuilder('achievement', new AchievementUtils.AchievementCategoryBuilder('category').buildAndSave()).asGroup().build();

        insert achievement;

        Achievement__c insertedAchievement = [SELECT Level_1_Details__c, Level_2_Details__c, Level_3_Details__c FROM Achievement__c WHERE Id=:achievement.Id];
        System.assertNotEquals(null, insertedAchievement.Level_1_Details__c);
        System.assertNotEquals(null, insertedAchievement.Level_2_Details__c);
        System.assertNotEquals(null, insertedAchievement.Level_3_Details__c);
    }

    @isTest
    private static void shouldCreateLevelDescriptionForSkillRecordType() {
        Achievement__c achievement = new AchievementUtils.AchievementBuilder('achievement', new AchievementUtils.AchievementCategoryBuilder('category').buildAndSave()).asSkill().build();

        insert achievement;

        Achievement__c insertedAchievement = [SELECT Level_1_Details__c, Level_2_Details__c, Level_3_Details__c FROM Achievement__c WHERE Id=:achievement.Id];
        System.assertNotEquals(null, insertedAchievement.Level_1_Details__c);
        System.assertNotEquals(null, insertedAchievement.Level_2_Details__c);
        System.assertNotEquals(null, insertedAchievement.Level_3_Details__c);
    }
}