force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>Achievement</description>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <inlineHelpText>Opis osiągnięcia, rozwinięcie skrótu.</inlineHelpText>
    <label>Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Group_Type__c.field-meta.xml
<CustomField>
    <fullName>Group_Type__c</fullName>
    <label>Group Calculation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Greatest Value</fullName>
                <default>true</default>
                <label>Greatest Value</label>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Greatest Value (Specialization)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Level_1_Details__c.field-meta.xml
<CustomField>
    <fullName>Level_1_Details__c</fullName>
    <defaultValue>&quot;uczy się, brak samodzielnosci, wymaga kontroli i sprawdzania efektów pracy, ma kontakt z technologią w projekcie&quot;</defaultValue>
    <inlineHelpText>Jakie warunki trzeba spełnić aby osiągnąć pierwszy poziom umiejętności</inlineHelpText>
    <label>Level 1 Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Level_2_Details__c.field-meta.xml
<CustomField>
    <fullName>Level_2_Details__c</fullName>
    <defaultValue>&quot;samodzielna praca przynajmniej w jednym projekcie, nie wymaga kontroli&quot;</defaultValue>
    <inlineHelpText>Jakie warunki trzeba spełnić aby osiągnąć drugi poziom umiejętności</inlineHelpText>
    <label>Level 2 Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Level_3_Details__c.field-meta.xml
<CustomField>
    <fullName>Level_3_Details__c</fullName>
    <defaultValue>&quot;może uczyć innych oraz wyceniać funkcjionalości, wiedza potwierdzona pracą w kilku projektach, osoba kontaktowa w przypadku zapytań o daną umiejętność&quot;</defaultValue>
    <inlineHelpText>Jakie warunki trzeba spełnić aby osiągnąć trzeci poziom umiejętności</inlineHelpText>
    <label>Level 3 Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/Achievement_Set_Item__c.object-meta.xml
<CustomObject>
    <description>Achievement Set Item</description>
    <label>Achievement Set Item</label>
    <nameField>
        <displayFormat>ASI{00000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Set Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipName>Position_Profile_Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Min_Speciality_Match__c.field-meta.xml
<CustomField>
    <fullName>Min_Speciality_Match__c</fullName>
    <defaultValue>1.0</defaultValue>
    <label>Min. Speciality Match</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/NumberOfMonths__c.field-meta.xml
<CustomField>
    <fullName>NumberOfMonths__c</fullName>
    <formula>((YEAR(Today()) - YEAR(DATEVALUE(Date__c))-1) * 12) + (12 - MONTH(DATEVALUE(Date__c))+1) + MONTH(Today())</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number Of Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement_Value__c/Achievement_Value__c.object-meta.xml
<CustomObject>
    <label>Achievement Value</label>
    <nameField>
        <label>Achievement Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Value__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>Achievement Values</relationshipLabel>
    <relationshipName>AchievementValues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement_Value__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Achievement.cls
/**
 * Achievement Set Item wrapper class.
 * @author Adam Siwek
 */
public with sharing class Achievement {

    public Achievement_Set_Item__c oldRecord {get; set;}
    public Boolean selected {get; set;}

    private Achievement_Set_Item__c cmpRecord;
    private Achievement__c achievement;

    public Achievement(Achievement__c achievement, Achievement_Set_Item__c data) {
        if (achievement == null || data == null || achievement.Id != data.Achievement__c) {
            throw new SystemUtils.SystemException(System.Label.InvalidConstructorParameters);
        }
        this.achievement = achievement;
        this.oldRecord = data;
        this.selected = data.Id != null && getIsCert();
    }

    public Achievement setDataToCmp(Achievement_Set_Item__c dataToCmp) {
        if (dataToCmp == null || achievement.Id != dataToCmp.Achievement__c || dataToCmp.Achievement__c != oldRecord.Achievement__c) {
            throw new SystemUtils.SystemException(System.Label.InvalidMethodParameters);
        }
        this.cmpRecord = dataToCmp;
        return this;
    }

    public Boolean getIsSkill() {
        return achievement.RecordTypeId == AchievementUtils.getAchievementSkillRecordType().Id;
    }
    public Boolean getIsCert() {
        return achievement.RecordTypeId == AchievementUtils.getAchievementCertificateRecordType().Id;
    }
    public Boolean getIsBadge() {
        return achievement.RecordTypeId == AchievementUtils.getAchievementBadgeRecordType().Id;
    }
    public Boolean getIsGroup() {
        return achievement.RecordTypeId == AchievementUtils.getAchievementGroupRecordType().Id;
    }
    public Boolean getIsSpecialization() {
        return achievement.RecordTypeId == AchievementUtils.getAchievementSpecializationRecordType().Id;
    }
    public Boolean getIsAttribute() {
        return achievement.RecordTypeId == AchievementUtils.getAchievementAttributeRecordType().Id;
    }
    public Boolean getIsMonthsFromDate() {
        return achievement.RecordTypeId == AchievementUtils.getAchievementMonthsFromDateRecordType().Id;
    }

    public List<SelectOption> getAttributeLevels() {
        List<SelectOption> attributeLevels = new List<SelectOption>();
        attributeLevels.add(new SelectOption('', System.Label.None));
        for (Achievement_Value__c av : achievement.AchievementValues__r) {
            attributeLevels.add(new SelectOption(String.valueOf(av.Value__c), av.Name));
        }
        return attributeLevels;
    }

    public String getAttributeLevelValues() {
         return getValueLevel(oldRecord.Amount__c);
    }

    public String getCmpRecordAttributeLevelValues() {
        return getValueLevel(cmpRecord.Amount__c);
    }

    private String getValueLevel(Decimal amount) {
        Map<Integer, Achievement_Value__c> levelValues = AchievementService.getAchievementsValues().get(achievement.Id);
        String valueLevel = '';
        Integer tmp = Integer.valueOf(amount);
        if (!levelValues.isEmpty() && tmp != null){
            for(Integer key : levelValues.keySet()) {
                if(tmp - key >= 0) {
                    valueLevel += levelValues.get(key).name + ', ';
                    tmp = tmp - key;
                }
                if (tmp == 0) {
                    break;
                }
            }
            valueLevel = valueLevel.substring(0, valueLevel.length()-2);
        }
        return valueLevel;
    }

    public String getDescription() {
        String dsc = achievement.Details__c != null ? achievement.Details__c : achievement.Name;
        String endline = '\n';//'&#013;';
        if (getIsSkill()) {
            dsc += endline + 'Junior - ' + (achievement.Level_1_Details__c != null ? achievement.Level_1_Details__c : '');
            dsc += endline + 'Professional - ' + (achievement.Level_2_Details__c != null ? achievement.Level_2_Details__c : '');
            dsc += endline + 'Senior - ' + (achievement.Level_3_Details__c != null ? achievement.Level_3_Details__c : '');
        }
        return dsc;
    }

    public String getHTMLDescription() {
        String dsc = '<h2>' + (achievement.Details__c != null ? achievement.Details__c : achievement.Name) + '</h2>';
        String endline = '<br>';
        if (getIsSkill()) {
            dsc += endline + '<b>Junior</b> - ' + (achievement.Level_1_Details__c != null ? achievement.Level_1_Details__c : '');
            dsc += endline + '<b>Professional</b> - ' + (achievement.Level_2_Details__c != null ? achievement.Level_2_Details__c : '');
            dsc += endline + '<b>Senior</b> - ' + (achievement.Level_3_Details__c != null ? achievement.Level_3_Details__c : '');
        }
        return dsc;
    }

    public Boolean getHasValue() {
        return level != '' || amount != '0' || minSpecialityMatch != '0.0' || selected;
    }

    public Boolean getIsNew() {
        return oldRecord.Id == null;
    }

    public Boolean getIsModificableGroup() {
        return achievement.Group_Type__c == AchievementUtils.ACHIEVEMENT_MANUAL_GROUP_TYPE;
    }

    public String level {
        get{return oldRecord.Level__c == null ? '' : oldRecord.Level__c;}
        set{oldRecord.Level__c = value;}
    }

    public String amount {
        get{return oldRecord.Amount__c == null ? '0' : String.valueOf(oldRecord.Amount__c);}
        set{oldRecord.Amount__c = value == null ? 0 : Integer.valueOf(value);}
    }

    public String minSpecialityMatch {
        get{return oldRecord.Min_Speciality_Match__c == null ? '0.0' : String.valueOf(oldRecord.Min_Speciality_Match__c);}
        set{oldRecord.Min_Speciality_Match__c = Double.valueOf(value);}
    }

    public String getName() {
        return achievement.Name;
    }

    public Boolean getHasValueToCompare() {
        return cmpRecord != null;
    }

    public Boolean getHasDifferentValue() {
        return getHasDifferentLevel() || getHasDifferentAmount() || getHasDifferentMinSpecialityMatch() || !getHasCert() || getHasDifferentNumberOfMonths() || getHasDifferentAttributeValue();
    }
    public Boolean getHasDifferentLevel() {
        return cmpRecord != null && AchievementUtils.compareLevel(oldRecord.Level__c, cmpRecord.Level__c);
    }
    public Boolean getHasDifferentAttributeValue() {
        return cmpRecord != null && oldRecord.Amount__c < cmpRecord.Amount__c && getIsAttribute();
    }
    public Boolean getHasDifferentAmount() {
        return cmpRecord != null && oldRecord.Amount__c < cmpRecord.Amount__c && getIsBadge();
    }
    public Boolean getHasDifferentMinSpecialityMatch() {
        return cmpRecord != null && oldRecord.Min_Speciality_Match__c < cmpRecord.Min_Speciality_Match__c;
    }
    public Boolean getHasCert() {
        return !(cmpRecord != null && !selected && getIsCert());
    }
    public Boolean getHasDifferentNumberOfMonths() {
        return cmpRecord != null && oldRecord.NumberOfMonths__c < cmpRecord.NumberOfMonths__c;
    }

    public String getDifferenceInfo() {
        if (getHasDifferentLevel()) {
            return ' (' + cmpRecord.Level__c + ')';
        }
        if (getHasDifferentAmount()) {
            return ' (' + String.valueOf(cmpRecord.Amount__c) + ')';
        }
        if (getHasDifferentNumberOfMonths()) {
            Double numberOfMonths = cmpRecord.NumberOfMonths__c.setScale(0);
            return ' (' + String.valueOf(numberOfMonths) + ')';
        }
        if (getHasDifferentMinSpecialityMatch()) {
            return ' (' + String.valueOf(cmpRecord.Min_Speciality_Match__c * 100) + '%)';
        }
        if (getHasDifferentAttributeValue()) {
            return   ' (' + getCmpRecordAttributeLevelValues() + ')';
        }
        return '';
    }
}