force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>Achievement</description>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Achievement_Category__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Category__c</fullName>
    <label>Achievement Category</label>
    <referenceTo>Achievement_Category__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement_Category__c/Achievement_Category__c.object-meta.xml
<CustomObject>
    <description>Achievement Category</description>
    <label>Achievement Category</label>
    <nameField>
        <label>Achievement Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set__c/Achievement_Set__c.object-meta.xml
<CustomObject>
    <description>Achievement Set</description>
    <label>Achievement Set</label>
    <nameField>
        <label>Achievement Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set__c/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact field is valid only for Contact Survey and Contact Profile record types</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Career_Path__c/Career_Path__c.object-meta.xml
<CustomObject>
    <label>Career Path</label>
    <nameField>
        <label>Career Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Career Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Achievement_Profile__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Achievement Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Achievement_Set__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee Profile</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Achievement_Set__c.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Contacts (Achievement Profile)</relationshipLabel>
    <relationshipName>Contact_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SkillAssessment__c.field-meta.xml
<CustomField>
    <fullName>SkillAssessment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skill Assessment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Profile_Score__c/Contact_Profile_Score__c.object-meta.xml
<CustomObject>
    <description>Employee Profile Score</description>
    <label>Employee Profile Probe</label>
    <nameField>
        <displayFormat>EPP{00000000}</displayFormat>
        <label>Profile Probe ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Profile Probes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Profile_Score__c/fields/Achievement_Profile__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Profile__c</fullName>
    <label>Achievement Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Achievement_Set__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Specialization, Position Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Employee Profile Probes (Achievement Profile)</relationshipLabel>
    <relationshipName>Achievement_Profiles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Profile_Score__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Profile Probes</relationshipLabel>
    <relationshipName>Contact_Position_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Profile_Score__c/fields/Contact_Profile__c.field-meta.xml
<CustomField>
    <fullName>Contact_Profile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Achievement_Set__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee Profile</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contact__c</field>
            <operation>equals</operation>
            <valueField>Achievement_Set__c.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Employee Profile Probes (Employee Profile)</relationshipLabel>
    <relationshipName>Contact_Profile_Scores</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactAchievementSetScorePageExtTest.cls
@isTest
private class ContactAchievementSetScorePageExtTest {

    @isTest
    private static void shouldGetAchievementSet() {
        //GIVEN
        Contact c = new Contact(FirstName = 'test', LastName = 'test', Email='test@test.com.pl', SkillAssessment__c=true);
        insert c;
        Achievement_Set__c delAchievment = [SELECT Id FROM Achievement_Set__c LIMIT 1];
        delete delAchievment;

        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPaths').buildAndSave();

        Achievement_Category__c category = new AchievementUtils.AchievementCategoryBuilder('Category').buildAndSave();
        List<Achievement__c> skills = new List<Achievement__c>{
            new AchievementUtils.AchievementBuilder('Skill1', category).asSkill().build(),
            new AchievementUtils.AchievementBuilder('Skill2', category).asSkill().build()
        };
        insert skills;
        Achievement_Set__c positionProfile = new AchievementUtils.AchievementSetBuilder('Junior SFDC').
                asPositionProfile(careerPath).
                addSkill(skills[0], AchievementUtils.ACHIEVEMENT_LEVEL_1).
                addSkill(skills[1], AchievementUtils.ACHIEVEMENT_LEVEL_1).
                buildAndSave();
        Achievement_Set__c achievementSet = new AchievementUtils.AchievementSetBuilder('ContactProfile').
                asContactProfile(c).
                addSkill(skills[0], AchievementUtils.ACHIEVEMENT_LEVEL_1).
                addSkill(skills[1], AchievementUtils.ACHIEVEMENT_LEVEL_1).
                buildAndSave();


        //WHEN
        Test.startTest();
        Database.executeBatch(new AchievementProfileCalcuationJob());
        Test.stopTest();
        List<Contact_Profile_Score__c> contactProfileScores = [SELECT Contact_Profile__c, Achievement_Profile__c FROM Contact_Profile_Score__c WHERE Contact__c=:c.Id LIMIT 1];
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(contactProfileScores[0]);
        ContactAchievementSetScorePageExtension ext = new ContactAchievementSetScorePageExtension(stdCtrl);

        //THEN
        System.assertEquals('test' + ' ' + 'test'+ ' - Employee Profile', ext.achievementSet.Name);
    }
}