force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>Achievement</description>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Achievement_Category__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Category__c</fullName>
    <label>Achievement Category</label>
    <referenceTo>Achievement_Category__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement_Category__c/Achievement_Category__c.object-meta.xml
<CustomObject>
    <description>Achievement Category</description>
    <label>Achievement Category</label>
    <nameField>
        <label>Achievement Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyConfiguration__c/SurveyConfiguration__c.object-meta.xml
<CustomObject>
    <label>Survey Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyConfiguration__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SurveyConfiguration__c/fields/ConfigSignature__c.field-meta.xml
<CustomField>
    <fullName>ConfigSignature__c</fullName>
    <label>Config signature</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/SurveyTemplate__c.object-meta.xml
<CustomObject>
    <label>Survey Template</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplate__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <label>Api Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/Config__c.field-meta.xml
<CustomField>
    <fullName>Config__c</fullName>
    <label>Config</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/Importance__c.field-meta.xml
<CustomField>
    <fullName>Importance__c</fullName>
    <label>Importance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/MultiSurvey__c.field-meta.xml
<CustomField>
    <fullName>MultiSurvey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multi survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/Private__c.field-meta.xml
<CustomField>
    <fullName>Private__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Private</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/Submittable__c.field-meta.xml
<CustomField>
    <fullName>Submittable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submittable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/SurveyHandler__c.field-meta.xml
<CustomField>
    <fullName>SurveyHandler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Survey Handler</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SurveyConfiguration__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Survey_Handler</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SurveyConfiguration__c</referenceTo>
    <relationshipLabel>Surveys Templates</relationshipLabel>
    <relationshipName>SurveysTemplates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateAccesses__c/SurveyTemplateAccesses__c.object-meta.xml
<CustomObject>
    <label>Survey Template Access</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SurveyTemplateAccesses Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Template Accesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplateAccesses__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Template Accesses</relationshipLabel>
    <relationshipName>SurveyTemplateAccesses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateAccesses__c/fields/OnlyLeaders__c.field-meta.xml
<CustomField>
    <fullName>OnlyLeaders__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Only Leaders</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateAccesses__c/fields/SurveyTemplate__c.field-meta.xml
<CustomField>
    <fullName>SurveyTemplate__c</fullName>
    <label>Survey Template</label>
    <referenceTo>SurveyTemplate__c</referenceTo>
    <relationshipLabel>Survey Template Accesses</relationshipLabel>
    <relationshipName>SurveyTemplateAccesses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/SurveyTemplateItem__c.object-meta.xml
<CustomObject>
    <label>Survey Template Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplateItem__c/fields/QuestionProvider__c.field-meta.xml
<CustomField>
    <fullName>QuestionProvider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Question Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SurveyConfiguration__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Survey_Question_Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SurveyConfiguration__c</referenceTo>
    <relationshipLabel>Survey Template Items</relationshipLabel>
    <relationshipName>SurveyTemplateItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/fields/SurveyTemplate__c.field-meta.xml
<CustomField>
    <fullName>SurveyTemplate__c</fullName>
    <label>Survey Template</label>
    <referenceTo>SurveyTemplate__c</referenceTo>
    <relationshipLabel>Survey Template Items</relationshipLabel>
    <relationshipName>SurveyTemplateItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SurveyTestUtils.cls
@isTest
public class SurveyTestUtils {

    public static final String DEFAULT_SURVEY_HANDLER_CONFIGURATION_CLASS = 'AchievementSurveyUtils.AchievementPositionProfileHandler';
    public static final String DEFAULT_QUESTION_PROVIDER_CLASS = 'AchievementSurveyUtils.AchievementQuestionProvider';
    public static final String DEFAULT_SURVEY_CONFIGURATION_SIGNATURE = '{"id": ""}';

    public static List<SurveyModel.TemplateInfo> templatesInfoRequest(String userId) {
        return SurveyFrontController.getInstance().getTemplatesInfo(new SurveyUtils.Request(userID));
    }

    public static SurveyModel.Template templateRequest(String userId, String templateApiName) {
        return SurveyFrontController.getInstance().getTemplate(new SurveyUtils.TemplateRequest(userID, templateApiName));
    }

    public static SurveyModel.Survey surveyRequest(String userId, String templateApiName, String surveyId) {
        return SurveyFrontController.getInstance().getSurvey(new SurveyUtils.SurveyRequest(userId, templateApiName, surveyId));
    }

    public static SurveyTemplateItem__c createDefaultTemplateItem(SurveyTemplate__c template) {
        return buildDefaultTemplateItem(template).buildAndSave();
    }

    public static TemplateItemBuilder buildDefaultTemplateItem(SurveyTemplate__c template) {
        SurveyTestUtils.SurveyConfigBuilder cfg = SurveyTestUtils.createDefaultQuestionProvider('questionProvider');
        Achievement_Category__c category = new AchievementUtils.AchievementCategoryBuilder('name').buildAndSave();
        Achievement__c achievement = new AchievementUtils.AchievementBuilder('Apex', category).asSkill().buildAndSave();

        return new SurveyTestUtils.TemplateItemBuilder(template, cfg.getConfigs().get('questionProvider')).withConfig('{"id": "'+achievement.Id+'", "getAll":"true"}');
    }

    public static SurveyTemplate__c createDefaultTemplate(String templateName) {
        return buildDefaultTemplate(templateName).buildAndSave();
    }

    public static TemplateBuilder buildDefaultTemplate(String templateName) {
        return new SurveyTestUtils.TemplateBuilder(templateName);
    }

    public static SurveyConfigBuilder createDefaultSurveyHandler(String name) {
        SurveyConfigBuilder cfg = new SurveyConfigBuilder().setServiceConfig(name, DEFAULT_SURVEY_HANDLER_CONFIGURATION_CLASS, DEFAULT_SURVEY_CONFIGURATION_SIGNATURE, null, true).setSurveyHandlerRecordType(name);
        cfg.buildAndSave();
        return cfg;
    }

    public static SurveyConfigBuilder createDefaultQuestionProvider(String name) {
        SurveyConfigBuilder cfg = new SurveyConfigBuilder().setServiceConfig(name, DEFAULT_QUESTION_PROVIDER_CLASS, DEFAULT_SURVEY_CONFIGURATION_SIGNATURE, null, true).setQuestionProviderRecordType(name);
        cfg.buildAndSave();
        return cfg;
    }

    public virtual class SurveyConfigBuilder {
        private Map<String, SurveyConfiguration__c> config;

        public SurveyConfigBuilder() {
            config = new Map<String, SurveyConfiguration__c>();
        }

        public SurveyConfigBuilder setServiceConfig(String configName, String configClass, String configSignature, ID recordType, Boolean active) {
            SurveyConfiguration__c cfg = config.containsKey(configName) ? config.get(configName) : new SurveyConfiguration__c(Name=configName);

            if (configClass != null){
                cfg.Class__c = configClass;
            }
            if (active != null){
                cfg.Active__c = active;
            }
            if (configSignature != null){
                cfg.ConfigSignature__c = configSignature;
            }
            if (recordType != null){
                cfg.RecordTypeId = recordType;
            }
            config.put(cfg.Name, cfg);
            return this;
        }

        public SurveyConfiguration__c build(){
            return config.values();
        }

        public SurveyConfiguration__c buildAndSave(){
            upsert config.values();
            return config.values();
        }

        public SurveyConfigBuilder setConfigSignature(String configName, String configSignature) {
            return setServiceConfig(configName, null, configSignature, null, true);
        }

        public SurveyConfigBuilder setConfigClass(String configName, String configClass) {
            return setServiceConfig(configName, configClass, null, null, true);
        }

        public SurveyConfigBuilder setQuestionProviderRecordType(String configName) {
            return setServiceConfig(configName, null, null, SurveyUtils.getSurveyConfigRecordType(SurveyUtils.SURVEY_CONFIGURATION_SURVEY_QUESTION_PROVIDER_RECORD_TYPE).Id, true);
        }

        public SurveyConfigBuilder setSurveyHandlerRecordType(String configName) {
            return setServiceConfig(configName, null, null, SurveyUtils.getSurveyConfigRecordType(SurveyUtils.SURVEY_CONFIGURATION_SURVEY_HANDLER_RECORD_TYPE).Id, true);
        }

        public Map<String, SurveyConfiguration__c> getConfigs(){
            return config;
        }
    }

    public class TemplateAccessBuilder {
        private SurveyTemplateAccesses__c record;

        public TemplateAccessBuilder(SurveyTemplate__c tamplate) {
            record = new SurveyTemplateAccesses__c(
                OnlyLeaders__c = true,
                SurveyTemplate__c = tamplate.Id
            );
        }

        public TemplateAccessBuilder withContact(Contact contact) {
            record.OnlyLeaders__c = false;
            record.Contact__c = contact.Id;
            return this;
        }

        public SurveyTemplateAccesses__c build() {
            return record;
        }

        public SurveyTemplateAccesses__c buildAndSave() {
            upsert record;
            return record;
        }
    }

    public class TemplateBuilder {

        protected SurveyTemplate__c record;
        protected List<SurveyTemplateItem__c> items = new List<SurveyTemplateItem__c>();

        public TemplateBuilder(String name) {
            record = new SurveyTemplate__c(
                Name = name,
                ApiName__c = name,
                Active__c = true,
                Description__c = 'Lorem ipsum',
                StartDate__c = System.today() - 7,
                EndDate__c = System.today() + 7,
                Importance__c = 'Medium',
                MultiSurvey__c = false,
                Private__c = false,
                Submittable__c = false,
                Config__c = '{}',
                SurveyHandler__c = createDefaultSurveyHandler('defaultName').config.get('defaultName').Id
            );
        }

        public SurveyTemplate__c buildAndSave() {
            upsert record;

            if (!items.isEmpty()) {
                for (SurveyTemplateItem__c item : items){
                    if (item.SurveyTemplate__c == null) {
                        item.SurveyTemplate__c = record.Id;
                        item.Config__c = '';
                        item.QuestionProvider__c = createDefaultQuestionProvider('defaultQuestionProvider').config.get('defaultQuestionProvider').Id;
                    }
                }
                upsert items;
            }

            return record;
        }

        public SurveyTemplate__c build() {
            return record;
        }

        public List<SurveyTemplateItem__c> getItems() {
            return items;
        }

        public TemplateBuilder withHandler(Id recordTypeId) {
            record.SurveyHandler__c = recordTypeId;
            return this;
        }

        public TemplateBuilder withNameAndApiName(String name) {
            record.Name = name;
            record.ApiName__c = name;
            return this;
        }

        public TemplateBuilder withConfig(String config) {
            record.Config__c = config;
            return this;
        }

        public TemplateBuilder deactivate() {
            record.Active__c = false;
            return this;
        }

        public TemplateBuilder fromFuture() {
            record.StartDate__c = Date.today() + 1;
            record.EndDate__c = Date.today() + 2;
            return this;
        }

        public TemplateBuilder fromPast() {
            record.StartDate__c = Date.today() - 2;
            record.EndDate__c = Date.today() - 1;
            return this;
        }

        public TemplateBuilder withActualDate() {
            record.StartDate__c = Date.today() - 1;
            record.EndDate__c = Date.today() + 1;
            return this;
        }

        public TemplateBuilder withStartDate(Date startDate) {
            record.StartDate__c = startDate;
            return this;
        }

        public TemplateBuilder withEndDate(Date endDate) {
            record.EndDate__c = endDate;
            return this;
        }

        public TemplateBuilder asMultisurvey() {
            record.MultiSurvey__c = true;
            return this;
        }

        public TemplateBuilder privateSurvey() {
            record.Private__c = true;
            return this;
        }

        public TemplateBuilder submittable() {
            record.Submittable__c = true;
            return this;
        }

        public TemplateBuilder addItem(SurveyTemplateItem__c item) {
            item.Order__c = items.size();
            items.add(item);
            return this;
        }
    }

    public virtual class TemplateItemBuilder {

        protected SurveyTemplateItem__c record;

        public TemplateItemBuilder() {}

        public TemplateItemBuilder(SurveyTemplate__c surveyTemplate, SurveyConfiguration__c questionProvider) {
            record = new SurveyTemplateItem__c(
                SurveyTemplate__c = surveyTemplate == null ? null : surveyTemplate.Id,
                QuestionProvider__c = questionProvider == null ? null : questionProvider.Id,
                Config__c = '',
                Order__c = 1
            );
        }

        public SurveyTemplateItem__c buildAndSave() {
            upsert record;
            return record;
        }

        public SurveyTemplateItem__c build() {
            return record;
        }

        public TemplateItemBuilder withOrder(Integer order) {
            record.Order__c = order;
            return this;
        }

        public TemplateItemBuilder withConfig(String config){
            record.Config__c = config;
            return this;
        }

        public TemplateItemBuilder withQuestionProvider(SurveyConfiguration__c provider){
            record.QuestionProvider__c = provider.Id;
            return this;
        }
    }
}