force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>Achievement</description>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Achievement_Category__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Category__c</fullName>
    <label>Achievement Category</label>
    <referenceTo>Achievement_Category__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement_Category__c/Achievement_Category__c.object-meta.xml
<CustomObject>
    <description>Achievement Category</description>
    <label>Achievement Category</label>
    <nameField>
        <label>Achievement Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set__c/Achievement_Set__c.object-meta.xml
<CustomObject>
    <description>Achievement Set</description>
    <label>Achievement Set</label>
    <nameField>
        <label>Achievement Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set__c/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact field is valid only for Contact Survey and Contact Profile record types</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/recordTypes/Survey.recordType-meta.xml
<RecordType>
    <fullName>Survey</fullName>
    <active>true</active>
    <description>Ankieta opisująca umiejętności pracownika</description>
    <label>Survey</label>
</RecordType>

force-app/main/default/objects/Career_Path__c/Career_Path__c.object-meta.xml
<CustomObject>
    <label>Career Path</label>
    <nameField>
        <label>Career Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Career Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SkillAssessment__c.field-meta.xml
<CustomField>
    <fullName>SkillAssessment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skill Assessment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/SurveyTemplate__c.object-meta.xml
<CustomObject>
    <label>Survey Template</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplate__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <label>Api Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SurveyTemplateAccesses__c/SurveyTemplateAccesses__c.object-meta.xml
<CustomObject>
    <label>Survey Template Access</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SurveyTemplateAccesses Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Template Accesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplateAccesses__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Template Accesses</relationshipLabel>
    <relationshipName>SurveyTemplateAccesses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateAccesses__c/fields/SurveyTemplate__c.field-meta.xml
<CustomField>
    <fullName>SurveyTemplate__c</fullName>
    <label>Survey Template</label>
    <referenceTo>SurveyTemplate__c</referenceTo>
    <relationshipLabel>Survey Template Accesses</relationshipLabel>
    <relationshipName>SurveyTemplateAccesses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/SurveyTemplateItem__c.object-meta.xml
<CustomObject>
    <label>Survey Template Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplateItem__c/fields/SurveyTemplate__c.field-meta.xml
<CustomField>
    <fullName>SurveyTemplate__c</fullName>
    <label>Survey Template</label>
    <referenceTo>SurveyTemplate__c</referenceTo>
    <relationshipLabel>Survey Template Items</relationshipLabel>
    <relationshipName>SurveyTemplateItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SurveyControllerTest.cls
@isTest
private class SurveyControllerTest {
    static final private String SFCD_URL = 'https://eu6.force.com';

    @isTest
    static private void shouldGetTemplatesInfo() {
        //GIVEN
        SurveyTemplate__c template = prepateTemplate();
        Contact contact = prepareUser(template);
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String url = SFCD_URL+'/services/apexrest/survey/gettemplatesinfo/'+contact.Email;

        //WHEN
        List<SurveyModel.TemplateInfo> templates = (List<SurveyModel.TemplateInfo>) JSON.deserialize(getResponse(url), List<SurveyModel.TemplateInfo>.class) ;

        //THEN
        System.assertEquals('surveytemplatetest', templates[0].name);
    }

    @isTest
    static private void shouldGetTemplate() {
        //GIVEN
        SurveyTemplate__c surveyTemplate = prepateTemplate();
        Contact contact = prepareUser(surveyTemplate);
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String url = SFCD_URL+'/services/apexrest/survey/gettemplate/'+contact.Email+'/surveytemplatetest';

        //WHEN
        SurveyModel.Template template = (SurveyModel.Template) JSON.deserialize(getResponse(url), SurveyModel.Template.class) ;

        //THEN
        System.assertEquals('surveytemplatetest', template.name);
        System.assertEquals(5, template.questions.size());
    }

    @isTest
    static private void shouldGetSurvey() {
        //GIVEN
        SurveyTemplate__c template = prepateTemplate();
        Contact contact = prepareUser(template);
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        Double minSpecialityMatch = 0.30;
        Map<ID, Achievement_Set__c> contactIdToAchievementSetMap  = new Map<ID, Achievement_Set__c>();
        for (Achievement_Set__c cpp : [SELECT Contact__c, Name FROM Achievement_Set__c WHERE Contact__c =: contact.Id]) {
            contactIdToAchievementSetMap.put(cpp.Contact__c, cpp);
        }
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(contact.Id))
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .addSpecialization(achievements[4], minSpecialityMatch)
            .buildAndSave();
        String url = SFCD_URL+'/services/apexrest/survey/getsurvey/'+contact.Email+'/surveytemplatetest/'+achievementSet.Id;

        //WHEN
        SurveyModel.Survey survey = (SurveyModel.Survey) JSON.deserialize(getResponse(url), SurveyModel.Survey.class) ;

        //THEN
        System.assertEquals('test test - Employee Profile', survey.name);
        System.assertEquals('test@test.pl', survey.userId);
        System.assertEquals(5, survey.answers.size());
    }

    @isTest
    static private void shouldSaveSurvey() {
        //GIVEN
        SurveyTemplate__c template = prepateTemplate();
        Contact contact = prepareUser(template);
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        Double minSpecialityMatch = 0.30;
        Map<ID, Achievement_Set__c> contactIdToAchievementSetMap  = new Map<ID, Achievement_Set__c>();
        for (Achievement_Set__c cpp : [SELECT Contact__c, Name FROM Achievement_Set__c WHERE Contact__c =: contact.Id]) {
            contactIdToAchievementSetMap.put(cpp.Contact__c, cpp);
        }
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(contact.Id))
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .addSpecialization(achievements[4], minSpecialityMatch)
            .buildAndSave();
        String url = SFCD_URL+'/services/apexrest/survey';
        SurveyUtils.SurveyRequest request = new SurveyUtils.SurveyRequest(contact.Email, template.ApiName__c, achievementSet.Id);
        SurveyModel.Survey survey = SurveyFrontController.getInstance().getSurvey(request);

        //WHEN
        SurveyModel.Survey surveyResponse = (SurveyModel.Survey) JSON.deserialize(getResponse(url, JSON.serialize(survey)), SurveyModel.Survey.class) ;

        //THEN
        System.assertEquals('test test - Employee Profile', surveyResponse.name);
        System.assertEquals('test@test.pl', surveyResponse.userId);
        System.assertEquals(5, surveyResponse.answers.size());
    }

    static private String getResponse(String url) {
        System.RestContext.request = new RestRequest();
        RestContext.request.requestURI = url;
        return SurveyController.getData();
    }

    static private String getResponse(String url, String post) {
        System.RestContext.request = new RestRequest();
        RestContext.request.requestURI = url;
        RestContext.request.httpMethod = 'POST';
        RestContext.request.requestBody = Blob.valueof(post);
        return SurveyController.saveSurvey();
    }

    static private List<Achievement__c> createAchievmentWithCategory(String name) {
        Achievement_Category__c category = new AchievementUtils.AchievementCategoryBuilder(name+'SurveyControllerTest').buildAndSave();
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPathAchievementSurveyControllerTest').buildAndSave();
        Achievement_Set__c achievementSet = new AchievementUtils.AchievementSetBuilder('Specjalization SurveyControllerTest').asProfile(careerPath).buildAndSave();
        List<Achievement__c> achievements = new List<Achievement__c>{
            new AchievementUtils.AchievementBuilder('AchievementSkill SurveyControllerTest', category).asSkill().build(),
            new AchievementUtils.AchievementBuilder('AchievementCertificate SurveyControllerTest', category).asCert().build(),
            new AchievementUtils.AchievementBuilder('AchievementBadge SurveyControllerTest', category).asBadge().build(),
            new AchievementUtils.AchievementBuilder('AchievementGroup SurveyControllerTest', category).asGroup().build(),
            new AchievementUtils.AchievementBuilder('AchievementSpecialization SurveyControllerTest', category).asSpecialization(achievementSet).build()
        };
        insert achievements;
        return achievements;
    }

    static private List<SurveyTestUtils.SurveyConfigBuilder> createConfig(String providerName, String handlerName, String configClassProvider, String configClassHandler) {
        String configSignature = '{}';
        Id providerRecordTypeId = SurveyUtils.getSurveyConfigRecordType(SurveyUtils.SURVEY_CONFIGURATION_SURVEY_QUESTION_PROVIDER_RECORD_TYPE).Id;
        Id handlerRecordTypeId = SurveyUtils.getSurveyConfigRecordType(SurveyUtils.SURVEY_CONFIGURATION_SURVEY_HANDLER_RECORD_TYPE).Id;

        return new List <SurveyTestUtils.SurveyConfigBuilder> {
            new SurveyTestUtils.SurveyConfigBuilder().setServiceConfig(providerName, configClassProvider, configSignature, providerRecordTypeId, true),
            new SurveyTestUtils.SurveyConfigBuilder().setServiceConfig(handlerName, configClassHandler, configSignature, handlerRecordTypeId, true)
        };

    }

    static private SurveyTemplate__c  prepateTemplate () {
        String configClassProvider = 'AchievementSurveyUtils.AchievementEmployeeProfileQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementEmployeeProfileHandler';
        String providerName = 'questionProviderSurveyControllerTest';
        String handlerName = 'surveyHandlerSurveyControllerTest';
        String configSignature = '{}';
        String templateConfig = '{}';
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        List<SurveyTestUtils.SurveyConfigBuilder> cfgs = createConfig(providerName, handlerName, configClassProvider, configClassHandler);
        cfgs[0].buildAndSave();
        cfgs[1].buildAndSave();
        SurveyTemplate__c template = new SurveyTestUtils.TemplateBuilder('surveytemplatetest').withHandler(cfgs[1].getConfigs().get(handlerName).Id).withConfig(templateConfig).buildAndSave();
        SurveyTemplateItem__c templateItem = new SurveyTestUtils.TemplateItemBuilder(template, cfgs[0].getConfigs().get(providerName)).withConfig(templateItemConfig).buildAndSave();
        return template;
    }

    static private Contact prepareUser(SurveyTemplate__c template) {
        Contact contact = new Contact(FirstName = 'test', LastName = 'test', Email='test@test.pl', SkillAssessment__c = true);
        insert contact;

        SurveyTemplateAccesses__c access = new SurveyTemplateAccesses__c(Contact__c=contact.Id, SurveyTemplate__c=template.Id);
        insert access;

        return contact;
    }
}