force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>Achievement</description>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Achievement_Category__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Category__c</fullName>
    <label>Achievement Category</label>
    <referenceTo>Achievement_Category__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Achievement_Category__c/Achievement_Category__c.object-meta.xml
<CustomObject>
    <description>Achievement Category</description>
    <label>Achievement Category</label>
    <nameField>
        <label>Achievement Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Category__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AchievementAccess__c/AchievementAccess__c.object-meta.xml
<CustomObject>
    <label>Achievement Access</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Achievements Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AchievementsAccess</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AchievementAccess__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>AchievementsAccess</relationshipLabel>
    <relationshipName>AchievementsAccess</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SkillAssessment__c.field-meta.xml
<CustomField>
    <fullName>SkillAssessment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skill Assessment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AchievementAccessTriggerTest.cls
@IsTest
private class AchievementAccessTriggerTest {

    @isTest
    private static void shouldSetAccessToLeaders() {
        //GIVEN
        Achievement_Category__c cat = new AchievementUtils.AchievementCategoryBuilder('AchievementAccessCategory').buildAndSave();
        Achievement__c achievement = new AchievementUtils.AchievementBuilder('Achievement', cat).asSkill().buildAndSave();

        //WHEN
        new AchievementUtils.AchievementAccessBuilder(achievement).onlyLeader().buildAndSave();

        //THEN
        AchievementAccess__c achievementAccess = [SELECT ExternalId__c FROM AchievementAccess__c LIMIT 1];
        System.assertEquals('Achievement#true', achievementAccess.ExternalId__c);
    }

    @isTest
    private static void shouldSetAccessToContact() {
        //GIVEN
        Contact c = new Contact(FirstName='Bruce', LastName='Wayne', Email='b.w@xample.com', SkillAssessment__c=true);
        insert c;
        Achievement_Category__c cat = new AchievementUtils.AchievementCategoryBuilder('AchievementAccessCategory').buildAndSave();
        Achievement__c achievement = new AchievementUtils.AchievementBuilder('Achievement', cat).asSkill().buildAndSave();

        //WHEN
        new AchievementUtils.AchievementAccessBuilder(achievement).withContact(c).buildAndSave();

        //THEN
        AchievementAccess__c achievementAccess = [SELECT ExternalId__c FROM AchievementAccess__c LIMIT 1];
        System.assertEquals('Achievement#b.w@xample.com', achievementAccess.ExternalId__c);
    }


}