force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>Achievement</description>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Achievement_Category__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Category__c</fullName>
    <label>Achievement Category</label>
    <referenceTo>Achievement_Category__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Achievement_Category__c/Achievement_Category__c.object-meta.xml
<CustomObject>
    <description>Achievement Category</description>
    <label>Achievement Category</label>
    <nameField>
        <label>Achievement Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Category__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/SurveyTemplate__c.object-meta.xml
<CustomObject>
    <label>Survey Template</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplate__c/fields/Config__c.field-meta.xml
<CustomField>
    <fullName>Config__c</fullName>
    <label>Config</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/SurveyTemplateItem__c.object-meta.xml
<CustomObject>
    <label>Survey Template Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplateItem__c/fields/SurveyTemplate__c.field-meta.xml
<CustomField>
    <fullName>SurveyTemplate__c</fullName>
    <label>Survey Template</label>
    <referenceTo>SurveyTemplate__c</referenceTo>
    <relationshipLabel>Survey Template Items</relationshipLabel>
    <relationshipName>SurveyTemplateItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SurveyRenameExternalIdTest.cls
@isTest
private class SurveyRenameExternalIdTest
{
    @isTest
    static void itShouldRenameAchievementExternalIdTemplateItem()
    {
        Test.startTest();
        // Given
        String configClassProvider = 'AchievementSurveyUtils.AchievementPositionProfileQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementPositionProfileHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentExternalId":"' + achievements[0].ExternalId__c + '","getAll":"false"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig);

        // When
        achievements[0].Name = 'New name';
        update achievements;
        Test.stopTest();

        // Then
        List<SurveyTemplateItem__c> surveyTemplateItem = [SELECT Config__c FROM SurveyTemplateItem__c];
        Map<String, Object> config = (Map<String, Object>) JSON.deserializeUntyped(surveyTemplateItem[0].Config__c);
        System.assertEquals('New name', (String) config.get(AchievementSurveyUtils.ACHIEVMENT_EXTERNALID_CONF_KEY));
    }

    @isTest
    static void itShouldRenameCategoryExternalIdTemplateItem()
    {
        Test.startTest();
        // Given
        String configClassProvider = 'AchievementSurveyUtils.AchievementSurveyQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementSurveyHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        Achievement_Category__c category = [SELECT Id, Name, ExternalId__c FROM Achievement_Category__c LIMIT 1];
        String templateItemConfig = '{"achievmentExternalId":"", "categoryExternalId":"' + category.ExternalId__c + '","getAll":"false", "email": "false"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig);

        // When
        category.Name = 'New category';
        update category;
        Test.stopTest();

        // Then
        List<SurveyTemplateItem__c> surveyTemplateItem = [SELECT Config__c FROM SurveyTemplateItem__c];
        Map<String, Object> config = (Map<String, Object>) JSON.deserializeUntyped(surveyTemplateItem[0].Config__c);
        System.assertEquals('New category', (String) config.get(AchievementSurveyUtils.CATEGORY_EXTERNALID_CONF_KEY));
    }

    static private List<Achievement__c> createAchievmentWithCategory(String name) {
        Achievement_Category__c category = new AchievementUtils.AchievementCategoryBuilder(name+'SurveyRenameExternalIdTest').buildAndSave();
        new AchievementUtils.AchievementBuilder('AchievementSkill', category).asSkill().buildAndSave();
        return [SELECT Id, Name, ExternalId__c FROM Achievement__c];
    }

    static private List<SurveyTestUtils.SurveyConfigBuilder> createConfig(String providerName, String handlerName, String configClassProvider, String configClassHandler) {
        String configSignature = '{}';
        Id providerRecordTypeId = SurveyUtils.getSurveyConfigRecordType(SurveyUtils.SURVEY_CONFIGURATION_SURVEY_QUESTION_PROVIDER_RECORD_TYPE).Id;
        Id handlerRecordTypeId = SurveyUtils.getSurveyConfigRecordType(SurveyUtils.SURVEY_CONFIGURATION_SURVEY_HANDLER_RECORD_TYPE).Id;

        return new List <SurveyTestUtils.SurveyConfigBuilder> {
            new SurveyTestUtils.SurveyConfigBuilder().setServiceConfig(providerName, configClassProvider, configSignature, providerRecordTypeId, true),
            new SurveyTestUtils.SurveyConfigBuilder().setServiceConfig(handlerName, configClassHandler, configSignature, handlerRecordTypeId, true)
        };
    }

    static private SurveyTemplate__c  prepateTemplate (String configClassProvider, String configClassHandler, String templateConfig, String templateItemConfig) {
        String providerName = 'questionProviderSurveyRenameExternalIdTest';
        String handlerName = 'surveyHandlerSurveyRenameExternalIdTest';
        String configSignature = '{}';
        List<SurveyTestUtils.SurveyConfigBuilder> cfgs = createConfig(providerName, handlerName, configClassProvider, configClassHandler);
        cfgs[0].buildAndSave();
        cfgs[1].buildAndSave();
        SurveyTemplate__c template = new SurveyTestUtils.TemplateBuilder('surveytemplatetest').withHandler(cfgs[1].getConfigs().get(handlerName).Id).withConfig(templateConfig).buildAndSave();
        SurveyTemplateItem__c templateItem = new SurveyTestUtils.TemplateItemBuilder(template, cfgs[0].getConfigs().get(providerName)).withConfig(templateItemConfig).buildAndSave();
        return template;
    }
}