force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>Achievement</description>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Achievement_Category__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Category__c</fullName>
    <label>Achievement Category</label>
    <referenceTo>Achievement_Category__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement__c/recordTypes/Badge.recordType-meta.xml
<RecordType>
    <fullName>Badge</fullName>
    <active>true</active>
    <description>Odznaka - współczynnik ilościowy</description>
    <label>Badge</label>
</RecordType>

force-app/main/default/objects/Achievement__c/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <description>Zbiór umiejętności.</description>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/Achievement__c/recordTypes/Skill.recordType-meta.xml
<RecordType>
    <fullName>Skill</fullName>
    <active>true</active>
    <description>Umiejętność określana jakościowo za pomocą trzy stopniowej skali</description>
    <label>Skill</label>
</RecordType>

force-app/main/default/objects/Achievement__c/recordTypes/Specialization.recordType-meta.xml
<RecordType>
    <fullName>Specialization</fullName>
    <active>true</active>
    <description>Specializacja</description>
    <label>Specialization</label>
</RecordType>

force-app/main/default/objects/Achievement_Category__c/Achievement_Category__c.object-meta.xml
<CustomObject>
    <description>Achievement Category</description>
    <label>Achievement Category</label>
    <nameField>
        <label>Achievement Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set__c/Achievement_Set__c.object-meta.xml
<CustomObject>
    <description>Achievement Set</description>
    <label>Achievement Set</label>
    <nameField>
        <label>Achievement Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set__c/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/Achievement_Set_Item__c.object-meta.xml
<CustomObject>
    <description>Achievement Set Item</description>
    <label>Achievement Set Item</label>
    <nameField>
        <displayFormat>ASI{00000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Set Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipName>Position_Profile_Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Achievement_Set__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Set__c</fullName>
    <label>Achievement Set</label>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Min_Speciality_Match__c.field-meta.xml
<CustomField>
    <fullName>Min_Speciality_Match__c</fullName>
    <defaultValue>1.0</defaultValue>
    <label>Min. Speciality Match</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/NumberOfMonths__c.field-meta.xml
<CustomField>
    <fullName>NumberOfMonths__c</fullName>
    <formula>((YEAR(Today()) - YEAR(DATEVALUE(Date__c))-1) * 12) + (12 - MONTH(DATEVALUE(Date__c))+1) + MONTH(Today())</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number Of Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Career_Path__c/Career_Path__c.object-meta.xml
<CustomObject>
    <label>Career Path</label>
    <nameField>
        <label>Career Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Career Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AchievementTest.cls
/**
 * Achievement class tests
 * @author Adam Siwek
 */
@isTest
private class AchievementTest {

    @isTest
    private static void testTheInvalidConstructorAtritbutes() {
        Achievement_Category__c base = new AchievementUtils.AchievementCategoryBuilder('Base Category').buildAndSave();
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('Career Path 1').buildAndSave();

        Achievement__c skill1 = new AchievementUtils.AchievementBuilder('Skill1', base).asSkill().buildAndSave();
        Achievement__c skill2 = new AchievementUtils.AchievementBuilder('Skill2', base).asSkill().buildAndSave();

        Achievement_Set__c pp1 = new AchievementUtils.AchievementSetBuilder('Junior Java Developer').asPositionProfile(careerPath).
                addSkill(skill1, AchievementUtils.ACHIEVEMENT_LEVEL_1).buildAndSave();
        Achievement_Set__c pp2 = new AchievementUtils.AchievementSetBuilder('Senior Java Developer').asPositionProfile(careerPath).
                addSkill(skill2, AchievementUtils.ACHIEVEMENT_LEVEL_3).buildAndSave();

        try {
            new Achievement(skill1, null);
            System.assert(false, 'Should not create class instance when achievement set item is not set');
        } catch (SystemUtils.SystemException ex) {}

        try {
            new Achievement(null, [SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c FROM Achievement_Set_Item__c LIMIT 1]);
            System.assert(false, 'Should not create class instance when achievement is not set');
        } catch (SystemUtils.SystemException ex) {}

        try {
            new Achievement(skill1, [SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c FROM Achievement_Set_Item__c WHERE Achievement__c != :skill1.Id LIMIT 1]);
            System.assert(false, 'Should not create class instance when achievement is not related with the achievement set item');
        } catch (SystemUtils.SystemException ex) {}
    }

    @isTest
    private static void testTheInvalidRecordToCompare() {
        Achievement_Category__c base = new AchievementUtils.AchievementCategoryBuilder('Base Category').buildAndSave();
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('Career Path 1').buildAndSave();

        Achievement__c skill1 = new AchievementUtils.AchievementBuilder('Skill1', base).asSkill().buildAndSave();
        Achievement__c skill2 = new AchievementUtils.AchievementBuilder('Skill2', base).asSkill().buildAndSave();

        Achievement_Set__c pp1 = new AchievementUtils.AchievementSetBuilder('Junior Java Developer').asPositionProfile(careerPath).
                addSkill(skill1, AchievementUtils.ACHIEVEMENT_LEVEL_1).buildAndSave();
        Achievement_Set__c pp2 = new AchievementUtils.AchievementSetBuilder('Senior Java Developer').asPositionProfile(careerPath).
                addSkill(skill2, AchievementUtils.ACHIEVEMENT_LEVEL_3).buildAndSave();

        Achievement wrapper = new Achievement(skill1, [SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c FROM Achievement_Set_Item__c WHERE Achievement__c = :skill1.Id LIMIT 1]);
        try {
            wrapper.setDataToCmp(null);
            System.assert(false, 'Data to compare cannot be null');
        } catch (SystemUtils.SystemException ex) {}

        try {
            wrapper.setDataToCmp([SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c FROM Achievement_Set_Item__c WHERE Achievement__c != :skill1.Id LIMIT 1]);
            System.assert(false, 'Data to compare cannot be ralated to different achievent');
        } catch (SystemUtils.SystemException ex) {}
    }

    @isTest
    private static void shouldReturnValidValues() {
        Achievement_Category__c base = new AchievementUtils.AchievementCategoryBuilder('Base Category').buildAndSave();
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('Career Path 1').buildAndSave();

        Achievement_Set__c specializationAchievementSet = new AchievementUtils.AchievementSetBuilder('Specialization').asProfile(careerPath).buildAndSave();

        Achievement__c skill = new AchievementUtils.AchievementBuilder('Skill', base).asSkill().build();
        Achievement__c cert = new AchievementUtils.AchievementBuilder('Cert1', base).asCert().build();
        Achievement__c badge = new AchievementUtils.AchievementBuilder('Badge1', base).asBadge().build();
        Achievement__c groupAch = new AchievementUtils.AchievementBuilder('Group', base).asGroup().build();
        Achievement__c specialization = new AchievementUtils.AchievementBuilder('Specialization', base).asSpecialization(specializationAchievementSet).build();
        insert new Achievement__c[] {skill, cert, badge, groupAch, specialization};

        Achievement_Set__c pp = new AchievementUtils.AchievementSetBuilder('Senior Java Developer').
                asPositionProfile(careerPath).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_2).
                addCert(cert).
                addBadge(badge, 2).
                addGroup(groupAch, 1).
                addSpecialization(specialization, 0.3.doubleValue()).
                buildAndSave();

        Achievement wrapper = new Achievement(skill, [SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c FROM Achievement_Set_Item__c WHERE Achievement__c = :skill.Id LIMIT 1]);
        System.assertEquals(AchievementUtils.ACHIEVEMENT_LEVEL_2, wrapper.level);
        System.assertEquals(skill.Name, wrapper.getName());
        System.assertEquals(true, wrapper.getIsSkill());
        System.assertEquals(false, wrapper.getIsCert());
        System.assertEquals(false, wrapper.getIsGroup());
        System.assertEquals(false, wrapper.getIsBadge());
        System.assertEquals(false, wrapper.getIsNew());
        System.assertEquals(true, wrapper.getHasValue());
        System.assertEquals(false, wrapper.getHasDifferentValue());
        System.assertEquals('', wrapper.getDifferenceInfo());

        wrapper = new Achievement(badge, [SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c FROM Achievement_Set_Item__c WHERE Achievement__c = :badge.Id LIMIT 1]);
        System.assertEquals('2', wrapper.amount);
        System.assertEquals(badge.Name, wrapper.getName());
        System.assertEquals(false, wrapper.getIsSkill());
        System.assertEquals(false, wrapper.getIsCert());
        System.assertEquals(true, wrapper.getIsBadge());
        System.assertEquals(false, wrapper.getIsGroup());
        System.assertEquals(false, wrapper.getIsSpecialization());
        System.assertEquals(false, wrapper.getIsNew());
        System.assertEquals(true, wrapper.getHasValue());
        System.assertEquals(false, wrapper.getHasDifferentValue());
        System.assertEquals('', wrapper.getDifferenceInfo());

        wrapper = new Achievement(cert, [SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c FROM Achievement_Set_Item__c WHERE Achievement__c = :cert.Id LIMIT 1]);
        System.assertEquals(true, wrapper.selected);
        System.assertEquals(cert.Name, wrapper.getName());
        System.assertEquals(false, wrapper.getIsSkill());
        System.assertEquals(true, wrapper.getIsCert());
        System.assertEquals(false, wrapper.getIsBadge());
        System.assertEquals(false, wrapper.getIsGroup());
        System.assertEquals(false, wrapper.getIsSpecialization());
        System.assertEquals(false, wrapper.getIsNew());
        System.assertEquals(true, wrapper.getHasValue());
        System.assertEquals(false, wrapper.getHasDifferentValue());
        System.assertEquals('', wrapper.getDifferenceInfo());

        wrapper = new Achievement(groupAch, [SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c FROM Achievement_Set_Item__c WHERE Achievement__c = :groupAch.Id LIMIT 1]);
        System.assertEquals('1', wrapper.amount);
        System.assertEquals(groupAch.Name, wrapper.getName());
        System.assertEquals(false, wrapper.getIsSkill());
        System.assertEquals(false, wrapper.getIsCert());
        System.assertEquals(false, wrapper.getIsBadge());
        System.assertEquals(true, wrapper.getIsGroup());
        System.assertEquals(false, wrapper.getIsSpecialization());
        System.assertEquals(false, wrapper.getIsNew());
        System.assertEquals(true, wrapper.getHasValue());
        System.assertEquals(false, wrapper.getHasDifferentValue());
        System.assertEquals('', wrapper.getDifferenceInfo());

        wrapper = new Achievement(specialization, [SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c FROM Achievement_Set_Item__c WHERE Achievement__c = :specialization.Id LIMIT 1]);
        System.assertEquals('0.30', wrapper.minSpecialityMatch);
        System.assertEquals(specialization.Name, wrapper.getName());
        System.assertEquals(false, wrapper.getIsSkill());
        System.assertEquals(false, wrapper.getIsCert());
        System.assertEquals(false, wrapper.getIsBadge());
        System.assertEquals(false, wrapper.getIsGroup());
        System.assertEquals(true, wrapper.getIsSpecialization());
        System.assertEquals(false, wrapper.getIsNew());
        System.assertEquals(true, wrapper.getHasValue());
        System.assertEquals(false, wrapper.getHasDifferentValue());
        System.assertEquals('', wrapper.getDifferenceInfo());
    }


    @isTest
    private static void shouldDetermineDifferences() {
        Achievement_Category__c base = new AchievementUtils.AchievementCategoryBuilder('Base Category').buildAndSave();
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('Career Path 1').buildAndSave();

        Achievement__c skill = new AchievementUtils.AchievementBuilder('Skill', base).asSkill().build();
        Achievement__c cert = new AchievementUtils.AchievementBuilder('Cert1', base).asCert().build();
        Achievement__c badge = new AchievementUtils.AchievementBuilder('Badge1', base).asBadge().build();
        insert new Achievement__c[] {skill, cert, badge};

        Achievement_Set__c pp1 = new AchievementUtils.AchievementSetBuilder('Junior Java Developer').
                asPositionProfile(careerPath).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_2).
                addBadge(badge, 2).
                buildAndSave();
        Achievement_Set__c pp2 = new AchievementUtils.AchievementSetBuilder('Senior Java Developer').
                asProfile(careerPath).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_2).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_3).
                addCert(cert).
                addBadge(badge, 3).
                buildAndSave();

        Achievement wrapper = new Achievement(skill, [SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c, NumberOfMonths__c FROM Achievement_Set_Item__c WHERE Achievement__c = :skill.Id AND Achievement_Set__c =:pp1.Id LIMIT 1]);
        wrapper.setDataToCmp([SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c, NumberOfMonths__c FROM Achievement_Set_Item__c WHERE Achievement__c = :skill.Id AND Achievement_Set__c =:pp2.Id LIMIT 1]);
        wrapper.level = AchievementUtils.ACHIEVEMENT_LEVEL_1;
        System.assertEquals(true, wrapper.getHasDifferentValue());
        System.assertEquals(true, wrapper.getHasDifferentLevel());
        System.assertNotEquals('', wrapper.getDifferenceInfo());

        wrapper = new Achievement(badge, [SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c, NumberOfMonths__c FROM Achievement_Set_Item__c WHERE Achievement__c = :badge.Id AND Achievement_Set__c =:pp1.Id LIMIT 1]);
        wrapper.setDataToCmp([SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c, NumberOfMonths__c FROM Achievement_Set_Item__c WHERE Achievement__c = :badge.Id AND Achievement_Set__c =:pp2.Id LIMIT 1]);
        wrapper.amount = '1';
        System.assertEquals(true, wrapper.getHasDifferentValue());
        System.assertEquals(true, wrapper.getHasDifferentAmount());
        System.assertNotEquals('', wrapper.getDifferenceInfo());

        wrapper = new Achievement(cert, new Achievement_Set_Item__c(Achievement__c=cert.Id));
        wrapper.setDataToCmp([SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c, NumberOfMonths__c FROM Achievement_Set_Item__c WHERE Achievement__c = :cert.Id AND Achievement_Set__c =:pp2.Id LIMIT 1]);
        System.assertEquals(true, wrapper.getHasDifferentValue());
        System.assertEquals('', wrapper.getDifferenceInfo());
        System.assertEquals(false, wrapper.getHasCert());
    }

    @isTest
    private static void shouldGetDescriptionWhenAchievementIsSkill() {
        Achievement_Category__c base = new AchievementUtils.AchievementCategoryBuilder('Base Category').buildAndSave();
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('Career Path 1').buildAndSave();
        Achievement__c skill = new AchievementUtils.AchievementBuilder('Skill', base).asSkill().buildAndSave();
        Achievement_Set__c achievementSet = new AchievementUtils.AchievementSetBuilder('Junior Java Developer').
                asPositionProfile(careerPath).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_2).
                buildAndSave();
        Achievement a = new Achievement(skill, [SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c, NumberOfMonths__c FROM Achievement_Set_Item__c WHERE Achievement__c = :skill.Id AND Achievement_Set__c =:achievementSet.Id LIMIT 1]);

        System.assertEquals('Skill\nJunior - \nProfessional - \nSenior - ', a.getDescription());
    }

    @isTest
    private static void shouldGetEmptyDescriptionWhenAchievementIsNotSkill() {
        Achievement_Category__c base = new AchievementUtils.AchievementCategoryBuilder('Base Category').buildAndSave();
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('Career Path 1').buildAndSave();
        Achievement__c badge = new AchievementUtils.AchievementBuilder('Badge1', base).asBadge().buildAndSave();
        Achievement_Set__c achievementSet = new AchievementUtils.AchievementSetBuilder('Junior Java Developer').
                asPositionProfile(careerPath).
                addBadge(badge, 2).
                buildAndSave();
        Achievement a = new Achievement(badge, [SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c, NumberOfMonths__c FROM Achievement_Set_Item__c WHERE Achievement__c = :badge.Id AND Achievement_Set__c =:achievementSet.Id LIMIT 1]);

        System.assertEquals('Badge1', a.getDescription());
    }

    @isTest
    private static void shouldGetHTMLDescriptionWhenAchievementIsSkill() {
        Achievement_Category__c base = new AchievementUtils.AchievementCategoryBuilder('Base Category').buildAndSave();
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('Career Path 1').buildAndSave();
        Achievement__c skill = new AchievementUtils.AchievementBuilder('Skill', base).asSkill().buildAndSave();
        Achievement_Set__c achievementSet = new AchievementUtils.AchievementSetBuilder('Junior Java Developer').
                asPositionProfile(careerPath).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_2).
                buildAndSave();
        Achievement a = new Achievement(skill, [SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c, NumberOfMonths__c FROM Achievement_Set_Item__c WHERE Achievement__c = :skill.Id AND Achievement_Set__c =:achievementSet.Id LIMIT 1]);

        System.assertEquals('<h2>Skill</h2><br><b>Junior</b> - <br><b>Professional</b> - <br><b>Senior</b> - ', a.getHTMLDescription());
    }

    @isTest
    private static void shouldGetEmptyHTMLDescriptionWhenAchievementIsNotSkill() {
        Achievement_Category__c base = new AchievementUtils.AchievementCategoryBuilder('Base Category').buildAndSave();
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('Career Path 1').buildAndSave();
        Achievement__c badge = new AchievementUtils.AchievementBuilder('Badge1', base).asBadge().buildAndSave();
        Achievement_Set__c achievementSet = new AchievementUtils.AchievementSetBuilder('Junior Java Developer').
                asPositionProfile(careerPath).
                addBadge(badge, 2).
                buildAndSave();
        Achievement a = new Achievement(badge, [SELECT Achievement__c, Level__c, Amount__c, Min_Speciality_Match__c, NumberOfMonths__c FROM Achievement_Set_Item__c WHERE Achievement__c = :badge.Id AND Achievement_Set__c =:achievementSet.Id LIMIT 1]);

        System.assertEquals('<h2>Badge1</h2>', a.getHTMLDescription());
    }
}