force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>Achievement</description>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Achievement_Category__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Category__c</fullName>
    <label>Achievement Category</label>
    <referenceTo>Achievement_Category__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Achievement__c/recordTypes/Specialization.recordType-meta.xml
<RecordType>
    <fullName>Specialization</fullName>
    <active>true</active>
    <description>Specializacja</description>
    <label>Specialization</label>
</RecordType>

force-app/main/default/objects/Achievement_Category__c/Achievement_Category__c.object-meta.xml
<CustomObject>
    <description>Achievement Category</description>
    <label>Achievement Category</label>
    <nameField>
        <label>Achievement Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Category__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/Achievement_Set__c.object-meta.xml
<CustomObject>
    <description>Achievement Set</description>
    <label>Achievement Set</label>
    <nameField>
        <label>Achievement Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set__c/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact field is valid only for Contact Survey and Contact Profile record types</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/recordTypes/Survey.recordType-meta.xml
<RecordType>
    <fullName>Survey</fullName>
    <active>true</active>
    <description>Ankieta opisująca umiejętności pracownika</description>
    <label>Survey</label>
</RecordType>

force-app/main/default/objects/Achievement_Set_Item__c/Achievement_Set_Item__c.object-meta.xml
<CustomObject>
    <description>Achievement Set Item</description>
    <label>Achievement Set Item</label>
    <nameField>
        <displayFormat>ASI{00000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Set Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipName>Position_Profile_Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Achievement_Set__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Set__c</fullName>
    <label>Achievement Set</label>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/LevelValue__c.field-meta.xml
<CustomField>
    <fullName>LevelValue__c</fullName>
    <label>LevelValue</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>Achievement__r.RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Career_Path__c/Career_Path__c.object-meta.xml
<CustomObject>
    <label>Career Path</label>
    <nameField>
        <label>Career Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Career Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SkillAssessment__c.field-meta.xml
<CustomField>
    <fullName>SkillAssessment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skill Assessment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Analytic</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/SurveyTemplate__c.object-meta.xml
<CustomObject>
    <label>Survey Template</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplate__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <label>Api Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SurveyTemplate__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SurveyTemplateAccesses__c/SurveyTemplateAccesses__c.object-meta.xml
<CustomObject>
    <label>Survey Template Access</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SurveyTemplateAccesses Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Template Accesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplateAccesses__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Template Accesses</relationshipLabel>
    <relationshipName>SurveyTemplateAccesses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateAccesses__c/fields/SurveyTemplate__c.field-meta.xml
<CustomField>
    <fullName>SurveyTemplate__c</fullName>
    <label>Survey Template</label>
    <referenceTo>SurveyTemplate__c</referenceTo>
    <relationshipLabel>Survey Template Accesses</relationshipLabel>
    <relationshipName>SurveyTemplateAccesses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SurveyTemplateItem__c/SurveyTemplateItem__c.object-meta.xml
<CustomObject>
    <label>Survey Template Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyTemplateItem__c/fields/SurveyTemplate__c.field-meta.xml
<CustomField>
    <fullName>SurveyTemplate__c</fullName>
    <label>Survey Template</label>
    <referenceTo>SurveyTemplate__c</referenceTo>
    <relationshipLabel>Survey Template Items</relationshipLabel>
    <relationshipName>SurveyTemplateItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AchievementSurveyUtilsTest.cls
@isTest
private class AchievementSurveyUtilsTest {
    
    @isTest 
    static void shouldGetTemplatePositionProfileWithAllQuestion() {
        // GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementPositionProfileQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementPositionProfileHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        SurveyUtils.TemplateRequest request = new SurveyUtils.TemplateRequest(contacts[0].Email, template.ApiName__c);
        //WHEN
        SurveyModel.Template surveyModelTemplate = SurveyFrontController.getInstance().getTemplate(request);

        //THEN
        System.assertEquals('surveytemplatetest', surveyModelTemplate.name);
        System.assertEquals(5, surveyModelTemplate.questions.size());
    }

    @isTest 
    static void shouldGetTemplateSurveyWithCategoryID() {
        String configClassProvider = 'AchievementSurveyUtils.AchievementSurveyQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementSurveyHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        Achievement_Category__c category = [SELECT Id, ExternalId__c FROM Achievement_Category__c LIMIT 1];
        String templateItemConfig = '{"achievmentExternalId":"", "categoryExternalId":"' + category.ExternalId__c + '","getAll":"false", "email": "false"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, true);
        List<Contact> contacts = prepareUsers(1, template);
        SurveyUtils.TemplateRequest request = new SurveyUtils.TemplateRequest(contacts[0].Email, template.ApiName__c);
        //WHEN
        SurveyModel.Template surveyModelTemplate = SurveyFrontController.getInstance().getTemplate(request);

        //THEN
        System.assertEquals('surveytemplatetest', surveyModelTemplate.name);
        System.assertEquals(4, surveyModelTemplate.questions.size());
    }

    @isTest 
    static void shouldGetTemplatePositionProfile() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementPositionProfileQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementPositionProfileHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentExternalId":"' + achievements[0].ExternalId__c + '","getAll":"false"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        SurveyUtils.TemplateRequest request = new SurveyUtils.TemplateRequest(contacts[0].Email, template.ApiName__c);

        //WHEN
        SurveyModel.Template surveyModelTemplate = SurveyFrontController.getInstance().getTemplate(request);

        //THEN
        System.assertEquals('surveytemplatetest', surveyModelTemplate.name);
        System.assertEquals(1, surveyModelTemplate.questions.size());
    }

    @isTest 
    static void shouldGetTemplateEmployeeProfileWithAllQuestion() {
        // GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementEmployeeProfileQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementEmployeeProfileHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        SurveyUtils.TemplateRequest request = new SurveyUtils.TemplateRequest(contacts[0].Email, template.ApiName__c);

        //WHEN
        SurveyModel.Template surveyModelTemplate = SurveyFrontController.getInstance().getTemplate(request);

        //THEN
        System.assertEquals('surveytemplatetest', surveyModelTemplate.name);
        System.assertEquals(5, surveyModelTemplate.questions.size());
    }

    @isTest 
    static void shouldGetTemplateEmployeeProfile() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementEmployeeProfileQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementEmployeeProfileHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentExternalId":"' + achievements[0].ExternalId__c + '","getAll":"false"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        SurveyUtils.TemplateRequest request = new SurveyUtils.TemplateRequest(contacts[0].Email, template.ApiName__c);

        //WHEN
        SurveyModel.Template surveyModelTemplate = SurveyFrontController.getInstance().getTemplate(request);

        //THEN
        System.assertEquals('surveytemplatetest', surveyModelTemplate.name);
        System.assertEquals(1, surveyModelTemplate.questions.size());
    }

    @isTest 
    static void shouldGetTemplateSurveyWithAllQuestion() {
        // GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementSurveyQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementSurveyHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true","email": "false" }';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, true);
        List<Contact> contacts = prepareUsers(1, template);
        SurveyUtils.TemplateRequest request = new SurveyUtils.TemplateRequest(contacts[0].Email, template.ApiName__c);

        //WHEN
        SurveyModel.Template surveyModelTemplate = SurveyFrontController.getInstance().getTemplate(request);

        //THEN
        System.assertEquals('surveytemplatetest', surveyModelTemplate.name);
        System.assertEquals(4, surveyModelTemplate.questions.size());
    }

    @isTest 
    static void shouldGetTemplateSurvey() {
        // GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementSurveyQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementSurveyHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentExternalId":"' + achievements[0].ExternalId__c + '","getAll":"false","email": "false" }';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, true);
        List<Contact> contacts = prepareUsers(1, template);
        SurveyUtils.TemplateRequest request = new SurveyUtils.TemplateRequest(contacts[0].Email, template.ApiName__c);

        //WHEN
        SurveyModel.Template surveyModelTemplate = SurveyFrontController.getInstance().getTemplate(request);

        //THEN
        System.assertEquals('surveytemplatetest', surveyModelTemplate.name);
        System.assertEquals(2, surveyModelTemplate.questions.size());
    }

    @isTest 
    static void shouldNotGetTemplateSurveyWithoutEmailItem() {
        // GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementSurveyQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementSurveyHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"' + achievements[0].Id + '","getAll":"false","email": "false" }';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        SurveyUtils.TemplateRequest request = new SurveyUtils.TemplateRequest(contacts[0].Email, template.ApiName__c);

        //WHEN
        try {
            SurveyModel.Template surveyModelTemplate = SurveyFrontController.getInstance().getTemplate(request);
            System.assert(false, 'Tamplate not contains question of email');
        } catch (Exception e){}
    }

    @isTest 
    static void shouldNotGetTemplatePositionProfileWithNoFoundAchievment() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementPositionProfileQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementPositionProfileHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"false"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        SurveyUtils.TemplateRequest request = new SurveyUtils.TemplateRequest(contacts[0].Email, template.ApiName__c);

        //WHEN
        try {
        SurveyModel.Template surveyModelTemplate = SurveyFrontController.getInstance().getTemplate(request);
            System.assert(false, 'AchievementId is mandatory!');
        } catch (Exception e){}
    }

    @isTest 
    static void shouldGetTemplateToGraph() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementQuestionGraphProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementBaseHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder('PositionProfile').asPositionProfile(careerPath)
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .buildAndSave();
        SurveyUtils.TemplateRequest request = new SurveyUtils.TemplateRequest(contacts[0].Email, template.ApiName__c);

        //WHEN
        SurveyModel.Template surveyModelTemplate = SurveyFrontController.getInstance().getTemplate(request);

        //THEN
        System.assertEquals('surveytemplatetest', surveyModelTemplate.name);
        System.assertEquals(10, surveyModelTemplate.questions.size());
    }

    @isTest 
    static void shouldNotGetTemplateWithWrongAchievmentId() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementPositionProfileQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementPositionProfileHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"5003000000D8cuIAEA","getAll":"false"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        SurveyUtils.TemplateRequest request = new SurveyUtils.TemplateRequest(contacts[0].Email, template.ApiName__c);

        //WHEN
        try {
            SurveyModel.Template surveyModelTemplate = SurveyFrontController.getInstance().getTemplate(request);
            System.assert(false, 'Wrong achievmentId');
        } catch (Exception e){}
    }

    @isTest 
    static void shouldNotGetTemplateWithoutAchievmentId() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementPositionProfileQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementPositionProfileHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"false"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        SurveyUtils.TemplateRequest request = new SurveyUtils.TemplateRequest(contacts[0].Email, template.ApiName__c);

        //WHEN
        try {
            SurveyModel.Template surveyModelTemplate = SurveyFrontController.getInstance().getTemplate(request);
            System.assert(false, 'Wrong achievmentId');
        } catch (Exception e){}
        
    }

    @isTest 
    static void shouldGetAchievementPositionProfile() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementPositionProfileQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementPositionProfileHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder('PositionProfile').asPositionProfile(careerPath)
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .buildAndSave();
        SurveyUtils.SurveyRequest request = new SurveyUtils.SurveyRequest(contacts[0].Email, template.ApiName__c, achievementSet.Id);

        //WHEN
        SurveyModel.Survey survey = SurveyFrontController.getInstance().getSurvey(request);

        //THEN
        System.assertEquals('PositionProfile', survey.name);
        System.assertEquals('test1@test.pl', survey.userId);
        System.assertEquals(3, survey.answers.size());
    }

    @isTest 
    static void shouldGetAchievementEmployeeProfile() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementEmployeeProfileQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementEmployeeProfileHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        Map<ID, Achievement_Set__c> contactIdToAchievementSetMap  = new Map<ID, Achievement_Set__c>();
        for (Achievement_Set__c cpp : [SELECT Contact__c, Name FROM Achievement_Set__c WHERE Contact__c =: contacts[0].Id]) {
            contactIdToAchievementSetMap.put(cpp.Contact__c, cpp);
        }

        Double minSpecialityMatch = 0.30;
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(contacts[0].Id))
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .addSpecialization(achievements[4], minSpecialityMatch)
            .buildAndSave();
        SurveyUtils.SurveyRequest request = new SurveyUtils.SurveyRequest(contacts[0].Email, template.ApiName__c, achievementSet.Id);

        //WHEN
        SurveyModel.Survey survey = SurveyFrontController.getInstance().getSurvey(request);

        //THEN
        System.assertEquals('test1 test1 - Employee Profile', survey.name);
        System.assertEquals('test1@test.pl', survey.userId);
        System.assertEquals(5, survey.answers.size());
    }

    @isTest 
    static void shouldGetAchievementSpecialization() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementSpecializationQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementSpecializationHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        Achievement_Set__c aSet = [SELECT Name, Career_Path__c FROM Achievement_Set__c WHERE RecordTypeId =: AchievementUtils.getAchievementSetProfileRecordType().Id];
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder(aSet)
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .buildAndSave();
        SurveyUtils.SurveyRequest request = new SurveyUtils.SurveyRequest(contacts[0].Email, template.ApiName__c, achievementSet.Id);

        //WHEN
        SurveyModel.Survey survey = SurveyFrontController.getInstance().getSurvey(request);
        //THEN
        System.assertEquals('Specialization', survey.name);
        System.assertEquals('test1@test.pl', survey.userId);
        System.assertEquals(3, survey.answers.size());
    }

    @isTest 
    static void shouldGetAchievementSurvey() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementSurveyQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementSurveyHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(2, template);
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder('Survey').asSurvey(contacts[0], contacts[1])
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .buildAndSave();
        SurveyUtils.SurveyRequest request = new SurveyUtils.SurveyRequest(contacts[0].Email, template.ApiName__c, achievementSet.Id);

        //WHEN
        SurveyModel.Survey survey = SurveyFrontController.getInstance().getSurvey(request);

        //THEN
        System.assertEquals('test2 test2', survey.name);
        System.assertEquals('test1@test.pl', survey.userId);
        System.assertEquals(4, survey.answers.size());
    }

    @isTest 
    static void shouldGetTemplateInfoEmployeeProfile() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementEmployeeProfileQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementEmployeeProfileHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        List<Contact> contacts = prepareUsers(1, template);
        Double minSpecialityMatch = 0.30;
        Map<ID, Achievement_Set__c> contactIdToAchievementSetMap  = new Map<ID, Achievement_Set__c>();
        for (Achievement_Set__c cpp : [SELECT Contact__c, Name FROM Achievement_Set__c WHERE Contact__c =: contacts[0].Id]) {
            contactIdToAchievementSetMap.put(cpp.Contact__c, cpp);
        }
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(contacts[0].Id))
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .addSpecialization(achievements[4], minSpecialityMatch)
            .buildAndSave();
        SurveyUtils.Request request = new SurveyUtils.Request(contacts[0].Email);

        //WHEN
        List<SurveyModel.TemplateInfo> templates = SurveyFrontController.getInstance().getTemplatesInfo(request);

        //THEN
        System.assertEquals('surveytemplatetest', templates[0].name);
        System.assertEquals(1, templates[0].surveys.size());
    }

    @isTest 
    static void shouldGetTemplateInfoSurvey() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementSurveyQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementSurveyHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        List<Contact> contacts = prepareUsers(1, template);
        Double minSpecialityMatch = 0.30;
       Achievement_Set__c achievementSet1  = new AchievementUtils.AchievementSetBuilder('Survey').asSurvey(contacts[0], contacts[0])
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .addSpecialization(achievements[4], minSpecialityMatch)
            .buildAndSave();
        SurveyUtils.Request request = new SurveyUtils.Request(contacts[0].Email);

        //WHEN
        List<SurveyModel.TemplateInfo> templates = SurveyFrontController.getInstance().getTemplatesInfo(request);

        //THEN
        System.assertEquals('surveytemplatetest', templates[0].name);
        System.assertEquals(1, templates[0].surveys.size());
    }

    @isTest 
    static void shouldNotGetTemplateInfoSurveyWithWrongWhoEmial() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementSurveyQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementSurveyHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        List<Contact> contacts = prepareUsers(1, template);
        Double minSpecialityMatch = 0.30;
       Achievement_Set__c achievementSet1  = new AchievementUtils.AchievementSetBuilder('Survey').asSurvey(contacts[0], contacts[0])
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .addSpecialization(achievements[4], minSpecialityMatch)
            .buildAndSave();
        SurveyUtils.Request request = new SurveyUtils.Request('t@test.com');

        //WHEN
        try {
            List<SurveyModel.TemplateInfo> templates = SurveyFrontController.getInstance().getTemplatesInfo(request);
            System.assert(false, 'You not have permission!');
        } catch (Exception e){}
    }

    @isTest 
    static void shouldGetTemplateInfoWithTemplateConfig() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementEmployeeProfileQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementEmployeeProfileHandler';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        Contact c = new Contact(FirstName = 'test', LastName = 'test', Email='test@test.com', SkillAssessment__c = true);
        insert c;
        Double minSpecialityMatch = 0.30;
        Map<ID, Achievement_Set__c> contactIdToAchievementSetMap  = new Map<ID, Achievement_Set__c>();
        for (Achievement_Set__c cpp : [SELECT Contact__c, Name FROM Achievement_Set__c WHERE Contact__c =: c.Id]) {
            contactIdToAchievementSetMap.put(cpp.Contact__c, cpp);
        }
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(c.Id))
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .addSpecialization(achievements[4], minSpecialityMatch)
            .buildAndSave();
        String templateConfig = '{"achievmentSetId": "'+achievementSet.Id+'"}';
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        insert new SurveyTemplateAccesses__c(Contact__c=c.Id, SurveyTemplate__c=template.Id);
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        SurveyUtils.Request request = new SurveyUtils.Request(c.Email);

        //WHEN
        List<SurveyModel.TemplateInfo> templates = SurveyFrontController.getInstance().getTemplatesInfo(request);

        //THEN
        System.assertEquals('surveytemplatetest', templates[0].name);
        System.assertEquals(1, templates[0].surveys.size());
    }

    @isTest 
    static void shouldUpdateEmployeeProfile() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementEmployeeProfileQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementEmployeeProfileHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        Double minSpecialityMatch = 0.30;
        Map<ID, Achievement_Set__c> contactIdToAchievementSetMap  = new Map<ID, Achievement_Set__c>();
        for (Achievement_Set__c cpp : [SELECT Contact__c, Name FROM Achievement_Set__c WHERE Contact__c =: contacts[0].Id]) {
            contactIdToAchievementSetMap.put(cpp.Contact__c, cpp);
        }
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(contacts[0].Id))
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .addSpecialization(achievements[4], minSpecialityMatch)
            .buildAndSave();
        SurveyUtils.SurveyRequest request = new SurveyUtils.SurveyRequest(contacts[0].Email, template.ApiName__c, achievementSet.Id);
        SurveyModel.Survey survey = SurveyFrontController.getInstance().getSurvey(request);
        survey.answers[0].value = AchievementUtils.ACHIEVEMENT_LEVEL_3_VALUE;
        survey.answers[2].value = '55';

        //WHEN
        SurveyModel.Survey newSurvey = SurveyFrontController.getInstance().saveSurvey(JSON.serialize(survey));

        //THEN
        System.assertEquals('test1 test1 - Employee Profile', newSurvey.name);
        System.assertEquals('test1@test.pl', newSurvey.userId);
        System.assertEquals(5, newSurvey.answers.size());
        System.assertEquals(AchievementUtils.ACHIEVEMENT_LEVEL_3_VALUE, newSurvey.answers[0].value);
        System.assertEquals('55', newSurvey.answers[2].value);
    }

    @isTest 
    static void shouldUpdatePositionProfile() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementPositionProfileQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementPositionProfileHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        Double minSpecialityMatch = 0.30;
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder('PrositionProfile').asPositionProfile(careerPath)
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .addSpecialization(achievements[4], minSpecialityMatch)
            .buildAndSave();
        SurveyUtils.SurveyRequest request = new SurveyUtils.SurveyRequest(contacts[0].Email, template.ApiName__c, achievementSet.Id);
        SurveyModel.Survey survey = SurveyFrontController.getInstance().getSurvey(request);
        survey.answers[0].value = AchievementUtils.ACHIEVEMENT_LEVEL_3_VALUE;
        survey.answers[2].value = '55';

        //WHEN
        SurveyModel.Survey newSurvey = SurveyFrontController.getInstance().saveSurvey(JSON.serialize(survey));

        //THEN
        System.assertEquals('PrositionProfile', newSurvey.name);
        System.assertEquals('test1@test.pl', newSurvey.userId);
        System.assertEquals(4, newSurvey.answers.size());
        System.assertEquals(AchievementUtils.ACHIEVEMENT_LEVEL_3_VALUE, newSurvey.answers[0].value);
        System.assertEquals('55', newSurvey.answers[2].value);
    }

    @isTest 
    static void shouldUpdateSpecialization() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementSpecializationQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementSpecializationHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        Double minSpecialityMatch = 0.30;
        Achievement_Set__c aSet = [SELECT Name, Career_Path__c FROM Achievement_Set__c WHERE RecordTypeId =: AchievementUtils.getAchievementSetProfileRecordType().Id];
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder(aSet)
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .addSpecialization(achievements[4], minSpecialityMatch)
            .buildAndSave();
        SurveyUtils.SurveyRequest request = new SurveyUtils.SurveyRequest(contacts[0].Email, template.ApiName__c, achievementSet.Id);
        SurveyModel.Survey survey = SurveyFrontController.getInstance().getSurvey(request);
        survey.answers[0].value = AchievementUtils.ACHIEVEMENT_LEVEL_3_VALUE;
        survey.answers[2].value = '55';

        //WHEN
        SurveyModel.Survey newSurvey = SurveyFrontController.getInstance().saveSurvey(JSON.serialize(survey));

        //THEN
        System.assertEquals('Specialization', newSurvey.name);
        System.assertEquals('test1@test.pl', newSurvey.userId);
        System.assertEquals(4, newSurvey.answers.size());
        System.assertEquals(AchievementUtils.ACHIEVEMENT_LEVEL_3_VALUE, newSurvey.answers[0].value);
        System.assertEquals('55', newSurvey.answers[2].value);
    }

    @isTest 
    static void shouldUpdateAchievementSurvey() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementSurveyQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementSurveyHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        List<Contact> contacts = prepareUsers(2, template);
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder('Survey').asSurvey(contacts[0], contacts[1])
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .buildAndSave();
        SurveyUtils.SurveyRequest request = new SurveyUtils.SurveyRequest(contacts[0].Email, template.ApiName__c, achievementSet.Id);
        SurveyModel.Survey survey = SurveyFrontController.getInstance().getSurvey(request);
        survey.answers[0].value = AchievementUtils.ACHIEVEMENT_LEVEL_3_VALUE;
        survey.answers[2].value = '55';
        survey.answers[3].value = 'test2@test.pl';

        //WHEN
        SurveyModel.Survey newSurvey = SurveyFrontController.getInstance().saveSurvey(JSON.serialize(survey));

        //THEN
        System.assertEquals('test2 test2', newSurvey.name);
        System.assertEquals('test1@test.pl', newSurvey.userId);
        System.assertEquals(4, newSurvey.answers.size());
        System.assertEquals(AchievementUtils.ACHIEVEMENT_LEVEL_3_VALUE, newSurvey.answers[0].value);
        System.assertEquals('55', newSurvey.answers[2].value);
        System.assertEquals('test2@test.pl', newSurvey.answers[3].value);
    }

    @isTest 
    static void shouldSaveNewAchievementSurvey() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementSurveyQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementSurveyHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        List<Contact> contacts = prepareUsers(2, template);
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder('Survey').asSurvey(contacts[0], contacts[1])
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .buildAndSave();
        SurveyUtils.SurveyRequest request = new SurveyUtils.SurveyRequest(contacts[0].Email, template.ApiName__c, achievementSet.Id);
        SurveyModel.Survey survey = SurveyFrontController.getInstance().getSurvey(request);
        delete achievementSet;
        survey.answers[0].value = AchievementUtils.ACHIEVEMENT_LEVEL_3_VALUE;
        survey.answers[2].value = '55';
        survey.answers[3].value = 'test2@test.pl';

        //WHEN
        SurveyModel.Survey newSurvey = SurveyFrontController.getInstance().saveSurvey(JSON.serialize(survey));

        //THEN
        System.assertEquals('test2 test2', newSurvey.name);
        System.assertEquals('test1@test.pl', newSurvey.userId);
        System.assertEquals(4, newSurvey.answers.size());
        System.assertEquals(1, [SELECT COUNT() FROM Achievement_Set_Item__c WHERE Type__c = :AchievementUtils.ACHIEVEMENT_SKILL_RECORD_TYPE AND LevelValue__c = :AchievementUtils.ACHIEVEMENT_LEVEL_3_VALUE]);
        System.assertEquals(1, [SELECT COUNT() FROM Achievement_Set_Item__c WHERE Type__c = :AchievementUtils.ACHIEVEMENT_BADGE_RECORD_TYPE AND Amount__c = 55]);
    }

    @isTest 
    static void shouldNotSaveNewAchievementSurveyWithoutTargetId() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementSurveyQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementSurveyHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        List<Contact> contacts = prepareUsers(2, template);
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder('Survey').asSurvey(contacts[0], contacts[1])
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .buildAndSave();
        SurveyUtils.SurveyRequest request = new SurveyUtils.SurveyRequest(contacts[0].Email, template.ApiName__c, achievementSet.Id);
        SurveyModel.Survey survey = SurveyFrontController.getInstance().getSurvey(request);
        survey.answers[0].value = 'Senior';
        survey.answers[2].value = '55';
        survey.answers[3].value = '';

        //WHEN
        try {
            SurveyModel.Survey newSurvey = SurveyFrontController.getInstance().saveSurvey(JSON.serialize(survey));
            System.assert(false, 'Please provide Target Id, this field is mandatory!');
        } catch (Exception e){}
    }

    @isTest 
    static void shouldNotSaveNewAchievementSurveyWithNotFoundAboutWho() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementSurveyQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementSurveyHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        List<Contact> contacts = prepareUsers(2, template);
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder('Survey').asSurvey(contacts[0], contacts[1])
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .buildAndSave();
        SurveyUtils.SurveyRequest request = new SurveyUtils.SurveyRequest(contacts[0].Email, template.ApiName__c, achievementSet.Id);
        SurveyModel.Survey survey = SurveyFrontController.getInstance().getSurvey(request);
        survey.answers[0].value = 'Senior';
        survey.answers[2].value = '55';
        survey.answers[3].value = 't@test.pl';

        //WHEN
        try {
            SurveyModel.Survey newSurvey = SurveyFrontController.getInstance().saveSurvey(JSON.serialize(survey));
            System.assert(false, 'Cannot find contact with email');
        } catch (Exception e){}
    }

    @isTest
    static void shouldNotGetAchievementSetWithNotFoundAvhievementId() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementSpecializationQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementSpecializationHandler';
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        Double minSpecialityMatch = 0.30;
        Achievement_Set__c aSet = [SELECT Name, Career_Path__c FROM Achievement_Set__c WHERE RecordTypeId =: AchievementUtils.getAchievementSetProfileRecordType().Id];
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder(aSet)
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .addSpecialization(achievements[4], minSpecialityMatch)
            .buildAndSave();
        String templateConfig = '{"achievmentSetId": "'+achievementSet.Id+'"}';
        String templateItemConfig = '{"achievmentId":"'+achievements[0].Id+'","getAll":"false"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        SurveyUtils.SurveyRequest request = new SurveyUtils.SurveyRequest(contacts[0].Email, template.ApiName__c, achievementSet.Id);
        delete achievementSet;

        //WHEN
        try {
        SurveyModel.Survey survey = SurveyFrontController.getInstance().getSurvey(request);
            System.assert(false, 'Not found Achievement Set with Id');
        } catch (Exception e){}
    }

    @isTest
    static void shouldNotGetAchievementSetWithNoSurveyId() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementSpecializationQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementSpecializationHandler';
        String templateConfig = '{}';
        Double minSpecialityMatch = 0.30;
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"'+achievements[0].Id+'","getAll":"false"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        Achievement_Set__c aSet = [SELECT Name, Career_Path__c FROM Achievement_Set__c WHERE RecordTypeId =: AchievementUtils.getAchievementSetProfileRecordType().Id];
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder(aSet)
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .addSpecialization(achievements[4], minSpecialityMatch)
            .buildAndSave();
        SurveyUtils.SurveyRequest request = new SurveyUtils.SurveyRequest(contacts[0].Email, template.ApiName__c, null);

        //WHEN
        try {
            SurveyModel.Survey survey = SurveyFrontController.getInstance().getSurvey(request);
            System.assert(false, 'Achievement Set was not set on the Survey Template!');
        } catch (Exception e){}
    }

    @isTest
    static void shouldNotUpdateSpecializationWithNoSurveyId() {
        //GIVEN
        String configClassProvider = 'AchievementSurveyUtils.AchievementSpecializationQuestionProvider';
        String configClassHandler = 'AchievementSurveyUtils.AchievementSpecializationHandler';
        String templateConfig = '{}';
        List<Achievement__c> achievements = createAchievmentWithCategory('categoryName');
        String templateItemConfig = '{"achievmentId":"","getAll":"true"}';
        SurveyTemplate__c template = prepateTemplate(configClassProvider, configClassHandler, templateConfig, templateItemConfig, false);
        List<Contact> contacts = prepareUsers(1, template);
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPath_1').buildAndSave();
        Double minSpecialityMatch = 0.30;
        Achievement_Set__c aSet = [SELECT Name, Career_Path__c FROM Achievement_Set__c WHERE RecordTypeId =: AchievementUtils.getAchievementSetProfileRecordType().Id];
        Achievement_Set__c achievementSet  = new AchievementUtils.AchievementSetBuilder(aSet)
            .addSkill(achievements[0], 'Junior')
            .addCert(achievements[1])
            .addBadge(achievements[2], 10)
            .addSpecialization(achievements[4], minSpecialityMatch)
            .buildAndSave();
        SurveyUtils.SurveyRequest request = new SurveyUtils.SurveyRequest(contacts[0].Email, template.ApiName__c, achievementSet.Id);
        SurveyModel.Survey survey = SurveyFrontController.getInstance().getSurvey(request);
        delete achievementSet;

        //WHEN
        try {
            SurveyModel.Survey newSurvey = SurveyFrontController.getInstance().saveSurvey(JSON.serialize(survey));
            System.assert(false, 'Cannot find proper survey!');
        } catch (Exception e){}
    }

    static private List<Achievement__c> createAchievmentWithCategory(String name) {
        Achievement_Category__c category = new AchievementUtils.AchievementCategoryBuilder(name+'AchievementSurveyUtilsTest').buildAndSave();
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('careerPathAchievementSurveyUtilsTest').buildAndSave();
        Achievement_Set__c achievementSet = new AchievementUtils.AchievementSetBuilder('Specialization').asProfile(careerPath).buildAndSave();
        List<Achievement__c> achievements = new List<Achievement__c>{
            new AchievementUtils.AchievementBuilder('AchievementSkill', category).asSkill().build(),
            new AchievementUtils.AchievementBuilder('AchievementCertificate', category).asCert().build(),
            new AchievementUtils.AchievementBuilder('AchievementBadge', category).asBadge().build(),
            new AchievementUtils.AchievementBuilder('AchievementGroup', category).asGroup().build(),
            new AchievementUtils.AchievementBuilder('AchievementSpecialization', category).asSpecialization(achievementSet).build()
        };
        insert achievements;
        return [SELECT Id, Name, ExternalId__c FROM Achievement__c];
    }

    static private List<SurveyTestUtils.SurveyConfigBuilder> createConfig(String providerName, String handlerName, String configClassProvider, String configClassHandler) {
        String configSignature = '{}';
        Id providerRecordTypeId = SurveyUtils.getSurveyConfigRecordType(SurveyUtils.SURVEY_CONFIGURATION_SURVEY_QUESTION_PROVIDER_RECORD_TYPE).Id;
        Id handlerRecordTypeId = SurveyUtils.getSurveyConfigRecordType(SurveyUtils.SURVEY_CONFIGURATION_SURVEY_HANDLER_RECORD_TYPE).Id;

        return new List <SurveyTestUtils.SurveyConfigBuilder> {
            new SurveyTestUtils.SurveyConfigBuilder().setServiceConfig(providerName, configClassProvider, configSignature, providerRecordTypeId, true),
            new SurveyTestUtils.SurveyConfigBuilder().setServiceConfig(handlerName, configClassHandler, configSignature, handlerRecordTypeId, true)
        };
    }

    static private SurveyTemplate__c  prepateTemplate (String configClassProvider, String configClassHandler, String templateConfig, String templateItemConfig, Boolean addItemEmail) {
        String providerName = 'questionProviderAchievementSurveyUtilsTest';
        String handlerName = 'surveyHandlerAchievementSurveyUtilsTest';
        String configSignature = '{}';
        List<SurveyTestUtils.SurveyConfigBuilder> cfgs = createConfig(providerName, handlerName, configClassProvider, configClassHandler);
        cfgs[0].buildAndSave();
        cfgs[1].buildAndSave();
        SurveyTemplate__c template = new SurveyTestUtils.TemplateBuilder('surveytemplatetest').withHandler(cfgs[1].getConfigs().get(handlerName).Id).withConfig(templateConfig).buildAndSave();
        SurveyTemplateItem__c templateItem = new SurveyTestUtils.TemplateItemBuilder(template, cfgs[0].getConfigs().get(providerName)).withConfig(templateItemConfig).buildAndSave();
        if (addItemEmail) {
            String templateItemEmailConfig = '{"achievmentId":"","getAll":"false","email": "true" }';
            SurveyTemplateItem__c templateItem1 = new SurveyTestUtils.TemplateItemBuilder(template, cfgs[0].getConfigs().get(providerName)).withConfig(templateItemEmailConfig).withOrder(2).buildAndSave();
        }
        return template;
    }

    static private List<Contact> prepareUsers(Integer count, SurveyTemplate__c template) {
        List<Contact> contacts = new List<Contact>();
        List<SurveyTemplateAccesses__c> accesses = new List<SurveyTemplateAccesses__c>();
        for (Integer i = 1; i <= count; i++) {
            contacts.add( new Contact(FirstName = 'test'+i, LastName = 'test'+i, Email='test'+i+'@test.pl', SkillAssessment__c = true) );
        }
        insert contacts;

        for (Contact item : contacts) {
            accesses.add( new SurveyTemplateAccesses__c(Contact__c=item.Id, SurveyTemplate__c=template.Id) );
        }
        insert accesses;
        return contacts;
    }
}