force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>Achievement</description>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Achievement_Category__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Category__c</fullName>
    <label>Achievement Category</label>
    <referenceTo>Achievement_Category__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement_Category__c/Achievement_Category__c.object-meta.xml
<CustomObject>
    <description>Achievement Category</description>
    <label>Achievement Category</label>
    <nameField>
        <label>Achievement Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Category__c/fields/Number_of_Achievements__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Achievements__c</fullName>
    <label>Number of Achievements</label>
    <summaryForeignKey>Achievement__c.Achievement_Category__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/Achievement_Set__c.object-meta.xml
<CustomObject>
    <description>Achievement Set</description>
    <label>Achievement Set</label>
    <nameField>
        <label>Achievement Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set__c/fields/Active_Contact__c.field-meta.xml
<CustomField>
    <fullName>Active_Contact__c</fullName>
    <formula>IF(ISBLANK(Contact__c), false, Contact__r.Active__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact field is valid only for Contact Survey and Contact Profile record types</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Number_Of_Achievements__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Achievements__c</fullName>
    <label>Number Of Achievements</label>
    <summaryForeignKey>Achievement_Set_Item__c.Achievement_Set__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Parent_Profile__c.field-meta.xml
<CustomField>
    <fullName>Parent_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Profile</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select the Profile Achievement set</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Position Profile, Specialization</value>
        </filterItems>
        <filterItems>
            <field>Achievement_Set__c.Career_Path__c</field>
            <operation>equals</operation>
            <valueField>$Source.Career_Path__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Score_Minimal_Value__c.field-meta.xml
<CustomField>
    <fullName>Score_Minimal_Value__c</fullName>
    <defaultValue>0.5</defaultValue>
    <description>Minimalne dopasowanie po jakim Profil zostanie przypisany do Pracownika</description>
    <inlineHelpText>Minimalne dopasowanie po jakim Profil zostanie przypisany do Pracownika</inlineHelpText>
    <label>Score Minimal Value</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/SelfSurvey__c.field-meta.xml
<CustomField>
    <fullName>SelfSurvey__c</fullName>
    <formula>NOT(ISBLANK(AboutWho__c)) &amp;&amp; NOT(ISBLANK(Who__c)) &amp;&amp; AboutWho__c = Who__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Self-Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/Achievement_Set_Item__c.object-meta.xml
<CustomObject>
    <description>Achievement Set Item</description>
    <label>Achievement Set Item</label>
    <nameField>
        <displayFormat>ASI{00000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Set Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipName>Position_Profile_Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Achievement_Set__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Set__c</fullName>
    <label>Achievement Set</label>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Min_Speciality_Match__c.field-meta.xml
<CustomField>
    <fullName>Min_Speciality_Match__c</fullName>
    <defaultValue>1.0</defaultValue>
    <label>Min. Speciality Match</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Career_Path__c/Career_Path__c.object-meta.xml
<CustomObject>
    <label>Career Path</label>
    <nameField>
        <label>Career Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Career Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Number_Of_Achievements__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Achievements__c</fullName>
    <formula>Achievement_Profile__r.Number_Of_Achievements__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number Of Achievements</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SkillAssessment__c.field-meta.xml
<CustomField>
    <fullName>SkillAssessment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skill Assessment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AchievementSetItemTriggerTest.cls
@isTest
private class AchievementSetItemTriggerTest {

    @isTest
    private static void shouldStartAchievementGroupPartialCalculationJob(){
        Contact c = new Contact(FirstName='Zdzisiek', LastName='Burak', Email='Zdzisiek@Burak.pl', SkillAssessment__c=true);
        insert c;
        Achievement_Category__c category = new AchievementUtils.AchievementCategoryBuilder('category Category').buildAndSave();
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('Career Path 1').buildAndSave();
        Achievement__c apexSkill = new AchievementUtils.AchievementBuilder('apexSkill', category).asSkill().buildAndSave();
        Achievement__c visualforceSkill = new AchievementUtils.AchievementBuilder('visualforceSkill', category).asSkill().buildAndSave();
        Achievement__c soqlSkill = new AchievementUtils.AchievementBuilder('soqlSkill', category).asSkill().buildAndSave();
        Achievement_Set__c achievementSet2 = new AchievementUtils.AchievementSetBuilder('positionProfile').asPositionProfile(careerPath).buildAndSave();
        Achievement_Set__c achievementSet = [SELECT Id, Contact__c, Number_Of_Achievements__c,Active_Contact__c,Career_Path__c,Description__c,Parent_Profile__c,Score_Minimal_Value__c, SelfSurvey__c FROM Achievement_Set__c WHERE Contact__c =: c.Id LIMIT 1];
        Achievement_Set_Item__c achievementSetItem1 = new Achievement_Set_Item__c(
                                                            Achievement_Set__c = achievementSet.id,
                                                            Achievement__c = apexSkill.Id,
                                                            Level__c = AchievementUtils.ACHIEVEMENT_LEVEL_1,
                                                            Amount__c = 1,
                                                            Min_Speciality_Match__c = 0.3);
        Achievement_Set_Item__c achievementSetItem2 = new Achievement_Set_Item__c(
                                                            Achievement_Set__c = achievementSet.id,
                                                            Achievement__c = visualforceSkill.Id,
                                                            Level__c = AchievementUtils.ACHIEVEMENT_LEVEL_1,
                                                            Amount__c = 2,
                                                            Min_Speciality_Match__c = 0.6);
        Achievement_Set_Item__c achievementSetItem3 = new Achievement_Set_Item__c(
                                                            Achievement_Set__c = achievementSet2.id,
                                                            Achievement__c = apexSkill.Id,
                                                            Level__c = AchievementUtils.ACHIEVEMENT_LEVEL_1,
                                                            Amount__c = 1,
                                                            Min_Speciality_Match__c = 0.3);
        Achievement_Set_Item__c achievementSetItem4 = new Achievement_Set_Item__c(
                                                            Achievement_Set__c = achievementSet2.id,
                                                            Achievement__c = visualforceSkill.Id,
                                                            Level__c = AchievementUtils.ACHIEVEMENT_LEVEL_1,
                                                            Amount__c = 2,
                                                            Min_Speciality_Match__c = 0.6);
        List<Achievement_Set_Item__c> achievementSetItems = new List<Achievement_Set_Item__c>{achievementSetItem1, achievementSetItem2, achievementSetItem3, achievementSetItem4};
        insert achievementSetItems;
        Achievement__c salesforceGroup = new AchievementUtils.AchievementBuilder('salesforceGroup', category).asGroup().addGroupItem(visualforceSkill).addGroupItem(apexSkill).buildAndSave();

        achievementSetItem1.Level__c = AchievementUtils.ACHIEVEMENT_LEVEL_3;
        achievementSetItem1.Min_Speciality_Match__c = 0.45;
    }

}