force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>Achievement</description>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Achievement_Category__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Category__c</fullName>
    <label>Achievement Category</label>
    <referenceTo>Achievement_Category__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement__c/recordTypes/Attribute.recordType-meta.xml
<RecordType>
    <fullName>Attribute</fullName>
    <active>true</active>
    <description>Umiejętność określana jakościowo za pomocą konfigurowalnej skali</description>
    <label>Attribute</label>
</RecordType>

force-app/main/default/objects/Achievement__c/recordTypes/Badge.recordType-meta.xml
<RecordType>
    <fullName>Badge</fullName>
    <active>true</active>
    <description>Odznaka - współczynnik ilościowy</description>
    <label>Badge</label>
</RecordType>

force-app/main/default/objects/Achievement__c/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <description>Zbiór umiejętności.</description>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/Achievement__c/recordTypes/Skill.recordType-meta.xml
<RecordType>
    <fullName>Skill</fullName>
    <active>true</active>
    <description>Umiejętność określana jakościowo za pomocą trzy stopniowej skali</description>
    <label>Skill</label>
</RecordType>

force-app/main/default/objects/Achievement__c/recordTypes/Specialization.recordType-meta.xml
<RecordType>
    <fullName>Specialization</fullName>
    <active>true</active>
    <description>Specializacja</description>
    <label>Specialization</label>
</RecordType>

force-app/main/default/objects/Achievement_Category__c/Achievement_Category__c.object-meta.xml
<CustomObject>
    <description>Achievement Category</description>
    <label>Achievement Category</label>
    <nameField>
        <label>Achievement Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Group_Item__c/Achievement_Group_Item__c.object-meta.xml
<CustomObject>
    <label>Achievement Group Item</label>
    <nameField>
        <displayFormat>AGI{00000000}</displayFormat>
        <label>Achievement Group Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Group Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Group_Item__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Achievement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Achievement__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>Achievement Group Items (Achievement)</relationshipLabel>
    <relationshipName>Achievement_Group_Items1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Group_Item__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Achievement__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>Achievement Group Items</relationshipLabel>
    <relationshipName>Achievement_Group_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/Achievement_Set__c.object-meta.xml
<CustomObject>
    <description>Achievement Set</description>
    <label>Achievement Set</label>
    <nameField>
        <label>Achievement Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set__c/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact field is valid only for Contact Survey and Contact Profile record types</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Achievement Sets</relationshipLabel>
    <relationshipName>Achievement_Sets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Score_Minimal_Value__c.field-meta.xml
<CustomField>
    <fullName>Score_Minimal_Value__c</fullName>
    <defaultValue>0.5</defaultValue>
    <description>Minimalne dopasowanie po jakim Profil zostanie przypisany do Pracownika</description>
    <inlineHelpText>Minimalne dopasowanie po jakim Profil zostanie przypisany do Pracownika</inlineHelpText>
    <label>Score Minimal Value</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement_Set__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Unique Name</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/Achievement_Set_Item__c.object-meta.xml
<CustomObject>
    <description>Achievement Set Item</description>
    <label>Achievement Set Item</label>
    <nameField>
        <displayFormat>ASI{00000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Set Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipName>Position_Profile_Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Achievement_Set__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Set__c</fullName>
    <label>Achievement Set</label>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/HistoryRecord__c.field-meta.xml
<CustomField>
    <fullName>HistoryRecord__c</fullName>
    <formula>NOT(ISBLANK(EndDate__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>History Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Achievement_Set_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>Achievement__r.RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Career_Path__c/Career_Path__c.object-meta.xml
<CustomObject>
    <label>Career Path</label>
    <nameField>
        <label>Career Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Career Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Achievement_Profile__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Achievement Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Achievement_Set__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee Profile</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Achievement_Set__c.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Contacts (Achievement Profile)</relationshipLabel>
    <relationshipName>Contact_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Career_Path__c.field-meta.xml
<CustomField>
    <fullName>Career_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Career Path</label>
    <referenceTo>Career_Path__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SkillAssessment__c.field-meta.xml
<CustomField>
    <fullName>SkillAssessment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skill Assessment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Analytic</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Profile_Score__c/Contact_Profile_Score__c.object-meta.xml
<CustomObject>
    <description>Employee Profile Score</description>
    <label>Employee Profile Probe</label>
    <nameField>
        <displayFormat>EPP{00000000}</displayFormat>
        <label>Profile Probe ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Profile Probes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Profile_Score__c/fields/Achievement_Profile__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Profile__c</fullName>
    <label>Achievement Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Achievement_Set__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Specialization, Position Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Employee Profile Probes (Achievement Profile)</relationshipLabel>
    <relationshipName>Achievement_Profiles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Profile_Score__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Profile Probes</relationshipLabel>
    <relationshipName>Contact_Position_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Profile_Score__c/fields/Contact_Profile__c.field-meta.xml
<CustomField>
    <fullName>Contact_Profile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Achievement_Set__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee Profile</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contact__c</field>
            <operation>equals</operation>
            <valueField>Achievement_Set__c.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Achievement_Set__c</referenceTo>
    <relationshipLabel>Employee Profile Probes (Employee Profile)</relationshipLabel>
    <relationshipName>Contact_Profile_Scores</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Profile_Score__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <label>Match</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contact_Profile_Score__c/fields/unique_name__c.field-meta.xml
<CustomField>
    <fullName>unique_name__c</fullName>
    <externalId>true</externalId>
    <label>unique name</label>
    <length>64</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AchievementServiceTest.cls
/**
 * Achievement Service Test
 * @author Adam Siwek
 */
@isTest
private class AchievementServiceTest {

    @isTest
    private static void shouldNotCalculateProfilesWhenNoData() {
        AchievementService.calculateContactProfileScores(null, null);
        System.assertEquals(0, [SELECT Count() FROM Contact_Profile_Score__c]);

        AchievementService.calculateContactProfileScores(new Set<Id>(), new Set<Id>());
        System.assertEquals(0, [SELECT Count() FROM Contact_Profile_Score__c]);
    }

    @isTest
    private static void groupItemShouldBeUnique() {
        Achievement_Category__c base = new AchievementUtils.AchievementCategoryBuilder('Base Category').buildAndSave();
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('Career Path 1').buildAndSave();
        
        Achievement__c skill1 = new AchievementUtils.AchievementBuilder('Skill1', base).asSkill().buildAndSave();
        Achievement__c grp = new AchievementUtils.AchievementBuilder('Group1', base).asGroup().addGroupItem(skill1).build();
        
        try {
            insert new Achievement_Group_Item__c(Achievement__c = skill1.Id, Group__c = grp.Id);
            System.assert(false, 'Group Items should be unique');
        } catch (DMLException e){}
        
    }

    @isTest
    private static void achievementSetItemShouldBeUnique() {
        Achievement_Category__c base = new AchievementUtils.AchievementCategoryBuilder('Base Category').buildAndSave();
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('Career Path 1').buildAndSave();
        
        Achievement__c skill1 = new AchievementUtils.AchievementBuilder('Skill1', base).asSkill().buildAndSave();

        Achievement_Set__c spec1 = new AchievementUtils.AchievementSetBuilder('Junior Java Developer').
                asProfile(careerPath).
                addSkill(skill1, AchievementUtils.ACHIEVEMENT_LEVEL_2).
                buildAndSave();

        try {
            insert new Achievement_Set_Item__c(Achievement_Set__c = spec1.Id, Achievement__c = skill1.Id);
            System.assert(false, 'Group Items should be unique');
        } catch (DMLException e){}
    }

    @isTest
    private static void shouldCalculateProfiles() {
        Achievement_Category__c base = new AchievementUtils.AchievementCategoryBuilder('Base Category').buildAndSave();
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('Career Path 1').buildAndSave();

        Achievement__c skill = new AchievementUtils.AchievementBuilder('Skill', base).asSkill().build();
        Achievement__c cert = new AchievementUtils.AchievementBuilder('Cert1', base).asCert().build();
        Achievement__c cert2 = new AchievementUtils.AchievementBuilder('Cert2', base).asCert().build();
        Achievement__c badge = new AchievementUtils.AchievementBuilder('Badge', base).asBadge().build();
        Achievement__c date_c = new AchievementUtils.AchievementBuilder('Date', base).asDate().build();
        insert new Achievement__c[] {skill, cert, cert2, badge, date_c};
        Achievement__c attribute = new AchievementUtils.AchievementBuilder('Attribute', base)
            .asAttribute()
            .addAttributeValue('option 1', 1)
            .addAttributeValue('option 2', 2)
            .addAttributeValue('option 3', 4)
            .addAttributeValue('option 4', 8)
            .buildAndSave();

        Contact c1 = new Contact(FirstName='Janusz', LastName='D', Email='j@text.com', SkillAssessment__c = true);
        Contact c2 = new Contact(FirstName='Andrzej', LastName='U', Email='a@text.com', SkillAssessment__c = true);
        Contact c3 = new Contact(FirstName='Grazyna', LastName='P', Email='g@text.com', SkillAssessment__c = true);
        Contact c4 = new Contact(FirstName='Zbigniew', LastName='E', Email='z@text.com', SkillAssessment__c = true);
        Contact c5 = new Contact(FirstName='Helena', LastName='K', Email='h@text.com', SkillAssessment__c = true);
        Contact c6 = new Contact(FirstName='Kamil', LastName='C', Email='ka@text.com', SkillAssessment__c = true);
        Contact[] contacts = new Contact[]{c1, c2, c3, c4, c5, c6};
        insert contacts;
        Map<ID, Contact> contactsMap = new Map<ID, Contact>(contacts);

        Map<ID, Achievement_Set__c> contactIdToAchievementSetMap  = new Map<ID, Achievement_Set__c>();
        for (Achievement_Set__c cpp : [SELECT Contact__c, Name FROM Achievement_Set__c WHERE Contact__c IN : contactsMap.keySet()]) {
            contactIdToAchievementSetMap.put(cpp.Contact__c, cpp);
        }
        Date dateInstance = Date.newInstance(Date.today().year(), Date.today().month(), 1);
        Test.startTest();
        new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(c1.Id)).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_3).
                addBadge(badge, 3).
                addAttribute(attribute, 8).
                addDate(date_c, dateInstance.addMonths(-8)).
                addCert(cert).
                buildAndSave();

        new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(c2.Id)).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_2).
                addBadge(badge, 2).
                addAttribute(attribute, 8).
                addDate(date_c, dateInstance.addMonths(-8)).
                addCert(cert).
                buildAndSave();

        new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(c3.Id)).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_1).
                addCert(cert).
                addAttribute(attribute, 2).
                addDate(date_c, dateInstance.addMonths(-2)).
                buildAndSave();

        new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(c4.Id)).
                addBadge(badge, 1).
                buildAndSave();

        new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(c5.Id)).
                addCert(cert).
                buildAndSave();

        new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(c5.Id)).
                addCert(cert2).
                buildAndSave();

        Achievement_Set__c pos = new AchievementUtils.AchievementSetBuilder('Senior Java Developer').
                asPositionProfile(careerPath).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_2).
                addCert(cert).
                addBadge(badge, 2).
                addAttribute(attribute, 8).
                addDate(date_c, dateInstance.addMonths(-5)).
                buildAndSave();
                
        Database.executeBatch(new AchievementProfileCalcuationJob());
        Test.stopTest();
        System.assertEquals(1.0, [SELECT Match__c FROM Contact_Profile_Score__c WHERE Contact__c=:c1.Id LIMIT 1].Match__c);
        System.assertEquals(1.0, [SELECT Match__c FROM Contact_Profile_Score__c WHERE Contact__c=:c2.Id LIMIT 1].Match__c);
        System.assertEquals(0.5, [SELECT Match__c FROM Contact_Profile_Score__c WHERE Contact__c=:c3.Id LIMIT 1].Match__c);
        System.assertEquals(0, [SELECT Count() FROM Contact_Profile_Score__c WHERE Contact__c=:c4.Id LIMIT 1]);
        System.assertEquals(0, [SELECT Count() FROM Contact_Profile_Score__c WHERE Contact__c=:c5.Id LIMIT 1]);
        System.assertEquals(0, [SELECT Count() FROM Contact_Profile_Score__c WHERE Contact__c=:c6.Id LIMIT 1]);
    }
    
    @isTest
    private static void shouldRemoveProbeWhenProfileDoesNotMatch() {
        Achievement_Category__c base = new AchievementUtils.AchievementCategoryBuilder('Base Category').buildAndSave();
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('Career Path 1').buildAndSave();

        Achievement__c skill = new AchievementUtils.AchievementBuilder('Skill', base).asSkill().build();
        Achievement__c cert = new AchievementUtils.AchievementBuilder('Cert1', base).asCert().build();
        insert new Achievement__c[] {skill, cert};

        Contact c1 = new Contact(FirstName='Janusz', LastName='D', Email='j@test.com', SkillAssessment__c = true);
        Contact[] contacts = new Contact[]{c1};
        insert contacts;
        Map<ID, Contact> contactsMap = new Map<ID, Contact>(contacts);

        Map<ID, Achievement_Set__c> contactIdToAchievementSetMap  = new Map<ID, Achievement_Set__c>();
        for (Achievement_Set__c cpp : [SELECT Contact__c, Name FROM Achievement_Set__c WHERE Contact__c IN : contactsMap.keySet()]) {
            contactIdToAchievementSetMap.put(cpp.Contact__c, cpp);
        }
        
        Achievement_Set__c prof = new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(c1.Id)).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_1).
                addCert(cert).
                buildAndSave();

        Achievement_Set__c pos = new AchievementUtils.AchievementSetBuilder('Senior Java Developer').
                asPositionProfile(careerPath).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_2).
                addCert(cert).
                buildAndSave();

        insert new Contact_Profile_Score__c(
                Contact__c = c1.Id,
                Contact_Profile__c = prof.Id,
                Achievement_Profile__c = pos.Id,
                unique_name__c = String.valueOf(c1.Id)+String.valueOf(pos.Id),
                Match__c = 0.75);

        Test.startTest();
        pos.Score_Minimal_Value__c = 1;
        update pos;
        Test.stopTest();
        
        System.assertEquals(0, [SELECT Count() FROM Contact_Profile_Score__c WHERE Contact__c=:c1.Id LIMIT 1]);
        
    }

    @isTest
    private static void shouldRewriteProfileScoreToAchievementsetItem() {
        Achievement_Category__c base = new AchievementUtils.AchievementCategoryBuilder('Base Category').buildAndSave();
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('Career Path 1').buildAndSave();

        Achievement__c skill = new AchievementUtils.AchievementBuilder('Skill', base).asSkill().build();
        Achievement__c cert = new AchievementUtils.AchievementBuilder('Cert1', base).asCert().build();
        Achievement__c cert2 = new AchievementUtils.AchievementBuilder('Cert2', base).asCert().build();
        Achievement__c badge = new AchievementUtils.AchievementBuilder('Badge', base).asBadge().build();
        insert new Achievement__c[] {skill, cert, cert2, badge};

        Contact c1 = new Contact(FirstName='Janusz', LastName='D', Email='j@text.com', SkillAssessment__c = true);
        Contact c2 = new Contact(FirstName='Andrzej', LastName='U', Email='a@text.com', SkillAssessment__c = true);
        Contact c3 = new Contact(FirstName='Grazyna', LastName='P', Email='g@text.com', SkillAssessment__c = true);
        Contact c4 = new Contact(FirstName='Zbigniew', LastName='E', Email='z@text.com', SkillAssessment__c = true);
        Contact c5 = new Contact(FirstName='Helena', LastName='K', Email='h@text.com', SkillAssessment__c = true);
        Contact c6 = new Contact(FirstName='Kamil', LastName='C', Email='k@text.com', SkillAssessment__c = true);
        Contact[] contacts = new Contact[]{c1, c2, c3, c4, c5, c6};
        insert contacts;
        Map<ID, Contact> contactsMap = new Map<ID, Contact>(contacts);

        Map<ID, Achievement_Set__c> contactIdToAchievementSetMap  = new Map<ID, Achievement_Set__c>();
        for (Achievement_Set__c cpp : [SELECT Contact__c, Name FROM Achievement_Set__c WHERE Contact__c IN : contactsMap.keySet()]) {
            contactIdToAchievementSetMap.put(cpp.Contact__c, cpp);
        }

        Test.startTest();
        new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(c1.Id)).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_3).
                addBadge(badge, 3).
                addCert(cert).
                addCert(cert2).
                buildAndSave();

        new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(c2.Id)).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_2).
                addBadge(badge, 2).
                addCert(cert).
                addCert(cert2).
                buildAndSave();

        new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(c3.Id)).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_1).
                addCert(cert).
                addCert(cert2).
                buildAndSave();

        new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(c4.Id)).
                addBadge(badge, 1).
                buildAndSave();

        new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(c5.Id)).
                addCert(cert).
                addCert(cert2).
                buildAndSave();

        Achievement_Set__c pos = new AchievementUtils.AchievementSetBuilder('Senior Java Developer').
                asPositionProfile(careerPath).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_2).
                addCert(cert).
                addBadge(badge, 2).
                buildAndSave();

        Achievement_Set__c specialization = new AchievementUtils.AchievementSetBuilder('Specialization').
                asProfile(careerPath).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_2).
                addBadge(badge, 2).
                addCert(cert).
                addCert(cert2).
                buildAndSave();

        new AchievementUtils.AchievementBuilder('Spec', base).asSpecialization(specialization).buildAndSave();

        Database.executeBatch(new AchievementProfileCalcuationJob());
        Test.stopTest();

        System.assertEquals(4, [SELECT COUNT() FROM Achievement_Set_Item__c WHERE Type__c =: AchievementUtils.ACHIEVEMENT_SPECIALIZATION_RECORD_TYPE]);
    }

    @isTest
    private static void shouldArchiveAchievementSetrItems() {
        Achievement_Category__c base = new AchievementUtils.AchievementCategoryBuilder('Base Category').buildAndSave();
        Career_Path__c careerPath = new AchievementUtils.CareerPathBuilder('Career Path 1').buildAndSave();

        Achievement__c skill = new AchievementUtils.AchievementBuilder('Skill', base).asSkill().build();
        Achievement__c cert = new AchievementUtils.AchievementBuilder('Cert1', base).asCert().build();
        Achievement__c badge = new AchievementUtils.AchievementBuilder('Badge', base).asBadge().build();
        Achievement__c date_c = new AchievementUtils.AchievementBuilder('Date', base).asDate().build();
        Achievement__c attribute = new AchievementUtils.AchievementBuilder('Attribute', base)
            .asAttribute()
            .addAttributeValue('option 1', 1)
            .addAttributeValue('option 2', 2)
            .addAttributeValue('option 3', 4)
            .addAttributeValue('option 4', 8)
            .build();

        insert new Achievement__c[] {skill, cert, badge, date_c, attribute};

        Contact c1 = new Contact(FirstName='Janusz', LastName='D', Email='j@test.com', SkillAssessment__c = true);
        Contact[] contacts = new Contact[]{c1};
        insert contacts;
        Map<ID, Contact> contactsMap = new Map<ID, Contact>(contacts);
        Date dateInstance = Date.newInstance(Date.today().year(), Date.today().month(), 1);

        Map<ID, Achievement_Set__c> contactIdToAchievementSetMap  = new Map<ID, Achievement_Set__c>();
        for (Achievement_Set__c cpp : [SELECT Contact__c, Name FROM Achievement_Set__c WHERE Contact__c IN : contactsMap.keySet()]) {
            contactIdToAchievementSetMap.put(cpp.Contact__c, cpp);
        }
        
        Achievement_Set__c prof = new AchievementUtils.AchievementSetBuilder(contactIdToAchievementSetMap.get(c1.Id)).
                addSkill(skill, AchievementUtils.ACHIEVEMENT_LEVEL_1).
                addBadge(badge, 2).
                addCert(cert).
                addDate(date_c, dateInstance).
                addAttribute(attribute, 2).
                buildAndSave();

        system.assertEquals(1, [SELECT COUNT() FROM Achievement_Set_Item__c WHERE Achievement__c = : skill.Id]);
        system.assertEquals(1, [SELECT COUNT() FROM Achievement_Set_Item__c WHERE Achievement__c = : cert.Id]);
        system.assertEquals(1, [SELECT COUNT() FROM Achievement_Set_Item__c WHERE Achievement__c = : badge.Id]);
        system.assertEquals(1, [SELECT COUNT() FROM Achievement_Set_Item__c WHERE Achievement__c = : date_c.Id]);
        system.assertEquals(1, [SELECT COUNT() FROM Achievement_Set_Item__c WHERE Achievement__c = : attribute.Id]);

        List<Achievement_Set_Item__c> items = [SELECT Id, Amount__c, Level__c, Type__c FROM Achievement_Set_Item__c];
        List<Achievement_Set_Item__c> deleteItems = new List<Achievement_Set_Item__c>();
        for (Achievement_Set_Item__c item : items) {
            if (item.Type__c == AchievementUtils.ACHIEVEMENT_SKILL_RECORD_TYPE) {
                item.Level__c = AchievementUtils.ACHIEVEMENT_LEVEL_3;
            } else if (item.Type__c == AchievementUtils.ACHIEVEMENT_MONTHSFROMDATE_RECORD_TYPE) {
                item.Date__c = dateInstance.addMonths(5);
            } else if (item.Type__c == AchievementUtils.ACHIEVEMENT_ATTRIBUTE_RECORD_TYPE) {
                item.Amount__c = 8;
            } else if (item.Type__c == AchievementUtils.ACHIEVEMENT_BADGE_RECORD_TYPE) {
                item.Amount__c = 4;
            } else if (item.Type__c == AchievementUtils.ACHIEVEMENT_CERTIFICATE_RECORD_TYPE) {
                deleteItems.add(item);
            }
        }
        update items;
        delete deleteItems;
        System.assertEquals(5, [SELECT COUNT() FROM Achievement_Set_Item__c WHERE HistoryRecord__c = true]);
        System.assertEquals(4, [SELECT COUNT() FROM Achievement_Set_Item__c WHERE HistoryRecord__c = false]);
        System.assertEquals(2, [SELECT COUNT() FROM Achievement_Set_Item__c WHERE Achievement__c = : skill.Id]);
        System.assertEquals(1, [SELECT COUNT() FROM Achievement_Set_Item__c WHERE Achievement__c = : cert.Id]);
        System.assertEquals(2, [SELECT COUNT() FROM Achievement_Set_Item__c WHERE Achievement__c = : badge.Id]);
        System.assertEquals(2, [SELECT COUNT() FROM Achievement_Set_Item__c WHERE Achievement__c = : date_c.Id]);
        System.assertEquals(2, [SELECT COUNT() FROM Achievement_Set_Item__c WHERE Achievement__c = : attribute.Id]);
    }

    @isTest
    private static void shouldGetSubCategoriesStartWithFirstLevel() {
        //GIVEN
        buildTreeCateogry();

        //WHEN
        Set<Id> ids = AchievementService.getSubCategoriesIds('Category 1');

        //THEN
        System.assertEquals(3, ids.size());
    }

    @isTest
    private static void shouldGetSubCategoriesStartWithSecondLevel() {
        //GIVEN
        buildTreeCateogry();

        //WHEN
        Set<Id> ids = AchievementService.getSubCategoriesIds('Category 1.1');

        //THEN
        System.assertEquals(2, ids.size());
    }

    @isTest
    private static void shouldGetSubCategoriesStartWithThirdLevel() {
        //GIVEN
        buildTreeCateogry();

        //WHEN
        Set<Id> ids = AchievementService.getSubCategoriesIds('Category 1.1.1');

        //THEN
        System.assertEquals(1, ids.size());
    }

    private static void buildTreeCateogry() {
        Achievement_Category__c category1 = new AchievementUtils.AchievementCategoryBuilder('Category 1').buildAndSave();
        Achievement_Category__c category2 = new AchievementUtils.AchievementCategoryBuilder('Category 1.1').addParent(category1.Id).buildAndSave();
        Achievement_Category__c category3 = new AchievementUtils.AchievementCategoryBuilder('Category 1.1.1').addParent(category2.Id).buildAndSave();
    }
}