force-app/main/default/objects/BTN_CV__c/BTN_CV__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CID{00000000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_CV__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Recruit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidates (Contact)</relationshipLabel>
    <relationshipName>Candidates1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/ResourceRequest__c.field-meta.xml
<CustomField>
    <fullName>ResourceRequest__c</fullName>
    <label>Resource request</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Resource request must not be closed</errorMessage>
        <filterItems>
            <field>BTN_ResourceRequest__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Closed Delivered, Closed Rejected</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BTN_ResourceRequest__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>CVs_lkp</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/ResourceRequestName_frm__c.field-meta.xml
<CustomField>
    <fullName>ResourceRequestName_frm__c</fullName>
    <formula>ResourceRequest__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Request Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/BTN_Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E{00000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Event__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>BTN_CV__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description (HR)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/DescriptionTechnical__c.field-meta.xml
<CustomField>
    <fullName>DescriptionTechnical__c</fullName>
    <label>Description (Technical)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Interviewed__c.field-meta.xml
<CustomField>
    <fullName>Interviewed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewed</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Events (Interviewed)</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lublin Hamleta</fullName>
            </value>
            <value>
                <fullName>Lublin Morwowa</fullName>
            </value>
            <value>
                <fullName>Warszawa Bukowińska</fullName>
            </value>
            <value>
                <fullName>Warszawa Wołoska</fullName>
            </value>
            <value>
                <fullName>Kielce IX Wieków</fullName>
            </value>
            <value>
                <fullName>Poznań Strzelecka</fullName>
            </value>
            <value>
                <fullName>Zdalnie</fullName>
            </value>
            <value>
                <fullName>U klienta [Other location is mandatory]</fullName>
            </value>
            <value>
                <fullName>Inne [Other location is mandatory]</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
                <isActive>false</isActive>
                <label>Call</label>
            </value>
            <value>
                <fullName>Meeting</fullName>
                <isActive>false</isActive>
                <label>Meeting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Profiling_date__c.field-meta.xml
<CustomField>
    <fullName>Profiling_date__c</fullName>
    <label>Profiling date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal Interview</fullName>
            </value>
            <value>
                <fullName>External Interview</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Periodic Assessment</fullName>
            </value>
            <value>
                <fullName>Notes</fullName>
                <isActive>false</isActive>
                <label>Notes</label>
            </value>
            <value>
                <fullName>Others</fullName>
                <isActive>false</isActive>
                <label>Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Meeting_Room__c/BTN_Meeting_Room__c.object-meta.xml
<CustomObject>
    <label>Meeting Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Meeting_Room__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Room is available to use</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BTN_Meeting_Room__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Office_Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Meeting_Room__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <inlineHelpText>Priority of room importance</inlineHelpText>
    <label>Priority</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/BTN_ResourceRequest__c.object-meta.xml
<CustomObject>
    <label>Resource request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Project Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kielce</fullName>
            </value>
            <value>
                <fullName>Lublin</fullName>
            </value>
            <value>
                <fullName>Poznań</fullName>
            </value>
            <value>
                <fullName>Warszawa</fullName>
            </value>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Position_frm__c.field-meta.xml
<CustomField>
    <fullName>Position_frm__c</fullName>
    <formula>IF(RecordType.DeveloperName == &apos;Auto&apos;, Opportunity__r.Name,  Position__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Position Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Resource_Manager__c.field-meta.xml
<CustomField>
    <fullName>Resource_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.Name_frm__c</field>
            <operation>contains</operation>
            <value>Codello</value>
        </filterItems>
        <filterItems>
            <field>Contact.Name_frm__c</field>
            <operation>contains</operation>
            <value>Łukaszewski</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Resource_Requests_RM</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Other Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Analytic</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/GoogleTokenDate__c.field-meta.xml
<CustomField>
    <fullName>GoogleTokenDate__c</fullName>
    <label>GoogleTokenDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User/fields/GoogleTokenExpiresIn__c.field-meta.xml
<CustomField>
    <fullName>GoogleTokenExpiresIn__c</fullName>
    <label>GoogleTokenExpiresIn</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Office_Locations.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Lublin Hamleta</fullName>
    </customValue>
    <customValue>
        <fullName>Lublin Morwowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kielce IX Wieków</fullName>
    </customValue>
    <customValue>
        <fullName>Warszawa Karolkowa</fullName>
    </customValue>
    <customValue>
        <fullName>Poznań Szyperska</fullName>
    </customValue>
    <customValue>
        <fullName>Warszawa Wołoska</fullName>
        <isActive>false</isActive>
        <label>Warszawa Wołoska</label>
    </customValue>
    <customValue>
        <fullName>Poznań Strzelecka</fullName>
        <isActive>false</isActive>
        <label>Poznań Strzelecka</label>
    </customValue>
    <customValue>
        <fullName>Warszawa Bukowińska</fullName>
        <isActive>false</isActive>
        <label>Warszawa Bukowińska</label>
    </customValue>
    <masterLabel>Office Locations</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BTN_EventController_Test.cls
/**
 * @author Mateusz Przywara
 * @date   2016-11-03
 * @description BTN_EventController_Test Test Class for Event Edit Page Controller
 */
@isTest
private class BTN_EventController_Test {
    private static String TEST_USER_FIRST_NAME = 'first';
    private static String TEST_USER_LAST_NAME = 'last';
    /**
     * @author Mateusz Przywara
     * @date   2016-11-07
     * @description Prepare data for tests
    */
    @TestSetup static void createDataStructure() {
        CollaborationGroup cg = BTN_TestDataFactory.getHRCollaborationGroup();
        BTN_TestDataFactory.getNewBssDummyConnections();
        Account acc = BTN_TestDataFactory.getBriteNetAccount();
        Contact internalCon = BTN_TestDataFactory.getRequestorInternalContact(acc.Id);
        BTN_ResourceRequest__c rr = BTN_ResourceRequestBuilderHelper.buildWithManualRecordType().save();
        rr.Resource_Manager__c = internalCon.Id;
        update rr;
        BTN_TestDataFactory.getCV(
                rr.Id,
                internalCon.Id
        );
    }
    /**
     * @author Mateusz Przywara
     * @date   2016-11-07
     * @description testConstruction
    */
    testMethod static private void testConstructionGeneral() {
        User testUser = BTN_TestDataFactory.getActiveUser(
                TEST_USER_FIRST_NAME,
                TEST_USER_LAST_NAME,
                null,
                BTN_TestDataFactory.getProfileId(BTN_ConstantRepo.ADMIN_PROFILE_NAME)
        );

        System.runAs(testUser){
            PageReference pageTest = Page.BTN_EventPage;
            Test.setCurrentPage(pageTest);
            BTN_CV__c candidate = new BTN_DAO_Candidate().findCandidates().get(0);
            pageTest.getParameters().put(
                    BTN_ConstantRepo.URL_PARAM_RECORDTYPE_ID,
                    BTN_RecordTypeUtils.getRecordTypeCustomEventGeneral().Id
            );
            pageTest.getParameters().put(
                    BTN_ConstantRepo.URL_PARAM_CONTACT_ID,
                    candidate.Contact__c
            );
            ApexPages.StandardController stdController = new ApexPages.StandardController(new BTN_Event__c());
            BTN_EventController controller = new BTN_EventController(stdController);

            System.assertEquals(BTN_RecordTypeUtils.CUSTOMEVENT_GENERAL_RECORDTYPE, controller.RT_General);
            System.assertEquals(BTN_RecordTypeUtils.CUSTOMEVENT_INTERVIEW_RECORDTYPE, controller.RT_Interview);
            controller.beforeSaveValidation();
            System.assertNotEquals(null, controller.doSaveAfterValidation());
            List<BTN_Event__c> resultEvents = [SELECT RecordTypeId,RecordType.Name, Type__c, Interviewed__c, Candidate__c, Start_Time__c, End_Time__c, Profiling_date__c FROM BTN_Event__c];
            System.assert(resultEvents.size() == 1);
            BTN_Event__c resultEvent = resultEvents[0];
            System.assertEquals(BTN_RecordTypeUtils.CUSTOMEVENT_GENERAL_RECORDTYPE,resultEvent.RecordType.Name);
        }
    }
    testMethod static private void testValidateBeforeSave() {
        User testUser = BTN_TestDataFactory.getActiveUser(TEST_USER_FIRST_NAME, TEST_USER_LAST_NAME, null, BTN_TestDataFactory.getProfileId(BTN_ConstantRepo.ADMIN_PROFILE_NAME));

        System.runAs(testUser) {
            String toLong = BTN_TestDataFactory.getGeneratedString(BTN_EventController.DESCRIPTION_MAX_LENGTH + 1);
            PageReference pageTest = Page.BTN_EventPage;
            Test.setCurrentPage(pageTest);
            BTN_CV__c candidate = new BTN_DAO_Candidate().findCandidates().get(0);
            pageTest.getParameters().put(
                    BTN_ConstantRepo.URL_PARAM_RECORDTYPE_ID,
                    BTN_RecordTypeUtils.getRecordTypeCustomEventGeneral().Id
            );
            pageTest.getParameters().put(
                    BTN_ConstantRepo.URL_PARAM_CONTACT_ID,
                    candidate.Contact__c
            );
            //when
            ApexPages.StandardController stdController = new ApexPages.StandardController(new BTN_Event__c());
            BTN_EventController controller = new BTN_EventController(stdController);
            controller.myEvent.Description__c = toLong;
            controller.myEvent.DescriptionTechnical__c = toLong;
            //then
            controller.beforeSaveValidation();
            System.assert(!controller.shouldSave);
            List<Apexpages.Message> msgs = ApexPages.getMessages();
            Boolean desMessExist = false;
            Boolean techDesMessExist = false;
            for (Apexpages.Message msg:msgs) {
                if ((msg.getSummary().contains(String.format(Label.MaximumFieldLengthError, new String[]{
                        SObjectType.BTN_Event__c.fields.Description__c.label,
                        String.valueOf(BTN_EventController.DESCRIPTION_MAX_LENGTH)
                }))) && (msg.getSeverity() == ApexPages.Severity.Error)) {
                    desMessExist = true;
                }
                if ((msg.getSummary().contains(String.format(Label.MaximumFieldLengthError, new String[]{
                        SObjectType.BTN_Event__c.fields.DescriptionTechnical__c.label,
                        String.valueOf(BTN_EventController.DESCRIPTION_MAX_LENGTH)
                }))) && (msg.getSeverity() == ApexPages.Severity.Error)) {
                    techDesMessExist = true;
                }

            }
            System.assert(desMessExist);
            System.assert(techDesMessExist);
            System.assertEquals(null, controller.doSaveAfterValidation());
        }
    }
    testMethod static private void mainSectionLabelShouldContainCandidateInformation() {
        User testUser = BTN_TestDataFactory.getActiveUser(TEST_USER_FIRST_NAME, TEST_USER_LAST_NAME, null, BTN_TestDataFactory.getProfileId(BTN_ConstantRepo.ADMIN_PROFILE_NAME));

        System.runAs(testUser) {
            PageReference pageTest = Page.BTN_EventPage;
            Test.setCurrentPage(pageTest);
            BTN_CV__c candidate = new BTN_DAO_Candidate().addResourceRequestFields().findCandidates().get(0);
            pageTest.getParameters().put(
                    BTN_ConstantRepo.URL_PARAM_RECORDTYPE_ID,
                    BTN_RecordTypeUtils.getRecordTypeCustomEventGeneral().Id
            );

            pageTest.getParameters().put(
                    BTN_ConstantRepo.URL_PARAM_CANDIDATE_ID,
                    candidate.Id
            );
            ApexPages.StandardController stdController = new ApexPages.StandardController(new BTN_Event__c());
            BTN_EventController controller = new BTN_EventController(stdController);
            System.assert(controller.getMainSectionLabel().contains(String.format(System.Label.InterviewSectionLabel, new String[]{
                    candidate.ResourceRequest__r.Position_frm__c,
                    candidate.ResourceRequestName_frm__c
            })));
            controller.beforeSaveValidation();
            System.assertNotEquals(null, controller.doSaveAfterValidation());
        }
    }
    testMethod static private void testTimeGetters() {
        User testUser = BTN_TestDataFactory.getActiveUser(TEST_USER_FIRST_NAME, TEST_USER_LAST_NAME, null, BTN_TestDataFactory.getProfileId(BTN_ConstantRepo.ADMIN_PROFILE_NAME));

        System.runAs(testUser) {
            PageReference pageTest = Page.BTN_EventPage;
            Test.setCurrentPage(pageTest);
            BTN_CV__c candidate = new BTN_DAO_Candidate().addResourceRequestFields().findCandidates().get(0);
            pageTest.getParameters().put(
                    BTN_ConstantRepo.URL_PARAM_RECORDTYPE_ID,
                    BTN_RecordTypeUtils.getRecordTypeCustomEventGeneral().Id
            );
            pageTest.getParameters().put(
                    BTN_ConstantRepo.URL_PARAM_CANDIDATE_ID,
                    candidate.Id
            );
            ApexPages.StandardController stdController = new ApexPages.StandardController(new BTN_Event__c());
            BTN_EventController controller = new BTN_EventController(stdController);
            DateTime testTime = System.now();
            controller.startTime = testTime;
            controller.endTime = testTime;
            controller.myEvent.Profiling_date__c = testTime;
            System.assertEquals(System.now().format('dd.MM.YYYY HH:mm'), controller.getStartTimeString());
            System.assertEquals(System.now().format('dd.MM.YYYY HH:mm'), controller.getEndTimeString());
            System.assertEquals(System.now().format('dd.MM.YYYY HH:mm'), controller.getProfilingTimeString());
            controller.profilingDate = testTime;
            System.assertEquals(System.now().format('dd.MM.YYYY HH:mm'), controller.getProfilingTimeString());
        }
    }
    testMethod static private void mainSectionLabelWithoutCandidate() {
        User testUser = BTN_TestDataFactory.getActiveUser(TEST_USER_FIRST_NAME, TEST_USER_LAST_NAME, null, BTN_TestDataFactory.getProfileId(BTN_ConstantRepo.ADMIN_PROFILE_NAME));

        System.runAs(testUser) {
            PageReference pageTest = Page.BTN_EventPage;
            Test.setCurrentPage(pageTest);
            BTN_CV__c candidate = new BTN_DAO_Candidate().addResourceRequestFields().findCandidates().get(0);
            pageTest.getParameters().put(
                    BTN_ConstantRepo.URL_PARAM_RECORDTYPE_ID,
                    BTN_RecordTypeUtils.getRecordTypeCustomEventGeneral().Id
            );
            pageTest.getParameters().put(
                    BTN_ConstantRepo.URL_PARAM_CONTACT_ID,
                    candidate.Contact__c
            );
            ApexPages.StandardController stdController = new ApexPages.StandardController(new BTN_Event__c());
            BTN_EventController controller = new BTN_EventController(stdController);
            System.assert(!controller.getMainSectionLabel().contains(candidate.ResourceRequestName_frm__c));
        }
    }
    testMethod static private void testOnLoadRedirectForPeriodicAssessmentWithEvent() {
        User testUser = BTN_TestDataFactory.getActiveUser(TEST_USER_FIRST_NAME, TEST_USER_LAST_NAME, null, BTN_TestDataFactory.getProfileId(BTN_ConstantRepo.ADMIN_PROFILE_NAME));

        System.runAs(testUser) {
            Contact internalContact = new BTN_DAO_Contact().findInternals().get(0);
            BTN_Event__c event = new BTN_Event__c();
            event.RecordTypeId = BTN_RecordTypeUtils.getRecordTypeCustomEventPeriodicAssessment().Id;
            insert event;
            ApexPages.StandardController stdController = new ApexPages.StandardController(event);
            BTN_EventController controller = new BTN_EventController(stdController);
            BTN_Event__c ev2 = [select RecordType.Name from BTN_Event__c where Id = :event.Id];
            controller.myEvent = ev2;
            //when
            PageReference redirectPage = controller.onLoadAction();
            //then
            System.assert(redirectPage.getUrl().contains(event.Id));
            System.assert(redirectPage.getUrl().contains('?id'));
        }
    }
    testMethod static private void testOnLoadRedirectForPeriodicAssessmentWithoutEvent() {
        User testUser = BTN_TestDataFactory.getActiveUser(TEST_USER_FIRST_NAME, TEST_USER_LAST_NAME, null, BTN_TestDataFactory.getProfileId(BTN_ConstantRepo.ADMIN_PROFILE_NAME));

        System.runAs(testUser) {
            Contact internalContact = new BTN_DAO_Contact().findInternals().get(0);
            BTN_Event__c event = new BTN_Event__c();
            event.RecordTypeId = BTN_RecordTypeUtils.getRecordTypeCustomEventPeriodicAssessment().Id;
            insert event;
            ApexPages.StandardController stdController = new ApexPages.StandardController(event);
            BTN_EventController controller = new BTN_EventController(stdController);
            BTN_Event__c ev2 = [select Id, RecordType.Name from BTN_Event__c where Id = :event.Id];
            ev2.Id = null;
            controller.myEvent = ev2;
            //when
            PageReference redirectPage = controller.onLoadAction();
            //then
            System.assert(redirectPage != null);
            System.assert(!redirectPage.getUrl().contains(event.Id));
            System.assert(!redirectPage.getUrl().contains('?id'));
        }
    }
    testMethod static private void testOnLoadRedirectWithoutEventForNotPeriodicAssessment() {
        User testUser = BTN_TestDataFactory.getActiveUser(TEST_USER_FIRST_NAME, TEST_USER_LAST_NAME, null, BTN_TestDataFactory.getProfileId(BTN_ConstantRepo.ADMIN_PROFILE_NAME));

        System.runAs(testUser) {
            Contact internalContact = new BTN_DAO_Contact().findInternals().get(0);
            BTN_Event__c event = new BTN_Event__c();
            event.RecordTypeId = BTN_RecordTypeUtils.getRecordTypeCustomEventGeneral().Id;
            insert event;
            ApexPages.StandardController stdController = new ApexPages.StandardController(event);
            BTN_EventController controller = new BTN_EventController(stdController);
            BTN_Event__c ev2 = [select Id, RecordType.Name from BTN_Event__c where Id = :event.Id];
            //when
            PageReference redirectPage = controller.onLoadAction();
            //then
            System.assert(redirectPage == null);
        }
    }

    testMethod static private void testBeforeSaveValidationForInterview() {
        //given
        User testUser = BTN_TestDataFactory.getActiveUser(TEST_USER_FIRST_NAME, TEST_USER_LAST_NAME, null, BTN_TestDataFactory.getProfileId(BTN_ConstantRepo.ADMIN_PROFILE_NAME));

        System.runAs(testUser) {
            prepareInterview();
            PageReference pageTest = Page.BTN_EventPage;
            Test.setCurrentPage(pageTest);
            BTN_CV__c candidate = new BTN_DAO_Candidate().findCandidates().get(0);
            pageTest.getParameters().put(
                    BTN_ConstantRepo.URL_PARAM_RECORDTYPE_ID,
                    BTN_RecordTypeUtils.getRecordTypeCustomEventInterview().Id
            );
            pageTest.getParameters().put(
                    BTN_ConstantRepo.URL_PARAM_CANDIDATE_ID,
                    candidate.Id
            );
            //when
            ApexPages.StandardController stdController = new ApexPages.StandardController(new BTN_Event__c());
            BTN_EventController controller = new BTN_EventController(stdController);
            controller.myEvent.Location__c = 'Lublin Morwowa';
            controller.refreshAvailableMeetingRooms();
            controller.chosenRoom = 'Salka .NET';
            //then
            Test.startTest();
            Test.setMock(
                    HttpCalloutMock.class,
                    new BTN_GoogleCalendarMock(BTN_GoogleCalendarMock.TEST_CALENDAR_ID)
            );
            controller.beforeSaveValidation();

            Test.stopTest();
            System.assert(controller.shouldSave);
            System.assertEquals(BTN_GoogleCalendarMock.TEST_CALENDAR_ID, controller.calendarId);
        }
    }

    testMethod static private void testBeforeSaveValidationForInterviewWithEvents() {
        //given
        User testUser = BTN_TestDataFactory.getActiveUser(TEST_USER_FIRST_NAME, TEST_USER_LAST_NAME, null, BTN_TestDataFactory.getProfileId(BTN_ConstantRepo.ADMIN_PROFILE_NAME));

        System.runAs(testUser) {
            prepareInterview();
            PageReference pageTest = Page.BTN_EventPage;
            Test.setCurrentPage(pageTest);
            BTN_CV__c candidate = new BTN_DAO_Candidate().findCandidates().get(0);
            pageTest.getParameters().put(
                    BTN_ConstantRepo.URL_PARAM_RECORDTYPE_ID,
                    BTN_RecordTypeUtils.getRecordTypeCustomEventInterview().Id
            );
            pageTest.getParameters().put(
                    BTN_ConstantRepo.URL_PARAM_CANDIDATE_ID,
                    candidate.Id
            );
            //when
            ApexPages.StandardController stdController = new ApexPages.StandardController(new BTN_Event__c());
            BTN_EventController controller = new BTN_EventController(stdController);
            controller.myEvent.Location__c = 'Lublin Morwowa';
            controller.refreshAvailableMeetingRooms();
            controller.chosenRoom = 'Salka PHP';
            //then
            Test.startTest();
            Test.setMock(
                    HttpCalloutMock.class,
                    new BTN_GoogleCalendarMock(BTN_GoogleCalendarMock.TEST_CALENDAR_ID_WITH_EVENTS)
            );
            controller.beforeSaveValidation();

            Test.stopTest();
            System.assertEquals(null, controller.calendarId);
            System.assert(!controller.shouldSave);
            List<Apexpages.Message> msgs = ApexPages.getMessages();
            Boolean messExist = false;
            for (Apexpages.Message msg:msgs) {
                if ((msg.getSummary().contains(Label.Event_Meeting_Room_Warning)) && (msg.getSeverity() == ApexPages.Severity.FATAL)) {
                    messExist = true;
                }

            }
            system.assert(messExist);
        }
    }
    testMethod static private void testBeforeSaveValidationForInterviewWithoutCustomSettings() {
        User testUser = BTN_TestDataFactory.getActiveUser(TEST_USER_FIRST_NAME, TEST_USER_LAST_NAME, null, BTN_TestDataFactory.getProfileId(BTN_ConstantRepo.ADMIN_PROFILE_NAME));

        System.runAs(testUser) {
            //given
            User current = BTN_Utils.getCurrentUser();
            current.GoogleTokenExpiresIn__c = 60;
            current.GoogleTokenDate__c = System.now();
            update current;
            PageReference pageTest = Page.BTN_EventPage;
            Test.setCurrentPage(pageTest);
            BTN_CV__c candidate = new BTN_DAO_Candidate().findCandidates().get(0);
            pageTest.getParameters().put(
                    BTN_ConstantRepo.URL_PARAM_RECORDTYPE_ID,
                    BTN_RecordTypeUtils.getRecordTypeCustomEventInterview().Id
            );
            pageTest.getParameters().put(
                    BTN_ConstantRepo.URL_PARAM_CANDIDATE_ID,
                    candidate.Id
            );
            //when
            ApexPages.StandardController stdController = new ApexPages.StandardController(new BTN_Event__c());
            BTN_EventController controller = new BTN_EventController(stdController);
            //then
            Test.startTest();
            Test.setMock(
                    HttpCalloutMock.class,
                    new BTN_GoogleCalendarMock(BTN_GoogleCalendarMock.TEST_CALENDAR_ID)
            );
            controller.beforeSaveValidation();

            Test.stopTest();
            System.assert(controller.shouldSave);
            System.assertNotEquals(BTN_GoogleCalendarMock.TEST_CALENDAR_ID, controller.calendarId);
            System.assertEquals(null, controller.save());
        }
    }
    private static List<BTN_Meeting_Room__c> prepareInterview (){
        User current = BTN_Utils.getCurrentUser();
        current.GoogleTokenExpiresIn__c = 60;
        current.GoogleTokenDate__c  = System.now().addDays(-2);
        update current;
        BTN_GoogleCalendarMock.prepareGoogleCalendarSettings();
        List<BTN_Meeting_Room__c> roomList = new List<BTN_Meeting_Room__c>();
        roomList.add(new BTN_Meeting_Room__c(Name='Salka .NET', Active__c=true, CurrencyIsoCode='PLN', Location__c='Lublin Morwowa', Priority__c=7));
        roomList.add(new BTN_Meeting_Room__c(Name='Salka Salesforce', Active__c=true, CurrencyIsoCode='PLN', Location__c='Lublin Morwowa', Priority__c=7));
        roomList.add(new BTN_Meeting_Room__c(Name='Salka Script', Active__c=true, CurrencyIsoCode='PLN', Location__c='Lublin Morwowa', Priority__c=4));
        roomList.add(new BTN_Meeting_Room__c(Name='Salka Eweliny', Active__c=true, CurrencyIsoCode='PLN', Location__c='Lublin Morwowa', Priority__c=2));
        roomList.add(new BTN_Meeting_Room__c(Name='Salka PHP', Active__c=true, CurrencyIsoCode='PLN', Location__c='Lublin Morwowa', Priority__c=1));
        roomList.add(new BTN_Meeting_Room__c(Name='test', Active__c=true, CurrencyIsoCode='PLN', Location__c='Kielce IX Wieków', Priority__c=2));
        roomList.add(new BTN_Meeting_Room__c(Name='Salka C++', Active__c=true, CurrencyIsoCode='PLN', Location__c='Lublin Morwowa', Priority__c=5));
        roomList.add(new BTN_Meeting_Room__c(Name='Salka Java', Active__c=true, CurrencyIsoCode='PLN', Location__c='Lublin Morwowa', Priority__c=6));
        insert roomList;
        return roomList;
    }
}