force-app/main/default/objects/BTN_CV__c/BTN_CV__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CID{00000000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_CV__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Recruit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidates (Contact)</relationshipLabel>
    <relationshipName>Candidates1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted to external</fullName>
            </value>
            <value>
                <fullName>Interview-in-progress</fullName>
            </value>
            <value>
                <fullName>Approved by external</fullName>
            </value>
            <value>
                <fullName>Contract signed</fullName>
            </value>
            <value>
                <fullName>Contract signed with different external</fullName>
            </value>
            <value>
                <fullName>Rejected by external</fullName>
            </value>
            <value>
                <fullName>Rejected by us</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Offer expired</fullName>
            </value>
            <value>
                <fullName>Closed in ZOHO</fullName>
                <isActive>false</isActive>
                <label>Closed in ZOHO</label>
            </value>
            <value>
                <fullName>Rejected by internal</fullName>
                <isActive>false</isActive>
                <label>Rejected by internal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Event__c/BTN_Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E{00000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Event__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>BTN_CV__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description (HR)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Interviewed__c.field-meta.xml
<CustomField>
    <fullName>Interviewed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewed</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Events (Interviewed)</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/PostOnRelatedCandidates__c.field-meta.xml
<CustomField>
    <fullName>PostOnRelatedCandidates__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Post on Related Candidates</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal Interview</fullName>
            </value>
            <value>
                <fullName>External Interview</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Periodic Assessment</fullName>
            </value>
            <value>
                <fullName>Notes</fullName>
                <isActive>false</isActive>
                <label>Notes</label>
            </value>
            <value>
                <fullName>Others</fullName>
                <isActive>false</isActive>
                <label>Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Event__c/recordTypes/Interview.recordType-meta.xml
<RecordType>
    <fullName>Interview</fullName>
    <active>true</active>
    <description>Interview with potential employee</description>
    <label>Interview</label>
</RecordType>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Analytic</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BTN_ChatterUtils.cls
/**
 * @author Mateusz Przywara
 * @date   2016-10-12
 * @description BTN_ChatterUtils
*/
public class BTN_ChatterUtils {
    public static String CHATTER_FEED_GROUP_RECORD = 'AllNetworks';
    public static String CHATTER_FEED_VISIBILITY = 'AllUsers';

    private static String hrGroupName = BTN_ConstantRepo.HUMAN_RESOURCES_GROUP_NAME;

    // cache Collaboration Group - This data cannot be changed during transaction.
    public static CollaborationGroup HUMAN_RESOURCES_GROUP {
        set;
        get {
            String hrGroupName = (Test.isRunningTest()) ? BTN_TestDataFactory.TEST_HR_COLLABORATION_GROUP_NAME : BTN_ConstantRepo.HUMAN_RESOURCES_GROUP_NAME;
            if (HUMAN_RESOURCES_GROUP == null) {
                HUMAN_RESOURCES_GROUP =
                        new BTN_DAO_CollaborationGroup().findGroupByName(hrGroupName);
            }
            return HUMAN_RESOURCES_GROUP;
    }}

    /**
     * @author Mateusz Przywara
     * @date   2016-10-12
     * @description postEvents Post Feed Items on the Contact and optionally on Candidates related to Contact
     * @return void
    */
    public static List<Database.SaveResult> postEvents(List<BTN_Event__c> events) {
        List<FeedItem> posts = new List<FeedItem>();
        Set<Id> contactIds = new Set<Id>();
        Set<Id> candidateIds = new Set<Id>();
        Id parentIdForFeedItem;
        for (BTN_Event__c eventItem : events) {
            if (BTN_RecordTypeUtils.isGeneral(eventItem)) {
                parentIdForFeedItem = eventItem.Interviewed__c;
            } else {
                parentIdForFeedItem = eventItem.Candidate__c;
                if(BTN_RecordTypeUtils.isInterview(eventItem) && eventItem.Candidate__c!=null){
                    candidateIds.add(eventItem.Candidate__c);
                }
            }
            if (!BTN_ValidationHandler.isNull(parentIdForFeedItem)) {
                posts.add(new FeedItem(
                        Body = eventItem.Type__c + ' ' + System.Label.HasBeenCreated,
                        ParentId = parentIdForFeedItem,
                        Visibility = CHATTER_FEED_VISIBILITY,
                        NetworkScope = CHATTER_FEED_GROUP_RECORD)
                );
            }
            contactIds.add(eventItem.Interviewed__c);
        }
        // Retrieve Candidates for Events
        List<BTN_CV__c> candidates = new List<BTN_CV__c>(new BTN_DAO_Candidate().findCandidatesInContactSet(contactIds));
        //iterate again to build FeedItems for related Candidates
        for (BTN_Event__c eventItem : events) {
            if (eventItem.PostOnRelatedCandidates__c) {
                for (BTN_CV__c candidate : candidates) {
                    if (candidate.Contact__c.equals(eventItem.Interviewed__c)) {
                        posts.add(new FeedItem(
                                Body = eventItem.Description__c,
                                ParentId = candidate.Id,
                                Visibility = CHATTER_FEED_VISIBILITY,
                                NetworkScope = CHATTER_FEED_GROUP_RECORD)
                        );
                    }
                }
            }
        }
        if(!candidateIds.isEmpty()){
            changeStatusOfCandidates(candidates,candidateIds);
        }
        return Database.insert(posts);
    }
    public static void changeStatusOfCandidates(List<BTN_CV__c> dbCondidates,Set<Id> candidateIds){
        List<BTN_CV__c> candidatesToBeUpdated = new  List<BTN_CV__c>();
        for (BTN_CV__c candidate : dbCondidates) {
            if (candidateIds.contains(candidate.Id)&&candidate.Status__c.equals('Open')) {
                candidate.Status__c = 'Interview-in-progress';
                candidatesToBeUpdated.add(candidate);
            }
        }
        update candidatesToBeUpdated;
    }
    /**
     * @author Mateusz Przywara
     * @date   2016-10-20
     * @description postChangesOnGroup Post Feed Items on Collaboration Group
     * @param oldObjectList List of sObjects before changes
     * @param newObjectMap Map of Fields after changes
     * @param trackingFieldNameSet API names of fields to track
     * @param recordsNameField API of field with Full Name of Contact / Candidate etc.
     * @param groupId Parent for FeedItems
     * @return List<Database.SaveResult> FeedItem List DML result
    */
    public static List<Database.SaveResult> postChangesOnGroup(
            List<sObject> oldObjectList,
            Map<Id, sObject> newObjectMap,
            Set<String> trackingFieldNameSet,
            String recordsNameField,
            Id groupId,
            String scopeName
    ) {
        List<FeedItem> posts = new List<FeedItem>();
        String tmpChanges = '';
        Set<String> objectsWithLink  = BTN_Utils.getSetValuesByName('ObjectsWithChatterLink');
        String domain = getDomain();
        for (sObject oldObjectItem : oldObjectList) {
            for (String fieldName : trackingFieldNameSet) {
                if (!oldObjectItem.get(fieldName).equals(newObjectMap.get(oldObjectItem.Id).get(fieldName))) {
                    tmpChanges +=
                            String.format(
                                    //{0} of {1} {2} has been changed from {3} to {4}
                                    System.Label.ChangeOnCandidate,
                                    new List<String>{
                                            Schema.getGlobalDescribe().get(oldObjectItem.getSobjectType().getDescribe().getName()).getDescribe().fields.getMap().get(fieldName).getDescribe().getLabel(),
                                            oldObjectItem.getSobjectType().getDescribe().getLabel(),
                                            String.valueOf(oldObjectItem.get(recordsNameField)),
                                            String.valueOf(oldObjectItem.get(fieldName)),
                                            String.valueOf(newObjectMap.get(oldObjectItem.Id).get(fieldName))
                                    }
                            );
                }
            }
            if (String.isBlank(tmpChanges)) {
                tmpChanges =
                        oldObjectItem.getSObjectType().getDescribe().getLabel()
                                + ' ' + oldObjectItem.get(recordsNameField)
                                + ' ' + System.Label.hasBeenUpdated;
            }
            if(!domain.equals('not exist')&& objectsWithLink.contains(oldObjectItem.getSobjectType().getDescribe().getName())){
                tmpChanges = checkIfLinkNeeded(oldObjectItem,tmpChanges,domain);
            }

            posts.add(new FeedItem(
                    Body = tmpChanges,
                    ParentId = groupId,
                    Visibility = CHATTER_FEED_VISIBILITY,
                    NetworkScope = scopeName)
            );
        }
        return Database.insert(posts);
    }
    private static String checkIfLinkNeeded(SObject record,String oldMessage,String domain ){
        return oldMessage + ' https://'+domain+'/'+ record.Id +' ';

    }
    private static String getDomain(){
        List<Domain> domainList = [SELECT Domain,DomainType FROM Domain];
        if(domainList.isEmpty()){
            return 'not exist';
        }else{
            return domainList[0].Domain;
        }


    }
    /**
     * @author Mateusz Przywara
     * @date   2016-10-20
     * @description postChangesOnGroup Post Feed Items on Collaboration Group
     * @param oldObjectList List of sObjects before changes
     * @param newObjectMap Map of Fields after changes
     * @param trackingFieldNameSet API names of fields to track
     * @return List<Database.SaveResult> FeedItem List DML result
    */
    public static List<Database.SaveResult> postChangesOnHumanResourcesGroup(
            List<sObject> oldObjectList,
            Map<Id, sObject> newObjectMap,
            Set<String> trackingFieldNameSet,
            String recordsNameField
    ) {
        return postChangesOnGroup(
                oldObjectList,
                newObjectMap,
                trackingFieldNameSet,
                recordsNameField,
                BTN_ChatterUtils.HUMAN_RESOURCES_GROUP.Id,
                BTN_ChatterUtils.HUMAN_RESOURCES_GROUP.NetworkId
        );
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-10-13
     * @description postChangesOnGroup Post Feed Items on Collaboration Group
     * @param oldObjectList List of sObjects before changes
     * @param newObjectMap Map of Fields after changes
     * @param recordsNameField API of field with Full Name of Contact / Candidate etc.
     * @param groupId Parent for FeedItems
     * @param String Scope Id of Network(Community) or CHATTER_FEED_GROUP_RECORD to post on record feed
     * @return void
    */
    public static List<Database.SaveResult> postInsertsOnGroup(
            Map<Id, sObject> newObjectMap,
            String recordsNameField,
            Id groupId,
            String scopeName
    ) {
        List<FeedItem> posts = new List<FeedItem>();
        Set<String> objectsWithLink  = BTN_Utils.getSetValuesByName('ObjectsWithChatterLink');
        String domain = getDomain();
        for (sObject objectItem : newObjectMap.values()) {
            String feedBody = objectItem.getSObjectType().getDescribe().getLabel()
                    + ' ' + objectItem.get(recordsNameField)
                    + ' ' + System.Label.hasBeenCreated;
            if(!domain.equals('not exist')&& objectsWithLink.contains(objectItem.getSobjectType().getDescribe().getName())){
                feedBody = checkIfLinkNeeded(objectItem,feedBody,domain);
            }
            posts.add(new FeedItem(
                    Body = feedBody,
                    ParentId = groupId,
                    Visibility = CHATTER_FEED_VISIBILITY,
                    NetworkScope = scopeName)
            );
        }
        return Database.insert(posts);
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-10-13
     * @description postChangesOnGroup Post Feed Items on Collaboration Group
     * @param oldObjectList List of sObjects before changes
     * @param newObjectMap Map of Fields after changes
     * @param recordsNameField API of field with Full Name of Contact / Candidate etc.
     * @return void
    */
    public static List<Database.SaveResult> postInsertsOnHumanResourcesGroup(
            Map<Id, sObject> newObjectMap,
            String recordsNameField
    ) {
        return postInsertsOnGroup(
                newObjectMap,
                recordsNameField,
                BTN_ChatterUtils.HUMAN_RESOURCES_GROUP.Id,
                BTN_ChatterUtils.HUMAN_RESOURCES_GROUP.NetworkId
        );
    }
}