force-app/main/default/objects/BTN_CV__c/BTN_CV__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CID{00000000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_CV__c/fields/ResourceRequest__c.field-meta.xml
<CustomField>
    <fullName>ResourceRequest__c</fullName>
    <label>Resource request</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Resource request must not be closed</errorMessage>
        <filterItems>
            <field>BTN_ResourceRequest__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Closed Delivered, Closed Rejected</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BTN_ResourceRequest__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>CVs_lkp</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/ResourceRequestName_frm__c.field-meta.xml
<CustomField>
    <fullName>ResourceRequestName_frm__c</fullName>
    <formula>ResourceRequest__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Request Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted to external</fullName>
            </value>
            <value>
                <fullName>Interview-in-progress</fullName>
            </value>
            <value>
                <fullName>Approved by external</fullName>
            </value>
            <value>
                <fullName>Contract signed</fullName>
            </value>
            <value>
                <fullName>Contract signed with different external</fullName>
            </value>
            <value>
                <fullName>Rejected by external</fullName>
            </value>
            <value>
                <fullName>Rejected by us</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Offer expired</fullName>
            </value>
            <value>
                <fullName>Closed in ZOHO</fullName>
                <isActive>false</isActive>
                <label>Closed in ZOHO</label>
            </value>
            <value>
                <fullName>Rejected by internal</fullName>
                <isActive>false</isActive>
                <label>Rejected by internal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Event__c/BTN_Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E{00000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Event__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>BTN_CV__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description (HR)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/DescriptionTechnical__c.field-meta.xml
<CustomField>
    <fullName>DescriptionTechnical__c</fullName>
    <label>Description (Technical)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Interviewed__c.field-meta.xml
<CustomField>
    <fullName>Interviewed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewed</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Events (Interviewed)</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lublin Hamleta</fullName>
            </value>
            <value>
                <fullName>Lublin Morwowa</fullName>
            </value>
            <value>
                <fullName>Warszawa Bukowińska</fullName>
            </value>
            <value>
                <fullName>Warszawa Wołoska</fullName>
            </value>
            <value>
                <fullName>Kielce IX Wieków</fullName>
            </value>
            <value>
                <fullName>Poznań Strzelecka</fullName>
            </value>
            <value>
                <fullName>Zdalnie</fullName>
            </value>
            <value>
                <fullName>U klienta [Other location is mandatory]</fullName>
            </value>
            <value>
                <fullName>Inne [Other location is mandatory]</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
                <isActive>false</isActive>
                <label>Call</label>
            </value>
            <value>
                <fullName>Meeting</fullName>
                <isActive>false</isActive>
                <label>Meeting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Meeting_Room__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Room__c</fullName>
    <label>Meeting Room</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Profiling_date__c.field-meta.xml
<CustomField>
    <fullName>Profiling_date__c</fullName>
    <label>Profiling date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BTN_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal Interview</fullName>
            </value>
            <value>
                <fullName>External Interview</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Periodic Assessment</fullName>
            </value>
            <value>
                <fullName>Notes</fullName>
                <isActive>false</isActive>
                <label>Notes</label>
            </value>
            <value>
                <fullName>Others</fullName>
                <isActive>false</isActive>
                <label>Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Event__c/recordTypes/Interview.recordType-meta.xml
<RecordType>
    <fullName>Interview</fullName>
    <active>true</active>
    <description>Interview with potential employee</description>
    <label>Interview</label>
</RecordType>

force-app/main/default/objects/BTN_Meeting_Room__c/BTN_Meeting_Room__c.object-meta.xml
<CustomObject>
    <label>Meeting Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_Meeting_Room__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Office_Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_Meeting_Room__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <inlineHelpText>Priority of room importance</inlineHelpText>
    <label>Priority</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/BTN_ResourceRequest__c.object-meta.xml
<CustomObject>
    <label>Resource request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Project Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kielce</fullName>
            </value>
            <value>
                <fullName>Lublin</fullName>
            </value>
            <value>
                <fullName>Poznań</fullName>
            </value>
            <value>
                <fullName>Warszawa</fullName>
            </value>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Position_frm__c.field-meta.xml
<CustomField>
    <fullName>Position_frm__c</fullName>
    <formula>IF(RecordType.DeveloperName == &apos;Auto&apos;, Opportunity__r.Name,  Position__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Position Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Waiting for client</fullName>
            </value>
            <value>
                <fullName>On shelf</fullName>
            </value>
            <value>
                <fullName>Closed - Success</fullName>
            </value>
            <value>
                <fullName>Closed - Failure</fullName>
            </value>
            <value>
                <fullName>Opportunity Closed</fullName>
            </value>
            <value>
                <fullName>Closed - We resign</fullName>
            </value>
            <value>
                <fullName>Closed - Blood in the sand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Other Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Analytic</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/GoogleTokenDate__c.field-meta.xml
<CustomField>
    <fullName>GoogleTokenDate__c</fullName>
    <label>GoogleTokenDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User/fields/GoogleTokenExpiresIn__c.field-meta.xml
<CustomField>
    <fullName>GoogleTokenExpiresIn__c</fullName>
    <label>GoogleTokenExpiresIn</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Office_Locations.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Lublin Hamleta</fullName>
    </customValue>
    <customValue>
        <fullName>Lublin Morwowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kielce IX Wieków</fullName>
    </customValue>
    <customValue>
        <fullName>Warszawa Karolkowa</fullName>
    </customValue>
    <customValue>
        <fullName>Poznań Szyperska</fullName>
    </customValue>
    <customValue>
        <fullName>Warszawa Wołoska</fullName>
        <isActive>false</isActive>
        <label>Warszawa Wołoska</label>
    </customValue>
    <customValue>
        <fullName>Poznań Strzelecka</fullName>
        <isActive>false</isActive>
        <label>Poznań Strzelecka</label>
    </customValue>
    <customValue>
        <fullName>Warszawa Bukowińska</fullName>
        <isActive>false</isActive>
        <label>Warszawa Bukowińska</label>
    </customValue>
    <masterLabel>Office Locations</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BTN_EventController.cls
/**
 * @author Mateusz Przywara
 * @date   2016-11-03
 * @description BTN_EventController handling Candidate status change to Interview-in-progress
 */
public with sharing class BTN_EventController {
    private static final String ERROR_MAIN_SECTION_NAME = System.Label.Information;
    @TestVisible private static final Integer DESCRIPTION_MAX_LENGTH = 32768;
    @TestVisible private BTN_Event__c myEvent;
    public DateTime startTime {set; get;}
    public DateTime endTime {set; get;}
    public DateTime profilingDate {set; get;}
    public Boolean meetingRoomWarning {get;set;}
    public String RT_Interview {set; get{
        return BTN_RecordTypeUtils.CUSTOMEVENT_INTERVIEW_RECORDTYPE;
    }}
    public String rt_general {set; get{
        return BTN_RecordTypeUtils.CUSTOMEVENT_GENERAL_RECORDTYPE;
    }}
    public List<SelectOption> availableMeetingRooms {get;set;}
    public String chosenRoom {get;set;}
    @TestVisible private String calendarId;
    private Boolean userChanged;
    @TestVisible private Boolean shouldSave;

    ApexPages.StandardController stdController;

    public BTN_EventController(ApexPages.StandardController stdController) {
        RecordType eventRecordType;
        this.myEvent = (BTN_Event__c) stdController.getRecord();
        this.stdController = stdController;
        if (!BTN_ValidationHandler.isNull(eventRecordType = getRecordType())) {
            myEvent.RecordTypeId = eventRecordType.Id;
            myEvent.RecordType = eventRecordType;
            myEvent.Type__c = getType();
            myEvent.Interviewed__c = getContact();
            myEvent.Candidate__c = getCandidate();
        }
        startTime = myEvent.Start_Time__c;
        endTime = myEvent.End_Time__c;

        meetingRoomWarning = false;
        availableMeetingRooms = new List<SelectOption>();
    }

     /**
     * @author Wojciech Mazur
     * @date   2016-12-13
     * @description Action exectud on load
    */
    public PageReference onLoadAction() {
    	if(BTN_RecordTypeUtils.CUSTOMEVENT_PERIODIC_RECORDTYPE == myEvent.RecordType.Name){
    		if(myEvent!=null && myEvent.Id!=null){
    			return new PageReference('/apex/BTN_EventPeriodic?id='+myEvent.Id);
    		}else{
    			return new PageReference('/apex/BTN_EventPeriodic');
    		}
    	}else{
    		return null;
    	}
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-11-03
     * @description Save override for standard Save action extended with Candidate status update
    */
    public PageReference save() {return null;}

    public PageReference beforeSaveValidation() {
        shouldSave = false;
        if (validateBeforeSave()) {
            return null;
        }
        if (myEvent.RecordType.Name == BTN_RecordTypeUtils.CUSTOMEVENT_INTERVIEW_RECORDTYPE && meetingRoomWarning == false) {
            User currUser = refreshUser();
            calendarId = BTN_MeetingRoomService.getFirstAvailableRoomCalendarIdForLocation(chosenRoom, myEvent.Location__c, startTime, endTime);
            if (availableMeetingRooms.isEmpty() == false) {
                if (String.isBlank(calendarId)) {
                    meetingRoomWarning = true;
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, Label.Event_Meeting_Room_Warning));
                    return null;
                } else {
                    myEvent.Meeting_Room__c = calendarId;
                    shouldSave = true;
                }
            }else{
                shouldSave = true;
            }
            if(userChanged){
                update currUser;
            }
        }else{
            shouldSave = true;
        }
        return null;
    }

    public PageReference doSaveAfterValidation() {
        if(shouldSave){
            myEvent.Start_Time__c = startTime;
            myEvent.End_Time__c = endTime;
            myEvent.Profiling_date__c = profilingDate;
            updateCandidateStatusToReviewInProgress();
            PageReference resultRef = stdController.save();
            if (resultRef != null) {
                if (myEvent.Candidate__c == null) {
                    resultRef = new PageReference('/' + myEvent.Interviewed__c);
                } else {
                    resultRef = new PageReference('/' + myEvent.Candidate__c);
                }
            }
            return resultRef;
        }
        return null;
    }

    private Boolean validateBeforeSave() {
        Boolean hasErrors = false;
        if (String.isNotBlank(myEvent.Description__c) && myEvent.Description__c.length() > DESCRIPTION_MAX_LENGTH) {
            String message = String.format(Label.MaximumFieldLengthError, new String[] {
                    SObjectType.BTN_Event__c.fields.Description__c.label,
                    String.valueOf(DESCRIPTION_MAX_LENGTH)
            });
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, message));
            hasErrors = true;
        }
        if (String.isNotBlank(myEvent.DescriptionTechnical__c) && myEvent.DescriptionTechnical__c.length() > DESCRIPTION_MAX_LENGTH) {
            String message = String.format(Label.MaximumFieldLengthError, new String[] {
                    SObjectType.BTN_Event__c.fields.DescriptionTechnical__c.label,
                    String.valueOf(DESCRIPTION_MAX_LENGTH)
            });
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, message));
            hasErrors = true;
        }

        return hasErrors;
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-11-03
     * @description Update Status on related Candidate
    */
    private Boolean updateCandidateStatusToReviewInProgress() {
        Boolean result = false;
        if (!BTN_ValidationHandler.isNull(myEvent.Candidate__c)) {
            BTN_CV__c affiliatedCandidate = new BTN_DAO_Candidate().findCandidateById(myEvent.Candidate__c);
            if (BTN_Utils.isOpenCandidate(affiliatedCandidate) || BTN_Utils.isInProgressCandidate(affiliatedCandidate)) {
                result = Database.update(new BTN_CV__c(
                        Id = myEvent.Candidate__c,
                        Status__c = BTN_ConstantRepo.CANDIDATE_STATUS_INTERVIEW_IN_PROGRESS
                )).isSuccess();
            }
        }
        return result;
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-11-03
     * @description get Record Type
    */
    private RecordType getRecordType() {
        Id rtId = ApexPages.currentPage().getParameters().get(BTN_ConstantRepo.URL_PARAM_RECORDTYPE_ID);
        return (RecordType) new BTN_DAO_RecordType().findSObjectById(rtId);
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-11-04
     * @description get Contact
    */
    private Id getContact() {
        return ApexPages.currentPage().getParameters().get(BTN_ConstantRepo.URL_PARAM_CONTACT_ID);
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-11-04
     * @description get Contact
    */
    private String getType() {
        return ApexPages.currentPage().getParameters().get(BTN_ConstantRepo.URL_PARAM_CUSTOMEVENT_TYPE);
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-11-04
     * @description get Candidate Id
    */
    private Id getCandidate() {
        String tmpId;
        if (String.isNotBlank(ApexPages.currentPage().getParameters().get(BTN_ConstantRepo.URL_PARAM_CANDIDATE_ID))) {
            tmpId = ApexPages.currentPage().getParameters().get(BTN_ConstantRepo.URL_PARAM_CANDIDATE_ID);
        }
        return tmpId;
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-11-22
     * @description get Label for Section
     * @return String Label content
    */
    public String getMainSectionLabel() {
        BTN_CV__c candidate = new BTN_DAO_Candidate().addResourceRequestFields().findCandidateById(getCandidate());
        String result;
        if (!BTN_ValidationHandler.isNull(candidate)) {
            result = String.format(System.Label.InterviewSectionLabel, new String[] {
                    candidate.ResourceRequest__r.Position_frm__c,
                    candidate.ResourceRequestName_frm__c
            });
        } else {
            result = ERROR_MAIN_SECTION_NAME;
        }
        return result;
    }

    public String getStartTimeString() {
        String res = '';
        if (startTime != null) {
            res = startTime.format('dd.MM.YYYY HH:mm');
        }
        return res;
    }

    public String getEndTimeString() {
        String res = '';
        if (endTime != null) {
            res = endTime.format('dd.MM.YYYY HH:mm');
        }
        return res;
    }

    public String getProfilingTimeString() {
        String res = '';
        if (profilingDate != null) {
            res = profilingDate.format('dd.MM.YYYY HH:mm');
        } else if (myEvent.Profiling_date__c != null) {
            res = myEvent.Profiling_date__c.format('dd.MM.YYYY HH:mm');
        }
        return res;
    }

    public PageReference refreshAvailableMeetingRooms(){
        availableMeetingRooms.clear();
        for(BTN_Meeting_Room__c room : [select Id,Name from BTN_Meeting_Room__c where Location__c =: myEvent.Location__c
                                        order by Priority__c asc]){
            availableMeetingRooms.add(new SelectOption(room.Name, room.Name));
        }
        if(!availableMeetingRooms.isEmpty()){
            chosenRoom = availableMeetingRooms[0].getLabel();
        }
        return null;
    }
    private User refreshUser(){
        userChanged = false;
        User current = BTN_Utils.getCurrentUser();
        if((current.GoogleTokenDate__c!=null)&&(((System.now().getTime() - current.GoogleTokenDate__c.getTime())/ 1000)>current.GoogleTokenExpiresIn__c-60)){
            current = BTN_GoogleCalendarHandler.refreshTokenForOneUser(current);
            BTN_Utils.currentUser = current;
            userChanged = true;
        }
        return current;
    }

}