force-app/main/default/objects/BTN_CV__c/BTN_CV__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CID{00000000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_CV__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted to external</fullName>
            </value>
            <value>
                <fullName>Interview-in-progress</fullName>
            </value>
            <value>
                <fullName>Approved by external</fullName>
            </value>
            <value>
                <fullName>Contract signed</fullName>
            </value>
            <value>
                <fullName>Contract signed with different external</fullName>
            </value>
            <value>
                <fullName>Rejected by external</fullName>
            </value>
            <value>
                <fullName>Rejected by us</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Offer expired</fullName>
            </value>
            <value>
                <fullName>Closed in ZOHO</fullName>
                <isActive>false</isActive>
                <label>Closed in ZOHO</label>
            </value>
            <value>
                <fullName>Rejected by internal</fullName>
                <isActive>false</isActive>
                <label>Rejected by internal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/BTN_ResourceRequest__c.object-meta.xml
<CustomObject>
    <label>Resource request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Waiting for client</fullName>
            </value>
            <value>
                <fullName>On shelf</fullName>
            </value>
            <value>
                <fullName>Closed - Success</fullName>
            </value>
            <value>
                <fullName>Closed - Failure</fullName>
            </value>
            <value>
                <fullName>Opportunity Closed</fullName>
            </value>
            <value>
                <fullName>Closed - We resign</fullName>
            </value>
            <value>
                <fullName>Closed - Blood in the sand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BTN_CloseResourceRequestController.cls
/**
 * Created by Adam on 12/20/2017.
 */

public with sharing class BTN_CloseResourceRequestController
{
	@TestVisible
	private BTN_ResourceRequest__c resourceRequest;
	@TestVisible
	private List<BTN_CV__c> candidates;

	public BTN_CloseResourceRequestController(ApexPages.StandardController stdController){
		this.resourceRequest = getResourceRequest(stdController);
	}

	public List<BTN_CV__c> getCandidates(){
		try{
			this.candidates = new BTN_DAO_Candidate().findCandidatesByResourceRequest(this.resourceRequest.Id);
			return this.candidates;
		}catch(Exception e){
			ApexPages.addMessages(e);
			return null;
		}
	}

	public PageReference save(){
		try{
			update this.candidates;
			update this.resourceRequest;
			return new PageReference('/'+this.resourceRequest.Id);
		}catch(Exception e){
			ApexPages.addMessages(e);
			return null;
		}
	}

	public PageReference cancel(){
		return new PageReference('/'+this.resourceRequest.Id);
	}

	private BTN_ResourceRequest__c getResourceRequest(ApexPages.StandardController stdController){
		if(!Test.isRunningTest()){
			List<String> queryFields = new List<String>{
					BTN_ResourceRequest__c.Name.getDescribe().getLocalName(),
					BTN_ResourceRequest__c.Status__c.getDescribe().getLocalName()
			};
			stdController.addFields(queryFields);
		}
		return (BTN_ResourceRequest__c) stdController.getRecord();
	}
}