force-app/main/default/objects/BTN_CV__c/BTN_CV__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CID{00000000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_CV__c/fields/Account_frm__c.field-meta.xml
<CustomField>
    <fullName>Account_frm__c</fullName>
    <formula>ResourceRequest__r.Account_frm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Recruit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidates (Contact)</relationshipLabel>
    <relationshipName>Candidates1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/ContactFirstName_frm__c.field-meta.xml
<CustomField>
    <fullName>ContactFirstName_frm__c</fullName>
    <formula>Contact__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/ContactLastName_frm__c.field-meta.xml
<CustomField>
    <fullName>ContactLastName_frm__c</fullName>
    <formula>Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/ContactName_frm__c.field-meta.xml
<CustomField>
    <fullName>ContactName_frm__c</fullName>
    <formula>ContactFirstName_frm__c + &apos; &apos; + ContactLastName_frm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/LastAttachmentId__c.field-meta.xml
<CustomField>
    <fullName>LastAttachmentId__c</fullName>
    <label>Last Attachment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/Position_Name_frm__c.field-meta.xml
<CustomField>
    <fullName>Position_Name_frm__c</fullName>
    <formula>ResourceRequest__r.Position_frm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Position Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/Project_Manager_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager_Email__c</fullName>
    <label>Project Manager Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/ResourceRequest__c.field-meta.xml
<CustomField>
    <fullName>ResourceRequest__c</fullName>
    <label>Resource request</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Resource request must not be closed</errorMessage>
        <filterItems>
            <field>BTN_ResourceRequest__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Closed Delivered, Closed Rejected</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BTN_ResourceRequest__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>CVs_lkp</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/ResourceRequestName_frm__c.field-meta.xml
<CustomField>
    <fullName>ResourceRequestName_frm__c</fullName>
    <formula>ResourceRequest__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Request Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_CV__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted to external</fullName>
            </value>
            <value>
                <fullName>Interview-in-progress</fullName>
            </value>
            <value>
                <fullName>Approved by external</fullName>
            </value>
            <value>
                <fullName>Contract signed</fullName>
            </value>
            <value>
                <fullName>Contract signed with different external</fullName>
            </value>
            <value>
                <fullName>Rejected by external</fullName>
            </value>
            <value>
                <fullName>Rejected by us</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Offer expired</fullName>
            </value>
            <value>
                <fullName>Closed in ZOHO</fullName>
                <isActive>false</isActive>
                <label>Closed in ZOHO</label>
            </value>
            <value>
                <fullName>Rejected by internal</fullName>
                <isActive>false</isActive>
                <label>Rejected by internal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/BTN_ResourceRequest__c.object-meta.xml
<CustomObject>
    <label>Resource request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Account_frm__c.field-meta.xml
<CustomField>
    <fullName>Account_frm__c</fullName>
    <formula>IF(RecordType.DeveloperName == &apos;Auto&apos;, Opportunity__r.Account.Name,  CustomerAccount__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/ContractStart_frm__c.field-meta.xml
<CustomField>
    <fullName>ContractStart_frm__c</fullName>
    <formula>IF(RecordType.DeveloperName == &apos;Auto&apos;, TEXT(Opportunity__r.ContractStart__c), ContractStart__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Start</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <inlineHelpText>Junior, Professional, Senior</inlineHelpText>
    <label>.Experience Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Resource_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Position_frm__c.field-meta.xml
<CustomField>
    <fullName>Position_frm__c</fullName>
    <formula>IF(RecordType.DeveloperName == &apos;Auto&apos;, Opportunity__r.Name,  Position__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Position Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BTN_ResourceRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Waiting for client</fullName>
            </value>
            <value>
                <fullName>On shelf</fullName>
            </value>
            <value>
                <fullName>Closed - Success</fullName>
            </value>
            <value>
                <fullName>Closed - Failure</fullName>
            </value>
            <value>
                <fullName>Opportunity Closed</fullName>
            </value>
            <value>
                <fullName>Closed - We resign</fullName>
            </value>
            <value>
                <fullName>Closed - Blood in the sand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/BSexternalId__c.field-meta.xml
<CustomField>
    <fullName>BSexternalId__c</fullName>
    <externalId>true</externalId>
    <label>Britesheet ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PersonalEmail__c.field-meta.xml
<CustomField>
    <fullName>PersonalEmail__c</fullName>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PersonalPhone__c.field-meta.xml
<CustomField>
    <fullName>PersonalPhone__c</fullName>
    <label>Personal Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Internal employees</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/classes/BTN_DAO_Candidate.cls
/**
 * @author Mateusz Przywara
 * @date   2016-07-05
 * @description DAO class - Data Access Object for BTN_CV__c (Candidate)
 */
public with sharing class BTN_DAO_Candidate extends BTN_DAO {
    /**
     * @author Mateusz Przywara
     * @date   2016-07-05
     * @description Constructor
    */
    public BTN_DAO_Candidate() {
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-07-05
     * @description Constructor setting custom List of fields
    */
    public BTN_DAO_Candidate(List<Schema.SObjectField> customFields) {
        setCustomFields(customFields);
    }

    public override Schema.SObjectType getSObjectType() {
        return BTN_CV__c.sObjectType;
    }

    public override List<Schema.SObjectField> getSObjectFields() {
        return new List<Schema.SObjectField>{
                BTN_CV__c.Id,
                BTN_CV__c.Name,
                BTN_CV__c.ContactFirstName_frm__c,
                BTN_CV__c.ContactLastName_frm__c,
                BTN_CV__c.ContactName_frm__c,
                BTN_CV__c.Contact__c,
                BTN_CV__c.Comment__c,
                BTN_CV__c.LastAttachmentId__c,
                BTN_CV__c.Position_Name_frm__c,
                BTN_CV__c.Project_Manager_Email__c,
                BTN_CV__c.ResourceRequest__c,
                BTN_CV__c.ResourceRequestName_frm__c,
                BTN_CV__c.Status__c
        };
    }

        /**
         * @author Mateusz Przywara
         * @date   2016-07-05
         * @description find all Candidates connected with Resource Request
         * @param  resourceRequestId - Id of Resource request
         * @return      List<BTN_CV__c>      Candidates affiliated with Resource Request
         */
    public List<BTN_CV__c> findCandidatesByResourceRequest(Id resourceRequestId) {
        return findSObjectsBy(new List<SearchCondition>{
                new SearchCondition('ResourceRequest__c', '=', resourceRequestId)
        });
    }
    
       /**
         * @author Wojciech Mazur
         * @date   2016-09-14
         * @description find all Candidates related to Contact (Internal)
         * @param  contactId - Id of contact
         * @return      List<BTN_CV__c>      Candidates affiliated with contact
         */
    public List<BTN_CV__c> findCandidatesBuContact(Id contactId) {
        return findSObjectsBy(new List<SearchCondition>{
                new SearchCondition('Contact__c', '=', contactId)
        });
    }

        /**
         * @author Mateusz Przywara
         * @date   2016-07-05
         * @description find Resource Request
         * @param  candidateId - collection of Id to search for
         * @return     BTN_CV__c       - collection of found Resource Requests
         */
    public BTN_CV__c findCandidateById(Id candidateId) {
        return (BTN_CV__c) findSObjectById(candidateId);
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-10-12
     * @description findCandidatesInContactSet
     * @param contactIds search set of Contact Ids
     * @return Candidates
    */
    public List<BTN_CV__c> findCandidatesInContactSet(Set<Id> contactIds) {
        return findSObjectsBy(new List<SearchCondition>{
                new SearchCondition('Contact__c', 'IN', contactIds)
        });
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-11-09
     * @description findCandidatesInId
     * @param contactIds search set of Contact Ids
     * @return Candidates
    */
    public List<BTN_CV__c> findCandidatesInId(Set<Id> candidateIds) {
        return findSObjectsBy(new List<SearchCondition>{
                new SearchCondition('Id', 'IN', candidateIds)
        });
    }

    /**
     * @author Konrad Kozaczuk
     * @date   2016-10-21
     * @description findCandidatesInContactSet
     * @param contactIds search set of Contact Ids
     * @return Candidates
    */
    public List<BTN_CV__c> findCandidates() {
        return (List<BTN_CV__c>)findSObjects();
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-08-04
     * @description add ResourceRequest Fields to Query
     * @return BTN_DAO_Candidate
    */
    public BTN_DAO_Candidate addResourceRequestFields() {
        currentFields.add('ResourceRequest__r.Opportunity__c');
        currentFields.add('ResourceRequest__r.RecordType.Name');
        currentFields.add('ResourceRequest__r.ContractStart_frm__c');
        currentFields.add('ResourceRequest__r.Account_frm__c');
        currentFields.add('ResourceRequest__r.Level__c');
        currentFields.add('ResourceRequest__r.Position_frm__c');
        return this;
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-11-09
     * @description add ResourceRequest Fields to Query
     * @return BTN_DAO_Candidate
    */
    public BTN_DAO_Candidate addResourceRequestName() {
        this.currentFields.add('ResourceRequest__r.Name');
        return this;
    }

    /**
     * @author Mateusz Przywara
     * @date   2016-10-07
     * @description add Contact Fields to Query
     * @return void
    */
    public BTN_DAO_Candidate addContactFields() {
        currentFields.add('Contact__r.FirstName');
        currentFields.add('Contact__r.LastName');
        currentFields.add('Contact__r.MobilePhone');
        currentFields.add('Contact__r.PersonalPhone__c');
        currentFields.add('Contact__r.PersonalEmail__c');
        currentFields.add('Contact__r.Email');
        currentFields.add('Contact__r.MailingCity');
        currentFields.add('Contact__r.MailingPostalCode');
        currentFields.add('Contact__r.MailingStreet');
        currentFields.add('Contact__r.BSexternalId__c');
        return this;
    }
}